//go:build !noasm && arm64
// Code generated by GoAT. DO NOT EDIT.
// versions:
// 	clang   21.1.8
// 	objdump 2.45.1
// flags: -march=armv8-a+simd+fp -fno-builtin-memset -O3
// source: /Users/ajroetker/go/src/github.com/ajroetker/go-highway/hwy/contrib/wavelet/asm/basesynthesize53core_c_s64_neon_arm64.c

TEXT ·synthesize53core_c_s64_neon(SB), $0-56
	MOVD data+0(FP), R0
	MOVD pn+8(FP), R1
	MOVD low+16(FP), R2
	MOVD psn+24(FP), R3
	MOVD high+32(FP), R4
	MOVD pdn+40(FP), R5
	MOVD pphase+48(FP), R6
	WORD $0xf94000a8       // ldr	x8, [x5]
	WORD $0xf94000ca       // ldr	x10, [x6]
	WORD $0xf9400069       // ldr	x9, [x3]
	WORD $0xf100052b       // subs	x11, x9, #1
	BLT  BB0_7
	WORD $0xd280000d       // mov	x13, #0                         ; =0x0
	WORD $0xb201f3ec       // mov	x12, #-6148914691236517206      ; =0xaaaaaaaaaaaaaaaa
	WORD $0xf295556c       // movk	x12, #43691
	WORD $0x9bcc7d6c       // umulh	x12, x11, x12
	WORD $0xd341fd8c       // lsr	x12, x12, #1
	WORD $0x8b0c058c       // add	x12, x12, x12, lsl #1
	WORD $0xcb0c016c       // sub	x12, x11, x12
	WORD $0x9100058e       // add	x14, x12, #1
	WORD $0xf1000ddf       // cmp	x14, #3
	WORD $0x9a8c07ec       // csinc	x12, xzr, x12, eq
	WORD $0xf1000d3f       // cmp	x9, #3
	BLO  BB0_4
	WORD $0xd280000d       // mov	x13, #0                         ; =0x0
	WORD $0xcb0c012f       // sub	x15, x9, x12
	WORD $0x91002010       // add	x16, x0, #8
	WORD $0x91002051       // add	x17, x2, #8

BB0_3:
	WORD $0xf85f8201 // ldur	x1, [x16, #-8]
	WORD $0xf81f8221 // stur	x1, [x17, #-8]
	WORD $0xf9400201 // ldr	x1, [x16]
	WORD $0xf9000221 // str	x1, [x17]
	WORD $0xf9400601 // ldr	x1, [x16, #8]
	WORD $0xf9000621 // str	x1, [x17, #8]
	WORD $0x91000dad // add	x13, x13, #3
	WORD $0x91006210 // add	x16, x16, #24
	WORD $0x91006231 // add	x17, x17, #24
	WORD $0xeb0d01ff // cmp	x15, x13
	BNE  BB0_3

BB0_4:
	WORD $0xf1000ddf // cmp	x14, #3
	BEQ  BB0_7
	WORD $0xd37df1ae // lsl	x14, x13, #3
	WORD $0x8b0e004d // add	x13, x2, x14
	WORD $0x8b0e000e // add	x14, x0, x14

BB0_6:
	WORD $0xf84085cf // ldr	x15, [x14], #8
	WORD $0xf80085af // str	x15, [x13], #8
	WORD $0xf100058c // subs	x12, x12, #1
	BNE  BB0_6

BB0_7:
	WORD $0xf100050c // subs	x12, x8, #1
	BLT  BB0_14
	WORD $0xd280000e // mov	x14, #0                         ; =0x0
	WORD $0xb201f3ed // mov	x13, #-6148914691236517206      ; =0xaaaaaaaaaaaaaaaa
	WORD $0xf295556d // movk	x13, #43691
	WORD $0x9bcd7d8d // umulh	x13, x12, x13
	WORD $0xd341fdad // lsr	x13, x13, #1
	WORD $0x8b0d05ad // add	x13, x13, x13, lsl #1
	WORD $0xcb0d018d // sub	x13, x12, x13
	WORD $0x910005af // add	x15, x13, #1
	WORD $0xf1000dff // cmp	x15, #3
	WORD $0x9a8d07ed // csinc	x13, xzr, x13, eq
	WORD $0xf1000d1f // cmp	x8, #3
	BLO  BB0_11
	WORD $0xd280000e // mov	x14, #0                         ; =0x0
	WORD $0xcb0d0110 // sub	x16, x8, x13
	WORD $0x8b090c11 // add	x17, x0, x9, lsl #3
	WORD $0x91002231 // add	x17, x17, #8
	WORD $0x91002081 // add	x1, x4, #8

BB0_10:
	WORD $0xf85f8223 // ldur	x3, [x17, #-8]
	WORD $0xf81f8023 // stur	x3, [x1, #-8]
	WORD $0xf9400223 // ldr	x3, [x17]
	WORD $0xf9000023 // str	x3, [x1]
	WORD $0xf9400623 // ldr	x3, [x17, #8]
	WORD $0xf9000423 // str	x3, [x1, #8]
	WORD $0x91000dce // add	x14, x14, #3
	WORD $0x91006231 // add	x17, x17, #24
	WORD $0x91006021 // add	x1, x1, #24
	WORD $0xeb0e021f // cmp	x16, x14
	BNE  BB0_10

BB0_11:
	WORD $0xf1000dff // cmp	x15, #3
	BEQ  BB0_14
	WORD $0xd37df1cf // lsl	x15, x14, #3
	WORD $0x8b0f008e // add	x14, x4, x15
	WORD $0x8b090def // add	x15, x15, x9, lsl #3
	WORD $0x8b0f000f // add	x15, x0, x15

BB0_13:
	WORD $0xf84085f0 // ldr	x16, [x15], #8
	WORD $0xf80085d0 // str	x16, [x14], #8
	WORD $0xf10005ad // subs	x13, x13, #1
	BNE  BB0_13

BB0_14:
	WORD $0xb400012a // cbz	x10, LBB0_17
	WORD $0xd280000f // mov	x15, #0                         ; =0x0
	WORD $0xeb0c013f // cmp	x9, x12
	WORD $0x9a8cb12d // csel	x13, x9, x12, lt
	WORD $0xb27f01ee // orr	x14, x15, #0x2
	WORD $0xeb0d01df // cmp	x14, x13
	BLE  BB0_18

BB0_16:
	WORD $0xaa0f03ee // mov	x14, x15
	B    BB0_20

BB0_17:
	WORD $0xf940008d // ldr	x13, [x4]
	WORD $0xd37ff9ad // lsl	x13, x13, #1
	WORD $0x910009ad // add	x13, x13, #2
	WORD $0xf940004e // ldr	x14, [x2]
	WORD $0xcb8d09cd // sub	x13, x14, x13, asr #2
	WORD $0xf900004d // str	x13, [x2]
	WORD $0xeb09011f // cmp	x8, x9
	WORD $0x9a89b10d // csel	x13, x8, x9, lt
	WORD $0x5280002f // mov	w15, #1                         ; =0x1
	WORD $0xb27f01ee // orr	x14, x15, #0x2
	WORD $0xeb0d01df // cmp	x14, x13
	BGT  BB0_16

BB0_18:
	WORD $0x5280010e // mov	w14, #8                         ; =0x8
	WORD $0xf100015f // cmp	x10, #0
	WORD $0x9a9f11ce // csel	x14, x14, xzr, ne
	WORD $0x928000f0 // mov	x16, #-8                        ; =0xfffffffffffffff8
	WORD $0x9a9013f0 // csel	x16, xzr, x16, ne
	WORD $0xd37df1e1 // lsl	x1, x15, #3
	WORD $0x8b010210 // add	x16, x16, x1
	WORD $0x8b100090 // add	x16, x4, x16
	WORD $0x8b0101ce // add	x14, x14, x1
	WORD $0x8b0e0091 // add	x17, x4, x14
	WORD $0x8b010041 // add	x1, x2, x1
	WORD $0x5280004e // mov	w14, #2                         ; =0x2
	WORD $0x4e080dc0 // dup.2d	v0, x14

BB0_19:
	WORD $0x3cc10601 // ldr	q1, [x16], #16
	WORD $0x3cc10622 // ldr	q2, [x17], #16
	WORD $0x4ee28421 // add.2d	v1, v1, v2
	WORD $0x4ee08421 // add.2d	v1, v1, v0
	WORD $0x4f7e0421 // sshr.2d	v1, v1, #2
	WORD $0x3dc00022 // ldr	q2, [x1]
	WORD $0x6ee18441 // sub.2d	v1, v2, v1
	WORD $0x3c810421 // str	q1, [x1], #16
	WORD $0x910009ee // add	x14, x15, #2
	WORD $0x910011e3 // add	x3, x15, #4
	WORD $0xaa0e03ef // mov	x15, x14
	WORD $0xeb0d007f // cmp	x3, x13
	BLE  BB0_19

BB0_20:
	WORD $0xeb0d01df // cmp	x14, x13
	BGE  BB0_24
	WORD $0xf100015f // cmp	x10, #0
	WORD $0xda9f13ef // csetm	x15, eq
	WORD $0x8b0f0c8f // add	x15, x4, x15, lsl #3

BB0_22:
	WORD $0xf100015f // cmp	x10, #0
	WORD $0x9a8e05d0 // cinc	x16, x14, ne
	WORD $0xf86e79f1 // ldr	x17, [x15, x14, lsl #3]
	WORD $0xf8707890 // ldr	x16, [x4, x16, lsl #3]
	WORD $0x8b100230 // add	x16, x17, x16
	WORD $0x91000a10 // add	x16, x16, #2
	WORD $0xf86e7851 // ldr	x17, [x2, x14, lsl #3]
	WORD $0xcb900a30 // sub	x16, x17, x16, asr #2
	WORD $0xf82e7850 // str	x16, [x2, x14, lsl #3]
	WORD $0x910005ce // add	x14, x14, #1
	WORD $0xeb0e01bf // cmp	x13, x14
	BNE  BB0_22
	WORD $0xaa0d03ee // mov	x14, x13

BB0_24:
	WORD $0xeb0901df // cmp	x14, x9
	BGE  BB0_27
	WORD $0xf100015f // cmp	x10, #0
	WORD $0xda9f13ed // csetm	x13, eq

BB0_26:
	WORD $0xf100015f // cmp	x10, #0
	WORD $0x9a8e05cf // cinc	x15, x14, ne
	WORD $0x8b0e01b0 // add	x16, x13, x14
	WORD $0xeb0c021f // cmp	x16, x12
	WORD $0x9a8cb210 // csel	x16, x16, x12, lt
	WORD $0xeb0c01ff // cmp	x15, x12
	WORD $0x9a8cb1ef // csel	x15, x15, x12, lt
	WORD $0xf8707890 // ldr	x16, [x4, x16, lsl #3]
	WORD $0xf86f788f // ldr	x15, [x4, x15, lsl #3]
	WORD $0x8b0f020f // add	x15, x16, x15
	WORD $0x910009ef // add	x15, x15, #2
	WORD $0xf86e7850 // ldr	x16, [x2, x14, lsl #3]
	WORD $0xcb8f0a0f // sub	x15, x16, x15, asr #2
	WORD $0xf82e784f // str	x15, [x2, x14, lsl #3]
	WORD $0x910005ce // add	x14, x14, #1
	WORD $0xeb0e013f // cmp	x9, x14
	BNE  BB0_26

BB0_27:
	WORD $0xf100055f // cmp	x10, #1
	BNE  BB0_29
	WORD $0xf940004c // ldr	x12, [x2]
	WORD $0xf940008d // ldr	x13, [x4]
	WORD $0x8b0c01ac // add	x12, x13, x12
	WORD $0xf900008c // str	x12, [x4]
	WORD $0x5280002e // mov	w14, #1                         ; =0x1
	WORD $0xeb08013f // cmp	x9, x8
	WORD $0x9a88b12c // csel	x12, x9, x8, lt
	WORD $0xb27f01cd // orr	x13, x14, #0x2
	WORD $0xeb0c01bf // cmp	x13, x12
	BGT  BB0_31
	B    BB0_33

BB0_29:
	WORD $0xd280000e // mov	x14, #0                         ; =0x0
	WORD $0xb400010a // cbz	x10, LBB0_32
	WORD $0xeb08013f // cmp	x9, x8
	WORD $0x9a88b12c // csel	x12, x9, x8, lt
	WORD $0xb27f01cd // orr	x13, x14, #0x2
	WORD $0xeb0c01bf // cmp	x13, x12
	BLE  BB0_33

BB0_31:
	WORD $0xaa0e03ed // mov	x13, x14
	B    BB0_35

BB0_32:
	WORD $0xeb0b011f // cmp	x8, x11
	WORD $0x9a8bb10c // csel	x12, x8, x11, lt
	WORD $0xb27f01cd // orr	x13, x14, #0x2
	WORD $0xeb0c01bf // cmp	x13, x12
	BGT  BB0_31

BB0_33:
	WORD $0x5280010d // mov	w13, #8                         ; =0x8
	WORD $0xf100015f // cmp	x10, #0
	WORD $0x9a8d13ed // csel	x13, xzr, x13, ne
	WORD $0x928000ef // mov	x15, #-8                        ; =0xfffffffffffffff8
	WORD $0x9a9f11ef // csel	x15, x15, xzr, ne
	WORD $0xd37df1d1 // lsl	x17, x14, #3
	WORD $0x8b110050 // add	x16, x2, x17
	WORD $0x8b0f020f // add	x15, x16, x15
	WORD $0x8b0d0210 // add	x16, x16, x13
	WORD $0x8b110091 // add	x17, x4, x17

BB0_34:
	WORD $0x3cc105e0 // ldr	q0, [x15], #16
	WORD $0x3cc10601 // ldr	q1, [x16], #16
	WORD $0x4ee08420 // add.2d	v0, v1, v0
	WORD $0x3dc00221 // ldr	q1, [x17]
	WORD $0x4f7f1401 // ssra.2d	v1, v0, #1
	WORD $0x3c810621 // str	q1, [x17], #16
	WORD $0x910009cd // add	x13, x14, #2
	WORD $0x910011c1 // add	x1, x14, #4
	WORD $0xaa0d03ee // mov	x14, x13
	WORD $0xeb0c003f // cmp	x1, x12
	BLE  BB0_34

BB0_35:
	WORD $0xeb0c01bf // cmp	x13, x12
	BGE  BB0_39
	WORD $0xf100015f // cmp	x10, #0
	WORD $0xda9f03ee // csetm	x14, ne
	WORD $0x8b0e0c4e // add	x14, x2, x14, lsl #3

BB0_37:
	WORD $0xf100015f // cmp	x10, #0
	WORD $0xf86d79cf // ldr	x15, [x14, x13, lsl #3]
	WORD $0x9a8d15b0 // cinc	x16, x13, eq
	WORD $0xf8707850 // ldr	x16, [x2, x16, lsl #3]
	WORD $0x8b0f020f // add	x15, x16, x15
	WORD $0xf86d7890 // ldr	x16, [x4, x13, lsl #3]
	WORD $0x8b8f060f // add	x15, x16, x15, asr #1
	WORD $0xf82d788f // str	x15, [x4, x13, lsl #3]
	WORD $0x910005ad // add	x13, x13, #1
	WORD $0xeb0d019f // cmp	x12, x13
	BNE  BB0_37
	WORD $0xaa0c03ed // mov	x13, x12

BB0_39:
	WORD $0xeb0801bf // cmp	x13, x8
	BGE  BB0_42
	WORD $0xf100015f // cmp	x10, #0
	WORD $0xda9f03ec // csetm	x12, ne

BB0_41:
	WORD $0x8b0d018e // add	x14, x12, x13
	WORD $0xf100015f // cmp	x10, #0
	WORD $0x9a8d15af // cinc	x15, x13, eq
	WORD $0x8aaefdce // bic	x14, x14, x14, asr #63
	WORD $0xeb0b01df // cmp	x14, x11
	WORD $0x9a8bb1ce // csel	x14, x14, x11, lt
	WORD $0xf86e784e // ldr	x14, [x2, x14, lsl #3]
	WORD $0xeb0b01ff // cmp	x15, x11
	WORD $0x9a8bb1ef // csel	x15, x15, x11, lt
	WORD $0xf86f784f // ldr	x15, [x2, x15, lsl #3]
	WORD $0x8b0e01ee // add	x14, x15, x14
	WORD $0xf86d788f // ldr	x15, [x4, x13, lsl #3]
	WORD $0x8b8e05ee // add	x14, x15, x14, asr #1
	WORD $0xf82d788e // str	x14, [x4, x13, lsl #3]
	WORD $0x910005ad // add	x13, x13, #1
	WORD $0xeb0d011f // cmp	x8, x13
	BNE  BB0_41

BB0_42:
	WORD $0xeb08013f // cmp	x9, x8
	WORD $0x9a88b12c // csel	x12, x9, x8, lt
	WORD $0xb4000a6a // cbz	x10, LBB0_57
	WORD $0xf100058a // subs	x10, x12, #1
	BLT  BB0_51
	WORD $0xd280000d // mov	x13, #0                         ; =0x0
	WORD $0xb201f3eb // mov	x11, #-6148914691236517206      ; =0xaaaaaaaaaaaaaaaa
	WORD $0xf295556b // movk	x11, #43691
	WORD $0x9bcb7d4b // umulh	x11, x10, x11
	WORD $0xd342fd6b // lsr	x11, x11, #2
	WORD $0x528000ce // mov	w14, #6                         ; =0x6
	WORD $0x9b0ea96a // msub	x10, x11, x14, x10
	WORD $0x9100054b // add	x11, x10, #1
	WORD $0xf100197f // cmp	x11, #6
	WORD $0x9a8a07ea // csinc	x10, xzr, x10, eq
	WORD $0xf100199f // cmp	x12, #6
	BLO  BB0_48
	WORD $0xd280000d // mov	x13, #0                         ; =0x0
	WORD $0xcb0c014c // sub	x12, x10, x12
	WORD $0x9100608e // add	x14, x4, #24
	WORD $0x9100c00f // add	x15, x0, #48
	WORD $0x91006050 // add	x16, x2, #24

BB0_46:
	WORD $0xf85e81d1 // ldur	x17, [x14, #-24]
	WORD $0xf81d01f1 // stur	x17, [x15, #-48]
	WORD $0xf85e8211 // ldur	x17, [x16, #-24]
	WORD $0xf81d81f1 // stur	x17, [x15, #-40]
	WORD $0xf85f01d1 // ldur	x17, [x14, #-16]
	WORD $0xf81e01f1 // stur	x17, [x15, #-32]
	WORD $0xf85f0211 // ldur	x17, [x16, #-16]
	WORD $0xf81e81f1 // stur	x17, [x15, #-24]
	WORD $0xf85f81d1 // ldur	x17, [x14, #-8]
	WORD $0xf81f01f1 // stur	x17, [x15, #-16]
	WORD $0xf85f8211 // ldur	x17, [x16, #-8]
	WORD $0xf81f81f1 // stur	x17, [x15, #-8]
	WORD $0xf94001d1 // ldr	x17, [x14]
	WORD $0xf90001f1 // str	x17, [x15]
	WORD $0xf9400211 // ldr	x17, [x16]
	WORD $0xf90005f1 // str	x17, [x15, #8]
	WORD $0xf94005d1 // ldr	x17, [x14, #8]
	WORD $0xf90009f1 // str	x17, [x15, #16]
	WORD $0xf9400611 // ldr	x17, [x16, #8]
	WORD $0xf9000df1 // str	x17, [x15, #24]
	WORD $0xf94009d1 // ldr	x17, [x14, #16]
	WORD $0xf90011f1 // str	x17, [x15, #32]
	WORD $0xd10019ad // sub	x13, x13, #6
	WORD $0xf9400a11 // ldr	x17, [x16, #16]
	WORD $0xf90015f1 // str	x17, [x15, #40]
	WORD $0x9100c1ce // add	x14, x14, #48
	WORD $0x910181ef // add	x15, x15, #96
	WORD $0x9100c210 // add	x16, x16, #48
	WORD $0xeb0d019f // cmp	x12, x13
	BNE  BB0_46
	WORD $0xcb0d03ed // neg	x13, x13

BB0_48:
	WORD $0xf100197f // cmp	x11, #6
	BEQ  BB0_51
	WORD $0xd37df1ae // lsl	x14, x13, #3
	WORD $0x8b0e004b // add	x11, x2, x14
	WORD $0x8b0d100c // add	x12, x0, x13, lsl #4
	WORD $0x9100218c // add	x12, x12, #8
	WORD $0x8b0e008d // add	x13, x4, x14

BB0_50:
	WORD $0xf84085ae // ldr	x14, [x13], #8
	WORD $0xf81f818e // stur	x14, [x12, #-8]
	WORD $0xf840856e // ldr	x14, [x11], #8
	WORD $0xf801058e // str	x14, [x12], #16
	WORD $0xf100054a // subs	x10, x10, #1
	BNE  BB0_50

BB0_51:
	WORD $0xeb08012a // subs	x10, x9, x8
	BLE  BB0_54
	WORD $0x8b080c4b // add	x11, x2, x8, lsl #3
	WORD $0x8b08100c // add	x12, x0, x8, lsl #4
	WORD $0x9100218c // add	x12, x12, #8

BB0_53:
	WORD $0xf840856d // ldr	x13, [x11], #8
	WORD $0xf801058d // str	x13, [x12], #16
	WORD $0xf100054a // subs	x10, x10, #1
	BNE  BB0_53

BB0_54:
	WORD $0xeb08013f // cmp	x9, x8
	BGE  BB0_67
	WORD $0xcb090108 // sub	x8, x8, x9
	WORD $0x8b090c8a // add	x10, x4, x9, lsl #3
	WORD $0x8b091009 // add	x9, x0, x9, lsl #4

BB0_56:
	WORD $0xf840854b // ldr	x11, [x10], #8
	WORD $0xf801052b // str	x11, [x9], #16
	WORD $0xf1000508 // subs	x8, x8, #1
	BNE  BB0_56
	B    BB0_67

BB0_57:
	WORD $0xf100099f // cmp	x12, #2
	BGE  BB0_59
	WORD $0xd280000d // mov	x13, #0                         ; =0x0
	WORD $0xeb0d018a // subs	x10, x12, x13
	BGT  BB0_62
	B    BB0_64

BB0_59:
	WORD $0x9100400b // add	x11, x0, #16
	WORD $0x5280004a // mov	w10, #2                         ; =0x2
	WORD $0xaa0403ed // mov	x13, x4
	WORD $0xaa0203ee // mov	x14, x2

BB0_60:
	WORD $0x3cc105c0 // ldr	q0, [x14], #16
	WORD $0x3cc105a1 // ldr	q1, [x13], #16
	WORD $0x4ec13802 // zip1.2d	v2, v0, v1
	WORD $0x4ec17800 // zip2.2d	v0, v0, v1
	WORD $0xad3f8162 // stp	q2, q0, [x11, #-16]
	WORD $0x9100094a // add	x10, x10, #2
	WORD $0x9100816b // add	x11, x11, #32
	WORD $0xeb0c015f // cmp	x10, x12
	BLE  BB0_60
	WORD $0xd100094d // sub	x13, x10, #2
	WORD $0xeb0d018a // subs	x10, x12, x13
	BLE  BB0_64

BB0_62:
	WORD $0xd37df1ac // lsl	x12, x13, #3
	WORD $0x8b0c008b // add	x11, x4, x12
	WORD $0x8b0c004c // add	x12, x2, x12
	WORD $0x8b0d100d // add	x13, x0, x13, lsl #4
	WORD $0x910021ad // add	x13, x13, #8

BB0_63:
	WORD $0xf840858e // ldr	x14, [x12], #8
	WORD $0xf81f81ae // stur	x14, [x13, #-8]
	WORD $0xf840856e // ldr	x14, [x11], #8
	WORD $0xf80105ae // str	x14, [x13], #16
	WORD $0xf100054a // subs	x10, x10, #1
	BNE  BB0_63

BB0_64:
	WORD $0xeb080129 // subs	x9, x9, x8
	BLE  BB0_67
	WORD $0x8b080c4a // add	x10, x2, x8, lsl #3
	WORD $0x8b081008 // add	x8, x0, x8, lsl #4

BB0_66:
	WORD $0xf840854b // ldr	x11, [x10], #8
	WORD $0xf801050b // str	x11, [x8], #16
	WORD $0xf1000529 // subs	x9, x9, #1
	BNE  BB0_66

BB0_67:
	RET
