//go:build !noasm && arm64
// Code generated by hwygen -c. DO NOT EDIT.

package asm

import "unsafe"

// LiftUpdate53_S32 calls the NEON SIMD assembly implementation.
func LiftUpdate53_S32(target unsafe.Pointer, ptLen unsafe.Pointer, neighbor unsafe.Pointer, pnLen unsafe.Pointer, pphase unsafe.Pointer) {
	liftupdate53_c_s32_neon(target, ptLen, neighbor, pnLen, pphase)
}

// LiftUpdate53_S64 calls the NEON SIMD assembly implementation.
func LiftUpdate53_S64(target unsafe.Pointer, ptLen unsafe.Pointer, neighbor unsafe.Pointer, pnLen unsafe.Pointer, pphase unsafe.Pointer) {
	liftupdate53_c_s64_neon(target, ptLen, neighbor, pnLen, pphase)
}

// LiftPredict53_S32 calls the NEON SIMD assembly implementation.
func LiftPredict53_S32(target unsafe.Pointer, ptLen unsafe.Pointer, neighbor unsafe.Pointer, pnLen unsafe.Pointer, pphase unsafe.Pointer) {
	liftpredict53_c_s32_neon(target, ptLen, neighbor, pnLen, pphase)
}

// LiftPredict53_S64 calls the NEON SIMD assembly implementation.
func LiftPredict53_S64(target unsafe.Pointer, ptLen unsafe.Pointer, neighbor unsafe.Pointer, pnLen unsafe.Pointer, pphase unsafe.Pointer) {
	liftpredict53_c_s64_neon(target, ptLen, neighbor, pnLen, pphase)
}

// LiftStep97_F16 calls the NEON SIMD assembly implementation.
func LiftStep97_F16(target unsafe.Pointer, ptLen unsafe.Pointer, neighbor unsafe.Pointer, pnLen unsafe.Pointer, coeff uint16, pphase unsafe.Pointer) {
	liftstep97_c_f16_neon(target, ptLen, neighbor, pnLen, coeff, pphase)
}

// LiftStep97_F32 calls the NEON SIMD assembly implementation.
func LiftStep97_F32(target unsafe.Pointer, ptLen unsafe.Pointer, neighbor unsafe.Pointer, pnLen unsafe.Pointer, coeff float32, pphase unsafe.Pointer) {
	liftstep97_c_f32_neon(target, ptLen, neighbor, pnLen, coeff, pphase)
}

// LiftStep97_F64 calls the NEON SIMD assembly implementation.
func LiftStep97_F64(target unsafe.Pointer, ptLen unsafe.Pointer, neighbor unsafe.Pointer, pnLen unsafe.Pointer, coeff float64, pphase unsafe.Pointer) {
	liftstep97_c_f64_neon(target, ptLen, neighbor, pnLen, coeff, pphase)
}

// ScaleSlice_F16 calls the NEON SIMD assembly implementation.
func ScaleSlice_F16(data unsafe.Pointer, pn unsafe.Pointer, scale uint16) {
	scaleslice_c_f16_neon(data, pn, scale)
}

// ScaleSlice_F32 calls the NEON SIMD assembly implementation.
func ScaleSlice_F32(data unsafe.Pointer, pn unsafe.Pointer, scale float32) {
	scaleslice_c_f32_neon(data, pn, scale)
}

// ScaleSlice_F64 calls the NEON SIMD assembly implementation.
func ScaleSlice_F64(data unsafe.Pointer, pn unsafe.Pointer, scale float64) {
	scaleslice_c_f64_neon(data, pn, scale)
}

// Synthesize53Core_S32 calls the NEON SIMD assembly implementation.
func Synthesize53Core_S32(data unsafe.Pointer, pn unsafe.Pointer, low unsafe.Pointer, psn unsafe.Pointer, high unsafe.Pointer, pdn unsafe.Pointer, pphase unsafe.Pointer) {
	synthesize53core_c_s32_neon(data, pn, low, psn, high, pdn, pphase)
}

// Synthesize53Core_S64 calls the NEON SIMD assembly implementation.
func Synthesize53Core_S64(data unsafe.Pointer, pn unsafe.Pointer, low unsafe.Pointer, psn unsafe.Pointer, high unsafe.Pointer, pdn unsafe.Pointer, pphase unsafe.Pointer) {
	synthesize53core_c_s64_neon(data, pn, low, psn, high, pdn, pphase)
}

