// Code generated by hwygen. DO NOT EDIT.

package vec

import (
	"github.com/ajroetker/go-highway/hwy"
	stdmath "math"
)

func BaseSquaredNorm_fallback_Float16(v []hwy.Float16) hwy.Float16 {
	if len(v) == 0 {
		return 0
	}
	n := len(v)
	sum := hwy.Zero[hwy.Float16]()
	lanes := sum.NumLanes()
	var i int
	for i = 0; i+lanes <= n; i += lanes {
		vec := hwy.Load(v[i:])
		prod := hwy.Mul(vec, vec)
		sum = hwy.Add(sum, prod)
	}
	result := hwy.ReduceSum(sum).Float32()
	for ; i < n; i++ {
		result += v[i].Float32() * v[i].Float32()
	}
	return hwy.Float32ToFloat16(result)
}

func BaseSquaredNorm_fallback_BFloat16(v []hwy.BFloat16) hwy.BFloat16 {
	if len(v) == 0 {
		return 0
	}
	n := len(v)
	sum := hwy.Zero[hwy.BFloat16]()
	lanes := sum.NumLanes()
	var i int
	for i = 0; i+lanes <= n; i += lanes {
		vec := hwy.Load(v[i:])
		prod := hwy.Mul(vec, vec)
		sum = hwy.Add(sum, prod)
	}
	result := hwy.ReduceSum(sum).Float32()
	for ; i < n; i++ {
		result += v[i].Float32() * v[i].Float32()
	}
	return hwy.Float32ToBFloat16(result)
}

func BaseSquaredNorm_fallback(v []float32) float32 {
	if len(v) == 0 {
		return 0
	}
	n := len(v)
	sum := hwy.Zero[float32]()
	lanes := sum.NumLanes()
	var i int
	for i = 0; i+lanes <= n; i += lanes {
		vec := hwy.Load(v[i:])
		prod := hwy.Mul(vec, vec)
		sum = hwy.Add(sum, prod)
	}
	result := hwy.ReduceSum(sum)
	for ; i < n; i++ {
		result += v[i] * v[i]
	}
	return result
}

func BaseSquaredNorm_fallback_Float64(v []float64) float64 {
	if len(v) == 0 {
		return 0
	}
	n := len(v)
	sum := hwy.Zero[float64]()
	lanes := sum.NumLanes()
	var i int
	for i = 0; i+lanes <= n; i += lanes {
		vec := hwy.Load(v[i:])
		prod := hwy.Mul(vec, vec)
		sum = hwy.Add(sum, prod)
	}
	result := hwy.ReduceSum(sum)
	for ; i < n; i++ {
		result += v[i] * v[i]
	}
	return result
}

func BaseNorm_fallback_Float16(v []hwy.Float16) hwy.Float16 {
	squaredNorm := BaseSquaredNorm_fallback_Float16(v)
	if squaredNorm == 0 {
		return 0
	}
	switch any(squaredNorm).(type) {
	case float32:
		return any(float32(stdmath.Sqrt(float64(any(squaredNorm).(float32))))).(hwy.Float16)
	case float64:
		return any(stdmath.Sqrt(any(squaredNorm).(float64))).(hwy.Float16)
	default:
		return any(float32(stdmath.Sqrt(float64(any(squaredNorm).(float32))))).(hwy.Float16)
	}
}

func BaseNorm_fallback_BFloat16(v []hwy.BFloat16) hwy.BFloat16 {
	squaredNorm := BaseSquaredNorm_fallback_BFloat16(v)
	if squaredNorm == 0 {
		return 0
	}
	switch any(squaredNorm).(type) {
	case float32:
		return any(float32(stdmath.Sqrt(float64(any(squaredNorm).(float32))))).(hwy.BFloat16)
	case float64:
		return any(stdmath.Sqrt(any(squaredNorm).(float64))).(hwy.BFloat16)
	default:
		return any(float32(stdmath.Sqrt(float64(any(squaredNorm).(float32))))).(hwy.BFloat16)
	}
}

func BaseNorm_fallback(v []float32) float32 {
	squaredNorm := BaseSquaredNorm_fallback(v)
	if squaredNorm == 0 {
		return 0
	}
	switch any(squaredNorm).(type) {
	case float32:
		return any(float32(stdmath.Sqrt(float64(any(squaredNorm).(float32))))).(float32)
	case float64:
		return any(stdmath.Sqrt(any(squaredNorm).(float64))).(float32)
	default:
		return any(float32(stdmath.Sqrt(float64(any(squaredNorm).(float32))))).(float32)
	}
}

func BaseNorm_fallback_Float64(v []float64) float64 {
	squaredNorm := BaseSquaredNorm_fallback_Float64(v)
	if squaredNorm == 0 {
		return 0
	}
	switch any(squaredNorm).(type) {
	case float32:
		return any(float32(stdmath.Sqrt(float64(any(squaredNorm).(float32))))).(float64)
	case float64:
		return any(stdmath.Sqrt(any(squaredNorm).(float64))).(float64)
	default:
		return any(float32(stdmath.Sqrt(float64(any(squaredNorm).(float32))))).(float64)
	}
}
