// Code generated by hwygen. DO NOT EDIT.
//go:build arm64

package softmax

import (
	"os"
)

var Softmax func(input []float32, output []float32)
var SoftmaxFloat64 func(input []float64, output []float64)

func init() {
	if os.Getenv("HWY_NO_SIMD") != "" {
		initFallback()
		return
	}
	initNEON()
	return
}

func initNEON() {
	Softmax = BaseSoftmax_neon
	SoftmaxFloat64 = BaseSoftmax_neon_Float64
}

func initFallback() {
	Softmax = BaseSoftmax_fallback
	SoftmaxFloat64 = BaseSoftmax_fallback_Float64
}
