// Code generated by github.com/ajroetker/go-highway/cmd/hwygen. DO NOT EDIT.

//go:build amd64 && goexperiment.simd

package activation

import (
	stdmath "math"
	"simd/archsimd"
	"unsafe"

	"github.com/ajroetker/go-highway/hwy"
	"github.com/ajroetker/go-highway/hwy/contrib/math"
)

func BaseGELU_avx512_Float16(input []hwy.Float16, output []hwy.Float16) {
	size := min(len(input), len(output))
	if size == 0 {
		return
	}
	vHalf := hwy.Const[hwy.Float16](0.5)
	vOne := hwy.Const[hwy.Float16](1.0)
	vInvSqrt2 := hwy.Const[hwy.Float16](0.7071067811865476)
	lanes := 32
	ii := 0
	for ; ii+lanes*2 <= size; ii += lanes * 2 {
		x := hwy.Load(input[ii:])
		xScaled := hwy.MulF16(x, vInvSqrt2)
		erfX := math.BaseErfVec_avx512_Float16(xScaled)
		onePlusErf := hwy.AddF16(vOne, erfX)
		halfOnePlusErf := hwy.MulF16(vHalf, onePlusErf)
		result := hwy.MulF16(x, halfOnePlusErf)
		hwy.StoreFull(result, output[ii:])
		x1 := hwy.Load(input[ii+32:])
		xScaled1 := hwy.MulF16(x1, vInvSqrt2)
		erfX1 := math.BaseErfVec_avx512_Float16(xScaled1)
		onePlusErf1 := hwy.AddF16(vOne, erfX1)
		halfOnePlusErf1 := hwy.MulF16(vHalf, onePlusErf1)
		result1 := hwy.MulF16(x1, halfOnePlusErf1)
		hwy.StoreFull(result1, output[ii+32:])
	}
	for ; ii+lanes <= size; ii += lanes {
		x := hwy.Load(input[ii:])
		xScaled := hwy.MulF16(x, vInvSqrt2)
		erfX := math.BaseErfVec_avx512_Float16(xScaled)
		onePlusErf := hwy.AddF16(vOne, erfX)
		halfOnePlusErf := hwy.MulF16(vHalf, onePlusErf)
		result := hwy.MulF16(x, halfOnePlusErf)
		hwy.StoreFull(result, output[ii:])
	}
	for i := ii; i < size; i++ {
		x := float64(input[i].Float32())
		output[i] = hwy.Float32ToFloat16(float32(x * 0.5 * (1.0 + stdmath.Erf(x*0.7071067811865476))))
	}
}

func BaseGELU_avx512_BFloat16(input []hwy.BFloat16, output []hwy.BFloat16) {
	size := min(len(input), len(output))
	if size == 0 {
		return
	}
	vHalf := hwy.Const[hwy.BFloat16](0.5)
	vOne := hwy.Const[hwy.BFloat16](1.0)
	vInvSqrt2 := hwy.Const[hwy.BFloat16](0.7071067811865476)
	lanes := 32
	ii := 0
	for ; ii+lanes*2 <= size; ii += lanes * 2 {
		x := hwy.Load(input[ii:])
		xScaled := hwy.MulBF16(x, vInvSqrt2)
		erfX := math.BaseErfVec_avx512_BFloat16(xScaled)
		onePlusErf := hwy.AddBF16(vOne, erfX)
		halfOnePlusErf := hwy.MulBF16(vHalf, onePlusErf)
		result := hwy.MulBF16(x, halfOnePlusErf)
		hwy.StoreFull(result, output[ii:])
		x1 := hwy.Load(input[ii+32:])
		xScaled1 := hwy.MulBF16(x1, vInvSqrt2)
		erfX1 := math.BaseErfVec_avx512_BFloat16(xScaled1)
		onePlusErf1 := hwy.AddBF16(vOne, erfX1)
		halfOnePlusErf1 := hwy.MulBF16(vHalf, onePlusErf1)
		result1 := hwy.MulBF16(x1, halfOnePlusErf1)
		hwy.StoreFull(result1, output[ii+32:])
	}
	for ; ii+lanes <= size; ii += lanes {
		x := hwy.Load(input[ii:])
		xScaled := hwy.MulBF16(x, vInvSqrt2)
		erfX := math.BaseErfVec_avx512_BFloat16(xScaled)
		onePlusErf := hwy.AddBF16(vOne, erfX)
		halfOnePlusErf := hwy.MulBF16(vHalf, onePlusErf)
		result := hwy.MulBF16(x, halfOnePlusErf)
		hwy.StoreFull(result, output[ii:])
	}
	for i := ii; i < size; i++ {
		x := float64(input[i].Float32())
		output[i] = hwy.Float32ToBFloat16(float32(x * 0.5 * (1.0 + stdmath.Erf(x*0.7071067811865476))))
	}
}

func BaseGELU_avx512(input []float32, output []float32) {
	size := min(len(input), len(output))
	if size == 0 {
		return
	}
	vHalf := archsimd.BroadcastFloat32x16(0.5)
	vOne := archsimd.BroadcastFloat32x16(1.0)
	vInvSqrt2 := archsimd.BroadcastFloat32x16(0.7071067811865476)
	lanes := 16
	ii := 0
	for ; ii+lanes*2 <= size; ii += lanes * 2 {
		x := archsimd.LoadFloat32x16((*[16]float32)(unsafe.Pointer(&input[ii])))
		xScaled := x.Mul(vInvSqrt2)
		erfX := math.BaseErfVec_avx512(xScaled)
		onePlusErf := vOne.Add(erfX)
		halfOnePlusErf := vHalf.Mul(onePlusErf)
		result := x.Mul(halfOnePlusErf)
		result.Store((*[16]float32)(unsafe.Pointer(&output[ii])))
		x1 := archsimd.LoadFloat32x16((*[16]float32)(unsafe.Pointer(&input[ii+16])))
		xScaled1 := x1.Mul(vInvSqrt2)
		erfX1 := math.BaseErfVec_avx512(xScaled1)
		onePlusErf1 := vOne.Add(erfX1)
		halfOnePlusErf1 := vHalf.Mul(onePlusErf1)
		result1 := x1.Mul(halfOnePlusErf1)
		result1.Store((*[16]float32)(unsafe.Pointer(&output[ii+16])))
	}
	for ; ii+lanes <= size; ii += lanes {
		x := archsimd.LoadFloat32x16((*[16]float32)(unsafe.Pointer(&input[ii])))
		xScaled := x.Mul(vInvSqrt2)
		erfX := math.BaseErfVec_avx512(xScaled)
		onePlusErf := vOne.Add(erfX)
		halfOnePlusErf := vHalf.Mul(onePlusErf)
		result := x.Mul(halfOnePlusErf)
		result.Store((*[16]float32)(unsafe.Pointer(&output[ii])))
	}
	for i := ii; i < size; i++ {
		x := float64(input[i])
		output[i] = float32(x * 0.5 * (1.0 + stdmath.Erf(x*0.7071067811865476)))
	}
}

func BaseGELU_avx512_Float64(input []float64, output []float64) {
	size := min(len(input), len(output))
	if size == 0 {
		return
	}
	vHalf := archsimd.BroadcastFloat64x8(0.5)
	vOne := archsimd.BroadcastFloat64x8(1.0)
	vInvSqrt2 := archsimd.BroadcastFloat64x8(0.7071067811865476)
	lanes := 8
	ii := 0
	for ; ii+lanes*2 <= size; ii += lanes * 2 {
		x := archsimd.LoadFloat64x8((*[8]float64)(unsafe.Pointer(&input[ii])))
		xScaled := x.Mul(vInvSqrt2)
		erfX := math.BaseErfVec_avx512_Float64(xScaled)
		onePlusErf := vOne.Add(erfX)
		halfOnePlusErf := vHalf.Mul(onePlusErf)
		result := x.Mul(halfOnePlusErf)
		result.Store((*[8]float64)(unsafe.Pointer(&output[ii])))
		x1 := archsimd.LoadFloat64x8((*[8]float64)(unsafe.Pointer(&input[ii+8])))
		xScaled1 := x1.Mul(vInvSqrt2)
		erfX1 := math.BaseErfVec_avx512_Float64(xScaled1)
		onePlusErf1 := vOne.Add(erfX1)
		halfOnePlusErf1 := vHalf.Mul(onePlusErf1)
		result1 := x1.Mul(halfOnePlusErf1)
		result1.Store((*[8]float64)(unsafe.Pointer(&output[ii+8])))
	}
	for ; ii+lanes <= size; ii += lanes {
		x := archsimd.LoadFloat64x8((*[8]float64)(unsafe.Pointer(&input[ii])))
		xScaled := x.Mul(vInvSqrt2)
		erfX := math.BaseErfVec_avx512_Float64(xScaled)
		onePlusErf := vOne.Add(erfX)
		halfOnePlusErf := vHalf.Mul(onePlusErf)
		result := x.Mul(halfOnePlusErf)
		result.Store((*[8]float64)(unsafe.Pointer(&output[ii])))
	}
	for i := ii; i < size; i++ {
		x := float64(input[i])
		output[i] = float64(x * 0.5 * (1.0 + stdmath.Erf(x*0.7071067811865476)))
	}
}

func BaseGELUApprox_avx512_Float16(input []hwy.Float16, output []hwy.Float16) {
	size := min(len(input), len(output))
	if size == 0 {
		return
	}
	vCoeff := hwy.Const[hwy.Float16](1.702)
	lanes := 32
	ii := 0
	for ; ii+lanes*2 <= size; ii += lanes * 2 {
		x := hwy.Load(input[ii:])
		xScaled := hwy.MulF16(x, vCoeff)
		sigmoidX := math.BaseSigmoidVec_avx512_Float16(xScaled)
		result := hwy.MulF16(x, sigmoidX)
		hwy.StoreFull(result, output[ii:])
		x1 := hwy.Load(input[ii+32:])
		xScaled1 := hwy.MulF16(x1, vCoeff)
		sigmoidX1 := math.BaseSigmoidVec_avx512_Float16(xScaled1)
		result1 := hwy.MulF16(x1, sigmoidX1)
		hwy.StoreFull(result1, output[ii+32:])
	}
	for ; ii+lanes <= size; ii += lanes {
		x := hwy.Load(input[ii:])
		xScaled := hwy.MulF16(x, vCoeff)
		sigmoidX := math.BaseSigmoidVec_avx512_Float16(xScaled)
		result := hwy.MulF16(x, sigmoidX)
		hwy.StoreFull(result, output[ii:])
	}
	for i := ii; i < size; i++ {
		x := float64(input[i].Float32())
		sigmoid := 1.0 / (1.0 + stdmath.Exp(-1.702*x))
		output[i] = hwy.Float32ToFloat16(float32(x * sigmoid))
	}
}

func BaseGELUApprox_avx512_BFloat16(input []hwy.BFloat16, output []hwy.BFloat16) {
	size := min(len(input), len(output))
	if size == 0 {
		return
	}
	vCoeff := hwy.Const[hwy.BFloat16](1.702)
	lanes := 32
	ii := 0
	for ; ii+lanes*2 <= size; ii += lanes * 2 {
		x := hwy.Load(input[ii:])
		xScaled := hwy.MulBF16(x, vCoeff)
		sigmoidX := math.BaseSigmoidVec_avx512_BFloat16(xScaled)
		result := hwy.MulBF16(x, sigmoidX)
		hwy.StoreFull(result, output[ii:])
		x1 := hwy.Load(input[ii+32:])
		xScaled1 := hwy.MulBF16(x1, vCoeff)
		sigmoidX1 := math.BaseSigmoidVec_avx512_BFloat16(xScaled1)
		result1 := hwy.MulBF16(x1, sigmoidX1)
		hwy.StoreFull(result1, output[ii+32:])
	}
	for ; ii+lanes <= size; ii += lanes {
		x := hwy.Load(input[ii:])
		xScaled := hwy.MulBF16(x, vCoeff)
		sigmoidX := math.BaseSigmoidVec_avx512_BFloat16(xScaled)
		result := hwy.MulBF16(x, sigmoidX)
		hwy.StoreFull(result, output[ii:])
	}
	for i := ii; i < size; i++ {
		x := float64(input[i].Float32())
		sigmoid := 1.0 / (1.0 + stdmath.Exp(-1.702*x))
		output[i] = hwy.Float32ToBFloat16(float32(x * sigmoid))
	}
}

func BaseGELUApprox_avx512(input []float32, output []float32) {
	size := min(len(input), len(output))
	if size == 0 {
		return
	}
	vCoeff := archsimd.BroadcastFloat32x16(1.702)
	lanes := 16
	ii := 0
	for ; ii+lanes*2 <= size; ii += lanes * 2 {
		x := archsimd.LoadFloat32x16((*[16]float32)(unsafe.Pointer(&input[ii])))
		xScaled := x.Mul(vCoeff)
		sigmoidX := math.BaseSigmoidVec_avx512(xScaled)
		result := x.Mul(sigmoidX)
		result.Store((*[16]float32)(unsafe.Pointer(&output[ii])))
		x1 := archsimd.LoadFloat32x16((*[16]float32)(unsafe.Pointer(&input[ii+16])))
		xScaled1 := x1.Mul(vCoeff)
		sigmoidX1 := math.BaseSigmoidVec_avx512(xScaled1)
		result1 := x1.Mul(sigmoidX1)
		result1.Store((*[16]float32)(unsafe.Pointer(&output[ii+16])))
	}
	for ; ii+lanes <= size; ii += lanes {
		x := archsimd.LoadFloat32x16((*[16]float32)(unsafe.Pointer(&input[ii])))
		xScaled := x.Mul(vCoeff)
		sigmoidX := math.BaseSigmoidVec_avx512(xScaled)
		result := x.Mul(sigmoidX)
		result.Store((*[16]float32)(unsafe.Pointer(&output[ii])))
	}
	for i := ii; i < size; i++ {
		x := float64(input[i])
		sigmoid := 1.0 / (1.0 + stdmath.Exp(-1.702*x))
		output[i] = float32(x * sigmoid)
	}
}

func BaseGELUApprox_avx512_Float64(input []float64, output []float64) {
	size := min(len(input), len(output))
	if size == 0 {
		return
	}
	vCoeff := archsimd.BroadcastFloat64x8(1.702)
	lanes := 8
	ii := 0
	for ; ii+lanes*2 <= size; ii += lanes * 2 {
		x := archsimd.LoadFloat64x8((*[8]float64)(unsafe.Pointer(&input[ii])))
		xScaled := x.Mul(vCoeff)
		sigmoidX := math.BaseSigmoidVec_avx512_Float64(xScaled)
		result := x.Mul(sigmoidX)
		result.Store((*[8]float64)(unsafe.Pointer(&output[ii])))
		x1 := archsimd.LoadFloat64x8((*[8]float64)(unsafe.Pointer(&input[ii+8])))
		xScaled1 := x1.Mul(vCoeff)
		sigmoidX1 := math.BaseSigmoidVec_avx512_Float64(xScaled1)
		result1 := x1.Mul(sigmoidX1)
		result1.Store((*[8]float64)(unsafe.Pointer(&output[ii+8])))
	}
	for ; ii+lanes <= size; ii += lanes {
		x := archsimd.LoadFloat64x8((*[8]float64)(unsafe.Pointer(&input[ii])))
		xScaled := x.Mul(vCoeff)
		sigmoidX := math.BaseSigmoidVec_avx512_Float64(xScaled)
		result := x.Mul(sigmoidX)
		result.Store((*[8]float64)(unsafe.Pointer(&output[ii])))
	}
	for i := ii; i < size; i++ {
		x := float64(input[i])
		sigmoid := 1.0 / (1.0 + stdmath.Exp(-1.702*x))
		output[i] = float64(x * sigmoid)
	}
}

func BaseReLU_avx512_Float16(input []hwy.Float16, output []hwy.Float16) {
	size := min(len(input), len(output))
	if size == 0 {
		return
	}
	vZero := hwy.Const[hwy.Float16](0.0)
	lanes := 32
	ii := 0
	for ; ii+lanes*3 <= size; ii += lanes * 3 {
		x := hwy.Load(input[ii:])
		result := hwy.MaxF16(x, vZero)
		hwy.StoreFull(result, output[ii:])
		x1 := hwy.Load(input[ii+32:])
		result1 := hwy.MaxF16(x1, vZero)
		hwy.StoreFull(result1, output[ii+32:])
		x2 := hwy.Load(input[ii+64:])
		result2 := hwy.MaxF16(x2, vZero)
		hwy.StoreFull(result2, output[ii+64:])
	}
	for ; ii+lanes <= size; ii += lanes {
		x := hwy.Load(input[ii:])
		result := hwy.MaxF16(x, vZero)
		hwy.StoreFull(result, output[ii:])
	}
	for i := ii; i < size; i++ {
		if input[i].Float32() > 0 {
			output[i] = hwy.Float32ToFloat16(input[i].Float32())
		} else {
			output[i] = hwy.Float32ToFloat16(0)
		}
	}
}

func BaseReLU_avx512_BFloat16(input []hwy.BFloat16, output []hwy.BFloat16) {
	size := min(len(input), len(output))
	if size == 0 {
		return
	}
	vZero := hwy.Const[hwy.BFloat16](0.0)
	lanes := 32
	ii := 0
	for ; ii+lanes*3 <= size; ii += lanes * 3 {
		x := hwy.Load(input[ii:])
		result := hwy.MaxBF16(x, vZero)
		hwy.StoreFull(result, output[ii:])
		x1 := hwy.Load(input[ii+32:])
		result1 := hwy.MaxBF16(x1, vZero)
		hwy.StoreFull(result1, output[ii+32:])
		x2 := hwy.Load(input[ii+64:])
		result2 := hwy.MaxBF16(x2, vZero)
		hwy.StoreFull(result2, output[ii+64:])
	}
	for ; ii+lanes <= size; ii += lanes {
		x := hwy.Load(input[ii:])
		result := hwy.MaxBF16(x, vZero)
		hwy.StoreFull(result, output[ii:])
	}
	for i := ii; i < size; i++ {
		if input[i].Float32() > 0 {
			output[i] = hwy.Float32ToBFloat16(input[i].Float32())
		} else {
			output[i] = hwy.Float32ToBFloat16(0)
		}
	}
}

func BaseReLU_avx512(input []float32, output []float32) {
	size := min(len(input), len(output))
	if size == 0 {
		return
	}
	vZero := archsimd.BroadcastFloat32x16(0.0)
	lanes := 16
	ii := 0
	for ; ii+lanes*3 <= size; ii += lanes * 3 {
		x := archsimd.LoadFloat32x16((*[16]float32)(unsafe.Pointer(&input[ii])))
		result := x.Max(vZero)
		result.Store((*[16]float32)(unsafe.Pointer(&output[ii])))
		x1 := archsimd.LoadFloat32x16((*[16]float32)(unsafe.Pointer(&input[ii+16])))
		result1 := x1.Max(vZero)
		result1.Store((*[16]float32)(unsafe.Pointer(&output[ii+16])))
		x2 := archsimd.LoadFloat32x16((*[16]float32)(unsafe.Pointer(&input[ii+32])))
		result2 := x2.Max(vZero)
		result2.Store((*[16]float32)(unsafe.Pointer(&output[ii+32])))
	}
	for ; ii+lanes <= size; ii += lanes {
		x := archsimd.LoadFloat32x16((*[16]float32)(unsafe.Pointer(&input[ii])))
		result := x.Max(vZero)
		result.Store((*[16]float32)(unsafe.Pointer(&output[ii])))
	}
	for i := ii; i < size; i++ {
		if input[i] > 0 {
			output[i] = input[i]
		} else {
			output[i] = 0
		}
	}
}

func BaseReLU_avx512_Float64(input []float64, output []float64) {
	size := min(len(input), len(output))
	if size == 0 {
		return
	}
	vZero := archsimd.BroadcastFloat64x8(0.0)
	lanes := 8
	ii := 0
	for ; ii+lanes*3 <= size; ii += lanes * 3 {
		x := archsimd.LoadFloat64x8((*[8]float64)(unsafe.Pointer(&input[ii])))
		result := x.Max(vZero)
		result.Store((*[8]float64)(unsafe.Pointer(&output[ii])))
		x1 := archsimd.LoadFloat64x8((*[8]float64)(unsafe.Pointer(&input[ii+8])))
		result1 := x1.Max(vZero)
		result1.Store((*[8]float64)(unsafe.Pointer(&output[ii+8])))
		x2 := archsimd.LoadFloat64x8((*[8]float64)(unsafe.Pointer(&input[ii+16])))
		result2 := x2.Max(vZero)
		result2.Store((*[8]float64)(unsafe.Pointer(&output[ii+16])))
	}
	for ; ii+lanes <= size; ii += lanes {
		x := archsimd.LoadFloat64x8((*[8]float64)(unsafe.Pointer(&input[ii])))
		result := x.Max(vZero)
		result.Store((*[8]float64)(unsafe.Pointer(&output[ii])))
	}
	for i := ii; i < size; i++ {
		if input[i] > 0 {
			output[i] = input[i]
		} else {
			output[i] = 0
		}
	}
}

func BaseSiLU_avx512_Float16(input []hwy.Float16, output []hwy.Float16) {
	size := min(len(input), len(output))
	if size == 0 {
		return
	}
	lanes := 32
	ii := 0
	for ; ii+lanes*2 <= size; ii += lanes * 2 {
		x := hwy.Load(input[ii:])
		sigmoidX := math.BaseSigmoidVec_avx512_Float16(x)
		result := hwy.MulF16(x, sigmoidX)
		hwy.StoreFull(result, output[ii:])
		x1 := hwy.Load(input[ii+32:])
		sigmoidX1 := math.BaseSigmoidVec_avx512_Float16(x1)
		result1 := hwy.MulF16(x1, sigmoidX1)
		hwy.StoreFull(result1, output[ii+32:])
	}
	for ; ii+lanes <= size; ii += lanes {
		x := hwy.Load(input[ii:])
		sigmoidX := math.BaseSigmoidVec_avx512_Float16(x)
		result := hwy.MulF16(x, sigmoidX)
		hwy.StoreFull(result, output[ii:])
	}
	for i := ii; i < size; i++ {
		x := float64(input[i].Float32())
		sigmoid := 1.0 / (1.0 + stdmath.Exp(-x))
		output[i] = hwy.Float32ToFloat16(float32(x * sigmoid))
	}
}

func BaseSiLU_avx512_BFloat16(input []hwy.BFloat16, output []hwy.BFloat16) {
	size := min(len(input), len(output))
	if size == 0 {
		return
	}
	lanes := 32
	ii := 0
	for ; ii+lanes*2 <= size; ii += lanes * 2 {
		x := hwy.Load(input[ii:])
		sigmoidX := math.BaseSigmoidVec_avx512_BFloat16(x)
		result := hwy.MulBF16(x, sigmoidX)
		hwy.StoreFull(result, output[ii:])
		x1 := hwy.Load(input[ii+32:])
		sigmoidX1 := math.BaseSigmoidVec_avx512_BFloat16(x1)
		result1 := hwy.MulBF16(x1, sigmoidX1)
		hwy.StoreFull(result1, output[ii+32:])
	}
	for ; ii+lanes <= size; ii += lanes {
		x := hwy.Load(input[ii:])
		sigmoidX := math.BaseSigmoidVec_avx512_BFloat16(x)
		result := hwy.MulBF16(x, sigmoidX)
		hwy.StoreFull(result, output[ii:])
	}
	for i := ii; i < size; i++ {
		x := float64(input[i].Float32())
		sigmoid := 1.0 / (1.0 + stdmath.Exp(-x))
		output[i] = hwy.Float32ToBFloat16(float32(x * sigmoid))
	}
}

func BaseSiLU_avx512(input []float32, output []float32) {
	size := min(len(input), len(output))
	if size == 0 {
		return
	}
	lanes := 16
	ii := 0
	for ; ii+lanes*2 <= size; ii += lanes * 2 {
		x := archsimd.LoadFloat32x16((*[16]float32)(unsafe.Pointer(&input[ii])))
		sigmoidX := math.BaseSigmoidVec_avx512(x)
		result := x.Mul(sigmoidX)
		result.Store((*[16]float32)(unsafe.Pointer(&output[ii])))
		x1 := archsimd.LoadFloat32x16((*[16]float32)(unsafe.Pointer(&input[ii+16])))
		sigmoidX1 := math.BaseSigmoidVec_avx512(x1)
		result1 := x1.Mul(sigmoidX1)
		result1.Store((*[16]float32)(unsafe.Pointer(&output[ii+16])))
	}
	for ; ii+lanes <= size; ii += lanes {
		x := archsimd.LoadFloat32x16((*[16]float32)(unsafe.Pointer(&input[ii])))
		sigmoidX := math.BaseSigmoidVec_avx512(x)
		result := x.Mul(sigmoidX)
		result.Store((*[16]float32)(unsafe.Pointer(&output[ii])))
	}
	for i := ii; i < size; i++ {
		x := float64(input[i])
		sigmoid := 1.0 / (1.0 + stdmath.Exp(-x))
		output[i] = float32(x * sigmoid)
	}
}

func BaseSiLU_avx512_Float64(input []float64, output []float64) {
	size := min(len(input), len(output))
	if size == 0 {
		return
	}
	lanes := 8
	ii := 0
	for ; ii+lanes*2 <= size; ii += lanes * 2 {
		x := archsimd.LoadFloat64x8((*[8]float64)(unsafe.Pointer(&input[ii])))
		sigmoidX := math.BaseSigmoidVec_avx512_Float64(x)
		result := x.Mul(sigmoidX)
		result.Store((*[8]float64)(unsafe.Pointer(&output[ii])))
		x1 := archsimd.LoadFloat64x8((*[8]float64)(unsafe.Pointer(&input[ii+8])))
		sigmoidX1 := math.BaseSigmoidVec_avx512_Float64(x1)
		result1 := x1.Mul(sigmoidX1)
		result1.Store((*[8]float64)(unsafe.Pointer(&output[ii+8])))
	}
	for ; ii+lanes <= size; ii += lanes {
		x := archsimd.LoadFloat64x8((*[8]float64)(unsafe.Pointer(&input[ii])))
		sigmoidX := math.BaseSigmoidVec_avx512_Float64(x)
		result := x.Mul(sigmoidX)
		result.Store((*[8]float64)(unsafe.Pointer(&output[ii])))
	}
	for i := ii; i < size; i++ {
		x := float64(input[i])
		sigmoid := 1.0 / (1.0 + stdmath.Exp(-x))
		output[i] = float64(x * sigmoid)
	}
}

func BaseLeakyReLU_avx512_Float16(input []hwy.Float16, output []hwy.Float16, alpha hwy.Float16) {
	size := min(len(input), len(output))
	if size == 0 {
		return
	}
	vAlpha := hwy.Set(alpha)
	lanes := 32
	ii := 0
	for ; ii+lanes*3 <= size; ii += lanes * 3 {
		x := hwy.Load(input[ii:])
		negPart := hwy.MulF16(x, vAlpha)
		result := hwy.MaxF16(x, negPart)
		hwy.StoreFull(result, output[ii:])
		x1 := hwy.Load(input[ii+32:])
		negPart1 := hwy.MulF16(x1, vAlpha)
		result1 := hwy.MaxF16(x1, negPart1)
		hwy.StoreFull(result1, output[ii+32:])
		x2 := hwy.Load(input[ii+64:])
		negPart2 := hwy.MulF16(x2, vAlpha)
		result2 := hwy.MaxF16(x2, negPart2)
		hwy.StoreFull(result2, output[ii+64:])
	}
	for ; ii+lanes <= size; ii += lanes {
		x := hwy.Load(input[ii:])
		negPart := hwy.MulF16(x, vAlpha)
		result := hwy.MaxF16(x, negPart)
		hwy.StoreFull(result, output[ii:])
	}
	for i := ii; i < size; i++ {
		if input[i].Float32() > 0 {
			output[i] = hwy.Float32ToFloat16(input[i].Float32())
		} else {
			output[i] = hwy.Float32ToFloat16(alpha.Float32() * input[i].Float32())
		}
	}
}

func BaseLeakyReLU_avx512_BFloat16(input []hwy.BFloat16, output []hwy.BFloat16, alpha hwy.BFloat16) {
	size := min(len(input), len(output))
	if size == 0 {
		return
	}
	vAlpha := hwy.Set(alpha)
	lanes := 32
	ii := 0
	for ; ii+lanes*3 <= size; ii += lanes * 3 {
		x := hwy.Load(input[ii:])
		negPart := hwy.MulBF16(x, vAlpha)
		result := hwy.MaxBF16(x, negPart)
		hwy.StoreFull(result, output[ii:])
		x1 := hwy.Load(input[ii+32:])
		negPart1 := hwy.MulBF16(x1, vAlpha)
		result1 := hwy.MaxBF16(x1, negPart1)
		hwy.StoreFull(result1, output[ii+32:])
		x2 := hwy.Load(input[ii+64:])
		negPart2 := hwy.MulBF16(x2, vAlpha)
		result2 := hwy.MaxBF16(x2, negPart2)
		hwy.StoreFull(result2, output[ii+64:])
	}
	for ; ii+lanes <= size; ii += lanes {
		x := hwy.Load(input[ii:])
		negPart := hwy.MulBF16(x, vAlpha)
		result := hwy.MaxBF16(x, negPart)
		hwy.StoreFull(result, output[ii:])
	}
	for i := ii; i < size; i++ {
		if input[i].Float32() > 0 {
			output[i] = hwy.Float32ToBFloat16(input[i].Float32())
		} else {
			output[i] = hwy.Float32ToBFloat16(alpha.Float32() * input[i].Float32())
		}
	}
}

func BaseLeakyReLU_avx512(input []float32, output []float32, alpha float32) {
	size := min(len(input), len(output))
	if size == 0 {
		return
	}
	vAlpha := archsimd.BroadcastFloat32x16(alpha)
	lanes := 16
	ii := 0
	for ; ii+lanes*3 <= size; ii += lanes * 3 {
		x := archsimd.LoadFloat32x16((*[16]float32)(unsafe.Pointer(&input[ii])))
		negPart := x.Mul(vAlpha)
		result := x.Max(negPart)
		result.Store((*[16]float32)(unsafe.Pointer(&output[ii])))
		x1 := archsimd.LoadFloat32x16((*[16]float32)(unsafe.Pointer(&input[ii+16])))
		negPart1 := x1.Mul(vAlpha)
		result1 := x1.Max(negPart1)
		result1.Store((*[16]float32)(unsafe.Pointer(&output[ii+16])))
		x2 := archsimd.LoadFloat32x16((*[16]float32)(unsafe.Pointer(&input[ii+32])))
		negPart2 := x2.Mul(vAlpha)
		result2 := x2.Max(negPart2)
		result2.Store((*[16]float32)(unsafe.Pointer(&output[ii+32])))
	}
	for ; ii+lanes <= size; ii += lanes {
		x := archsimd.LoadFloat32x16((*[16]float32)(unsafe.Pointer(&input[ii])))
		negPart := x.Mul(vAlpha)
		result := x.Max(negPart)
		result.Store((*[16]float32)(unsafe.Pointer(&output[ii])))
	}
	for i := ii; i < size; i++ {
		if input[i] > 0 {
			output[i] = input[i]
		} else {
			output[i] = alpha * input[i]
		}
	}
}

func BaseLeakyReLU_avx512_Float64(input []float64, output []float64, alpha float64) {
	size := min(len(input), len(output))
	if size == 0 {
		return
	}
	vAlpha := archsimd.BroadcastFloat64x8(alpha)
	lanes := 8
	ii := 0
	for ; ii+lanes*3 <= size; ii += lanes * 3 {
		x := archsimd.LoadFloat64x8((*[8]float64)(unsafe.Pointer(&input[ii])))
		negPart := x.Mul(vAlpha)
		result := x.Max(negPart)
		result.Store((*[8]float64)(unsafe.Pointer(&output[ii])))
		x1 := archsimd.LoadFloat64x8((*[8]float64)(unsafe.Pointer(&input[ii+8])))
		negPart1 := x1.Mul(vAlpha)
		result1 := x1.Max(negPart1)
		result1.Store((*[8]float64)(unsafe.Pointer(&output[ii+8])))
		x2 := archsimd.LoadFloat64x8((*[8]float64)(unsafe.Pointer(&input[ii+16])))
		negPart2 := x2.Mul(vAlpha)
		result2 := x2.Max(negPart2)
		result2.Store((*[8]float64)(unsafe.Pointer(&output[ii+16])))
	}
	for ; ii+lanes <= size; ii += lanes {
		x := archsimd.LoadFloat64x8((*[8]float64)(unsafe.Pointer(&input[ii])))
		negPart := x.Mul(vAlpha)
		result := x.Max(negPart)
		result.Store((*[8]float64)(unsafe.Pointer(&output[ii])))
	}
	for i := ii; i < size; i++ {
		if input[i] > 0 {
			output[i] = input[i]
		} else {
			output[i] = alpha * input[i]
		}
	}
}

func BaseELU_avx512_Float16(input []hwy.Float16, output []hwy.Float16, alpha hwy.Float16) {
	size := min(len(input), len(output))
	if size == 0 {
		return
	}
	vZero := hwy.Const[hwy.Float16](0.0)
	vOne := hwy.Const[hwy.Float16](1.0)
	vAlpha := hwy.Set(alpha)
	lanes := 32
	ii := 0
	for ; ii+lanes*2 <= size; ii += lanes * 2 {
		x := hwy.Load(input[ii:])
		expX := math.BaseExpVec_avx512_Float16(x)
		expM1 := hwy.SubF16(expX, vOne)
		negPart := hwy.MulF16(vAlpha, expM1)
		isPositive := hwy.GreaterThanF16(x, vZero)
		result := hwy.IfThenElseF16(isPositive, x, negPart)
		hwy.StoreFull(result, output[ii:])
		x1 := hwy.Load(input[ii+32:])
		expX1 := math.BaseExpVec_avx512_Float16(x1)
		expM11 := hwy.SubF16(expX1, vOne)
		negPart1 := hwy.MulF16(vAlpha, expM11)
		isPositive1 := hwy.GreaterThanF16(x1, vZero)
		result1 := hwy.IfThenElseF16(isPositive1, x1, negPart1)
		hwy.StoreFull(result1, output[ii+32:])
	}
	for ; ii+lanes <= size; ii += lanes {
		x := hwy.Load(input[ii:])
		expX := math.BaseExpVec_avx512_Float16(x)
		expM1 := hwy.SubF16(expX, vOne)
		negPart := hwy.MulF16(vAlpha, expM1)
		isPositive := hwy.GreaterThanF16(x, vZero)
		result := hwy.IfThenElseF16(isPositive, x, negPart)
		hwy.StoreFull(result, output[ii:])
	}
	for i := ii; i < size; i++ {
		if input[i].Float32() > 0 {
			output[i] = hwy.Float32ToFloat16(input[i].Float32())
		} else {
			x := float64(input[i].Float32())
			output[i] = hwy.Float32ToFloat16(float32(float64(alpha) * (stdmath.Exp(x) - 1.0)))
		}
	}
}

func BaseELU_avx512_BFloat16(input []hwy.BFloat16, output []hwy.BFloat16, alpha hwy.BFloat16) {
	size := min(len(input), len(output))
	if size == 0 {
		return
	}
	vZero := hwy.Const[hwy.BFloat16](0.0)
	vOne := hwy.Const[hwy.BFloat16](1.0)
	vAlpha := hwy.Set(alpha)
	lanes := 32
	ii := 0
	for ; ii+lanes*2 <= size; ii += lanes * 2 {
		x := hwy.Load(input[ii:])
		expX := math.BaseExpVec_avx512_BFloat16(x)
		expM1 := hwy.SubBF16(expX, vOne)
		negPart := hwy.MulBF16(vAlpha, expM1)
		isPositive := hwy.GreaterThanBF16(x, vZero)
		result := hwy.IfThenElseBF16(isPositive, x, negPart)
		hwy.StoreFull(result, output[ii:])
		x1 := hwy.Load(input[ii+32:])
		expX1 := math.BaseExpVec_avx512_BFloat16(x1)
		expM11 := hwy.SubBF16(expX1, vOne)
		negPart1 := hwy.MulBF16(vAlpha, expM11)
		isPositive1 := hwy.GreaterThanBF16(x1, vZero)
		result1 := hwy.IfThenElseBF16(isPositive1, x1, negPart1)
		hwy.StoreFull(result1, output[ii+32:])
	}
	for ; ii+lanes <= size; ii += lanes {
		x := hwy.Load(input[ii:])
		expX := math.BaseExpVec_avx512_BFloat16(x)
		expM1 := hwy.SubBF16(expX, vOne)
		negPart := hwy.MulBF16(vAlpha, expM1)
		isPositive := hwy.GreaterThanBF16(x, vZero)
		result := hwy.IfThenElseBF16(isPositive, x, negPart)
		hwy.StoreFull(result, output[ii:])
	}
	for i := ii; i < size; i++ {
		if input[i].Float32() > 0 {
			output[i] = hwy.Float32ToBFloat16(input[i].Float32())
		} else {
			x := float64(input[i].Float32())
			output[i] = hwy.Float32ToBFloat16(float32(float64(alpha) * (stdmath.Exp(x) - 1.0)))
		}
	}
}

func BaseELU_avx512(input []float32, output []float32, alpha float32) {
	size := min(len(input), len(output))
	if size == 0 {
		return
	}
	vZero := archsimd.BroadcastFloat32x16(0.0)
	vOne := archsimd.BroadcastFloat32x16(1.0)
	vAlpha := archsimd.BroadcastFloat32x16(alpha)
	lanes := 16
	ii := 0
	for ; ii+lanes*2 <= size; ii += lanes * 2 {
		x := archsimd.LoadFloat32x16((*[16]float32)(unsafe.Pointer(&input[ii])))
		expX := math.BaseExpVec_avx512(x)
		expM1 := expX.Sub(vOne)
		negPart := vAlpha.Mul(expM1)
		isPositive := x.Greater(vZero)
		result := x.Merge(negPart, isPositive)
		result.Store((*[16]float32)(unsafe.Pointer(&output[ii])))
		x1 := archsimd.LoadFloat32x16((*[16]float32)(unsafe.Pointer(&input[ii+16])))
		expX1 := math.BaseExpVec_avx512(x1)
		expM11 := expX1.Sub(vOne)
		negPart1 := vAlpha.Mul(expM11)
		isPositive1 := x1.Greater(vZero)
		result1 := x1.Merge(negPart1, isPositive1)
		result1.Store((*[16]float32)(unsafe.Pointer(&output[ii+16])))
	}
	for ; ii+lanes <= size; ii += lanes {
		x := archsimd.LoadFloat32x16((*[16]float32)(unsafe.Pointer(&input[ii])))
		expX := math.BaseExpVec_avx512(x)
		expM1 := expX.Sub(vOne)
		negPart := vAlpha.Mul(expM1)
		isPositive := x.Greater(vZero)
		result := x.Merge(negPart, isPositive)
		result.Store((*[16]float32)(unsafe.Pointer(&output[ii])))
	}
	for i := ii; i < size; i++ {
		if input[i] > 0 {
			output[i] = input[i]
		} else {
			x := float64(input[i])
			output[i] = float32(float64(alpha) * (stdmath.Exp(x) - 1.0))
		}
	}
}

func BaseELU_avx512_Float64(input []float64, output []float64, alpha float64) {
	size := min(len(input), len(output))
	if size == 0 {
		return
	}
	vZero := archsimd.BroadcastFloat64x8(0.0)
	vOne := archsimd.BroadcastFloat64x8(1.0)
	vAlpha := archsimd.BroadcastFloat64x8(alpha)
	lanes := 8
	ii := 0
	for ; ii+lanes*2 <= size; ii += lanes * 2 {
		x := archsimd.LoadFloat64x8((*[8]float64)(unsafe.Pointer(&input[ii])))
		expX := math.BaseExpVec_avx512_Float64(x)
		expM1 := expX.Sub(vOne)
		negPart := vAlpha.Mul(expM1)
		isPositive := x.Greater(vZero)
		result := x.Merge(negPart, isPositive)
		result.Store((*[8]float64)(unsafe.Pointer(&output[ii])))
		x1 := archsimd.LoadFloat64x8((*[8]float64)(unsafe.Pointer(&input[ii+8])))
		expX1 := math.BaseExpVec_avx512_Float64(x1)
		expM11 := expX1.Sub(vOne)
		negPart1 := vAlpha.Mul(expM11)
		isPositive1 := x1.Greater(vZero)
		result1 := x1.Merge(negPart1, isPositive1)
		result1.Store((*[8]float64)(unsafe.Pointer(&output[ii+8])))
	}
	for ; ii+lanes <= size; ii += lanes {
		x := archsimd.LoadFloat64x8((*[8]float64)(unsafe.Pointer(&input[ii])))
		expX := math.BaseExpVec_avx512_Float64(x)
		expM1 := expX.Sub(vOne)
		negPart := vAlpha.Mul(expM1)
		isPositive := x.Greater(vZero)
		result := x.Merge(negPart, isPositive)
		result.Store((*[8]float64)(unsafe.Pointer(&output[ii])))
	}
	for i := ii; i < size; i++ {
		if input[i] > 0 {
			output[i] = input[i]
		} else {
			x := float64(input[i])
			output[i] = float64(float64(alpha) * (stdmath.Exp(x) - 1.0))
		}
	}
}
