//go:build !noasm && arm64
// Code generated by GoAT. DO NOT EDIT.
// versions:
// 	clang   21.1.8
// 	objdump 2.45.1
// flags: -march=armv8-a+simd+fp -O3
// source: ../c/prefix_sum_neon_arm64.c

TEXT ·prefix_sum_inplace_f32(SB), $0-16
	MOVD data+0(FP), R0
	MOVD n+8(FP), R1
	WORD $0xf100103f    // cmp	x1, #4
	BGE  BB0_2
	WORD $0xd280000a    // mov	x10, #0                         ; =0x0
	WORD $0x6f00e400    // movi.2d	v0, #0000000000000000
	B    BB0_4

BB0_2:
	WORD $0xd2800008 // mov	x8, #0                          ; =0x0
	WORD $0x6f00e401 // movi.2d	v1, #0000000000000000
	WORD $0xaa0003e9 // mov	x9, x0
	WORD $0x6f00e400 // movi.2d	v0, #0000000000000000

BB0_3:
	WORD $0x3dc00122 // ldr	q2, [x9]
	WORD $0x6e026023 // ext.16b	v3, v1, v2, #12
	WORD $0x4e23d442 // fadd.4s	v2, v2, v3
	WORD $0x6e024023 // ext.16b	v3, v1, v2, #8
	WORD $0x4e23d442 // fadd.4s	v2, v2, v3
	WORD $0x4e22d400 // fadd.4s	v0, v0, v2
	WORD $0x3c810520 // str	q0, [x9], #16
	WORD $0x4e1c0400 // dup.4s	v0, v0[3]
	WORD $0x9100110a // add	x10, x8, #4
	WORD $0x9100210b // add	x11, x8, #8
	WORD $0xaa0a03e8 // mov	x8, x10
	WORD $0xeb01017f // cmp	x11, x1
	BLE  BB0_3

BB0_4:
	WORD $0xeb0a0028 // subs	x8, x1, x10
	BLE  BB0_7
	WORD $0x8b0a0809 // add	x9, x0, x10, lsl #2

BB0_6:
	WORD $0xbd400121 // ldr	s1, [x9]
	WORD $0x1e212800 // fadd	s0, s0, s1
	WORD $0xbc004520 // str	s0, [x9], #4
	WORD $0xf1000508 // subs	x8, x8, #1
	BNE  BB0_6

BB0_7:
	RET

TEXT ·prefix_sum_inplace_f64(SB), $0-16
	MOVD data+0(FP), R0
	MOVD n+8(FP), R1
	WORD $0xf100083f    // cmp	x1, #2
	BGE  BB1_2
	WORD $0xd2800008    // mov	x8, #0                          ; =0x0
	WORD $0x6f00e400    // movi.2d	v0, #0000000000000000
	B    BB1_4

BB1_2:
	WORD $0xd2800009 // mov	x9, #0                          ; =0x0
	WORD $0x6f00e401 // movi.2d	v1, #0000000000000000
	WORD $0xaa0003ea // mov	x10, x0
	WORD $0x6f00e400 // movi.2d	v0, #0000000000000000

BB1_3:
	WORD $0x3dc00142 // ldr	q2, [x10]
	WORD $0x6e024023 // ext.16b	v3, v1, v2, #8
	WORD $0x4e63d442 // fadd.2d	v2, v2, v3
	WORD $0x4e62d400 // fadd.2d	v0, v0, v2
	WORD $0x3c810540 // str	q0, [x10], #16
	WORD $0x4e180400 // dup.2d	v0, v0[1]
	WORD $0x91000928 // add	x8, x9, #2
	WORD $0x9100112b // add	x11, x9, #4
	WORD $0xaa0803e9 // mov	x9, x8
	WORD $0xeb01017f // cmp	x11, x1
	BLE  BB1_3

BB1_4:
	WORD $0xeb080029 // subs	x9, x1, x8
	BLE  BB1_7
	WORD $0x8b080c08 // add	x8, x0, x8, lsl #3

BB1_6:
	WORD $0xfd400101 // ldr	d1, [x8]
	WORD $0x1e612800 // fadd	d0, d0, d1
	WORD $0xfc008500 // str	d0, [x8], #8
	WORD $0xf1000529 // subs	x9, x9, #1
	BNE  BB1_6

BB1_7:
	RET

TEXT ·prefix_sum_inplace_i32(SB), $0-16
	MOVD data+0(FP), R0
	MOVD n+8(FP), R1
	WORD $0xf100103f    // cmp	x1, #4
	BGE  BB2_2
	WORD $0xd280000a    // mov	x10, #0                         ; =0x0
	WORD $0x6f00e400    // movi.2d	v0, #0000000000000000
	B    BB2_4

BB2_2:
	WORD $0xd2800008 // mov	x8, #0                          ; =0x0
	WORD $0x6f00e401 // movi.2d	v1, #0000000000000000
	WORD $0xaa0003e9 // mov	x9, x0
	WORD $0x6f00e400 // movi.2d	v0, #0000000000000000

BB2_3:
	WORD $0x3dc00122 // ldr	q2, [x9]
	WORD $0x6e026023 // ext.16b	v3, v1, v2, #12
	WORD $0x4ea28462 // add.4s	v2, v3, v2
	WORD $0x6e024023 // ext.16b	v3, v1, v2, #8
	WORD $0x4ea08440 // add.4s	v0, v2, v0
	WORD $0x4ea38400 // add.4s	v0, v0, v3
	WORD $0x3c810520 // str	q0, [x9], #16
	WORD $0x4e1c0400 // dup.4s	v0, v0[3]
	WORD $0x9100110a // add	x10, x8, #4
	WORD $0x9100210b // add	x11, x8, #8
	WORD $0xaa0a03e8 // mov	x8, x10
	WORD $0xeb01017f // cmp	x11, x1
	BLE  BB2_3

BB2_4:
	WORD $0xeb0a0028 // subs	x8, x1, x10
	BLE  BB2_7
	WORD $0x1e260009 // fmov	w9, s0
	WORD $0x8b0a080a // add	x10, x0, x10, lsl #2

BB2_6:
	WORD $0xb940014b // ldr	w11, [x10]
	WORD $0x0b090169 // add	w9, w11, w9
	WORD $0xb8004549 // str	w9, [x10], #4
	WORD $0xf1000508 // subs	x8, x8, #1
	BNE  BB2_6

BB2_7:
	RET

TEXT ·prefix_sum_inplace_i64(SB), $0-16
	MOVD data+0(FP), R0
	MOVD n+8(FP), R1
	WORD $0xf100043f    // cmp	x1, #1
	BLT  BB3_3
	WORD $0xd2800008    // mov	x8, #0                          ; =0x0

BB3_2:
	WORD $0xf9400009 // ldr	x9, [x0]
	WORD $0x8b080128 // add	x8, x9, x8
	WORD $0xf8008408 // str	x8, [x0], #8
	WORD $0xf1000421 // subs	x1, x1, #1
	BNE  BB3_2

BB3_3:
	RET

TEXT ·prefix_sum_inplace_u32(SB), $0-16
	MOVD data+0(FP), R0
	MOVD n+8(FP), R1
	WORD $0xf100103f    // cmp	x1, #4
	BGE  BB4_2
	WORD $0xd280000a    // mov	x10, #0                         ; =0x0
	WORD $0x6f00e400    // movi.2d	v0, #0000000000000000
	B    BB4_4

BB4_2:
	WORD $0xd2800008 // mov	x8, #0                          ; =0x0
	WORD $0x6f00e401 // movi.2d	v1, #0000000000000000
	WORD $0xaa0003e9 // mov	x9, x0
	WORD $0x6f00e400 // movi.2d	v0, #0000000000000000

BB4_3:
	WORD $0x3dc00122 // ldr	q2, [x9]
	WORD $0x6e026023 // ext.16b	v3, v1, v2, #12
	WORD $0x4ea28462 // add.4s	v2, v3, v2
	WORD $0x6e024023 // ext.16b	v3, v1, v2, #8
	WORD $0x4ea08440 // add.4s	v0, v2, v0
	WORD $0x4ea38400 // add.4s	v0, v0, v3
	WORD $0x3c810520 // str	q0, [x9], #16
	WORD $0x4e1c0400 // dup.4s	v0, v0[3]
	WORD $0x9100110a // add	x10, x8, #4
	WORD $0x9100210b // add	x11, x8, #8
	WORD $0xaa0a03e8 // mov	x8, x10
	WORD $0xeb01017f // cmp	x11, x1
	BLE  BB4_3

BB4_4:
	WORD $0xeb0a0028 // subs	x8, x1, x10
	BLE  BB4_7
	WORD $0x1e260009 // fmov	w9, s0
	WORD $0x8b0a080a // add	x10, x0, x10, lsl #2

BB4_6:
	WORD $0xb940014b // ldr	w11, [x10]
	WORD $0x0b090169 // add	w9, w11, w9
	WORD $0xb8004549 // str	w9, [x10], #4
	WORD $0xf1000508 // subs	x8, x8, #1
	BNE  BB4_6

BB4_7:
	RET

TEXT ·prefix_sum_inplace_u64(SB), $0-16
	MOVD data+0(FP), R0
	MOVD n+8(FP), R1
	WORD $0xf100043f    // cmp	x1, #1
	BLT  BB5_3
	WORD $0xd2800008    // mov	x8, #0                          ; =0x0

BB5_2:
	WORD $0xf9400009 // ldr	x9, [x0]
	WORD $0x8b080128 // add	x8, x9, x8
	WORD $0xf8008408 // str	x8, [x0], #8
	WORD $0xf1000421 // subs	x1, x1, #1
	BNE  BB5_2

BB5_3:
	RET

TEXT ·delta_decode_inplace_i32(SB), $0-20
	MOVD  data+0(FP), R0
	MOVD  n+8(FP), R1
	MOVWU base+16(FP), R2
	WORD  $0x4e040c40     // dup.4s	v0, w2
	WORD  $0xf100103f     // cmp	x1, #4
	BGE   BB6_2
	WORD  $0xd280000a     // mov	x10, #0                         ; =0x0
	B     BB6_4

BB6_2:
	WORD $0xd2800008 // mov	x8, #0                          ; =0x0
	WORD $0x6f00e401 // movi.2d	v1, #0000000000000000
	WORD $0xaa0003e9 // mov	x9, x0

BB6_3:
	WORD $0x3dc00122 // ldr	q2, [x9]
	WORD $0x6e026023 // ext.16b	v3, v1, v2, #12
	WORD $0x4ea28462 // add.4s	v2, v3, v2
	WORD $0x6e024023 // ext.16b	v3, v1, v2, #8
	WORD $0x4ea08440 // add.4s	v0, v2, v0
	WORD $0x4ea38400 // add.4s	v0, v0, v3
	WORD $0x3c810520 // str	q0, [x9], #16
	WORD $0x4e1c0400 // dup.4s	v0, v0[3]
	WORD $0x9100110a // add	x10, x8, #4
	WORD $0x9100210b // add	x11, x8, #8
	WORD $0xaa0a03e8 // mov	x8, x10
	WORD $0xeb01017f // cmp	x11, x1
	BLE  BB6_3

BB6_4:
	WORD $0xeb0a0028 // subs	x8, x1, x10
	BLE  BB6_7
	WORD $0x1e260009 // fmov	w9, s0
	WORD $0x8b0a080a // add	x10, x0, x10, lsl #2

BB6_6:
	WORD $0xb940014b // ldr	w11, [x10]
	WORD $0x0b090169 // add	w9, w11, w9
	WORD $0xb8004549 // str	w9, [x10], #4
	WORD $0xf1000508 // subs	x8, x8, #1
	BNE  BB6_6

BB6_7:
	RET

TEXT ·delta_decode_inplace_i64(SB), $0-24
	MOVD data+0(FP), R0
	MOVD n+8(FP), R1
	MOVD base+16(FP), R2
	WORD $0xf100043f     // cmp	x1, #1
	BLT  BB7_2

BB7_1:
	WORD $0xf9400008 // ldr	x8, [x0]
	WORD $0x8b020102 // add	x2, x8, x2
	WORD $0xf8008402 // str	x2, [x0], #8
	WORD $0xf1000421 // subs	x1, x1, #1
	BNE  BB7_1

BB7_2:
	RET

TEXT ·delta_decode_inplace_u32(SB), $0-20
	MOVD  data+0(FP), R0
	MOVD  n+8(FP), R1
	MOVWU base+16(FP), R2
	WORD  $0x4e040c40     // dup.4s	v0, w2
	WORD  $0xf100103f     // cmp	x1, #4
	BGE   BB8_2
	WORD  $0xd280000a     // mov	x10, #0                         ; =0x0
	B     BB8_4

BB8_2:
	WORD $0xd2800008 // mov	x8, #0                          ; =0x0
	WORD $0x6f00e401 // movi.2d	v1, #0000000000000000
	WORD $0xaa0003e9 // mov	x9, x0

BB8_3:
	WORD $0x3dc00122 // ldr	q2, [x9]
	WORD $0x6e026023 // ext.16b	v3, v1, v2, #12
	WORD $0x4ea28462 // add.4s	v2, v3, v2
	WORD $0x6e024023 // ext.16b	v3, v1, v2, #8
	WORD $0x4ea08440 // add.4s	v0, v2, v0
	WORD $0x4ea38400 // add.4s	v0, v0, v3
	WORD $0x3c810520 // str	q0, [x9], #16
	WORD $0x4e1c0400 // dup.4s	v0, v0[3]
	WORD $0x9100110a // add	x10, x8, #4
	WORD $0x9100210b // add	x11, x8, #8
	WORD $0xaa0a03e8 // mov	x8, x10
	WORD $0xeb01017f // cmp	x11, x1
	BLE  BB8_3

BB8_4:
	WORD $0xeb0a0028 // subs	x8, x1, x10
	BLE  BB8_7
	WORD $0x1e260009 // fmov	w9, s0
	WORD $0x8b0a080a // add	x10, x0, x10, lsl #2

BB8_6:
	WORD $0xb940014b // ldr	w11, [x10]
	WORD $0x0b090169 // add	w9, w11, w9
	WORD $0xb8004549 // str	w9, [x10], #4
	WORD $0xf1000508 // subs	x8, x8, #1
	BNE  BB8_6

BB8_7:
	RET

TEXT ·delta_decode_inplace_u64(SB), $0-24
	MOVD data+0(FP), R0
	MOVD n+8(FP), R1
	MOVD base+16(FP), R2
	WORD $0xf100043f     // cmp	x1, #1
	BLT  BB9_2

BB9_1:
	WORD $0xf9400008 // ldr	x8, [x0]
	WORD $0x8b020102 // add	x2, x8, x2
	WORD $0xf8008402 // str	x2, [x0], #8
	WORD $0xf1000421 // subs	x1, x1, #1
	BNE  BB9_1

BB9_2:
	RET
