//go:build !noasm && amd64

// AVX2 Matrix Multiplication for AMD64
// Uses AVX2 SIMD instructions for efficient matrix multiply.
package asm

import (
	"unsafe"

	"github.com/ajroetker/go-highway/hwy"
)

// AVX2 with F16C and FMA for f16/bf16 support
//go:generate go tool goat ../c/matmul_avx2_amd64.c -O3 --target amd64 -m avx2 -m fma -m f16c

// ============================================================================
// AVX2 Matrix Multiplication
// ============================================================================

// MatMulAVX2F16 performs matrix multiplication using AVX2: C = A * B
// Uses F16C for f16<->f32 conversion, compute in f32.
// A is M x K (row-major), B is K x N (row-major), C is M x N (row-major).
//
// Requires N to be a multiple of 8 (AVX2 f32 = 8 elements per vector).
//
// Parameters:
//   - a: M x K matrix (row-major)
//   - b: K x N matrix (row-major)
//   - c: M x N matrix (row-major, output)
//   - m, n, k: matrix dimensions
func MatMulAVX2F16(a, b, c []hwy.Float16, m, n, k int) {
	if m == 0 || n == 0 || k == 0 {
		return
	}
	if len(a) < m*k || len(b) < k*n || len(c) < m*n {
		return
	}
	mVal := int64(m)
	nVal := int64(n)
	kVal := int64(k)
	matmul_avx2_f16(
		unsafe.Pointer(&a[0]),
		unsafe.Pointer(&b[0]),
		unsafe.Pointer(&c[0]),
		unsafe.Pointer(&mVal),
		unsafe.Pointer(&nVal),
		unsafe.Pointer(&kVal),
	)
}

// MatMulAVX2BF16 performs matrix multiplication using AVX2: C = A * B
// Emulates bf16 via f32 conversion (no native bf16 in AVX2).
// A is M x K (row-major), B is K x N (row-major), C is M x N (row-major).
//
// Requires N to be a multiple of 8.
//
// Parameters:
//   - a: M x K matrix (row-major)
//   - b: K x N matrix (row-major)
//   - c: M x N matrix (row-major, output)
//   - m, n, k: matrix dimensions
func MatMulAVX2BF16(a, b, c []hwy.BFloat16, m, n, k int) {
	if m == 0 || n == 0 || k == 0 {
		return
	}
	if len(a) < m*k || len(b) < k*n || len(c) < m*n {
		return
	}
	mVal := int64(m)
	nVal := int64(n)
	kVal := int64(k)
	matmul_avx2_bf16(
		unsafe.Pointer(&a[0]),
		unsafe.Pointer(&b[0]),
		unsafe.Pointer(&c[0]),
		unsafe.Pointer(&mVal),
		unsafe.Pointer(&nVal),
		unsafe.Pointer(&kVal),
	)
}

// MatMulAVX2F32 performs matrix multiplication using AVX2: C = A * B
// A is M x K (row-major), B is K x N (row-major), C is M x N (row-major).
//
// Requires N to be a multiple of 8 (AVX2 f32 = 8 elements per vector).
//
// Parameters:
//   - a: M x K matrix (row-major)
//   - b: K x N matrix (row-major)
//   - c: M x N matrix (row-major, output)
//   - m, n, k: matrix dimensions
func MatMulAVX2F32(a, b, c []float32, m, n, k int) {
	if m == 0 || n == 0 || k == 0 {
		return
	}
	if len(a) < m*k || len(b) < k*n || len(c) < m*n {
		return
	}
	mVal := int64(m)
	nVal := int64(n)
	kVal := int64(k)
	matmul_avx2_f32(
		unsafe.Pointer(&a[0]),
		unsafe.Pointer(&b[0]),
		unsafe.Pointer(&c[0]),
		unsafe.Pointer(&mVal),
		unsafe.Pointer(&nVal),
		unsafe.Pointer(&kVal),
	)
}

// MatMulAVX2F64 performs matrix multiplication using AVX2: C = A * B
// A is M x K (row-major), B is K x N (row-major), C is M x N (row-major).
//
// Requires N to be a multiple of 4 (AVX2 f64 = 4 elements per vector).
//
// Parameters:
//   - a: M x K matrix (row-major)
//   - b: K x N matrix (row-major)
//   - c: M x N matrix (row-major, output)
//   - m, n, k: matrix dimensions
func MatMulAVX2F64(a, b, c []float64, m, n, k int) {
	if m == 0 || n == 0 || k == 0 {
		return
	}
	if len(a) < m*k || len(b) < k*n || len(c) < m*n {
		return
	}
	mVal := int64(m)
	nVal := int64(n)
	kVal := int64(k)
	matmul_avx2_f64(
		unsafe.Pointer(&a[0]),
		unsafe.Pointer(&b[0]),
		unsafe.Pointer(&c[0]),
		unsafe.Pointer(&mVal),
		unsafe.Pointer(&nVal),
		unsafe.Pointer(&kVal),
	)
}

// Assembly function declarations are in matmul_avx2_amd64.go (generated by GoAT)
