// Copyright 2025 go-highway Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//go:build !noasm && amd64

// AVX-512 Matrix Multiplication for AMD64
// Uses AVX-512 SIMD instructions for efficient matrix multiply.
// Requires AVX-512 FP16 (Sapphire Rapids+) for native f16 and
// AVX-512 BF16 (Cooper Lake+) for native bf16.
package asm

import (
	"unsafe"

	"github.com/ajroetker/go-highway/hwy"
)

// AVX-512 with FP16 and BF16 extensions
//go:generate go tool goat ../c/matmul_avx512_amd64.c -O3 --target amd64 -m avx512f -m avx512fp16 -m avx512bf16 -m avx512vl

// ============================================================================
// AVX-512 Matrix Multiplication
// ============================================================================

// MatMulAVX512F16 performs matrix multiplication using AVX-512 FP16: C = A * B
// Uses native AVX-512 FP16 arithmetic (Intel Sapphire Rapids, AMD Zen5+).
// A is M x K (row-major), B is K x N (row-major), C is M x N (row-major).
//
// Requires N to be a multiple of 32 (AVX-512 FP16 = 32 elements per vector).
//
// Parameters:
//   - a: M x K matrix (row-major)
//   - b: K x N matrix (row-major)
//   - c: M x N matrix (row-major, output)
//   - m, n, k: matrix dimensions
func MatMulAVX512F16(a, b, c []hwy.Float16, m, n, k int) {
	if m == 0 || n == 0 || k == 0 {
		return
	}
	if len(a) < m*k || len(b) < k*n || len(c) < m*n {
		return
	}
	mVal := int64(m)
	nVal := int64(n)
	kVal := int64(k)
	matmul_avx512_f16(
		unsafe.Pointer(&a[0]),
		unsafe.Pointer(&b[0]),
		unsafe.Pointer(&c[0]),
		unsafe.Pointer(&mVal),
		unsafe.Pointer(&nVal),
		unsafe.Pointer(&kVal),
	)
}

// MatMulAVX512BF16 performs matrix multiplication using AVX-512 BF16: C = A * B
// Uses VDPBF16PS for bf16 dot product accumulate (Intel Cooper Lake, AMD Zen4+).
// A is M x K (row-major), B is K x N (row-major), C is M x N (row-major).
//
// Requires N to be a multiple of 16 (f32 accumulator width).
//
// Parameters:
//   - a: M x K matrix (row-major)
//   - b: K x N matrix (row-major)
//   - c: M x N matrix (row-major, output)
//   - m, n, k: matrix dimensions
func MatMulAVX512BF16(a, b, c []hwy.BFloat16, m, n, k int) {
	if m == 0 || n == 0 || k == 0 {
		return
	}
	if len(a) < m*k || len(b) < k*n || len(c) < m*n {
		return
	}
	mVal := int64(m)
	nVal := int64(n)
	kVal := int64(k)
	matmul_avx512_bf16(
		unsafe.Pointer(&a[0]),
		unsafe.Pointer(&b[0]),
		unsafe.Pointer(&c[0]),
		unsafe.Pointer(&mVal),
		unsafe.Pointer(&nVal),
		unsafe.Pointer(&kVal),
	)
}

// MatMulAVX512F32 performs matrix multiplication using AVX-512: C = A * B
// A is M x K (row-major), B is K x N (row-major), C is M x N (row-major).
//
// Requires N to be a multiple of 16 (AVX-512 f32 = 16 elements per vector).
//
// Parameters:
//   - a: M x K matrix (row-major)
//   - b: K x N matrix (row-major)
//   - c: M x N matrix (row-major, output)
//   - m, n, k: matrix dimensions
func MatMulAVX512F32(a, b, c []float32, m, n, k int) {
	if m == 0 || n == 0 || k == 0 {
		return
	}
	if len(a) < m*k || len(b) < k*n || len(c) < m*n {
		return
	}
	mVal := int64(m)
	nVal := int64(n)
	kVal := int64(k)
	matmul_avx512_f32(
		unsafe.Pointer(&a[0]),
		unsafe.Pointer(&b[0]),
		unsafe.Pointer(&c[0]),
		unsafe.Pointer(&mVal),
		unsafe.Pointer(&nVal),
		unsafe.Pointer(&kVal),
	)
}

// MatMulAVX512F64 performs matrix multiplication using AVX-512: C = A * B
// A is M x K (row-major), B is K x N (row-major), C is M x N (row-major).
//
// Requires N to be a multiple of 8 (AVX-512 f64 = 8 elements per vector).
//
// Parameters:
//   - a: M x K matrix (row-major)
//   - b: K x N matrix (row-major)
//   - c: M x N matrix (row-major, output)
//   - m, n, k: matrix dimensions
func MatMulAVX512F64(a, b, c []float64, m, n, k int) {
	if m == 0 || n == 0 || k == 0 {
		return
	}
	if len(a) < m*k || len(b) < k*n || len(c) < m*n {
		return
	}
	mVal := int64(m)
	nVal := int64(n)
	kVal := int64(k)
	matmul_avx512_f64(
		unsafe.Pointer(&a[0]),
		unsafe.Pointer(&b[0]),
		unsafe.Pointer(&c[0]),
		unsafe.Pointer(&mVal),
		unsafe.Pointer(&nVal),
		unsafe.Pointer(&kVal),
	)
}

// Assembly function declarations are in matmul_avx512_amd64.go (generated by GoAT)
