//go:build !noasm && arm64
// Code generated by GoAT. DO NOT EDIT.
// versions:
// 	clang   21.1.8
// 	objdump 2.45.1
// flags: -march=armv8-a+simd+fp -fno-builtin-memset -O3
// source: /Users/ajroetker/go/src/github.com/ajroetker/go-highway/hwy/contrib/matmul/asm/basefusednf4matmulgeluapprox_c_f32_neon_arm64.c

TEXT ·fusednf4matmulgeluapprox_c_f32_neon(SB), $128-64
	MOVD input+0(FP), R0
	MOVD packed+8(FP), R1
	MOVD scales+16(FP), R2
	MOVD output+24(FP), R3
	MOVD pM+32(FP), R4
	MOVD pK+40(FP), R5
	MOVD pN+48(FP), R6
	MOVD pgroupSize+56(FP), R7
	WORD $0xf80303f9           // str	x25, [sp, #-80]!                ; 8-byte Folded Spill [transformed]
	WORD $0xa9045ff8           // stp	x24, x23, [sp, #16]             ; 16-byte Folded Spill [offset adjusted]
	WORD $0xa90557f6           // stp	x22, x21, [sp, #32]             ; 16-byte Folded Spill [offset adjusted]
	WORD $0xa9064ff4           // stp	x20, x19, [sp, #48]             ; 16-byte Folded Spill [offset adjusted]
	WORD $0xa9077bfd           // stp	x29, x30, [sp, #64]             ; 16-byte Folded Spill [offset adjusted]
	WORD $0x910103fd           // add	x29, sp, #64
	WORD $0xf81a83a3           // stur	x3, [x29, #-88]                 ; 8-byte Folded Spill
	WORD $0x90000008           // adrp	x8, ___stack_chk_guard@GOTPAGE
	WORD $0xf9400108           // ldr	x8, [x8, ___stack_chk_guard@GOTPAGEOFF]
	WORD $0xf9400108           // ldr	x8, [x8]
	WORD $0xf81b83a8           // stur	x8, [x29, #-72]
	WORD $0xf94000b6           // ldr	x22, [x5]
	WORD $0xf9400089           // ldr	x9, [x4]
	WORD $0xf94000ca           // ldr	x10, [x6]
	WORD $0xf100013f           // cmp	x9, #0
	WORD $0xfa401ac4           // ccmp	x22, #0, #4, ne
	WORD $0xfa401944           // ccmp	x10, #0, #4, ne
	BEQ  BB0_23
	WORD $0x910003e8           // mov	x8, sp
	WORD $0xf81903a8           // stur	x8, [x29, #-112]                ; 8-byte Folded Spill
	WORD $0xd10043eb           // sub	x11, sp, #16
	WORD $0x9100017f           // mov	sp, x11
	WORD $0xf100053f           // cmp	x9, #1
	BLT  BB0_22
	WORD $0xaa0203f5           // mov	x21, x2
	WORD $0xaa0003f4           // mov	x20, x0
	WORD $0xd280000c           // mov	x12, #0                         ; =0x0
	WORD $0xf94000ed           // ldr	x13, [x7]
	WORD $0x8b0d0148           // add	x8, x10, x13
	WORD $0xd1000508           // sub	x8, x8, #1
	WORD $0x9acd0d08           // sdiv	x8, x8, x13
	WORD $0xd37ef50e           // lsl	x14, x8, #2
	WORD $0xd37ef6c8           // lsl	x8, x22, #2
	WORD $0xf81983a8           // stur	x8, [x29, #-104]                ; 8-byte Folded Spill
	WORD $0x90000010           // adrp	x16, _nf4LookupTable@PAGE
	WORD $0x91000210           // add	x16, x16, _nf4LookupTable@PAGEOFF
	WORD $0x5290000f           // mov	w15, #32768                     ; =0x8000
	WORD $0x72b7e62f           // movk	w15, #48945, lsl #16
	WORD $0x52901071           // mov	w17, #32899                     ; =0x8083
	WORD $0x72a72bd1           // movk	w17, #14686, lsl #16
	WORD $0x52911120           // mov	w0, #34953                      ; =0x8889
	WORD $0x72a78100           // movk	w0, #15368, lsl #16
	WORD $0x52816c22           // mov	w2, #2913                       ; =0xb61
	WORD $0x72a756c2           // movk	w2, #15030, lsl #16
	WORD $0x52955563           // mov	w3, #43691                      ; =0xaaab
	WORD $0x72a7a543           // movk	w3, #15658, lsl #16
	WORD $0x52955564           // mov	w4, #43691                      ; =0xaaab
	WORD $0x72a7c544           // movk	w4, #15914, lsl #16
	WORD $0x1e2c1000           // fmov	s0, #0.50000000
	WORD $0x529b6468           // mov	w8, #56099                      ; =0xdb23
	WORD $0x72a7fb28           // movk	w8, #16345, lsl #16
	WORD $0x4e040d01           // dup.4s	v1, w8
	WORD $0x528e4308           // mov	w8, #29208                      ; =0x7218
	WORD $0x72b85628           // movk	w8, #49841, lsl #16
	WORD $0x4e040d02           // dup.4s	v2, w8
	WORD $0x52954768           // mov	w8, #43579                      ; =0xaa3b
	WORD $0x72b7f708           // movk	w8, #49080, lsl #16
	WORD $0x4e040d03           // dup.4s	v3, w8
	WORD $0x4e040de4           // dup.4s	v4, w15
	WORD $0x4e040e25           // dup.4s	v5, w17
	WORD $0x4e040c46           // dup.4s	v6, w2
	WORD $0x1e2e1007           // fmov	s7, #1.00000000
	WORD $0x4e040c10           // dup.4s	v16, w0
	WORD $0x52958a08           // mov	w8, #44112                      ; =0xac50
	WORD $0x72a855c8           // movk	w8, #17070, lsl #16
	WORD $0x4e040d11           // dup.4s	v17, w8
	WORD $0x4e040c72           // dup.4s	v18, w3
	WORD $0x4e040c93           // dup.4s	v19, w4
	WORD $0x4f03f614           // fmov.4s	v20, #1.00000000
	WORD $0xf81a03a9           // stur	x9, [x29, #-96]                 ; 8-byte Folded Spill
	B    BB0_4

BB0_3:
	WORD $0xf85b03ac // ldur	x12, [x29, #-80]                ; 8-byte Folded Reload
	WORD $0x9100058c // add	x12, x12, #1
	WORD $0xa979a7a8 // ldp	x8, x9, [x29, #-104]            ; 16-byte Folded Reload
	WORD $0x8b080294 // add	x20, x20, x8
	WORD $0xeb09019f // cmp	x12, x9
	BEQ  BB0_22

BB0_4:
	WORD $0xf81b03ac // stur	x12, [x29, #-80]                ; 8-byte Folded Spill
	WORD $0x9b0a7d88 // mul	x8, x12, x10
	WORD $0xf85a83a9 // ldur	x9, [x29, #-88]                 ; 8-byte Folded Reload
	WORD $0x8b08093e // add	x30, x9, x8, lsl #2
	WORD $0xf100115f // cmp	x10, #4
	BGE  BB0_16
	WORD $0xd280000f // mov	x15, #0                         ; =0x0

BB0_6:
	WORD $0xeb0a01ff // cmp	x15, x10
	WORD $0x529b6462 // mov	w2, #56099                      ; =0xdb23
	WORD $0x72b7fb22 // movk	w2, #49113, lsl #16
	WORD $0x52a85603 // mov	w3, #1118830592                 ; =0x42b00000
	WORD $0x52b85604 // mov	w4, #-1028653056                ; =0xc2b00000
	WORD $0x52954765 // mov	w5, #43579                      ; =0xaa3b
	WORD $0x72a7f705 // movk	w5, #16312, lsl #16
	WORD $0x52900006 // mov	w6, #32768                      ; =0x8000
	WORD $0x72b7e626 // movk	w6, #48945, lsl #16
	WORD $0x52901067 // mov	w7, #32899                      ; =0x8083
	WORD $0x72a72bc7 // movk	w7, #14686, lsl #16
	WORD $0x52911133 // mov	w19, #34953                     ; =0x8889
	WORD $0x72a78113 // movk	w19, #15368, lsl #16
	WORD $0x52816c37 // mov	w23, #2913                      ; =0xb61
	WORD $0x72a756d7 // movk	w23, #15030, lsl #16
	WORD $0x52955578 // mov	w24, #43691                     ; =0xaaab
	WORD $0x72a7a558 // movk	w24, #15658, lsl #16
	WORD $0x52955579 // mov	w25, #43691                     ; =0xaaab
	WORD $0x72a7c559 // movk	w25, #15914, lsl #16
	BLT  BB0_9
	B    BB0_3

BB0_7:
	WORD $0x52aff008 // mov	w8, #2139095040                 ; =0x7f800000
	WORD $0x1e270117 // fmov	s23, w8

BB0_8:
	WORD $0x1e371ab5 // fdiv	s21, s21, s23
	WORD $0xbc2f7bd5 // str	s21, [x30, x15, lsl #2]
	WORD $0x910005ef // add	x15, x15, #1
	WORD $0xeb0a01ff // cmp	x15, x10
	BEQ  BB0_3

BB0_9:
	WORD $0xf10006df // cmp	x22, #1
	BLT  BB0_13
	WORD $0xd2800008 // mov	x8, #0                          ; =0x0
	WORD $0x9acd0de9 // sdiv	x9, x15, x13
	WORD $0x8b090aa9 // add	x9, x21, x9, lsl #2
	WORD $0x2f00e415 // movi	d21, #0000000000000000
	WORD $0xaa0f03e0 // mov	x0, x15

BB0_11:
	WORD $0x8b40fc0c // add	x12, x0, x0, lsr #63
	WORD $0x9341fd8c // asr	x12, x12, #1
	WORD $0x386c682c // ldrb	w12, [x1, x12]
	WORD $0x12000d91 // and	w17, w12, #0xf
	WORD $0x53047d8c // lsr	w12, w12, #4
	WORD $0xf240001f // tst	x0, #0x1
	WORD $0x1a8c022c // csel	w12, w17, w12, eq
	WORD $0xbd400136 // ldr	s22, [x9]
	WORD $0xbc6c5a17 // ldr	s23, [x16, w12, uxtw #2]
	WORD $0xbc687a98 // ldr	s24, [x20, x8, lsl #2]
	WORD $0x1e370ad6 // fmul	s22, s22, s23
	WORD $0x1f165715 // fmadd	s21, s24, s22, s21
	WORD $0x91000508 // add	x8, x8, #1
	WORD $0x8b0e0129 // add	x9, x9, x14
	WORD $0x8b0a0000 // add	x0, x0, x10
	WORD $0xeb0802df // cmp	x22, x8
	BNE  BB0_11
	WORD $0x1e270056 // fmov	s22, w2
	WORD $0x1e360ab6 // fmul	s22, s21, s22
	WORD $0x1e270077 // fmov	s23, w3
	WORD $0x1e3722c0 // fcmp	s22, s23
	BGT  BB0_7
	B    BB0_14

BB0_13:
	WORD $0x2f00e415 // movi	d21, #0000000000000000
	WORD $0x1e270056 // fmov	s22, w2
	WORD $0x1e360ab6 // fmul	s22, s21, s22
	WORD $0x1e270077 // fmov	s23, w3
	WORD $0x1e3722c0 // fcmp	s22, s23
	BGT  BB0_7

BB0_14:
	WORD $0x1e2e1017 // fmov	s23, #1.00000000
	WORD $0x1e270098 // fmov	s24, w4
	WORD $0x1e3822c0 // fcmp	s22, s24
	BMI  BB0_8
	WORD $0x1e2700b7 // fmov	s23, w5
	WORD $0x1e370ad7 // fmul	s23, s22, s23
	WORD $0x1e2642f8 // frinta	s24, s23
	WORD $0x1e2700d9 // fmov	s25, w6
	WORD $0x1f195b16 // fmadd	s22, s24, s25, s22
	WORD $0x1e2700f9 // fmov	s25, w7
	WORD $0x1f195b16 // fmadd	s22, s24, s25, s22
	WORD $0x1e270278 // fmov	s24, w19
	WORD $0x1e2702f9 // fmov	s25, w23
	WORD $0x1f1962d8 // fmadd	s24, s22, s25, s24
	WORD $0x1e270319 // fmov	s25, w24
	WORD $0x1f166718 // fmadd	s24, s24, s22, s25
	WORD $0x1e270339 // fmov	s25, w25
	WORD $0x1f166718 // fmadd	s24, s24, s22, s25
	WORD $0x1f160318 // fmadd	s24, s24, s22, s0
	WORD $0x1f161f18 // fmadd	s24, s24, s22, s7
	WORD $0x1f161f16 // fmadd	s22, s24, s22, s7
	WORD $0x1e2402e8 // fcvtas	w8, s23
	WORD $0x52a7f009 // mov	w9, #1065353216                 ; =0x3f800000
	WORD $0x0b085d28 // add	w8, w9, w8, lsl #23
	WORD $0x1e270117 // fmov	s23, w8
	WORD $0x1e370ad6 // fmul	s22, s22, s23
	WORD $0x1e272ad7 // fadd	s23, s22, s7
	B    BB0_8

BB0_16:
	WORD $0xd2800004 // mov	x4, #0                          ; =0x0
	WORD $0x52800083 // mov	w3, #4                          ; =0x4
	B    BB0_19

BB0_17:
	WORD $0x6f00e415 // movi.2d	v21, #0000000000000000

BB0_18:
	WORD $0x6e21deb6 // fmul.4s	v22, v21, v1
	WORD $0x6eb6e457 // fcmgt.4s	v23, v2, v22
	WORD $0x6e23ded8 // fmul.4s	v24, v22, v3
	WORD $0x4e218b18 // frintn.4s	v24, v24
	WORD $0x6e24df19 // fmul.4s	v25, v24, v4
	WORD $0x4eb6d739 // fsub.4s	v25, v25, v22
	WORD $0x6e25df1a // fmul.4s	v26, v24, v5
	WORD $0x4e39d759 // fadd.4s	v25, v26, v25
	WORD $0x4eb01e1a // mov.16b	v26, v16
	WORD $0x4e39ccda // fmla.4s	v26, v6, v25
	WORD $0x4eb21e5b // mov.16b	v27, v18
	WORD $0x4e3acf3b // fmla.4s	v27, v25, v26
	WORD $0x4eb31e7a // mov.16b	v26, v19
	WORD $0x4e3bcf3a // fmla.4s	v26, v25, v27
	WORD $0x4f0167fb // movi.4s	v27, #63, lsl #24
	WORD $0x4e3acf3b // fmla.4s	v27, v25, v26
	WORD $0x4eb41e9a // mov.16b	v26, v20
	WORD $0x4e3bcf3a // fmla.4s	v26, v25, v27
	WORD $0x4eb41e9b // mov.16b	v27, v20
	WORD $0x4e3acf3b // fmla.4s	v27, v25, v26
	WORD $0x4e21ab18 // fcvtns.4s	v24, v24
	WORD $0x4f375718 // shl.4s	v24, v24, #23
	WORD $0x4eb48718 // add.4s	v24, v24, v20
	WORD $0x6e38df78 // fmul.4s	v24, v27, v24
	WORD $0x6eb1e6d6 // fcmgt.4s	v22, v22, v17
	WORD $0x4e34d718 // fadd.4s	v24, v24, v20
	WORD $0x6e38fe98 // fdiv.4s	v24, v20, v24
	WORD $0x4e771f17 // bic.16b	v23, v24, v23
	WORD $0x6e771e96 // bsl.16b	v22, v20, v23
	WORD $0x6e36deb5 // fmul.4s	v21, v21, v22
	WORD $0xd37ef488 // lsl	x8, x4, #2
	WORD $0x3ca86bd5 // str	q21, [x30, x8]
	WORD $0xaa0303ef // mov	x15, x3
	WORD $0x91001063 // add	x3, x3, #4
	WORD $0x91001084 // add	x4, x4, #4
	WORD $0xeb0a007f // cmp	x3, x10
	BGT  BB0_6

BB0_19:
	WORD $0xf10006df // cmp	x22, #1
	BLT  BB0_17
	WORD $0xd280000f // mov	x15, #0                         ; =0x0
	WORD $0x9acd0c89 // sdiv	x9, x4, x13
	WORD $0xb2400088 // orr	x8, x4, #0x1
	WORD $0x9acd0d07 // sdiv	x7, x8, x13
	WORD $0xb27f0088 // orr	x8, x4, #0x2
	WORD $0x9acd0d13 // sdiv	x19, x8, x13
	WORD $0xb2400497 // orr	x23, x4, #0x3
	WORD $0x6f00e415 // movi.2d	v21, #0000000000000000
	WORD $0xaa1403e0 // mov	x0, x20
	WORD $0xaa1503e2 // mov	x2, x21
	WORD $0xaa1603e8 // mov	x8, x22
	WORD $0x9acd0ef7 // sdiv	x23, x23, x13

BB0_21:
	WORD $0x8b0f0098 // add	x24, x4, x15
	WORD $0xd341ff19 // lsr	x25, x24, #1
	WORD $0x38796839 // ldrb	w25, [x1, x25]
	WORD $0x12000f26 // and	w6, w25, #0xf
	WORD $0x53047f39 // lsr	w25, w25, #4
	WORD $0x9100070c // add	x12, x24, #1
	WORD $0xd341fd91 // lsr	x17, x12, #1
	WORD $0x38716831 // ldrb	w17, [x1, x17]
	WORD $0x12000e25 // and	w5, w17, #0xf
	WORD $0x53047e31 // lsr	w17, w17, #4
	WORD $0xf240019f // tst	x12, #0x1
	WORD $0x1a9100ac // csel	w12, w5, w17, eq
	WORD $0xf24001ff // tst	x15, #0x1
	WORD $0x1a9900d1 // csel	w17, w6, w25, eq
	WORD $0xbc697856 // ldr	s22, [x2, x9, lsl #2]
	WORD $0xbc715a17 // ldr	s23, [x16, w17, uxtw #2]
	WORD $0x1e370ad6 // fmul	s22, s22, s23
	WORD $0xbc677857 // ldr	s23, [x2, x7, lsl #2]
	WORD $0xbc6c5a18 // ldr	s24, [x16, w12, uxtw #2]
	WORD $0x1e380af7 // fmul	s23, s23, s24
	WORD $0x91000b0c // add	x12, x24, #2
	WORD $0xd341fd8c // lsr	x12, x12, #1
	WORD $0x386c682c // ldrb	w12, [x1, x12]
	WORD $0x12000d91 // and	w17, w12, #0xf
	WORD $0x53047d8c // lsr	w12, w12, #4
	WORD $0x1a8c022c // csel	w12, w17, w12, eq
	WORD $0xbc737858 // ldr	s24, [x2, x19, lsl #2]
	WORD $0xbc6c5a19 // ldr	s25, [x16, w12, uxtw #2]
	WORD $0x2d005d76 // stp	s22, s23, [x11]
	WORD $0x1e390b16 // fmul	s22, s24, s25
	WORD $0x91000f0c // add	x12, x24, #3
	WORD $0xd341fd91 // lsr	x17, x12, #1
	WORD $0x38716831 // ldrb	w17, [x1, x17]
	WORD $0x12000e25 // and	w5, w17, #0xf
	WORD $0x53047e31 // lsr	w17, w17, #4
	WORD $0xf240019f // tst	x12, #0x1
	WORD $0x1a9100ac // csel	w12, w5, w17, eq
	WORD $0xbc777857 // ldr	s23, [x2, x23, lsl #2]
	WORD $0xbc6c5a18 // ldr	s24, [x16, w12, uxtw #2]
	WORD $0x1e380af7 // fmul	s23, s23, s24
	WORD $0xbc404418 // ldr	s24, [x0], #4
	WORD $0x2d015d76 // stp	s22, s23, [x11, #8]
	WORD $0x3dc00176 // ldr	q22, [x11]
	WORD $0x4f9812d5 // fmla.4s	v21, v22, v24[0]
	WORD $0x8b0e0042 // add	x2, x2, x14
	WORD $0x8b0a01ef // add	x15, x15, x10
	WORD $0xf1000508 // subs	x8, x8, #1
	BNE  BB0_21
	B    BB0_18

BB0_22:
	WORD $0xf85903a8 // ldur	x8, [x29, #-112]                ; 8-byte Folded Reload
	WORD $0x9100011f // mov	sp, x8

BB0_23:
	WORD $0xf85b83a8 // ldur	x8, [x29, #-72]
	WORD $0x90000009 // adrp	x9, ___stack_chk_guard@GOTPAGE
	WORD $0xf9400129 // ldr	x9, [x9, ___stack_chk_guard@GOTPAGEOFF]
	WORD $0xf9400129 // ldr	x9, [x9]
	WORD $0xeb08013f // cmp	x9, x8
	BNE  BB0_25
	WORD $0xd10103bf // sub	sp, x29, #64
	WORD $0xa9477bfd // ldp	x29, x30, [sp, #64]             ; 16-byte Folded Reload [offset adjusted]
	WORD $0xa9464ff4 // ldp	x20, x19, [sp, #48]             ; 16-byte Folded Reload [offset adjusted]
	WORD $0xa94557f6 // ldp	x22, x21, [sp, #32]             ; 16-byte Folded Reload [offset adjusted]
	WORD $0xa9445ff8 // ldp	x24, x23, [sp, #16]             ; 16-byte Folded Reload [offset adjusted]
	WORD $0xf84303f9 // ldr	x25, [sp], #80                  ; 8-byte Folded Reload [transformed]
	RET

BB0_25:
	WORD $0x94000000 // bl	___stack_chk_fail
