//go:build !noasm && amd64
// Code generated by GoAT. DO NOT EDIT.
// versions:
// 	clang   21.1.8
// 	objdump 2.45.1
// flags: -mavx2 -mfma -mf16c -O3
// source: ../c/matmul_avx2_amd64.c

package asm

import "unsafe"

//go:noescape
func matmul_avx2_f16(a, b, c, pm, pn, pk unsafe.Pointer)

//go:noescape
func matmul_avx2_bf16(a, b, c, pm, pn, pk unsafe.Pointer)

//go:noescape
func matmul_avx2_f32(a, b, c, pm, pn, pk unsafe.Pointer)

//go:noescape
func matmul_avx2_f64(a, b, c, pm, pn, pk unsafe.Pointer)
