//go:build !noasm && arm64
// Code generated by GoAT. DO NOT EDIT.
// versions:
// 	clang   21.1.8
// 	objdump 2.45.1
// flags: -march=armv8-a -O3
// source: ../c/matmul_blocked_neon_f32f64_arm64.c

TEXT ·blocked_matmul_neon_f32(SB), $368-48
	MOVD a+0(FP), R0
	MOVD b+8(FP), R1
	MOVD c+16(FP), R2
	MOVD pm+24(FP), R3
	MOVD pn+32(FP), R4
	MOVD pk+40(FP), R5
	WORD $0xa9116ffc   // stp	x28, x27, [sp, #272]            ; 16-byte Folded Spill
	WORD $0xa91267fa   // stp	x26, x25, [sp, #288]            ; 16-byte Folded Spill
	WORD $0xa9135ff8   // stp	x24, x23, [sp, #304]            ; 16-byte Folded Spill
	WORD $0xa91457f6   // stp	x22, x21, [sp, #320]            ; 16-byte Folded Spill
	WORD $0xa9154ff4   // stp	x20, x19, [sp, #336]            ; 16-byte Folded Spill
	WORD $0xa9167bfd   // stp	x29, x30, [sp, #352]            ; 16-byte Folded Spill
	WORD $0xf9007be2   // str	x2, [sp, #240]                  ; 8-byte Folded Spill
	WORD $0xf9001fe1   // str	x1, [sp, #56]                   ; 8-byte Folded Spill
	WORD $0xf9005fe0   // str	x0, [sp, #184]                  ; 8-byte Folded Spill
	WORD $0xf940006d   // ldr	x13, [x3]
	WORD $0xf9400082   // ldr	x2, [x4]
	WORD $0xf94000ae   // ldr	x14, [x5]
	WORD $0x9b0d7c48   // mul	x8, x2, x13
	WORD $0xf100051f   // cmp	x8, #1
	BLT  BB0_14
	WORD $0xf1000d1f   // cmp	x8, #3
	BHI  BB0_3
	WORD $0xd2800009   // mov	x9, #0                          ; =0x0
	B    BB0_12

BB0_3:
	WORD $0xf100411f // cmp	x8, #16
	BHS  BB0_5
	WORD $0xd2800009 // mov	x9, #0                          ; =0x0
	B    BB0_9

BB0_5:
	WORD $0x927ce909 // and	x9, x8, #0x7ffffffffffffff0
	WORD $0xf9407bea // ldr	x10, [sp, #240]                 ; 8-byte Folded Reload
	WORD $0x9100814a // add	x10, x10, #32
	WORD $0x6f00e400 // movi.2d	v0, #0000000000000000
	WORD $0xaa0903eb // mov	x11, x9

BB0_6:
	WORD $0xad3f0140 // stp	q0, q0, [x10, #-32]
	WORD $0xac820140 // stp	q0, q0, [x10], #64
	WORD $0xf100416b // subs	x11, x11, #16
	BNE  BB0_6
	WORD $0xeb09011f // cmp	x8, x9
	BEQ  BB0_14
	WORD $0xf27e051f // tst	x8, #0xc
	BEQ  BB0_12

BB0_9:
	WORD $0xaa0903eb // mov	x11, x9
	WORD $0x927ef109 // and	x9, x8, #0x7ffffffffffffffc
	WORD $0xcb09016a // sub	x10, x11, x9
	WORD $0xf9407bec // ldr	x12, [sp, #240]                 ; 8-byte Folded Reload
	WORD $0x8b0b098b // add	x11, x12, x11, lsl #2

BB0_10:
	WORD $0xa8817d7f // stp	xzr, xzr, [x11], #16
	WORD $0xb100114a // adds	x10, x10, #4
	BNE  BB0_10
	WORD $0xeb09011f // cmp	x8, x9
	BEQ  BB0_14

BB0_12:
	WORD $0xcb090108 // sub	x8, x8, x9
	WORD $0xf9407bea // ldr	x10, [sp, #240]                 ; 8-byte Folded Reload
	WORD $0x8b090949 // add	x9, x10, x9, lsl #2

BB0_13:
	WORD $0xb800453f // str	wzr, [x9], #4
	WORD $0xf1000508 // subs	x8, x8, #1
	BNE  BB0_13

BB0_14:
	WORD $0xf10005bf // cmp	x13, #1
	WORD $0xfa41a848 // ccmp	x2, #1, #8, ge
	WORD $0xfa41a9c8 // ccmp	x14, #1, #8, ge
	BGE  BB0_16

BB0_15:
	WORD $0xa9567bfd // ldp	x29, x30, [sp, #352]            ; 16-byte Folded Reload
	WORD $0xa9554ff4 // ldp	x20, x19, [sp, #336]            ; 16-byte Folded Reload
	WORD $0xa95457f6 // ldp	x22, x21, [sp, #320]            ; 16-byte Folded Reload
	WORD $0xa9535ff8 // ldp	x24, x23, [sp, #304]            ; 16-byte Folded Reload
	WORD $0xa95267fa // ldp	x26, x25, [sp, #288]            ; 16-byte Folded Reload
	WORD $0xa9516ffc // ldp	x28, x27, [sp, #272]            ; 16-byte Folded Reload
	RET

BB0_16:
	WORD $0xd280000a // mov	x10, #0                         ; =0x0
	WORD $0x8b020448 // add	x8, x2, x2, lsl #1
	WORD $0xd37ae508 // lsl	x8, x8, #6
	WORD $0xf90037e8 // str	x8, [sp, #104]                  ; 8-byte Folded Spill
	WORD $0xd37ef44c // lsl	x12, x2, #2
	WORD $0x8b0e05c8 // add	x8, x14, x14, lsl #1
	WORD $0xf9405fe9 // ldr	x9, [sp, #184]                  ; 8-byte Folded Reload
	WORD $0x91008129 // add	x9, x9, #32
	WORD $0xf90027e9 // str	x9, [sp, #72]                   ; 8-byte Folded Spill
	WORD $0xf9401fe9 // ldr	x9, [sp, #56]                   ; 8-byte Folded Reload
	WORD $0x9100c12b // add	x11, x9, #48
	WORD $0xa902b7eb // stp	x11, x13, [sp, #40]             ; 16-byte Folded Spill
	WORD $0x9100412b // add	x11, x9, #16
	WORD $0xd37ae508 // lsl	x8, x8, #6
	WORD $0xa901afe8 // stp	x8, x11, [sp, #24]              ; 16-byte Folded Spill
	WORD $0x91008128 // add	x8, x9, #32
	WORD $0xf9000be8 // str	x8, [sp, #16]                   ; 8-byte Folded Spill
	WORD $0xd37ef5c5 // lsl	x5, x14, #2
	WORD $0xf90087e2 // str	x2, [sp, #264]                  ; 8-byte Folded Spill
	WORD $0xf90057ee // str	x14, [sp, #168]                 ; 8-byte Folded Spill
	B    BB0_18

BB0_17:
	WORD $0xf9405fe8 // ldr	x8, [sp, #184]                  ; 8-byte Folded Reload
	WORD $0xf9400fe9 // ldr	x9, [sp, #24]                   ; 8-byte Folded Reload
	WORD $0x8b090108 // add	x8, x8, x9
	WORD $0xf9005fe8 // str	x8, [sp, #184]                  ; 8-byte Folded Spill
	WORD $0xf94027e8 // ldr	x8, [sp, #72]                   ; 8-byte Folded Reload
	WORD $0x8b090108 // add	x8, x8, x9
	WORD $0xf90027e8 // str	x8, [sp, #72]                   ; 8-byte Folded Spill
	WORD $0xf94023e8 // ldr	x8, [sp, #64]                   ; 8-byte Folded Reload
	WORD $0xaa0803ea // mov	x10, x8
	WORD $0xf9401bed // ldr	x13, [sp, #48]                  ; 8-byte Folded Reload
	WORD $0xeb0d011f // cmp	x8, x13
	BGE  BB0_15

BB0_18:
	WORD $0xd280000b // mov	x11, #0                         ; =0x0
	WORD $0xf9005bea // str	x10, [sp, #176]                 ; 8-byte Folded Spill
	WORD $0x9100c148 // add	x8, x10, #48
	WORD $0xeb0d011f // cmp	x8, x13
	WORD $0xf90023e8 // str	x8, [sp, #64]                   ; 8-byte Folded Spill
	WORD $0x9a8db108 // csel	x8, x8, x13, lt
	WORD $0xf9007fe8 // str	x8, [sp, #248]                  ; 8-byte Folded Spill
	WORD $0xf9400be0 // ldr	x0, [sp, #16]                   ; 8-byte Folded Reload
	WORD $0xa94227ea // ldp	x10, x9, [sp, #32]              ; 16-byte Folded Reload
	WORD $0xf9401fe8 // ldr	x8, [sp, #56]                   ; 8-byte Folded Reload
	WORD $0xa90cabe8 // stp	x8, x10, [sp, #200]             ; 16-byte Folded Spill
	B    BB0_20

BB0_19:
	WORD $0xa94ca3eb // ldp	x11, x8, [sp, #200]             ; 16-byte Folded Reload
	WORD $0x9103016a // add	x10, x11, #192
	WORD $0xa94583e9 // ldp	x9, x0, [sp, #88]               ; 16-byte Folded Reload
	WORD $0x91030129 // add	x9, x9, #192
	WORD $0x91030108 // add	x8, x8, #192
	WORD $0xa90ca3ea // stp	x10, x8, [sp, #200]             ; 16-byte Folded Spill
	WORD $0x91030000 // add	x0, x0, #192
	WORD $0xf9402be8 // ldr	x8, [sp, #80]                   ; 8-byte Folded Reload
	WORD $0xaa0803eb // mov	x11, x8
	WORD $0xeb02011f // cmp	x8, x2
	BGE  BB0_17

BB0_20:
	WORD $0x9100c168 // add	x8, x11, #48
	WORD $0xeb02011f // cmp	x8, x2
	WORD $0xa90527e8 // stp	x8, x9, [sp, #80]               ; 16-byte Folded Spill
	WORD $0x9a82b119 // csel	x25, x8, x2, lt
	WORD $0xf90083eb // str	x11, [sp, #256]                 ; 8-byte Folded Spill
	WORD $0xb27e0168 // orr	x8, x11, #0x4
	WORD $0xf90063e8 // str	x8, [sp, #192]                  ; 8-byte Folded Spill
	WORD $0xeb19011f // cmp	x8, x25
	WORD $0xf90033e0 // str	x0, [sp, #96]                   ; 8-byte Folded Spill
	WORD $0xd280000b // mov	x11, #0                         ; =0x0
	BLE  BB0_40
	WORD $0xd2800003 // mov	x3, #0                          ; =0x0
	WORD $0xd2800011 // mov	x17, #0                         ; =0x0
	WORD $0xf94027ea // ldr	x10, [sp, #72]                  ; 8-byte Folded Reload
	WORD $0x5280002f // mov	w15, #1                         ; =0x1
	WORD $0x52800610 // mov	w16, #48                        ; =0x30
	B    BB0_23

BB0_22:
	WORD $0xa94e2fe3 // ldp	x3, x11, [sp, #224]             ; 16-byte Folded Reload
	WORD $0x91000463 // add	x3, x3, #1
	WORD $0x9100c210 // add	x16, x16, #48
	WORD $0x9100c1ef // add	x15, x15, #48
	WORD $0xd100c16b // sub	x11, x11, #48
	WORD $0x9103014a // add	x10, x10, #192
	WORD $0x91030000 // add	x0, x0, #192
	WORD $0xf9406fe8 // ldr	x8, [sp, #216]                  ; 8-byte Folded Reload
	WORD $0xaa0803f1 // mov	x17, x8
	WORD $0xf94057ee // ldr	x14, [sp, #168]                 ; 8-byte Folded Reload
	WORD $0xeb0e011f // cmp	x8, x14
	WORD $0xf94087e2 // ldr	x2, [sp, #264]                  ; 8-byte Folded Reload
	BGE  BB0_19

BB0_23:
	WORD $0xeb1001df // cmp	x14, x16
	WORD $0x9a90b1c8 // csel	x8, x14, x16, lt
	WORD $0xeb0f011f // cmp	x8, x15
	WORD $0x9a8fc108 // csel	x8, x8, x15, gt
	WORD $0x9240050d // and	x13, x8, #0x3
	WORD $0x92400d09 // and	x9, x8, #0xf
	WORD $0xa90e2fe3 // stp	x3, x11, [sp, #224]             ; 16-byte Folded Spill
	WORD $0x8b0b0108 // add	x8, x8, x11
	WORD $0xcb09010b // sub	x11, x8, x9
	WORD $0x9100c229 // add	x9, x17, #48
	WORD $0xeb0901df // cmp	x14, x9
	WORD $0xf9006fe9 // str	x9, [sp, #216]                  ; 8-byte Folded Spill
	WORD $0x9a89b1c9 // csel	x9, x14, x9, lt
	WORD $0xb240022e // orr	x14, x17, #0x1
	WORD $0xeb0e013f // cmp	x9, x14
	WORD $0x9a91c52e // csinc	x14, x9, x17, gt
	WORD $0x928005e1 // mov	x1, #-48                        ; =0xffffffffffffffd0
	WORD $0x9b013861 // madd	x1, x3, x1, x14
	WORD $0xf1000c3f // cmp	x1, #3
	WORD $0xfa418840 // ccmp	x2, #1, #0, hi
	WORD $0x1a9f17e2 // cset	w2, eq
	WORD $0x92400dc3 // and	x3, x14, #0xf
	WORD $0xcb030024 // sub	x4, x1, x3
	WORD $0x8b040226 // add	x6, x17, x4
	WORD $0x924005d3 // and	x19, x14, #0x3
	WORD $0xcb13002e // sub	x14, x1, x19
	WORD $0x8b0e0235 // add	x21, x17, x14
	WORD $0xcb0d0116 // sub	x22, x8, x13
	WORD $0xa94b5ffa // ldp	x26, x23, [sp, #176]            ; 16-byte Folded Reload
	WORD $0xaa0a03ee // mov	x14, x10
	B    BB0_25

BB0_24:
	WORD $0x9100075a // add	x26, x26, #1
	WORD $0x8b0501ce // add	x14, x14, x5
	WORD $0x8b0502f7 // add	x23, x23, x5
	WORD $0xf9407fe8 // ldr	x8, [sp, #248]                  ; 8-byte Folded Reload
	WORD $0xeb08035f // cmp	x26, x8
	BGE  BB0_22

BB0_25:
	WORD $0xa95023f4 // ldp	x20, x8, [sp, #256]             ; 16-byte Folded Reload
	WORD $0x9b087f48 // mul	x8, x26, x8
	WORD $0xf9407bed // ldr	x13, [sp, #240]                 ; 8-byte Folded Reload
	WORD $0x8b0809bb // add	x27, x13, x8, lsl #2
	WORD $0xf94067fc // ldr	x28, [sp, #200]                 ; 8-byte Folded Reload
	WORD $0xaa0003ed // mov	x13, x0
	B    BB0_27

BB0_26:
	WORD $0xbc347b60 // str	s0, [x27, x20, lsl #2]
	WORD $0x91000694 // add	x20, x20, #1
	WORD $0x910011ad // add	x13, x13, #4
	WORD $0x9100139c // add	x28, x28, #4
	WORD $0xeb19029f // cmp	x20, x25
	BGE  BB0_24

BB0_27:
	WORD $0xbc747b60 // ldr	s0, [x27, x20, lsl #2]
	WORD $0x340000a2 // cbz	w2, LBB0_30
	WORD $0xf100403f // cmp	x1, #16
	BHS  BB0_31
	WORD $0xd2800007 // mov	x7, #0                          ; =0x0
	B    BB0_35

BB0_30:
	WORD $0xaa1103e8 // mov	x8, x17
	B    BB0_38

BB0_31:
	WORD $0xaa0d03fe // mov	x30, x13
	WORD $0xaa0e03f8 // mov	x24, x14
	WORD $0xaa0b03e8 // mov	x8, x11

BB0_32:
	WORD $0xad7f0b01 // ldp	q1, q2, [x24, #-32]
	WORD $0xacc21303 // ldp	q3, q4, [x24], #64
	WORD $0xad7f1bc5 // ldp	q5, q6, [x30, #-32]
	WORD $0xacc243c7 // ldp	q7, q16, [x30], #64
	WORD $0x6e25dc21 // fmul.4s	v1, v1, v5
	WORD $0x5e1c0425 // mov	s5, v1[3]
	WORD $0x5e140431 // mov	s17, v1[2]
	WORD $0x5e0c0432 // mov	s18, v1[1]
	WORD $0x6e26dc42 // fmul.4s	v2, v2, v6
	WORD $0x5e1c0446 // mov	s6, v2[3]
	WORD $0x5e140453 // mov	s19, v2[2]
	WORD $0x5e0c0454 // mov	s20, v2[1]
	WORD $0x6e27dc63 // fmul.4s	v3, v3, v7
	WORD $0x5e1c0467 // mov	s7, v3[3]
	WORD $0x5e140475 // mov	s21, v3[2]
	WORD $0x5e0c0476 // mov	s22, v3[1]
	WORD $0x6e30dc84 // fmul.4s	v4, v4, v16
	WORD $0x5e1c0490 // mov	s16, v4[3]
	WORD $0x5e140497 // mov	s23, v4[2]
	WORD $0x5e0c0498 // mov	s24, v4[1]
	WORD $0x1e212800 // fadd	s0, s0, s1
	WORD $0x1e322800 // fadd	s0, s0, s18
	WORD $0x1e312800 // fadd	s0, s0, s17
	WORD $0x1e252800 // fadd	s0, s0, s5
	WORD $0x1e222800 // fadd	s0, s0, s2
	WORD $0x1e342800 // fadd	s0, s0, s20
	WORD $0x1e332800 // fadd	s0, s0, s19
	WORD $0x1e262800 // fadd	s0, s0, s6
	WORD $0x1e232800 // fadd	s0, s0, s3
	WORD $0x1e362800 // fadd	s0, s0, s22
	WORD $0x1e352800 // fadd	s0, s0, s21
	WORD $0x1e272800 // fadd	s0, s0, s7
	WORD $0x1e242800 // fadd	s0, s0, s4
	WORD $0x1e382800 // fadd	s0, s0, s24
	WORD $0x1e372800 // fadd	s0, s0, s23
	WORD $0x1e302800 // fadd	s0, s0, s16
	WORD $0xf1004108 // subs	x8, x8, #16
	BNE  BB0_32
	WORD $0xb4fff923 // cbz	x3, LBB0_26
	WORD $0xaa0403e7 // mov	x7, x4
	WORD $0xaa0603e8 // mov	x8, x6
	WORD $0xf100107f // cmp	x3, #4
	BLO  BB0_38

BB0_35:
	WORD $0xcb0702c8 // sub	x8, x22, x7
	WORD $0x8b070227 // add	x7, x17, x7
	WORD $0xd37ef4f8 // lsl	x24, x7, #2
	WORD $0x8b180387 // add	x7, x28, x24
	WORD $0x8b1802f8 // add	x24, x23, x24

BB0_36:
	WORD $0x3cc10701 // ldr	q1, [x24], #16
	WORD $0x3cc104e2 // ldr	q2, [x7], #16
	WORD $0x6e22dc21 // fmul.4s	v1, v1, v2
	WORD $0x5e1c0422 // mov	s2, v1[3]
	WORD $0x5e140423 // mov	s3, v1[2]
	WORD $0x5e0c0424 // mov	s4, v1[1]
	WORD $0x1e212800 // fadd	s0, s0, s1
	WORD $0x1e242800 // fadd	s0, s0, s4
	WORD $0x1e232800 // fadd	s0, s0, s3
	WORD $0x1e222800 // fadd	s0, s0, s2
	WORD $0xf1001108 // subs	x8, x8, #4
	BNE  BB0_36
	WORD $0xaa1503e8 // mov	x8, x21
	WORD $0xb4fff653 // cbz	x19, LBB0_26

BB0_38:
	WORD $0x9b087d87 // mul	x7, x12, x8

BB0_39:
	WORD $0xbc687ae1 // ldr	s1, [x23, x8, lsl #2]
	WORD $0xbc676b82 // ldr	s2, [x28, x7]
	WORD $0x1f020020 // fmadd	s0, s1, s2, s0
	WORD $0x91000508 // add	x8, x8, #1
	WORD $0x8b0c00e7 // add	x7, x7, x12
	WORD $0xeb09011f // cmp	x8, x9
	BLT  BB0_39
	B    BB0_26

BB0_40:
	WORD $0xd280000d // mov	x13, #0                         ; =0x0
	WORD $0xd2800006 // mov	x6, #0                          ; =0x0
	WORD $0xf9406be8 // ldr	x8, [sp, #208]                  ; 8-byte Folded Reload
	WORD $0xa90e23e9 // stp	x9, x8, [sp, #224]              ; 16-byte Folded Spill
	WORD $0xf94027fa // ldr	x26, [sp, #72]                  ; 8-byte Folded Reload
	WORD $0x52800029 // mov	w9, #1                          ; =0x1
	WORD $0x5280060a // mov	w10, #48                        ; =0x30
	WORD $0xf9405fe0 // ldr	x0, [sp, #184]                  ; 8-byte Folded Reload
	WORD $0xf94067e8 // ldr	x8, [sp, #200]                  ; 8-byte Folded Reload
	WORD $0xf9006fe8 // str	x8, [sp, #216]                  ; 8-byte Folded Spill
	B    BB0_42

BB0_41:
	WORD $0xa949afed // ldp	x13, x11, [sp, #152]            ; 16-byte Folded Reload
	WORD $0x910005ad // add	x13, x13, #1
	WORD $0xf94037e8 // ldr	x8, [sp, #104]                  ; 8-byte Folded Reload
	WORD $0xf9406fe9 // ldr	x9, [sp, #216]                  ; 8-byte Folded Reload
	WORD $0x8b080129 // add	x9, x9, x8
	WORD $0xf9006fe9 // str	x9, [sp, #216]                  ; 8-byte Folded Spill
	WORD $0xa947abe0 // ldp	x0, x10, [sp, #120]             ; 16-byte Folded Reload
	WORD $0x91030000 // add	x0, x0, #192
	WORD $0x9100c14a // add	x10, x10, #48
	WORD $0xa948ebe9 // ldp	x9, x26, [sp, #136]             ; 16-byte Folded Reload
	WORD $0x9100c129 // add	x9, x9, #48
	WORD $0xd100c16b // sub	x11, x11, #48
	WORD $0x9103035a // add	x26, x26, #192
	WORD $0xf94073e8 // ldr	x8, [sp, #224]                  ; 8-byte Folded Reload
	WORD $0x91030108 // add	x8, x8, #192
	WORD $0xf90073e8 // str	x8, [sp, #224]                  ; 8-byte Folded Spill
	WORD $0xf94077e8 // ldr	x8, [sp, #232]                  ; 8-byte Folded Reload
	WORD $0x91030108 // add	x8, x8, #192
	WORD $0xf90077e8 // str	x8, [sp, #232]                  ; 8-byte Folded Spill
	WORD $0xf9403be8 // ldr	x8, [sp, #112]                  ; 8-byte Folded Reload
	WORD $0xaa0803e6 // mov	x6, x8
	WORD $0xf94057ee // ldr	x14, [sp, #168]                 ; 8-byte Folded Reload
	WORD $0xeb0e011f // cmp	x8, x14
	BGE  BB0_19

BB0_42:
	WORD $0xeb0a01df // cmp	x14, x10
	WORD $0xa90827ea // stp	x10, x9, [sp, #128]             ; 16-byte Folded Spill
	WORD $0x9a8ab1c8 // csel	x8, x14, x10, lt
	WORD $0xeb09011f // cmp	x8, x9
	WORD $0x9a89c108 // csel	x8, x8, x9, gt
	WORD $0x92400509 // and	x9, x8, #0x3
	WORD $0x92400d0a // and	x10, x8, #0xf
	WORD $0xa909afed // stp	x13, x11, [sp, #152]            ; 16-byte Folded Spill
	WORD $0x8b0b0108 // add	x8, x8, x11
	WORD $0xcb0a0107 // sub	x7, x8, x10
	WORD $0x9100c0ca // add	x10, x6, #48
	WORD $0xeb0a01df // cmp	x14, x10
	WORD $0xa90703ea // stp	x10, x0, [sp, #112]             ; 16-byte Folded Spill
	WORD $0x9a8ab1d3 // csel	x19, x14, x10, lt
	WORD $0xb24000ca // orr	x10, x6, #0x1
	WORD $0xeb0a027f // cmp	x19, x10
	WORD $0x9a86c66a // csinc	x10, x19, x6, gt
	WORD $0x928005eb // mov	x11, #-48                       ; =0xffffffffffffffd0
	WORD $0x9b0b29af // madd	x15, x13, x11, x10
	WORD $0xf1000dff // cmp	x15, #3
	WORD $0xfa418840 // ccmp	x2, #1, #0, hi
	WORD $0x1a9f17eb // cset	w11, eq
	WORD $0x92400d44 // and	x4, x10, #0xf
	WORD $0xcb0401f1 // sub	x17, x15, x4
	WORD $0x8b1100ce // add	x14, x6, x17
	WORD $0x9240054a // and	x10, x10, #0x3
	WORD $0xcb0a01ed // sub	x13, x15, x10
	WORD $0x8b0d00c1 // add	x1, x6, x13
	WORD $0xcb09011b // sub	x27, x8, x9
	WORD $0xa94b73f0 // ldp	x16, x28, [sp, #176]            ; 16-byte Folded Reload
	WORD $0xf9004bfa // str	x26, [sp, #144]                 ; 8-byte Folded Spill
	B    BB0_44

BB0_43:
	WORD $0x91000610 // add	x16, x16, #1
	WORD $0x8b050000 // add	x0, x0, x5
	WORD $0x8b05035a // add	x26, x26, x5
	WORD $0x8b05039c // add	x28, x28, x5
	WORD $0xf9407fe8 // ldr	x8, [sp, #248]                  ; 8-byte Folded Reload
	WORD $0xeb08021f // cmp	x16, x8
	BGE  BB0_41

BB0_44:
	WORD $0x9b027e08 // mul	x8, x16, x2
	WORD $0xf9407be9 // ldr	x9, [sp, #240]                  ; 8-byte Folded Reload
	WORD $0x8b080923 // add	x3, x9, x8, lsl #2
	WORD $0xa94d53e2 // ldp	x2, x20, [sp, #208]             ; 16-byte Folded Reload
	WORD $0xa94e27e8 // ldp	x8, x9, [sp, #224]              ; 16-byte Folded Reload
	WORD $0xf94063f8 // ldr	x24, [sp, #192]                 ; 8-byte Folded Reload
	WORD $0xf94083f7 // ldr	x23, [sp, #256]                 ; 8-byte Folded Reload

BB0_45:
	WORD $0x8b17086d // add	x13, x3, x23, lsl #2
	WORD $0xaa1803f7 // mov	x23, x24
	WORD $0xaa0803f6 // mov	x22, x8
	WORD $0xaa0903f5 // mov	x21, x9
	WORD $0xaa0203fe // mov	x30, x2
	WORD $0x3dc001a0 // ldr	q0, [x13]
	WORD $0xaa0003e8 // mov	x8, x0
	WORD $0xaa1403e9 // mov	x9, x20
	WORD $0xaa0603e2 // mov	x2, x6

BB0_46:
	WORD $0xbc404501 // ldr	s1, [x8], #4
	WORD $0x3dc00122 // ldr	q2, [x9]
	WORD $0x4f811040 // fmla.4s	v0, v2, v1[0]
	WORD $0x91000442 // add	x2, x2, #1
	WORD $0x8b0c0129 // add	x9, x9, x12
	WORD $0xeb13005f // cmp	x2, x19
	BLT  BB0_46
	WORD $0x910012f8 // add	x24, x23, #4
	WORD $0x91004294 // add	x20, x20, #16
	WORD $0x3d8001a0 // str	q0, [x13]
	WORD $0x910042c8 // add	x8, x22, #16
	WORD $0x910042a9 // add	x9, x21, #16
	WORD $0x910043c2 // add	x2, x30, #16
	WORD $0xeb19031f // cmp	x24, x25
	BLE  BB0_45
	WORD $0xeb1902ff // cmp	x23, x25
	WORD $0xf94087e2 // ldr	x2, [sp, #264]                  ; 8-byte Folded Reload
	BLT  BB0_50
	B    BB0_43

BB0_49:
	WORD $0xbc377860 // str	s0, [x3, x23, lsl #2]
	WORD $0x910006f7 // add	x23, x23, #1
	WORD $0x910012d6 // add	x22, x22, #4
	WORD $0x910012b5 // add	x21, x21, #4
	WORD $0x910013de // add	x30, x30, #4
	WORD $0xeb1902ff // cmp	x23, x25
	BGE  BB0_43

BB0_50:
	WORD $0xbc777860 // ldr	s0, [x3, x23, lsl #2]
	WORD $0x340000ab // cbz	w11, LBB0_53
	WORD $0xf10041ff // cmp	x15, #16
	BHS  BB0_54
	WORD $0xd2800008 // mov	x8, #0                          ; =0x0
	B    BB0_58

BB0_53:
	WORD $0xaa0603ed // mov	x13, x6
	B    BB0_61

BB0_54:
	WORD $0xaa1603f4 // mov	x20, x22
	WORD $0xaa1a03ed // mov	x13, x26
	WORD $0xaa0703f8 // mov	x24, x7

BB0_55:
	WORD $0xad7f09a1 // ldp	q1, q2, [x13, #-32]
	WORD $0xacc211a3 // ldp	q3, q4, [x13], #64
	WORD $0xad7f1a85 // ldp	q5, q6, [x20, #-32]
	WORD $0xacc24287 // ldp	q7, q16, [x20], #64
	WORD $0x6e25dc21 // fmul.4s	v1, v1, v5
	WORD $0x5e1c0425 // mov	s5, v1[3]
	WORD $0x5e140431 // mov	s17, v1[2]
	WORD $0x5e0c0432 // mov	s18, v1[1]
	WORD $0x6e26dc42 // fmul.4s	v2, v2, v6
	WORD $0x5e1c0446 // mov	s6, v2[3]
	WORD $0x5e140453 // mov	s19, v2[2]
	WORD $0x5e0c0454 // mov	s20, v2[1]
	WORD $0x6e27dc63 // fmul.4s	v3, v3, v7
	WORD $0x5e1c0467 // mov	s7, v3[3]
	WORD $0x5e140475 // mov	s21, v3[2]
	WORD $0x5e0c0476 // mov	s22, v3[1]
	WORD $0x6e30dc84 // fmul.4s	v4, v4, v16
	WORD $0x5e1c0490 // mov	s16, v4[3]
	WORD $0x5e140497 // mov	s23, v4[2]
	WORD $0x5e0c0498 // mov	s24, v4[1]
	WORD $0x1e212800 // fadd	s0, s0, s1
	WORD $0x1e322800 // fadd	s0, s0, s18
	WORD $0x1e312800 // fadd	s0, s0, s17
	WORD $0x1e252800 // fadd	s0, s0, s5
	WORD $0x1e222800 // fadd	s0, s0, s2
	WORD $0x1e342800 // fadd	s0, s0, s20
	WORD $0x1e332800 // fadd	s0, s0, s19
	WORD $0x1e262800 // fadd	s0, s0, s6
	WORD $0x1e232800 // fadd	s0, s0, s3
	WORD $0x1e362800 // fadd	s0, s0, s22
	WORD $0x1e352800 // fadd	s0, s0, s21
	WORD $0x1e272800 // fadd	s0, s0, s7
	WORD $0x1e242800 // fadd	s0, s0, s4
	WORD $0x1e382800 // fadd	s0, s0, s24
	WORD $0x1e372800 // fadd	s0, s0, s23
	WORD $0x1e302800 // fadd	s0, s0, s16
	WORD $0xf1004318 // subs	x24, x24, #16
	BNE  BB0_55
	WORD $0xb4fff904 // cbz	x4, LBB0_49
	WORD $0xaa1103e8 // mov	x8, x17
	WORD $0xaa0e03ed // mov	x13, x14
	WORD $0xf100109f // cmp	x4, #4
	BLO  BB0_61

BB0_58:
	WORD $0xcb08036d // sub	x13, x27, x8
	WORD $0xd37ef514 // lsl	x20, x8, #2

BB0_59:
	WORD $0x3cf46801 // ldr	q1, [x0, x20]
	WORD $0x3cf46aa2 // ldr	q2, [x21, x20]
	WORD $0x6e22dc21 // fmul.4s	v1, v1, v2
	WORD $0x5e1c0422 // mov	s2, v1[3]
	WORD $0x5e140423 // mov	s3, v1[2]
	WORD $0x5e0c0424 // mov	s4, v1[1]
	WORD $0x1e212800 // fadd	s0, s0, s1
	WORD $0x1e242800 // fadd	s0, s0, s4
	WORD $0x1e232800 // fadd	s0, s0, s3
	WORD $0x1e222800 // fadd	s0, s0, s2
	WORD $0x91004294 // add	x20, x20, #16
	WORD $0xf10011ad // subs	x13, x13, #4
	BNE  BB0_59
	WORD $0xaa0103ed // mov	x13, x1
	WORD $0xb4fff66a // cbz	x10, LBB0_49

BB0_61:
	WORD $0x9b0d7988 // madd	x8, x12, x13, x30

BB0_62:
	WORD $0xbc6d7b81 // ldr	s1, [x28, x13, lsl #2]
	WORD $0xbd400102 // ldr	s2, [x8]
	WORD $0x1f020020 // fmadd	s0, s1, s2, s0
	WORD $0x910005ad // add	x13, x13, #1
	WORD $0x8b0c0108 // add	x8, x8, x12
	WORD $0xeb1301bf // cmp	x13, x19
	BLT  BB0_62
	B    BB0_49

TEXT ·blocked_matmul_neon_f64(SB), $304-48
	MOVD a+0(FP), R0
	MOVD b+8(FP), R1
	MOVD c+16(FP), R2
	MOVD pm+24(FP), R3
	MOVD pn+32(FP), R4
	MOVD pk+40(FP), R5
	WORD $0xa90d6ffc   // stp	x28, x27, [sp, #208]            ; 16-byte Folded Spill
	WORD $0xa90e67fa   // stp	x26, x25, [sp, #224]            ; 16-byte Folded Spill
	WORD $0xa90f5ff8   // stp	x24, x23, [sp, #240]            ; 16-byte Folded Spill
	WORD $0xa91057f6   // stp	x22, x21, [sp, #256]            ; 16-byte Folded Spill
	WORD $0xa9114ff4   // stp	x20, x19, [sp, #272]            ; 16-byte Folded Spill
	WORD $0xa9127bfd   // stp	x29, x30, [sp, #288]            ; 16-byte Folded Spill
	WORD $0xf9001fe1   // str	x1, [sp, #56]                   ; 8-byte Folded Spill
	WORD $0xf940006d   // ldr	x13, [x3]
	WORD $0xf9400089   // ldr	x9, [x4]
	WORD $0xf94000a1   // ldr	x1, [x5]
	WORD $0x9b0d7d28   // mul	x8, x9, x13
	WORD $0xf100051f   // cmp	x8, #1
	BLT  BB1_8
	WORD $0xf100211f   // cmp	x8, #8
	BHS  BB1_3
	WORD $0xd280000a   // mov	x10, #0                         ; =0x0
	B    BB1_6

BB1_3:
	WORD $0x927ded0a // and	x10, x8, #0x7ffffffffffffff8
	WORD $0x9100804b // add	x11, x2, #32
	WORD $0x6f00e400 // movi.2d	v0, #0000000000000000
	WORD $0xaa0a03ec // mov	x12, x10

BB1_4:
	WORD $0xad3f0160 // stp	q0, q0, [x11, #-32]
	WORD $0xac820160 // stp	q0, q0, [x11], #64
	WORD $0xf100218c // subs	x12, x12, #8
	BNE  BB1_4
	WORD $0xeb0a011f // cmp	x8, x10
	BEQ  BB1_8

BB1_6:
	WORD $0xcb0a0108 // sub	x8, x8, x10
	WORD $0x8b0a0c4a // add	x10, x2, x10, lsl #3

BB1_7:
	WORD $0xf800855f // str	xzr, [x10], #8
	WORD $0xf1000508 // subs	x8, x8, #1
	BNE  BB1_7

BB1_8:
	WORD $0xf10005bf // cmp	x13, #1
	WORD $0xfa41a928 // ccmp	x9, #1, #8, ge
	WORD $0xfa41a828 // ccmp	x1, #1, #8, ge
	BGE  BB1_10

BB1_9:
	WORD $0xa9527bfd // ldp	x29, x30, [sp, #288]            ; 16-byte Folded Reload
	WORD $0xa9514ff4 // ldp	x20, x19, [sp, #272]            ; 16-byte Folded Reload
	WORD $0xa95057f6 // ldp	x22, x21, [sp, #256]            ; 16-byte Folded Reload
	WORD $0xa94f5ff8 // ldp	x24, x23, [sp, #240]            ; 16-byte Folded Reload
	WORD $0xa94e67fa // ldp	x26, x25, [sp, #224]            ; 16-byte Folded Reload
	WORD $0xa94d6ffc // ldp	x28, x27, [sp, #208]            ; 16-byte Folded Reload
	RET

BB1_10:
	WORD $0xd2800017 // mov	x23, #0                         ; =0x0
	WORD $0x8b090528 // add	x8, x9, x9, lsl #1
	WORD $0xd379e108 // lsl	x8, x8, #7
	WORD $0xf90037e8 // str	x8, [sp, #104]                  ; 8-byte Folded Spill
	WORD $0xd37df12c // lsl	x12, x9, #3
	WORD $0x8b010428 // add	x8, x1, x1, lsl #1
	WORD $0x9100800a // add	x10, x0, #32
	WORD $0xf90027ea // str	x10, [sp, #72]                  ; 8-byte Folded Spill
	WORD $0xf9401fea // ldr	x10, [sp, #56]                  ; 8-byte Folded Reload
	WORD $0x9100c14b // add	x11, x10, #48
	WORD $0xa902b7eb // stp	x11, x13, [sp, #40]             ; 16-byte Folded Spill
	WORD $0x9100414b // add	x11, x10, #16
	WORD $0xd379e108 // lsl	x8, x8, #7
	WORD $0xa901afe8 // stp	x8, x11, [sp, #24]              ; 16-byte Folded Spill
	WORD $0x91008148 // add	x8, x10, #32
	WORD $0xf9000be8 // str	x8, [sp, #16]                   ; 8-byte Folded Spill
	WORD $0xd37df025 // lsl	x5, x1, #3
	WORD $0xf9005be1 // str	x1, [sp, #176]                  ; 8-byte Folded Spill
	B    BB1_12

BB1_11:
	WORD $0xf9400fea // ldr	x10, [sp, #24]                  ; 8-byte Folded Reload
	WORD $0x8b0a0000 // add	x0, x0, x10
	WORD $0xf94027e8 // ldr	x8, [sp, #72]                   ; 8-byte Folded Reload
	WORD $0x8b0a0108 // add	x8, x8, x10
	WORD $0xf90027e8 // str	x8, [sp, #72]                   ; 8-byte Folded Spill
	WORD $0xf94023e8 // ldr	x8, [sp, #64]                   ; 8-byte Folded Reload
	WORD $0xaa0803f7 // mov	x23, x8
	WORD $0xf9401bed // ldr	x13, [sp, #48]                  ; 8-byte Folded Reload
	WORD $0xeb0d011f // cmp	x8, x13
	BGE  BB1_9

BB1_12:
	WORD $0xd280001b // mov	x27, #0                         ; =0x0
	WORD $0x9100c2e8 // add	x8, x23, #48
	WORD $0xeb0d011f // cmp	x8, x13
	WORD $0xf90023e8 // str	x8, [sp, #64]                   ; 8-byte Folded Spill
	WORD $0x9a8db107 // csel	x7, x8, x13, lt
	WORD $0xf9400bf1 // ldr	x17, [sp, #16]                  ; 8-byte Folded Reload
	WORD $0xa9427bea // ldp	x10, x30, [sp, #32]             ; 16-byte Folded Reload
	WORD $0xf9401fe8 // ldr	x8, [sp, #56]                   ; 8-byte Folded Reload
	WORD $0xa90c23ea // stp	x10, x8, [sp, #192]             ; 16-byte Folded Spill
	WORD $0xf9005ff7 // str	x23, [sp, #184]                 ; 8-byte Folded Spill
	WORD $0xf9003be0 // str	x0, [sp, #112]                  ; 8-byte Folded Spill
	B    BB1_14

BB1_13:
	WORD $0xa94c2fe8 // ldp	x8, x11, [sp, #192]             ; 16-byte Folded Reload
	WORD $0x9106016a // add	x10, x11, #384
	WORD $0xa945c7fe // ldp	x30, x17, [sp, #88]             ; 16-byte Folded Reload
	WORD $0x910603de // add	x30, x30, #384
	WORD $0x91060108 // add	x8, x8, #384
	WORD $0xa90c2be8 // stp	x8, x10, [sp, #192]             ; 16-byte Folded Spill
	WORD $0x91060231 // add	x17, x17, #384
	WORD $0xf9402be8 // ldr	x8, [sp, #80]                   ; 8-byte Folded Reload
	WORD $0xaa0803fb // mov	x27, x8
	WORD $0xeb09011f // cmp	x8, x9
	BGE  BB1_11

BB1_14:
	WORD $0x9100c368 // add	x8, x27, #48
	WORD $0xeb09011f // cmp	x8, x9
	WORD $0xa9057be8 // stp	x8, x30, [sp, #80]              ; 16-byte Folded Spill
	WORD $0x9a89b119 // csel	x25, x8, x9, lt
	WORD $0xb27f037a // orr	x26, x27, #0x2
	WORD $0xeb19035f // cmp	x26, x25
	WORD $0xf90033f1 // str	x17, [sp, #96]                  ; 8-byte Folded Spill
	WORD $0xd280000d // mov	x13, #0                         ; =0x0
	BLE  BB1_28
	WORD $0xd280000e // mov	x14, #0                         ; =0x0
	WORD $0xd2800010 // mov	x16, #0                         ; =0x0
	WORD $0xf94027e8 // ldr	x8, [sp, #72]                   ; 8-byte Folded Reload
	WORD $0x52800023 // mov	w3, #1                          ; =0x1
	WORD $0x5280060f // mov	w15, #48                        ; =0x30
	B    BB1_17

BB1_16:
	WORD $0xa94a37ee // ldp	x14, x13, [sp, #160]            ; 16-byte Folded Reload
	WORD $0x910005ce // add	x14, x14, #1
	WORD $0x9100c1ef // add	x15, x15, #48
	WORD $0x9100c063 // add	x3, x3, #48
	WORD $0xd100c1ad // sub	x13, x13, #48
	WORD $0x91060108 // add	x8, x8, #384
	WORD $0x91060231 // add	x17, x17, #384
	WORD $0xf9404fea // ldr	x10, [sp, #152]                 ; 8-byte Folded Reload
	WORD $0xaa0a03f0 // mov	x16, x10
	WORD $0xa94b5fe1 // ldp	x1, x23, [sp, #176]             ; 16-byte Folded Reload
	WORD $0xeb01015f // cmp	x10, x1
	BGE  BB1_13

BB1_17:
	WORD $0xeb0f003f // cmp	x1, x15
	WORD $0x9a8fb02a // csel	x10, x1, x15, lt
	WORD $0xeb03015f // cmp	x10, x3
	WORD $0x9a83c14a // csel	x10, x10, x3, gt
	WORD $0x9240094b // and	x11, x10, #0x7
	WORD $0xa90a37ee // stp	x14, x13, [sp, #160]            ; 16-byte Folded Spill
	WORD $0x8b0d014a // add	x10, x10, x13
	WORD $0xcb0b014b // sub	x11, x10, x11
	WORD $0x9100c20a // add	x10, x16, #48
	WORD $0xeb0a003f // cmp	x1, x10
	WORD $0xf9004fea // str	x10, [sp, #152]                 ; 8-byte Folded Spill
	WORD $0x9a8ab021 // csel	x1, x1, x10, lt
	WORD $0xb240020a // orr	x10, x16, #0x1
	WORD $0xeb0a003f // cmp	x1, x10
	WORD $0x9a90c42a // csinc	x10, x1, x16, gt
	WORD $0x928005ed // mov	x13, #-48                       ; =0xffffffffffffffd0
	WORD $0x9b0d29cd // madd	x13, x14, x13, x10
	WORD $0xf1001dbf // cmp	x13, #7
	WORD $0xfa418920 // ccmp	x9, #1, #0, hi
	WORD $0x1a9f17e4 // cset	w4, eq
	WORD $0x92400946 // and	x6, x10, #0x7
	WORD $0xcb0601aa // sub	x10, x13, x6
	WORD $0x8b0a0213 // add	x19, x16, x10
	WORD $0xaa0003f5 // mov	x21, x0
	WORD $0xaa0803ed // mov	x13, x8
	B    BB1_19

BB1_18:
	WORD $0x910006f7 // add	x23, x23, #1
	WORD $0x8b0501ad // add	x13, x13, x5
	WORD $0x8b0502b5 // add	x21, x21, x5
	WORD $0xeb0702ff // cmp	x23, x7
	BGE  BB1_16

BB1_19:
	WORD $0x9b097eea // mul	x10, x23, x9
	WORD $0x8b0a0c58 // add	x24, x2, x10, lsl #3
	WORD $0xf94067fa // ldr	x26, [sp, #200]                 ; 8-byte Folded Reload
	WORD $0xaa1103ea // mov	x10, x17
	WORD $0xaa1b03fe // mov	x30, x27
	B    BB1_21

BB1_20:
	WORD $0xfc3e7b00 // str	d0, [x24, x30, lsl #3]
	WORD $0x910007de // add	x30, x30, #1
	WORD $0x9100214a // add	x10, x10, #8
	WORD $0x9100235a // add	x26, x26, #8
	WORD $0xeb1903df // cmp	x30, x25
	BGE  BB1_18

BB1_21:
	WORD $0xfc7e7b00 // ldr	d0, [x24, x30, lsl #3]
	WORD $0x340003a4 // cbz	w4, LBB1_25
	WORD $0xaa0a03fc // mov	x28, x10
	WORD $0xaa0d03f6 // mov	x22, x13
	WORD $0xaa0b03ee // mov	x14, x11

BB1_23:
	WORD $0xad7f0ac1 // ldp	q1, q2, [x22, #-32]
	WORD $0xacc212c3 // ldp	q3, q4, [x22], #64
	WORD $0xad7f1b85 // ldp	q5, q6, [x28, #-32]
	WORD $0xacc24387 // ldp	q7, q16, [x28], #64
	WORD $0x6e65dc21 // fmul.2d	v1, v1, v5
	WORD $0x5e180425 // mov	d5, v1[1]
	WORD $0x6e66dc42 // fmul.2d	v2, v2, v6
	WORD $0x5e180446 // mov	d6, v2[1]
	WORD $0x6e67dc63 // fmul.2d	v3, v3, v7
	WORD $0x5e180467 // mov	d7, v3[1]
	WORD $0x6e70dc84 // fmul.2d	v4, v4, v16
	WORD $0x5e180490 // mov	d16, v4[1]
	WORD $0x1e612800 // fadd	d0, d0, d1
	WORD $0x1e652800 // fadd	d0, d0, d5
	WORD $0x1e622800 // fadd	d0, d0, d2
	WORD $0x1e662800 // fadd	d0, d0, d6
	WORD $0x1e632800 // fadd	d0, d0, d3
	WORD $0x1e672800 // fadd	d0, d0, d7
	WORD $0x1e642800 // fadd	d0, d0, d4
	WORD $0x1e702800 // fadd	d0, d0, d16
	WORD $0xf10021ce // subs	x14, x14, #8
	BNE  BB1_23
	WORD $0xaa1303f4 // mov	x20, x19
	WORD $0xb5000066 // cbnz	x6, LBB1_26
	B    BB1_20

BB1_25:
	WORD $0xaa1003f4 // mov	x20, x16

BB1_26:
	WORD $0x9b14698e // madd	x14, x12, x20, x26

BB1_27:
	WORD $0xfc747aa1 // ldr	d1, [x21, x20, lsl #3]
	WORD $0xfd4001c2 // ldr	d2, [x14]
	WORD $0x1f420020 // fmadd	d0, d1, d2, d0
	WORD $0x91000694 // add	x20, x20, #1
	WORD $0x8b0c01ce // add	x14, x14, x12
	WORD $0xeb01029f // cmp	x20, x1
	BLT  BB1_27
	B    BB1_20

BB1_28:
	WORD $0xd280000f // mov	x15, #0                         ; =0x0
	WORD $0xd2800008 // mov	x8, #0                          ; =0x0
	WORD $0xf94027e3 // ldr	x3, [sp, #72]                   ; 8-byte Folded Reload
	WORD $0x5280002b // mov	w11, #1                         ; =0x1
	WORD $0x5280060a // mov	w10, #48                        ; =0x30
	WORD $0xaa0003e4 // mov	x4, x0
	WORD $0xf94067ee // ldr	x14, [sp, #200]                 ; 8-byte Folded Reload
	B    BB1_30

BB1_29:
	WORD $0xa94a37ef // ldp	x15, x13, [sp, #160]            ; 16-byte Folded Reload
	WORD $0x910005ef // add	x15, x15, #1
	WORD $0xa94683e8 // ldp	x8, x0, [sp, #104]              ; 16-byte Folded Reload
	WORD $0x8b0801ce // add	x14, x14, x8
	WORD $0xa9482be4 // ldp	x4, x10, [sp, #128]             ; 16-byte Folded Reload
	WORD $0x91060084 // add	x4, x4, #384
	WORD $0x9100c14a // add	x10, x10, #48
	WORD $0xa9490feb // ldp	x11, x3, [sp, #144]             ; 16-byte Folded Reload
	WORD $0x9100c16b // add	x11, x11, #48
	WORD $0xd100c1ad // sub	x13, x13, #48
	WORD $0x91060063 // add	x3, x3, #384
	WORD $0x910603de // add	x30, x30, #384
	WORD $0xf9403ff0 // ldr	x16, [sp, #120]                 ; 8-byte Folded Reload
	WORD $0xaa1003e8 // mov	x8, x16
	WORD $0xa94b5fe1 // ldp	x1, x23, [sp, #176]             ; 16-byte Folded Reload
	WORD $0xeb01021f // cmp	x16, x1
	BGE  BB1_13

BB1_30:
	WORD $0xeb0a003f // cmp	x1, x10
	WORD $0xa908afea // stp	x10, x11, [sp, #136]            ; 16-byte Folded Spill
	WORD $0x9a8ab02a // csel	x10, x1, x10, lt
	WORD $0xeb0b015f // cmp	x10, x11
	WORD $0x9a8bc14a // csel	x10, x10, x11, gt
	WORD $0x9240094b // and	x11, x10, #0x7
	WORD $0xa90a37ef // stp	x15, x13, [sp, #160]            ; 16-byte Folded Spill
	WORD $0x8b0d014a // add	x10, x10, x13
	WORD $0xcb0b0150 // sub	x16, x10, x11
	WORD $0x9100c10a // add	x10, x8, #48
	WORD $0xeb0a003f // cmp	x1, x10
	WORD $0xa90793ea // stp	x10, x4, [sp, #120]             ; 16-byte Folded Spill
	WORD $0x9a8ab038 // csel	x24, x1, x10, lt
	WORD $0xb240010a // orr	x10, x8, #0x1
	WORD $0xeb0a031f // cmp	x24, x10
	WORD $0x9a88c70a // csinc	x10, x24, x8, gt
	WORD $0x928005eb // mov	x11, #-48                       ; =0xffffffffffffffd0
	WORD $0x9b0b29eb // madd	x11, x15, x11, x10
	WORD $0xf1001d7f // cmp	x11, #7
	WORD $0xfa418920 // ccmp	x9, #1, #0, hi
	WORD $0x1a9f17f3 // cset	w19, eq
	WORD $0x92400955 // and	x21, x10, #0x7
	WORD $0xcb15016a // sub	x10, x11, x21
	WORD $0x8b0a010b // add	x11, x8, x10
	WORD $0xaa0003f1 // mov	x17, x0
	WORD $0xf9004fe3 // str	x3, [sp, #152]                  ; 8-byte Folded Spill
	WORD $0xaa0303e1 // mov	x1, x3
	WORD $0xaa0403e0 // mov	x0, x4
	WORD $0xaa1703ea // mov	x10, x23
	B    BB1_32

BB1_31:
	WORD $0x9100054a // add	x10, x10, #1
	WORD $0x8b050000 // add	x0, x0, x5
	WORD $0x8b050021 // add	x1, x1, x5
	WORD $0x8b050231 // add	x17, x17, x5
	WORD $0xeb07015f // cmp	x10, x7
	BGE  BB1_29

BB1_32:
	WORD $0x9b097d4d // mul	x13, x10, x9
	WORD $0x8b0d0c46 // add	x6, x2, x13, lsl #3
	WORD $0xf94063f6 // ldr	x22, [sp, #192]                 ; 8-byte Folded Reload
	WORD $0xaa1e03fc // mov	x28, x30
	WORD $0xaa0e03e3 // mov	x3, x14
	WORD $0xaa1a03ef // mov	x15, x26
	WORD $0xaa1b03f7 // mov	x23, x27

BB1_33:
	WORD $0x8b170ccd // add	x13, x6, x23, lsl #3
	WORD $0xaa0f03f7 // mov	x23, x15
	WORD $0xaa1c03f4 // mov	x20, x28
	WORD $0xaa1603e4 // mov	x4, x22
	WORD $0x3dc001a0 // ldr	q0, [x13]
	WORD $0xaa0003ef // mov	x15, x0
	WORD $0xaa0303f6 // mov	x22, x3
	WORD $0xaa0803fc // mov	x28, x8

BB1_34:
	WORD $0xfc4085e1 // ldr	d1, [x15], #8
	WORD $0x3dc002c2 // ldr	q2, [x22]
	WORD $0x4fc11040 // fmla.2d	v0, v2, v1[0]
	WORD $0x9100079c // add	x28, x28, #1
	WORD $0x8b0c02d6 // add	x22, x22, x12
	WORD $0xeb18039f // cmp	x28, x24
	BLT  BB1_34
	WORD $0x91000aef // add	x15, x23, #2
	WORD $0x3d8001a0 // str	q0, [x13]
	WORD $0x91004063 // add	x3, x3, #16
	WORD $0x9100429c // add	x28, x20, #16
	WORD $0x91004096 // add	x22, x4, #16
	WORD $0xeb1901ff // cmp	x15, x25
	BLE  BB1_33
	B    BB1_37

BB1_36:
	WORD $0xfc3778c0 // str	d0, [x6, x23, lsl #3]
	WORD $0x910006f7 // add	x23, x23, #1
	WORD $0x91002294 // add	x20, x20, #8
	WORD $0x91002084 // add	x4, x4, #8

BB1_37:
	WORD $0xeb1902ff // cmp	x23, x25
	BGE  BB1_31
	WORD $0xfc7778c0 // ldr	d0, [x6, x23, lsl #3]
	WORD $0x340003b3 // cbz	w19, LBB1_42
	WORD $0xaa1403f6 // mov	x22, x20
	WORD $0xaa0103ed // mov	x13, x1
	WORD $0xaa1003ef // mov	x15, x16

BB1_40:
	WORD $0xad7f09a1 // ldp	q1, q2, [x13, #-32]
	WORD $0xacc211a3 // ldp	q3, q4, [x13], #64
	WORD $0xad7f1ac5 // ldp	q5, q6, [x22, #-32]
	WORD $0xacc242c7 // ldp	q7, q16, [x22], #64
	WORD $0x6e65dc21 // fmul.2d	v1, v1, v5
	WORD $0x5e180425 // mov	d5, v1[1]
	WORD $0x6e66dc42 // fmul.2d	v2, v2, v6
	WORD $0x5e180446 // mov	d6, v2[1]
	WORD $0x6e67dc63 // fmul.2d	v3, v3, v7
	WORD $0x5e180467 // mov	d7, v3[1]
	WORD $0x6e70dc84 // fmul.2d	v4, v4, v16
	WORD $0x5e180490 // mov	d16, v4[1]
	WORD $0x1e612800 // fadd	d0, d0, d1
	WORD $0x1e652800 // fadd	d0, d0, d5
	WORD $0x1e622800 // fadd	d0, d0, d2
	WORD $0x1e662800 // fadd	d0, d0, d6
	WORD $0x1e632800 // fadd	d0, d0, d3
	WORD $0x1e672800 // fadd	d0, d0, d7
	WORD $0x1e642800 // fadd	d0, d0, d4
	WORD $0x1e702800 // fadd	d0, d0, d16
	WORD $0xf10021ef // subs	x15, x15, #8
	BNE  BB1_40
	WORD $0xaa0b03ed // mov	x13, x11
	WORD $0xb5000075 // cbnz	x21, LBB1_43
	B    BB1_36

BB1_42:
	WORD $0xaa0803ed // mov	x13, x8

BB1_43:
	WORD $0x9b0d118f // madd	x15, x12, x13, x4

BB1_44:
	WORD $0xfc6d7a21 // ldr	d1, [x17, x13, lsl #3]
	WORD $0xfd4001e2 // ldr	d2, [x15]
	WORD $0x1f420020 // fmadd	d0, d1, d2, d0
	WORD $0x910005ad // add	x13, x13, #1
	WORD $0x8b0c01ef // add	x15, x15, x12
	WORD $0xeb1801bf // cmp	x13, x24
	BLT  BB1_44
	B    BB1_36
