//go:build !noasm && arm64
// Code generated by GoAT. DO NOT EDIT.
// versions:
// 	clang   21.1.8
// 	objdump 2.45.1
// flags: -O3
// source: ../c/packed_kernel_neon_arm64.c

package asm

import "unsafe"

//go:noescape
func packed_microkernel_neon_f32(packedA, packedB, c, pkc, pn, pmr, pnr unsafe.Pointer)

//go:noescape
func packed_microkernel_neon_f64(packedA, packedB, c, pkc, pn, pmr, pnr unsafe.Pointer)
