//go:build !noasm && arm64
// Code generated by GoAT. DO NOT EDIT.
// versions:
// 	clang   21.1.8
// 	objdump 2.45.1
// flags: --target=arm64 -march=armv9-a+sme -fno-builtin-memset -O3
// source: /Users/ajroetker/go/src/github.com/ajroetker/go-highway/hwy/contrib/vec/asm/basedot_c_f32_sve_darwin_arm64.c

TEXT ·dot_c_f32_sve_darwin(SB), $0-32
	MOVD a+0(FP), R0
	MOVD b+8(FP), R1
	MOVD plen_a+16(FP), R2
	MOVD pout_result+24(FP), R3
	WORD $0xf9400048            // ldr	x8, [x2]
	WORD $0xb40008c8            // cbz	x8, .LBB0_13
	WORD $0xf101011f            // cmp	x8, #64
	BGE  BB0_5
	WORD $0x6f00e401            // movi	v1.2d, #0000000000000000
	WORD $0x6f00e402            // movi	v2.2d, #0000000000000000
	WORD $0xaa1f03e9            // mov	x9, xzr
	WORD $0x6f00e403            // movi	v3.2d, #0000000000000000
	WORD $0x6f00e400            // movi	v0.2d, #0000000000000000
	WORD $0xb27c03ea            // orr	x10, xzr, #0x10
	WORD $0xeb08015f            // cmp	x10, x8
	BGT  BB0_8
	WORD $0xd503477f            // smstart	sm

BB0_3:
	WORD $0x2598e3e0 // ptrue	p0.s

BB0_4:
	WORD $0xa5494004 // ld1w	{ z4.s }, p0/z, [x0, x9, lsl #2]
	WORD $0xa5494025 // ld1w	{ z5.s }, p0/z, [x1, x9, lsl #2]
	WORD $0x9100812b // add	x11, x9, #32
	WORD $0x9100412a // add	x10, x9, #16
	WORD $0xeb08017f // cmp	x11, x8
	WORD $0xaa0a03e9 // mov	x9, x10
	WORD $0x65a50080 // fmla	z0.s, p0/m, z4.s, z5.s
	BLE  BB0_4
	B    BB0_9

BB0_5:
	WORD $0x6f00e400 // movi	v0.2d, #0000000000000000
	WORD $0x6f00e403 // movi	v3.2d, #0000000000000000
	WORD $0xaa1f03e9 // mov	x9, xzr
	WORD $0x6f00e402 // movi	v2.2d, #0000000000000000
	WORD $0x6f00e401 // movi	v1.2d, #0000000000000000
	WORD $0xd280020a // mov	x10, #16
	WORD $0xd503477f // smstart	sm
	WORD $0x2598e3e0 // ptrue	p0.s
	WORD $0xd280040b // mov	x11, #32
	WORD $0xd280060c // mov	x12, #48

BB0_6:
	WORD $0xd37ef52d // lsl	x13, x9, #2
	WORD $0xa5494004 // ld1w	{ z4.s }, p0/z, [x0, x9, lsl #2]
	WORD $0xa5494025 // ld1w	{ z5.s }, p0/z, [x1, x9, lsl #2]
	WORD $0x8b0d000e // add	x14, x0, x13
	WORD $0x8b0d002d // add	x13, x1, x13
	WORD $0xa54a41c6 // ld1w	{ z6.s }, p0/z, [x14, x10, lsl #2]
	WORD $0xa54b41c7 // ld1w	{ z7.s }, p0/z, [x14, x11, lsl #2]
	WORD $0xa54a41b0 // ld1w	{ z16.s }, p0/z, [x13, x10, lsl #2]
	WORD $0xa54c41d1 // ld1w	{ z17.s }, p0/z, [x14, x12, lsl #2]
	WORD $0xa54b41b2 // ld1w	{ z18.s }, p0/z, [x13, x11, lsl #2]
	WORD $0xa54c41b3 // ld1w	{ z19.s }, p0/z, [x13, x12, lsl #2]
	WORD $0x65a50080 // fmla	z0.s, p0/m, z4.s, z5.s
	WORD $0x9102012d // add	x13, x9, #128
	WORD $0x91010129 // add	x9, x9, #64
	WORD $0x65b000c3 // fmla	z3.s, p0/m, z6.s, z16.s
	WORD $0xeb0801bf // cmp	x13, x8
	WORD $0x65b200e2 // fmla	z2.s, p0/m, z7.s, z18.s
	WORD $0x65b30221 // fmla	z1.s, p0/m, z17.s, z19.s
	BLE  BB0_6
	WORD $0x927ae109 // and	x9, x8, #0x7fffffffffffffc0
	WORD $0xb27c012a // orr	x10, x9, #0x10
	WORD $0xeb08015f // cmp	x10, x8
	BLE  BB0_3

BB0_8:
	WORD $0xaa0903ea // mov	x10, x9
	WORD $0xd503477f // smstart	sm

BB0_9:
	WORD $0x65800060 // fadd	z0.s, z3.s, z0.s
	WORD $0x65820021 // fadd	z1.s, z1.s, z2.s
	WORD $0xeb0a0108 // subs	x8, x8, x10
	WORD $0x2598e3e0 // ptrue	p0.s
	WORD $0x65800020 // fadd	z0.s, z1.s, z0.s
	WORD $0x65802000 // faddv	s0, p0, z0.s
	BLE  BB0_12
	WORD $0xd37ef54a // lsl	x10, x10, #2
	WORD $0x8b0a0029 // add	x9, x1, x10
	WORD $0x8b0a000a // add	x10, x0, x10

BB0_11:
	WORD $0xbc404541 // ldr	s1, [x10], #4
	WORD $0xf1000508 // subs	x8, x8, #1
	WORD $0xbc404522 // ldr	s2, [x9], #4
	WORD $0x1f020020 // fmadd	s0, s1, s2, s0
	BNE  BB0_11

BB0_12:
	WORD $0x9e380008 // fcvtzs	x8, s0

BB0_13:
	WORD $0xf9000068 // str	x8, [x3]
	WORD $0xd503467f // smstop	sm
	RET
