//go:build !noasm && arm64
// Code generated by GoAT. DO NOT EDIT.
// versions:
// 	clang   21.1.8
// 	objdump 2.45.1
// flags: -march=armv9-a+sme -O3
// source: ../c/batch_sme_arm64.c

TEXT ·batch_dot_sme_f32(SB), $0-40
	MOVD query+0(FP), R0
	MOVD data+8(FP), R1
	MOVD dots+16(FP), R2
	MOVD pcount+24(FP), R3
	MOVD pdims+32(FP), R4
	WORD $0xf9400068       // ldr	x8, [x3]
	WORD $0xf9400089       // ldr	x9, [x4]
	WORD $0xf100051f       // cmp	x8, #1
	WORD $0xfa41a928       // ccmp	x9, #1, #8, ge
	BGE  BB0_2

BB0_1:
	WORD $0xd503467f // smstop	sm
	RET

BB0_2:
	WORD $0xf101013f // cmp	x9, #64
	BHS  BB0_8
	WORD $0xf100413f // cmp	x9, #16
	BHS  BB0_16
	WORD $0xd280000a // mov	x10, #0                         ; =0x0
	WORD $0xd503477f // smstart	sm
	WORD $0x25b8c000 // mov	z0.s, #0                        ; =0x0
	WORD $0x2598e3e0 // ptrue	p0.s
	WORD $0x65802000 // faddv	s0, p0, z0.s
	WORD $0xd37ef52b // lsl	x11, x9, #2

BB0_5:
	WORD $0xaa0003ec // mov	x12, x0
	WORD $0xaa0103ed // mov	x13, x1
	WORD $0xaa0903ee // mov	x14, x9
	WORD $0x1e604001 // fmov	d1, d0

BB0_6:
	WORD $0xbc404582 // ldr	s2, [x12], #4
	WORD $0xbc4045a3 // ldr	s3, [x13], #4
	WORD $0x1f030441 // fmadd	s1, s2, s3, s1
	WORD $0xf10005ce // subs	x14, x14, #1
	BNE  BB0_6
	WORD $0xbc2a7841 // str	s1, [x2, x10, lsl #2]
	WORD $0x9100054a // add	x10, x10, #1
	WORD $0x8b0b0021 // add	x1, x1, x11
	WORD $0xeb08015f // cmp	x10, x8
	BNE  BB0_5
	B    BB0_1

BB0_8:
	WORD $0xd280000a // mov	x10, #0                         ; =0x0
	WORD $0x927ae12b // and	x11, x9, #0x7fffffffffffffc0
	WORD $0xb27c016c // orr	x12, x11, #0x10
	WORD $0xd37ef52d // lsl	x13, x9, #2
	WORD $0xd503477f // smstart	sm
	WORD $0x2598e3e0 // ptrue	p0.s
	WORD $0xd280020e // mov	x14, #16                        ; =0x10
	WORD $0xd280040f // mov	x15, #32                        ; =0x20
	WORD $0xd2800610 // mov	x16, #48                        ; =0x30
	B    BB0_10

BB0_9:
	WORD $0xbc2a7840 // str	s0, [x2, x10, lsl #2]
	WORD $0x9100054a // add	x10, x10, #1
	WORD $0x8b0d0021 // add	x1, x1, x13
	WORD $0xeb08015f // cmp	x10, x8
	BEQ  BB0_1

BB0_10:
	WORD $0xd2800011 // mov	x17, #0                         ; =0x0
	WORD $0x25b8c000 // mov	z0.s, #0                        ; =0x0
	WORD $0x25b8c001 // mov	z1.s, #0                        ; =0x0
	WORD $0x25b8c002 // mov	z2.s, #0                        ; =0x0
	WORD $0x25b8c003 // mov	z3.s, #0                        ; =0x0

BB0_11:
	WORD $0xd37ef623 // lsl	x3, x17, #2
	WORD $0x8b030004 // add	x4, x0, x3
	WORD $0xa5514004 // ld1w	{ z4.s }, p0/z, [x0, x17, lsl #2]
	WORD $0xa54e4085 // ld1w	{ z5.s }, p0/z, [x4, x14, lsl #2]
	WORD $0xa54f4086 // ld1w	{ z6.s }, p0/z, [x4, x15, lsl #2]
	WORD $0xa5504087 // ld1w	{ z7.s }, p0/z, [x4, x16, lsl #2]
	WORD $0x8b030023 // add	x3, x1, x3
	WORD $0xa5514030 // ld1w	{ z16.s }, p0/z, [x1, x17, lsl #2]
	WORD $0xa54e4071 // ld1w	{ z17.s }, p0/z, [x3, x14, lsl #2]
	WORD $0xa54f4072 // ld1w	{ z18.s }, p0/z, [x3, x15, lsl #2]
	WORD $0xa5504073 // ld1w	{ z19.s }, p0/z, [x3, x16, lsl #2]
	WORD $0x65b00080 // fmla	z0.s, p0/m, z4.s, z16.s
	WORD $0x65b100a1 // fmla	z1.s, p0/m, z5.s, z17.s
	WORD $0x65b200c2 // fmla	z2.s, p0/m, z6.s, z18.s
	WORD $0x65b300e3 // fmla	z3.s, p0/m, z7.s, z19.s
	WORD $0x91020223 // add	x3, x17, #128
	WORD $0x91010231 // add	x17, x17, #64
	WORD $0xeb09007f // cmp	x3, x9
	BLE  BB0_11
	WORD $0xaa0b03f1 // mov	x17, x11
	WORD $0xeb09019f // cmp	x12, x9
	BGT  BB0_14

BB0_13:
	WORD $0xa5514004 // ld1w	{ z4.s }, p0/z, [x0, x17, lsl #2]
	WORD $0xa5514025 // ld1w	{ z5.s }, p0/z, [x1, x17, lsl #2]
	WORD $0x65a50080 // fmla	z0.s, p0/m, z4.s, z5.s
	WORD $0x91008223 // add	x3, x17, #32
	WORD $0x91004231 // add	x17, x17, #16
	WORD $0xeb09007f // cmp	x3, x9
	BLE  BB0_13

BB0_14:
	WORD $0x65800020 // fadd	z0.s, z1.s, z0.s
	WORD $0x65820061 // fadd	z1.s, z3.s, z2.s
	WORD $0x65800020 // fadd	z0.s, z1.s, z0.s
	WORD $0x65802000 // faddv	s0, p0, z0.s
	WORD $0xeb09023f // cmp	x17, x9
	BGE  BB0_9

BB0_15:
	WORD $0xbc717801 // ldr	s1, [x0, x17, lsl #2]
	WORD $0xbc717822 // ldr	s2, [x1, x17, lsl #2]
	WORD $0x1f020020 // fmadd	s0, s1, s2, s0
	WORD $0x91000631 // add	x17, x17, #1
	WORD $0xeb11013f // cmp	x9, x17
	BNE  BB0_15
	B    BB0_9

BB0_16:
	WORD $0xd280000a // mov	x10, #0                         ; =0x0
	WORD $0x927c052b // and	x11, x9, #0x30
	WORD $0xd37ef52c // lsl	x12, x9, #2
	WORD $0xd503477f // smstart	sm
	WORD $0x2598e3e0 // ptrue	p0.s
	WORD $0x25b8c000 // mov	z0.s, #0                        ; =0x0
	B    BB0_18

BB0_17:
	WORD $0xbc2a7841 // str	s1, [x2, x10, lsl #2]
	WORD $0x9100054a // add	x10, x10, #1
	WORD $0x8b0c0021 // add	x1, x1, x12
	WORD $0xeb08015f // cmp	x10, x8
	BEQ  BB0_1

BB0_18:
	WORD $0xd280000d // mov	x13, #0                         ; =0x0
	WORD $0x25b8c001 // mov	z1.s, #0                        ; =0x0

BB0_19:
	WORD $0xa54d4002 // ld1w	{ z2.s }, p0/z, [x0, x13, lsl #2]
	WORD $0xa54d4023 // ld1w	{ z3.s }, p0/z, [x1, x13, lsl #2]
	WORD $0x65a30041 // fmla	z1.s, p0/m, z2.s, z3.s
	WORD $0x910081ae // add	x14, x13, #32
	WORD $0x910041ad // add	x13, x13, #16
	WORD $0xeb0901df // cmp	x14, x9
	BLE  BB0_19
	WORD $0x65800021 // fadd	z1.s, z1.s, z0.s
	WORD $0x65802021 // faddv	s1, p0, z1.s
	WORD $0xaa0b03ed // mov	x13, x11
	WORD $0xeb09017f // cmp	x11, x9
	BGE  BB0_17

BB0_21:
	WORD $0xbc6d7802 // ldr	s2, [x0, x13, lsl #2]
	WORD $0xbc6d7823 // ldr	s3, [x1, x13, lsl #2]
	WORD $0x1f030441 // fmadd	s1, s2, s3, s1
	WORD $0x910005ad // add	x13, x13, #1
	WORD $0xeb0d013f // cmp	x9, x13
	BNE  BB0_21
	B    BB0_17

TEXT ·batch_dot_sme_f64(SB), $0-40
	MOVD query+0(FP), R0
	MOVD data+8(FP), R1
	MOVD dots+16(FP), R2
	MOVD pcount+24(FP), R3
	MOVD pdims+32(FP), R4
	WORD $0xf9400068       // ldr	x8, [x3]
	WORD $0xf9400089       // ldr	x9, [x4]
	WORD $0xf100051f       // cmp	x8, #1
	WORD $0xfa41a928       // ccmp	x9, #1, #8, ge
	BGE  BB1_2

BB1_1:
	WORD $0xd503467f // smstop	sm
	RET

BB1_2:
	WORD $0xf100813f // cmp	x9, #32
	BHS  BB1_13
	WORD $0xf100213f // cmp	x9, #8
	BHS  BB1_21
	WORD $0xd503477f // smstart	sm
	WORD $0x25f8c000 // mov	z0.d, #0                        ; =0x0
	WORD $0x25d8e3e0 // ptrue	p0.d
	WORD $0x65c02000 // faddv	d0, p0, z0.d
	WORD $0x9100602a // add	x10, x1, #24
	WORD $0xd37df12b // lsl	x11, x9, #3
	B    BB1_6

BB1_5:
	WORD $0xfc008441 // str	d1, [x2], #8
	WORD $0x8b0b014a // add	x10, x10, x11
	WORD $0xf1000508 // subs	x8, x8, #1
	BEQ  BB1_1

BB1_6:
	WORD $0xfd400001 // ldr	d1, [x0]
	WORD $0xfc5e8142 // ldur	d2, [x10, #-24]
	WORD $0x1f420021 // fmadd	d1, d1, d2, d0
	WORD $0xf100053f // cmp	x9, #1
	BEQ  BB1_5
	WORD $0xfd400402 // ldr	d2, [x0, #8]
	WORD $0xfc5f0143 // ldur	d3, [x10, #-16]
	WORD $0x1f430441 // fmadd	d1, d2, d3, d1
	WORD $0xf100093f // cmp	x9, #2
	BEQ  BB1_5
	WORD $0xfd400802 // ldr	d2, [x0, #16]
	WORD $0xfc5f8143 // ldur	d3, [x10, #-8]
	WORD $0x1f430441 // fmadd	d1, d2, d3, d1
	WORD $0xf1000d3f // cmp	x9, #3
	BEQ  BB1_5
	WORD $0xfd400c02 // ldr	d2, [x0, #24]
	WORD $0xfd400143 // ldr	d3, [x10]
	WORD $0x1f430441 // fmadd	d1, d2, d3, d1
	WORD $0xf100113f // cmp	x9, #4
	BEQ  BB1_5
	WORD $0xfd401002 // ldr	d2, [x0, #32]
	WORD $0xfd400543 // ldr	d3, [x10, #8]
	WORD $0x1f430441 // fmadd	d1, d2, d3, d1
	WORD $0xf100153f // cmp	x9, #5
	BEQ  BB1_5
	WORD $0xfd401402 // ldr	d2, [x0, #40]
	WORD $0xfd400943 // ldr	d3, [x10, #16]
	WORD $0x1f430441 // fmadd	d1, d2, d3, d1
	WORD $0xf100193f // cmp	x9, #6
	BEQ  BB1_5
	WORD $0xfd401802 // ldr	d2, [x0, #48]
	WORD $0xfd400d43 // ldr	d3, [x10, #24]
	WORD $0x1f430441 // fmadd	d1, d2, d3, d1
	B    BB1_5

BB1_13:
	WORD $0xd280000a // mov	x10, #0                         ; =0x0
	WORD $0x927be52b // and	x11, x9, #0x7fffffffffffffe0
	WORD $0xb27d016c // orr	x12, x11, #0x8
	WORD $0xd37df12d // lsl	x13, x9, #3
	WORD $0xd503477f // smstart	sm
	WORD $0x25d8e3e0 // ptrue	p0.d
	WORD $0xd280010e // mov	x14, #8                         ; =0x8
	WORD $0xd280020f // mov	x15, #16                        ; =0x10
	WORD $0xd2800310 // mov	x16, #24                        ; =0x18
	B    BB1_15

BB1_14:
	WORD $0xfc2a7840 // str	d0, [x2, x10, lsl #3]
	WORD $0x9100054a // add	x10, x10, #1
	WORD $0x8b0d0021 // add	x1, x1, x13
	WORD $0xeb08015f // cmp	x10, x8
	BEQ  BB1_1

BB1_15:
	WORD $0xd2800011 // mov	x17, #0                         ; =0x0
	WORD $0x25f8c000 // mov	z0.d, #0                        ; =0x0
	WORD $0x25f8c001 // mov	z1.d, #0                        ; =0x0
	WORD $0x25f8c002 // mov	z2.d, #0                        ; =0x0
	WORD $0x25f8c003 // mov	z3.d, #0                        ; =0x0

BB1_16:
	WORD $0xd37df223 // lsl	x3, x17, #3
	WORD $0x8b030004 // add	x4, x0, x3
	WORD $0xa5f14004 // ld1d	{ z4.d }, p0/z, [x0, x17, lsl #3]
	WORD $0xa5ee4085 // ld1d	{ z5.d }, p0/z, [x4, x14, lsl #3]
	WORD $0xa5ef4086 // ld1d	{ z6.d }, p0/z, [x4, x15, lsl #3]
	WORD $0xa5f04087 // ld1d	{ z7.d }, p0/z, [x4, x16, lsl #3]
	WORD $0x8b030023 // add	x3, x1, x3
	WORD $0xa5f14030 // ld1d	{ z16.d }, p0/z, [x1, x17, lsl #3]
	WORD $0xa5ee4071 // ld1d	{ z17.d }, p0/z, [x3, x14, lsl #3]
	WORD $0xa5ef4072 // ld1d	{ z18.d }, p0/z, [x3, x15, lsl #3]
	WORD $0xa5f04073 // ld1d	{ z19.d }, p0/z, [x3, x16, lsl #3]
	WORD $0x65f00080 // fmla	z0.d, p0/m, z4.d, z16.d
	WORD $0x65f100a1 // fmla	z1.d, p0/m, z5.d, z17.d
	WORD $0x65f200c2 // fmla	z2.d, p0/m, z6.d, z18.d
	WORD $0x65f300e3 // fmla	z3.d, p0/m, z7.d, z19.d
	WORD $0x91010223 // add	x3, x17, #64
	WORD $0x91008231 // add	x17, x17, #32
	WORD $0xeb09007f // cmp	x3, x9
	BLE  BB1_16
	WORD $0xaa0b03f1 // mov	x17, x11
	WORD $0xeb09019f // cmp	x12, x9
	BGT  BB1_19

BB1_18:
	WORD $0xa5f14004 // ld1d	{ z4.d }, p0/z, [x0, x17, lsl #3]
	WORD $0xa5f14025 // ld1d	{ z5.d }, p0/z, [x1, x17, lsl #3]
	WORD $0x65e50080 // fmla	z0.d, p0/m, z4.d, z5.d
	WORD $0x91004223 // add	x3, x17, #16
	WORD $0x91002231 // add	x17, x17, #8
	WORD $0xeb09007f // cmp	x3, x9
	BLE  BB1_18

BB1_19:
	WORD $0x65c00020 // fadd	z0.d, z1.d, z0.d
	WORD $0x65c20061 // fadd	z1.d, z3.d, z2.d
	WORD $0x65c00020 // fadd	z0.d, z1.d, z0.d
	WORD $0x65c02000 // faddv	d0, p0, z0.d
	WORD $0xeb09023f // cmp	x17, x9
	BGE  BB1_14

BB1_20:
	WORD $0xfc717801 // ldr	d1, [x0, x17, lsl #3]
	WORD $0xfc717822 // ldr	d2, [x1, x17, lsl #3]
	WORD $0x1f420020 // fmadd	d0, d1, d2, d0
	WORD $0x91000631 // add	x17, x17, #1
	WORD $0xeb11013f // cmp	x9, x17
	BNE  BB1_20
	B    BB1_14

BB1_21:
	WORD $0xd280000a // mov	x10, #0                         ; =0x0
	WORD $0x927d052b // and	x11, x9, #0x18
	WORD $0xd37df12c // lsl	x12, x9, #3
	WORD $0xd503477f // smstart	sm
	WORD $0x25d8e3e0 // ptrue	p0.d
	WORD $0x25f8c000 // mov	z0.d, #0                        ; =0x0
	B    BB1_23

BB1_22:
	WORD $0xfc2a7841 // str	d1, [x2, x10, lsl #3]
	WORD $0x9100054a // add	x10, x10, #1
	WORD $0x8b0c0021 // add	x1, x1, x12
	WORD $0xeb08015f // cmp	x10, x8
	BEQ  BB1_1

BB1_23:
	WORD $0xd280000d // mov	x13, #0                         ; =0x0
	WORD $0x25f8c001 // mov	z1.d, #0                        ; =0x0

BB1_24:
	WORD $0xa5ed4002 // ld1d	{ z2.d }, p0/z, [x0, x13, lsl #3]
	WORD $0xa5ed4023 // ld1d	{ z3.d }, p0/z, [x1, x13, lsl #3]
	WORD $0x65e30041 // fmla	z1.d, p0/m, z2.d, z3.d
	WORD $0x910041ae // add	x14, x13, #16
	WORD $0x910021ad // add	x13, x13, #8
	WORD $0xeb0901df // cmp	x14, x9
	BLE  BB1_24
	WORD $0x65c00021 // fadd	z1.d, z1.d, z0.d
	WORD $0x65c02021 // faddv	d1, p0, z1.d
	WORD $0xaa0b03ed // mov	x13, x11
	WORD $0xeb09017f // cmp	x11, x9
	BGE  BB1_22

BB1_26:
	WORD $0xfc6d7802 // ldr	d2, [x0, x13, lsl #3]
	WORD $0xfc6d7823 // ldr	d3, [x1, x13, lsl #3]
	WORD $0x1f430441 // fmadd	d1, d2, d3, d1
	WORD $0x910005ad // add	x13, x13, #1
	WORD $0xeb0d013f // cmp	x9, x13
	BNE  BB1_26
	B    BB1_22

TEXT ·batch_l2_squared_sme_f32(SB), $0-40
	MOVD query+0(FP), R0
	MOVD data+8(FP), R1
	MOVD distances+16(FP), R2
	MOVD pcount+24(FP), R3
	MOVD pdims+32(FP), R4
	WORD $0xf9400068          // ldr	x8, [x3]
	WORD $0xf9400089          // ldr	x9, [x4]
	WORD $0xf100051f          // cmp	x8, #1
	WORD $0xfa41a928          // ccmp	x9, #1, #8, ge
	BGE  BB2_2

BB2_1:
	WORD $0xd503467f // smstop	sm
	RET

BB2_2:
	WORD $0xf101013f // cmp	x9, #64
	BHS  BB2_8
	WORD $0xf100413f // cmp	x9, #16
	BHS  BB2_16
	WORD $0xd280000a // mov	x10, #0                         ; =0x0
	WORD $0xd503477f // smstart	sm
	WORD $0x25b8c000 // mov	z0.s, #0                        ; =0x0
	WORD $0x2598e3e0 // ptrue	p0.s
	WORD $0x65802000 // faddv	s0, p0, z0.s
	WORD $0xd37ef52b // lsl	x11, x9, #2

BB2_5:
	WORD $0xaa0003ec // mov	x12, x0
	WORD $0xaa0103ed // mov	x13, x1
	WORD $0xaa0903ee // mov	x14, x9
	WORD $0x1e604001 // fmov	d1, d0

BB2_6:
	WORD $0xbc404582 // ldr	s2, [x12], #4
	WORD $0xbc4045a3 // ldr	s3, [x13], #4
	WORD $0x1e233842 // fsub	s2, s2, s3
	WORD $0x1f020441 // fmadd	s1, s2, s2, s1
	WORD $0xf10005ce // subs	x14, x14, #1
	BNE  BB2_6
	WORD $0xbc2a7841 // str	s1, [x2, x10, lsl #2]
	WORD $0x9100054a // add	x10, x10, #1
	WORD $0x8b0b0021 // add	x1, x1, x11
	WORD $0xeb08015f // cmp	x10, x8
	BNE  BB2_5
	B    BB2_1

BB2_8:
	WORD $0xd280000a // mov	x10, #0                         ; =0x0
	WORD $0x927ae12b // and	x11, x9, #0x7fffffffffffffc0
	WORD $0xb27c016c // orr	x12, x11, #0x10
	WORD $0xd37ef52d // lsl	x13, x9, #2
	WORD $0xd503477f // smstart	sm
	WORD $0x2598e3e0 // ptrue	p0.s
	WORD $0xd280020e // mov	x14, #16                        ; =0x10
	WORD $0xd280040f // mov	x15, #32                        ; =0x20
	WORD $0xd2800610 // mov	x16, #48                        ; =0x30
	B    BB2_10

BB2_9:
	WORD $0xbc2a7840 // str	s0, [x2, x10, lsl #2]
	WORD $0x9100054a // add	x10, x10, #1
	WORD $0x8b0d0021 // add	x1, x1, x13
	WORD $0xeb08015f // cmp	x10, x8
	BEQ  BB2_1

BB2_10:
	WORD $0xd2800011 // mov	x17, #0                         ; =0x0
	WORD $0x25b8c000 // mov	z0.s, #0                        ; =0x0
	WORD $0x25b8c001 // mov	z1.s, #0                        ; =0x0
	WORD $0x25b8c002 // mov	z2.s, #0                        ; =0x0
	WORD $0x25b8c003 // mov	z3.s, #0                        ; =0x0

BB2_11:
	WORD $0xd37ef623 // lsl	x3, x17, #2
	WORD $0x8b030004 // add	x4, x0, x3
	WORD $0xa5514004 // ld1w	{ z4.s }, p0/z, [x0, x17, lsl #2]
	WORD $0xa54e4085 // ld1w	{ z5.s }, p0/z, [x4, x14, lsl #2]
	WORD $0xa54f4086 // ld1w	{ z6.s }, p0/z, [x4, x15, lsl #2]
	WORD $0xa5504087 // ld1w	{ z7.s }, p0/z, [x4, x16, lsl #2]
	WORD $0x8b030023 // add	x3, x1, x3
	WORD $0xa5514030 // ld1w	{ z16.s }, p0/z, [x1, x17, lsl #2]
	WORD $0xa54e4071 // ld1w	{ z17.s }, p0/z, [x3, x14, lsl #2]
	WORD $0xa54f4072 // ld1w	{ z18.s }, p0/z, [x3, x15, lsl #2]
	WORD $0xa5504073 // ld1w	{ z19.s }, p0/z, [x3, x16, lsl #2]
	WORD $0x65900484 // fsub	z4.s, z4.s, z16.s
	WORD $0x659104a5 // fsub	z5.s, z5.s, z17.s
	WORD $0x659204c6 // fsub	z6.s, z6.s, z18.s
	WORD $0x659304e7 // fsub	z7.s, z7.s, z19.s
	WORD $0x65a40080 // fmla	z0.s, p0/m, z4.s, z4.s
	WORD $0x65a500a1 // fmla	z1.s, p0/m, z5.s, z5.s
	WORD $0x65a600c2 // fmla	z2.s, p0/m, z6.s, z6.s
	WORD $0x65a700e3 // fmla	z3.s, p0/m, z7.s, z7.s
	WORD $0x91020223 // add	x3, x17, #128
	WORD $0x91010231 // add	x17, x17, #64
	WORD $0xeb09007f // cmp	x3, x9
	BLE  BB2_11
	WORD $0xaa0b03f1 // mov	x17, x11
	WORD $0xeb09019f // cmp	x12, x9
	BGT  BB2_14

BB2_13:
	WORD $0xa5514004 // ld1w	{ z4.s }, p0/z, [x0, x17, lsl #2]
	WORD $0xa5514025 // ld1w	{ z5.s }, p0/z, [x1, x17, lsl #2]
	WORD $0x65850484 // fsub	z4.s, z4.s, z5.s
	WORD $0x65a40080 // fmla	z0.s, p0/m, z4.s, z4.s
	WORD $0x91008223 // add	x3, x17, #32
	WORD $0x91004231 // add	x17, x17, #16
	WORD $0xeb09007f // cmp	x3, x9
	BLE  BB2_13

BB2_14:
	WORD $0x65800020 // fadd	z0.s, z1.s, z0.s
	WORD $0x65820061 // fadd	z1.s, z3.s, z2.s
	WORD $0x65800020 // fadd	z0.s, z1.s, z0.s
	WORD $0x65802000 // faddv	s0, p0, z0.s
	WORD $0xeb09023f // cmp	x17, x9
	BGE  BB2_9

BB2_15:
	WORD $0xbc717801 // ldr	s1, [x0, x17, lsl #2]
	WORD $0xbc717822 // ldr	s2, [x1, x17, lsl #2]
	WORD $0x1e223821 // fsub	s1, s1, s2
	WORD $0x1f010020 // fmadd	s0, s1, s1, s0
	WORD $0x91000631 // add	x17, x17, #1
	WORD $0xeb11013f // cmp	x9, x17
	BNE  BB2_15
	B    BB2_9

BB2_16:
	WORD $0xd280000a // mov	x10, #0                         ; =0x0
	WORD $0x927c052b // and	x11, x9, #0x30
	WORD $0xd37ef52c // lsl	x12, x9, #2
	WORD $0xd503477f // smstart	sm
	WORD $0x2598e3e0 // ptrue	p0.s
	WORD $0x25b8c000 // mov	z0.s, #0                        ; =0x0
	B    BB2_18

BB2_17:
	WORD $0xbc2a7841 // str	s1, [x2, x10, lsl #2]
	WORD $0x9100054a // add	x10, x10, #1
	WORD $0x8b0c0021 // add	x1, x1, x12
	WORD $0xeb08015f // cmp	x10, x8
	BEQ  BB2_1

BB2_18:
	WORD $0xd280000d // mov	x13, #0                         ; =0x0
	WORD $0x25b8c001 // mov	z1.s, #0                        ; =0x0

BB2_19:
	WORD $0xa54d4002 // ld1w	{ z2.s }, p0/z, [x0, x13, lsl #2]
	WORD $0xa54d4023 // ld1w	{ z3.s }, p0/z, [x1, x13, lsl #2]
	WORD $0x65830442 // fsub	z2.s, z2.s, z3.s
	WORD $0x65a20041 // fmla	z1.s, p0/m, z2.s, z2.s
	WORD $0x910081ae // add	x14, x13, #32
	WORD $0x910041ad // add	x13, x13, #16
	WORD $0xeb0901df // cmp	x14, x9
	BLE  BB2_19
	WORD $0x65800021 // fadd	z1.s, z1.s, z0.s
	WORD $0x65802021 // faddv	s1, p0, z1.s
	WORD $0xaa0b03ed // mov	x13, x11
	WORD $0xeb09017f // cmp	x11, x9
	BGE  BB2_17

BB2_21:
	WORD $0xbc6d7802 // ldr	s2, [x0, x13, lsl #2]
	WORD $0xbc6d7823 // ldr	s3, [x1, x13, lsl #2]
	WORD $0x1e233842 // fsub	s2, s2, s3
	WORD $0x1f020441 // fmadd	s1, s2, s2, s1
	WORD $0x910005ad // add	x13, x13, #1
	WORD $0xeb0d013f // cmp	x9, x13
	BNE  BB2_21
	B    BB2_17

TEXT ·batch_l2_squared_sme_f64(SB), $0-40
	MOVD query+0(FP), R0
	MOVD data+8(FP), R1
	MOVD distances+16(FP), R2
	MOVD pcount+24(FP), R3
	MOVD pdims+32(FP), R4
	WORD $0xf9400068          // ldr	x8, [x3]
	WORD $0xf9400089          // ldr	x9, [x4]
	WORD $0xf100051f          // cmp	x8, #1
	WORD $0xfa41a928          // ccmp	x9, #1, #8, ge
	BGE  BB3_2

BB3_1:
	WORD $0xd503467f // smstop	sm
	RET

BB3_2:
	WORD $0xf100813f // cmp	x9, #32
	BHS  BB3_13
	WORD $0xf100213f // cmp	x9, #8
	BHS  BB3_21
	WORD $0xd503477f // smstart	sm
	WORD $0x25f8c000 // mov	z0.d, #0                        ; =0x0
	WORD $0x25d8e3e0 // ptrue	p0.d
	WORD $0x65c02000 // faddv	d0, p0, z0.d
	WORD $0x9100602a // add	x10, x1, #24
	WORD $0xd37df12b // lsl	x11, x9, #3
	B    BB3_6

BB3_5:
	WORD $0xfc008441 // str	d1, [x2], #8
	WORD $0x8b0b014a // add	x10, x10, x11
	WORD $0xf1000508 // subs	x8, x8, #1
	BEQ  BB3_1

BB3_6:
	WORD $0xfd400001 // ldr	d1, [x0]
	WORD $0xfc5e8142 // ldur	d2, [x10, #-24]
	WORD $0x1e623821 // fsub	d1, d1, d2
	WORD $0x1f410021 // fmadd	d1, d1, d1, d0
	WORD $0xf100053f // cmp	x9, #1
	BEQ  BB3_5
	WORD $0xfd400402 // ldr	d2, [x0, #8]
	WORD $0xfc5f0143 // ldur	d3, [x10, #-16]
	WORD $0x1e633842 // fsub	d2, d2, d3
	WORD $0x1f420441 // fmadd	d1, d2, d2, d1
	WORD $0xf100093f // cmp	x9, #2
	BEQ  BB3_5
	WORD $0xfd400802 // ldr	d2, [x0, #16]
	WORD $0xfc5f8143 // ldur	d3, [x10, #-8]
	WORD $0x1e633842 // fsub	d2, d2, d3
	WORD $0x1f420441 // fmadd	d1, d2, d2, d1
	WORD $0xf1000d3f // cmp	x9, #3
	BEQ  BB3_5
	WORD $0xfd400c02 // ldr	d2, [x0, #24]
	WORD $0xfd400143 // ldr	d3, [x10]
	WORD $0x1e633842 // fsub	d2, d2, d3
	WORD $0x1f420441 // fmadd	d1, d2, d2, d1
	WORD $0xf100113f // cmp	x9, #4
	BEQ  BB3_5
	WORD $0xfd401002 // ldr	d2, [x0, #32]
	WORD $0xfd400543 // ldr	d3, [x10, #8]
	WORD $0x1e633842 // fsub	d2, d2, d3
	WORD $0x1f420441 // fmadd	d1, d2, d2, d1
	WORD $0xf100153f // cmp	x9, #5
	BEQ  BB3_5
	WORD $0xfd401402 // ldr	d2, [x0, #40]
	WORD $0xfd400943 // ldr	d3, [x10, #16]
	WORD $0x1e633842 // fsub	d2, d2, d3
	WORD $0x1f420441 // fmadd	d1, d2, d2, d1
	WORD $0xf100193f // cmp	x9, #6
	BEQ  BB3_5
	WORD $0xfd401802 // ldr	d2, [x0, #48]
	WORD $0xfd400d43 // ldr	d3, [x10, #24]
	WORD $0x1e633842 // fsub	d2, d2, d3
	WORD $0x1f420441 // fmadd	d1, d2, d2, d1
	B    BB3_5

BB3_13:
	WORD $0xd280000a // mov	x10, #0                         ; =0x0
	WORD $0x927be52b // and	x11, x9, #0x7fffffffffffffe0
	WORD $0xb27d016c // orr	x12, x11, #0x8
	WORD $0xd37df12d // lsl	x13, x9, #3
	WORD $0xd503477f // smstart	sm
	WORD $0x25d8e3e0 // ptrue	p0.d
	WORD $0xd280010e // mov	x14, #8                         ; =0x8
	WORD $0xd280020f // mov	x15, #16                        ; =0x10
	WORD $0xd2800310 // mov	x16, #24                        ; =0x18
	B    BB3_15

BB3_14:
	WORD $0xfc2a7840 // str	d0, [x2, x10, lsl #3]
	WORD $0x9100054a // add	x10, x10, #1
	WORD $0x8b0d0021 // add	x1, x1, x13
	WORD $0xeb08015f // cmp	x10, x8
	BEQ  BB3_1

BB3_15:
	WORD $0xd2800011 // mov	x17, #0                         ; =0x0
	WORD $0x25f8c000 // mov	z0.d, #0                        ; =0x0
	WORD $0x25f8c001 // mov	z1.d, #0                        ; =0x0
	WORD $0x25f8c002 // mov	z2.d, #0                        ; =0x0
	WORD $0x25f8c003 // mov	z3.d, #0                        ; =0x0

BB3_16:
	WORD $0xd37df223 // lsl	x3, x17, #3
	WORD $0x8b030004 // add	x4, x0, x3
	WORD $0xa5f14004 // ld1d	{ z4.d }, p0/z, [x0, x17, lsl #3]
	WORD $0xa5ee4085 // ld1d	{ z5.d }, p0/z, [x4, x14, lsl #3]
	WORD $0xa5ef4086 // ld1d	{ z6.d }, p0/z, [x4, x15, lsl #3]
	WORD $0xa5f04087 // ld1d	{ z7.d }, p0/z, [x4, x16, lsl #3]
	WORD $0x8b030023 // add	x3, x1, x3
	WORD $0xa5f14030 // ld1d	{ z16.d }, p0/z, [x1, x17, lsl #3]
	WORD $0xa5ee4071 // ld1d	{ z17.d }, p0/z, [x3, x14, lsl #3]
	WORD $0xa5ef4072 // ld1d	{ z18.d }, p0/z, [x3, x15, lsl #3]
	WORD $0xa5f04073 // ld1d	{ z19.d }, p0/z, [x3, x16, lsl #3]
	WORD $0x65d00484 // fsub	z4.d, z4.d, z16.d
	WORD $0x65d104a5 // fsub	z5.d, z5.d, z17.d
	WORD $0x65d204c6 // fsub	z6.d, z6.d, z18.d
	WORD $0x65d304e7 // fsub	z7.d, z7.d, z19.d
	WORD $0x65e40080 // fmla	z0.d, p0/m, z4.d, z4.d
	WORD $0x65e500a1 // fmla	z1.d, p0/m, z5.d, z5.d
	WORD $0x65e600c2 // fmla	z2.d, p0/m, z6.d, z6.d
	WORD $0x65e700e3 // fmla	z3.d, p0/m, z7.d, z7.d
	WORD $0x91010223 // add	x3, x17, #64
	WORD $0x91008231 // add	x17, x17, #32
	WORD $0xeb09007f // cmp	x3, x9
	BLE  BB3_16
	WORD $0xaa0b03f1 // mov	x17, x11
	WORD $0xeb09019f // cmp	x12, x9
	BGT  BB3_19

BB3_18:
	WORD $0xa5f14004 // ld1d	{ z4.d }, p0/z, [x0, x17, lsl #3]
	WORD $0xa5f14025 // ld1d	{ z5.d }, p0/z, [x1, x17, lsl #3]
	WORD $0x65c50484 // fsub	z4.d, z4.d, z5.d
	WORD $0x65e40080 // fmla	z0.d, p0/m, z4.d, z4.d
	WORD $0x91004223 // add	x3, x17, #16
	WORD $0x91002231 // add	x17, x17, #8
	WORD $0xeb09007f // cmp	x3, x9
	BLE  BB3_18

BB3_19:
	WORD $0x65c00020 // fadd	z0.d, z1.d, z0.d
	WORD $0x65c20061 // fadd	z1.d, z3.d, z2.d
	WORD $0x65c00020 // fadd	z0.d, z1.d, z0.d
	WORD $0x65c02000 // faddv	d0, p0, z0.d
	WORD $0xeb09023f // cmp	x17, x9
	BGE  BB3_14

BB3_20:
	WORD $0xfc717801 // ldr	d1, [x0, x17, lsl #3]
	WORD $0xfc717822 // ldr	d2, [x1, x17, lsl #3]
	WORD $0x1e623821 // fsub	d1, d1, d2
	WORD $0x1f410020 // fmadd	d0, d1, d1, d0
	WORD $0x91000631 // add	x17, x17, #1
	WORD $0xeb11013f // cmp	x9, x17
	BNE  BB3_20
	B    BB3_14

BB3_21:
	WORD $0xd280000a // mov	x10, #0                         ; =0x0
	WORD $0x927d052b // and	x11, x9, #0x18
	WORD $0xd37df12c // lsl	x12, x9, #3
	WORD $0xd503477f // smstart	sm
	WORD $0x25d8e3e0 // ptrue	p0.d
	WORD $0x25f8c000 // mov	z0.d, #0                        ; =0x0
	B    BB3_23

BB3_22:
	WORD $0xfc2a7841 // str	d1, [x2, x10, lsl #3]
	WORD $0x9100054a // add	x10, x10, #1
	WORD $0x8b0c0021 // add	x1, x1, x12
	WORD $0xeb08015f // cmp	x10, x8
	BEQ  BB3_1

BB3_23:
	WORD $0xd280000d // mov	x13, #0                         ; =0x0
	WORD $0x25f8c001 // mov	z1.d, #0                        ; =0x0

BB3_24:
	WORD $0xa5ed4002 // ld1d	{ z2.d }, p0/z, [x0, x13, lsl #3]
	WORD $0xa5ed4023 // ld1d	{ z3.d }, p0/z, [x1, x13, lsl #3]
	WORD $0x65c30442 // fsub	z2.d, z2.d, z3.d
	WORD $0x65e20041 // fmla	z1.d, p0/m, z2.d, z2.d
	WORD $0x910041ae // add	x14, x13, #16
	WORD $0x910021ad // add	x13, x13, #8
	WORD $0xeb0901df // cmp	x14, x9
	BLE  BB3_24
	WORD $0x65c00021 // fadd	z1.d, z1.d, z0.d
	WORD $0x65c02021 // faddv	d1, p0, z1.d
	WORD $0xaa0b03ed // mov	x13, x11
	WORD $0xeb09017f // cmp	x11, x9
	BGE  BB3_22

BB3_26:
	WORD $0xfc6d7802 // ldr	d2, [x0, x13, lsl #3]
	WORD $0xfc6d7823 // ldr	d3, [x1, x13, lsl #3]
	WORD $0x1e633842 // fsub	d2, d2, d3
	WORD $0x1f420441 // fmadd	d1, d2, d2, d1
	WORD $0x910005ad // add	x13, x13, #1
	WORD $0xeb0d013f // cmp	x9, x13
	BNE  BB3_26
	B    BB3_22
