//go:build !noasm && darwin && arm64
// Code generated by hwygen -c. DO NOT EDIT.

package asm

import "unsafe"

// Dot_F32 calls the SVE_DARWIN SIMD assembly implementation.
func Dot_F32(a unsafe.Pointer, b unsafe.Pointer, plen unsafe.Pointer, pout_result unsafe.Pointer) {
	dot_c_f32_sve_darwin(a, b, plen, pout_result)
}

// Dot_F64 calls the SVE_DARWIN SIMD assembly implementation.
func Dot_F64(a unsafe.Pointer, b unsafe.Pointer, plen unsafe.Pointer, pout_result unsafe.Pointer) {
	dot_c_f64_sve_darwin(a, b, plen, pout_result)
}

