//go:build !noasm && arm64
// Code generated by GoAT. DO NOT EDIT.
// versions:
// 	clang   21.1.8
// 	objdump 2.45.1
// flags: --target=arm64 -march=armv8-a+simd+fp -fno-builtin-memset -O3
// source: /Users/ajroetker/go/src/github.com/ajroetker/go-highway/hwy/contrib/image/asm/baseforwardict_c_f32_neon_arm64.c

TEXT ·forwardict_c_f32_neon(SB), $96-48
	MOVD r+0(FP), R0
	MOVD gv+8(FP), R1
	MOVD b+16(FP), R2
	MOVD outY+24(FP), R3
	MOVD outCb+32(FP), R4
	MOVD outCr+40(FP), R5
	WORD $0xb40013c0      // cbz	x0, .LBB0_22
	WORD $0xb40013a1      // cbz	x1, .LBB0_22
	WORD $0xb4001382      // cbz	x2, .LBB0_22
	WORD $0xb4001363      // cbz	x3, .LBB0_22
	WORD $0xb4001344      // cbz	x4, .LBB0_22
	WORD $0xb4001325      // cbz	x5, .LBB0_22
	WORD $0xf9400008      // ldr	x8, [x0]
	WORD $0xb40012e8      // cbz	x8, .LBB0_22
	WORD $0xf9400028      // ldr	x8, [x1]
	WORD $0xb40012a8      // cbz	x8, .LBB0_22
	WORD $0xf9400048      // ldr	x8, [x2]
	WORD $0xb4001268      // cbz	x8, .LBB0_22
	WORD $0xf9400068      // ldr	x8, [x3]
	WORD $0xb4001228      // cbz	x8, .LBB0_22
	WORD $0xf9400088      // ldr	x8, [x4]
	WORD $0xb40011e8      // cbz	x8, .LBB0_22
	WORD $0xf94000a8      // ldr	x8, [x5]
	WORD $0xb40011a8      // cbz	x8, .LBB0_22
	WORD $0xf9400408      // ldr	x8, [x0, #8]
	WORD $0xf9000bfd      // str	x29, [sp, #16]
	WORD $0xa90267fe      // stp	x30, x25, [sp, #32]
	WORD $0xf100051f      // cmp	x8, #1
	WORD $0xa9035ff8      // stp	x24, x23, [sp, #48]
	WORD $0xa90457f6      // stp	x22, x21, [sp, #64]
	WORD $0xa9054ff4      // stp	x20, x19, [sp, #80]
	WORD $0xf90003e8      // str	x8, [sp]
	BLT  BB0_21
	WORD $0x528f1aa8      // mov	w8, #30933
	WORD $0x5288b44a      // mov	w10, #17826
	WORD $0x5282d0eb      // mov	w11, #5767
	WORD $0x72a7bd28      // movk	w8, #15849, lsl #16
	WORD $0x72a7e2ca      // movk	w10, #16150, lsl #16
	WORD $0x72a7d32b      // movk	w11, #16025, lsl #16
	WORD $0x4e040d00      // dup	v0.4s, w8
	WORD $0x52935d28      // mov	w8, #39657
	WORD $0x4e040d41      // dup	v1.4s, w10
	WORD $0x72b7d528      // movk	w8, #48809, lsl #16
	WORD $0x4e040d62      // dup	v2.4s, w11
	WORD $0x5290bb6a      // mov	w10, #34267
	WORD $0x4e040d04      // dup	v4.4s, w8
	WORD $0x529999a8      // mov	w8, #52429
	WORD $0x528bd12b      // mov	w11, #24201
	WORD $0x4f0167e3      // movi	v3.4s, #63, lsl #24
	WORD $0x72b7c588      // movk	w8, #48684, lsl #16
	WORD $0x72b7b4ca      // movk	w10, #48550, lsl #16
	WORD $0x72b7dacb      // movk	w11, #48854, lsl #16
	WORD $0x4e040d05      // dup	v5.4s, w8
	WORD $0x4e040d46      // dup	v6.4s, w10
	WORD $0x4e040d67      // dup	v7.4s, w11
	WORD $0xf9400c0a      // ldr	x10, [x0, #24]
	WORD $0xaa1f03e9      // mov	x9, xzr
	WORD $0xaa1f03eb      // mov	x11, xzr
	B    BB0_15

BB0_14:
	WORD $0xf94003e8 // ldr	x8, [sp]
	WORD $0x9100056b // add	x11, x11, #1
	WORD $0x91001129 // add	x9, x9, #4
	WORD $0xeb08017f // cmp	x11, x8
	BEQ  BB0_21

BB0_15:
	WORD $0xf9400011 // ldr	x17, [x0]
	WORD $0xf9400807 // ldr	x7, [x0, #16]
	WORD $0xf100115f // cmp	x10, #4
	WORD $0xf9400033 // ldr	x19, [x1]
	WORD $0xf9400835 // ldr	x21, [x1, #16]
	WORD $0xf9400054 // ldr	x20, [x2]
	WORD $0xf9400856 // ldr	x22, [x2, #16]
	WORD $0xf940006e // ldr	x14, [x3]
	WORD $0xf9400866 // ldr	x6, [x3, #16]
	WORD $0xf940008c // ldr	x12, [x4]
	WORD $0xf9400890 // ldr	x16, [x4, #16]
	WORD $0xf94000a8 // ldr	x8, [x5]
	WORD $0xf94008af // ldr	x15, [x5, #16]
	WORD $0xf9000fe8 // str	x8, [sp, #24]
	WORD $0xf90007ec // str	x12, [sp, #8]
	BGE  BB0_17
	WORD $0xaa1f03ed // mov	x13, xzr
	B    BB0_19

BB0_17:
	WORD $0x9b0944f7 // madd	x23, x7, x9, x17
	WORD $0x9b094eb8 // madd	x24, x21, x9, x19
	WORD $0x9b0952d9 // madd	x25, x22, x9, x20
	WORD $0x9b0938dd // madd	x29, x6, x9, x14
	WORD $0x9b09321e // madd	x30, x16, x9, x12
	WORD $0xaa1f03ec // mov	x12, xzr
	WORD $0x9b0921e8 // madd	x8, x15, x9, x8

BB0_18:
	WORD $0x3cc10730 // ldr	q16, [x25], #16
	WORD $0x9100118d // add	x13, x12, #4
	WORD $0x3cc10713 // ldr	q19, [x24], #16
	WORD $0x9100218c // add	x12, x12, #8
	WORD $0x6e20de11 // fmul	v17.4s, v16.4s, v0.4s
	WORD $0x6e23de12 // fmul	v18.4s, v16.4s, v3.4s
	WORD $0x6e26de10 // fmul	v16.4s, v16.4s, v6.4s
	WORD $0x3cc106f4 // ldr	q20, [x23], #16
	WORD $0xeb0a019f // cmp	x12, x10
	WORD $0xaa0d03ec // mov	x12, x13
	WORD $0x4e33cc31 // fmla	v17.4s, v1.4s, v19.4s
	WORD $0x4e33cc92 // fmla	v18.4s, v4.4s, v19.4s
	WORD $0x4e33ccf0 // fmla	v16.4s, v7.4s, v19.4s
	WORD $0x4e34cc51 // fmla	v17.4s, v2.4s, v20.4s
	WORD $0x4e34ccb2 // fmla	v18.4s, v5.4s, v20.4s
	WORD $0x4e34cc70 // fmla	v16.4s, v3.4s, v20.4s
	WORD $0x3c8107b1 // str	q17, [x29], #16
	WORD $0x3c8107d2 // str	q18, [x30], #16
	WORD $0x3c810510 // str	q16, [x8], #16
	BLE  BB0_18

BB0_19:
	WORD $0xeb0d015f // cmp	x10, x13
	BLE  BB0_14
	WORD $0x9b0b7ecc // mul	x12, x22, x11
	WORD $0xd37ef5a8 // lsl	x8, x13, #2
	WORD $0x9b0b7eb5 // mul	x21, x21, x11
	WORD $0x8b0c0a8c // add	x12, x20, x12, lsl #2
	WORD $0x3ce86990 // ldr	q16, [x12, x8]
	WORD $0x9b0b7cec // mul	x12, x7, x11
	WORD $0x8b150a6d // add	x13, x19, x21, lsl #2
	WORD $0x6e20de11 // fmul	v17.4s, v16.4s, v0.4s
	WORD $0x3ce869b2 // ldr	q18, [x13, x8]
	WORD $0x6e23de13 // fmul	v19.4s, v16.4s, v3.4s
	WORD $0x6e26de10 // fmul	v16.4s, v16.4s, v6.4s
	WORD $0x9b0b7ccd // mul	x13, x6, x11
	WORD $0x8b0c0a2c // add	x12, x17, x12, lsl #2
	WORD $0x4e32cc31 // fmla	v17.4s, v1.4s, v18.4s
	WORD $0x4e32cc93 // fmla	v19.4s, v4.4s, v18.4s
	WORD $0x3ce86994 // ldr	q20, [x12, x8]
	WORD $0x4e32ccf0 // fmla	v16.4s, v7.4s, v18.4s
	WORD $0x9b0b7e0c // mul	x12, x16, x11
	WORD $0x8b0d09cd // add	x13, x14, x13, lsl #2
	WORD $0x9b0b7dee // mul	x14, x15, x11
	WORD $0xf94007ef // ldr	x15, [sp, #8]
	WORD $0x4e34cc51 // fmla	v17.4s, v2.4s, v20.4s
	WORD $0x4e34ccb3 // fmla	v19.4s, v5.4s, v20.4s
	WORD $0x8b0801ad // add	x13, x13, x8
	WORD $0x4e34cc70 // fmla	v16.4s, v3.4s, v20.4s
	WORD $0x8b0c09ec // add	x12, x15, x12, lsl #2
	WORD $0x910031af // add	x15, x13, #12
	WORD $0x6e112232 // ext	v18.16b, v17.16b, v17.16b, #4
	WORD $0xbd0001b1 // str	s17, [x13]
	WORD $0x6e132274 // ext	v20.16b, v19.16b, v19.16b, #4
	WORD $0x4d0091f1 // st1	{ v17.s }[3], [x15]
	WORD $0x6e102211 // ext	v17.16b, v16.16b, v16.16b, #4
	WORD $0x8b08018c // add	x12, x12, x8
	WORD $0xfc0041b2 // stur	d18, [x13, #4]
	WORD $0xf9400fed // ldr	x13, [sp, #24]
	WORD $0xbd000193 // str	s19, [x12]
	WORD $0x8b0e09ad // add	x13, x13, x14, lsl #2
	WORD $0x9100318e // add	x14, x12, #12
	WORD $0xfc004194 // stur	d20, [x12, #4]
	WORD $0x4d0091d3 // st1	{ v19.s }[3], [x14]
	WORD $0x8b0801a8 // add	x8, x13, x8
	WORD $0x9100310c // add	x12, x8, #12
	WORD $0xbd000110 // str	s16, [x8]
	WORD $0xfc004111 // stur	d17, [x8, #4]
	WORD $0x4d009190 // st1	{ v16.s }[3], [x12]
	B    BB0_14

BB0_21:
	WORD $0xa9454ff4 // ldp	x20, x19, [sp, #80]
	WORD $0xf9400bfd // ldr	x29, [sp, #16]
	WORD $0xa94457f6 // ldp	x22, x21, [sp, #64]
	WORD $0xa9435ff8 // ldp	x24, x23, [sp, #48]
	WORD $0xa94267fe // ldp	x30, x25, [sp, #32]

BB0_22:
	RET
