//go:build !noasm && arm64
// Code generated by GoAT. DO NOT EDIT.
// versions:
// 	clang   21.1.8
// 	objdump 2.45.1
// flags: --target=arm64 -march=armv8-a+simd+fp -fno-builtin-memset -O3
// source: /Users/ajroetker/go/src/github.com/ajroetker/go-highway2/hwy/contrib/image/asm/baseforwardrct_c_s32_neon_arm64.c

package asm

import "unsafe"

//go:noescape
func forwardrct_c_s32_neon(r, gv, b, outY, outCb, outCr unsafe.Pointer)
