// Code generated by hwygen. DO NOT EDIT.
//go:build amd64 && goexperiment.simd

package dot

import (
	"os"

	"github.com/ajroetker/go-highway/hwy"
	"simd/archsimd"
)

var DotFloat32 func(a []float32, b []float32) float32
var DotFloat64 func(a []float64, b []float64) float64

// Dot is the generic API that dispatches to the appropriate SIMD implementation.
func Dot[T hwy.Floats](a []T, b []T) T {
	switch any(a).(type) {
	case []float32:
		return any(DotFloat32(any(a).([]float32), any(b).([]float32))).(T)
	case []float64:
		return any(DotFloat64(any(a).([]float64), any(b).([]float64))).(T)
	}
	panic("unreachable")
}

func init() {
	if os.Getenv("HWY_NO_SIMD") != "" {
		initDotFallback()
		return
	}
	if archsimd.X86.AVX2() {
		initDotAVX2()
		return
	}
	if archsimd.X86.AVX512() {
		initDotAVX512()
		return
	}
	initDotFallback()
}

func initDotAVX2() {
	DotFloat32 = BaseDot_avx2
	DotFloat64 = BaseDot_avx2_Float64
}

func initDotAVX512() {
	DotFloat32 = BaseDot_avx512
	DotFloat64 = BaseDot_avx512_Float64
}

func initDotFallback() {
	DotFloat32 = BaseDot_fallback
	DotFloat64 = BaseDot_fallback_Float64
}
