// Code generated by hwygen. DO NOT EDIT.

package dot

import (
	"github.com/ajroetker/go-highway/hwy"
)

func BaseDot_fallback(a []float32, b []float32) float32 {
	if len(a) == 0 || len(b) == 0 {
		return 0
	}
	n := min(len(a), len(b))
	sum := hwy.Zero[float32]()
	lanes := sum.NumLanes()
	var i int
	for i = 0; i+lanes <= n; i += lanes {
		va := hwy.Load(a[i:])
		vb := hwy.Load(b[i:])
		prod := hwy.Mul(va, vb)
		sum = hwy.Add(sum, prod)
	}
	result := hwy.ReduceSum(sum)
	for ; i < n; i++ {
		result += a[i] * b[i]
	}
	return result
}

func BaseDot_fallback_Float64(a []float64, b []float64) float64 {
	if len(a) == 0 || len(b) == 0 {
		return 0
	}
	n := min(len(a), len(b))
	sum := hwy.Zero[float64]()
	lanes := sum.NumLanes()
	var i int
	for i = 0; i+lanes <= n; i += lanes {
		va := hwy.Load(a[i:])
		vb := hwy.Load(b[i:])
		prod := hwy.Mul(va, vb)
		sum = hwy.Add(sum, prod)
	}
	result := hwy.ReduceSum(sum)
	for ; i < n; i++ {
		result += a[i] * b[i]
	}
	return result
}
