//go:build !noasm && arm64
// Code generated by GoAT. DO NOT EDIT.

TEXT ·geluapprox_bulk_f64_neon(SB), $0-24
	MOVD input+0(FP), R0
	MOVD output+8(FP), R1
	MOVD len+16(FP), R2
	WORD $0x6dbb3bef      // stp	d15, d14, [sp,
	WORD $0x6d0133ed      // stp	d13, d12, [sp,
	WORD $0x6d022beb      // stp	d11, d10, [sp,
	WORD $0x6d0323e9      // stp	d9, d8, [sp,
	WORD $0xa9047bfd      // stp	x29, x30, [sp,
	WORD $0x910103fd      // add	x29, sp,
	WORD $0xd108c3ff      // sub	sp, sp,
	WORD $0xd2873de9      // mov	x9,
	WORD $0xd2905fc8      // mov	x8,
	WORD $0x6f00e404      // movi	v4.2d,
	WORD $0xf2bfdf49      // movk	x9,
	WORD $0xf2aca568      // movk	x8,
	WORD $0xf2c5c849      // movk	x9,
	WORD $0xf2c2a8e8      // movk	x8,
	WORD $0xf2e7fcc9      // movk	x9,
	WORD $0xf2e7fee8      // movk	x8,
	WORD $0x4e080d21      // dup	v1.2d, x9
	WORD $0xd2873de9      // mov	x9,
	WORD $0x4e080d00      // dup	v0.2d, x8
	WORD $0xf2bfdf49      // movk	x9,
	WORD $0xd299abc8      // mov	x8,
	WORD $0xf2c5c849      // movk	x9,
	WORD $0xf2b1cf68      // movk	x8,
	WORD $0xf2e810c9      // movk	x9,
	WORD $0xf2d7f7c8      // movk	x8,
	WORD $0x4e080d23      // dup	v3.2d, x9
	WORD $0xd2873de9      // mov	x9,
	WORD $0xf2f7bd08      // movk	x8,
	WORD $0xf2bfdf49      // movk	x9,
	WORD $0x4e080d02      // dup	v2.2d, x8
	WORD $0xf9400048      // ldr	x8, [x2]
	WORD $0xf2c5c849      // movk	x9,
	WORD $0x3d808be0      // str	q0, [sp,
	WORD $0xf2f810c9      // movk	x9,
	WORD $0x3d8087e1      // str	q1, [sp,
	WORD $0x6f03f601      // fmov	v1.2d,
	WORD $0x4e080d20      // dup	v0.2d, x9
	WORD $0xb200f3e9      // mov	x9,
	WORD $0x3d8083e2      // str	q2, [sp,
	WORD $0xf2e7f8a9      // movk	x9,
	WORD $0x6f03f402      // fmov	v2.2d,
	WORD $0x3d807fe3      // str	q3, [sp,
	WORD $0xf100211f      // cmp	x8,
	WORD $0x3d807be0      // str	q0, [sp,
	WORD $0x4e080d20      // dup	v0.2d, x9
	WORD $0xb200f3e9      // mov	x9,
	WORD $0xf2e7f4a9      // movk	x9,
	WORD $0x3d8077e1      // str	q1, [sp,
	WORD $0x4e080d23      // dup	v3.2d, x9
	WORD $0xb200e3e9      // mov	x9,
	WORD $0x3d8073e2      // str	q2, [sp,
	WORD $0xf2e7f029      // movk	x9,
	WORD $0x3d806fe0      // str	q0, [sp,
	WORD $0x4e080d22      // dup	v2.2d, x9
	WORD $0xd28d82e9      // mov	x9,
	WORD $0xf2a2d829      // movk	x9,
	WORD $0x3d806be3      // str	q3, [sp,
	WORD $0x6f01f683      // fmov	v3.2d,
	WORD $0xf2d82d89      // movk	x9,
	WORD $0xf2e7eac9      // movk	x9,
	WORD $0x3d8067e2      // str	q2, [sp,
	WORD $0x4e080d20      // dup	v0.2d, x9
	WORD $0xd2effe09      // mov	x9,
	WORD $0x4e080d22      // dup	v2.2d, x9
	WORD $0x52807fe9      // mov	w9,
	WORD $0x3d8063e0      // str	q0, [sp,
	WORD $0x4e080d20      // dup	v0.2d, x9
	WORD $0xd28147a9      // mov	x9,
	WORD $0xf2b47ae9      // movk	x9,
	WORD $0x3d805fe4      // str	q4, [sp,
	WORD $0xf2c7ae09      // movk	x9,
	WORD $0x3d805be2      // str	q2, [sp,
	WORD $0x6f05f682      // fmov	v2.2d,
	WORD $0xf2e7ff69      // movk	x9,
	WORD $0x3d8057e0      // str	q0, [sp,
	WORD $0x4e080d20      // dup	v0.2d, x9
	WORD $0x3d8053e1      // str	q1, [sp,
	WORD $0x3d804fe3      // str	q3, [sp,
	WORD $0x3d804be2      // str	q2, [sp,
	WORD $0x3d8047e0      // str	q0, [sp,
	WORD $0x54001c2b      // b.lt	.LBB0_5
	WORD $0x91008029      // add	x9, x1,
	WORD $0x9100800b      // add	x11, x0,
	WORD $0x528000ea      // mov	w10,

LBB0_2:
	WORD $0xad7f0961 // ldp	q1, q2, [x11,
	WORD $0x9100214a // add	x10, x10,
	WORD $0xacc20178 // ldp	q24, q0, [x11],
	WORD $0xeb08015f // cmp	x10, x8
	WORD $0x3d8043e1 // str	q1, [sp,
	WORD $0x3d801ff8 // str	q24, [sp,
	WORD $0x3d8027e0 // str	q0, [sp,
	WORD $0x3dc047e0 // ldr	q0, [sp,
	WORD $0x6e60dc21 // fmul	v1.2d, v1.2d, v0.2d
	WORD $0xad0707e2 // stp	q2, q1, [sp,
	WORD $0x3dc04fe0 // ldr	q0, [sp,
	WORD $0x4ee0f420 // fmin	v0.2d, v1.2d, v0.2d
	WORD $0x3dc04be1 // ldr	q1, [sp,
	WORD $0x3dc08be3 // ldr	q3, [sp,
	WORD $0x3dc087e4 // ldr	q4, [sp,
	WORD $0x3dc083f2 // ldr	q18, [sp,
	WORD $0x3dc067f6 // ldr	q22, [sp,
	WORD $0x3dc063f5 // ldr	q21, [sp,
	WORD $0x3dc06bee // ldr	q14, [sp,
	WORD $0x3dc06fec // ldr	q12, [sp,
	WORD $0x3dc073eb // ldr	q11, [sp,
	WORD $0x3dc077ea // ldr	q10, [sp,
	WORD $0x3dc077f0 // ldr	q16, [sp,
	WORD $0x4e61f400 // fmax	v0.2d, v0.2d, v1.2d
	WORD $0x3dc057ef // ldr	q15, [sp,
	WORD $0x3dc053e5 // ldr	q5, [sp,
	WORD $0x3dc053e1 // ldr	q1, [sp,
	WORD $0xad0107e5 // stp	q5, q1, [sp,
	WORD $0x6ee0f800 // fneg	v0.2d, v0.2d
	WORD $0x3dc04fe5 // ldr	q5, [sp,
	WORD $0x3dc053e6 // ldr	q6, [sp,
	WORD $0x3dc04be1 // ldr	q1, [sp,
	WORD $0xad0507e5 // stp	q5, q1, [sp,
	WORD $0x3dc05fe1 // ldr	q1, [sp,
	WORD $0x6e60dc63 // fmul	v3.2d, v3.2d, v0.2d
	WORD $0xad0607e6 // stp	q6, q1, [sp,
	WORD $0x3dc047f1 // ldr	q17, [sp,
	WORD $0x3dc04ff3 // ldr	q19, [sp,
	WORD $0x3dc04bf4 // ldr	q20, [sp,
	WORD $0x4e618863 // frintn	v3.2d, v3.2d
	WORD $0x6e71dc48 // fmul	v8.2d, v2.2d, v17.2d
	WORD $0x4ee3cc80 // fmls	v0.2d, v4.2d, v3.2d
	WORD $0x3dc08be4 // ldr	q4, [sp,
	WORD $0x3dc087f7 // ldr	q23, [sp,
	WORD $0x4ef3f513 // fmin	v19.2d, v8.2d, v19.2d
	WORD $0x3dc083e5 // ldr	q5, [sp,
	WORD $0x3dc067e2 // ldr	q2, [sp,
	WORD $0x3dc063e7 // ldr	q7, [sp,
	WORD $0x3dc06be9 // ldr	q9, [sp,
	WORD $0x3dc06fff // ldr	q31, [sp,
	WORD $0x3dc073fd // ldr	q29, [sp,
	WORD $0x3dc077fb // ldr	q27, [sp,
	WORD $0x3dc077fc // ldr	q28, [sp,
	WORD $0x3dc057ed // ldr	q13, [sp,
	WORD $0x3dc053e6 // ldr	q6, [sp,
	WORD $0x3dc053e1 // ldr	q1, [sp,
	WORD $0x4e74f673 // fmax	v19.2d, v19.2d, v20.2d
	WORD $0x4ee3ce40 // fmls	v0.2d, v18.2d, v3.2d
	WORD $0x4ee1b863 // fcvtzs	v3.2d, v3.2d
	WORD $0xad0007e6 // stp	q6, q1, [sp]                    // 32-byte Folded Spill
	WORD $0x3dc04fe6 // ldr	q6, [sp,
	WORD $0x3dc053e1 // ldr	q1, [sp,
	WORD $0xad0207e6 // stp	q6, q1, [sp,
	WORD $0x6ee0fa7a // fneg	v26.2d, v19.2d
	WORD $0x4e75cc16 // fmla	v22.2d, v0.2d, v21.2d
	WORD $0x3dc04be1 // ldr	q1, [sp,
	WORD $0x3d801be1 // str	q1, [sp,
	WORD $0x3dc05fe1 // ldr	q1, [sp,
	WORD $0x6e7adc84 // fmul	v4.2d, v4.2d, v26.2d
	WORD $0x4e76cc0e // fmla	v14.2d, v0.2d, v22.2d
	WORD $0x3d8023e1 // str	q1, [sp,
	WORD $0x3dc047e1 // ldr	q1, [sp,
	WORD $0x4e618886 // frintn	v6.2d, v4.2d
	WORD $0x4e6ecc0c // fmla	v12.2d, v0.2d, v14.2d
	WORD $0x6e61df18 // fmul	v24.2d, v24.2d, v1.2d
	WORD $0x3dc04fe1 // ldr	q1, [sp,
	WORD $0x4ee6cefa // fmls	v26.2d, v23.2d, v6.2d
	WORD $0x3dc04bf7 // ldr	q23, [sp,
	WORD $0x4e6ccc0b // fmla	v11.2d, v0.2d, v12.2d
	WORD $0x4ee1f701 // fmin	v1.2d, v24.2d, v1.2d
	WORD $0x4ee6ccba // fmls	v26.2d, v5.2d, v6.2d
	WORD $0x4e6bcc0a // fmla	v10.2d, v0.2d, v11.2d
	WORD $0x4ee1b8c6 // fcvtzs	v6.2d, v6.2d
	WORD $0x4e77f421 // fmax	v1.2d, v1.2d, v23.2d
	WORD $0x4e67cf42 // fmla	v2.2d, v26.2d, v7.2d
	WORD $0x4e6acc10 // fmla	v16.2d, v0.2d, v10.2d
	WORD $0x4ee685a6 // add	v6.2d, v13.2d, v6.2d
	WORD $0x6ee0f82b // fneg	v11.2d, v1.2d
	WORD $0x4ee385e1 // add	v1.2d, v15.2d, v3.2d
	WORD $0x3dc08be3 // ldr	q3, [sp,
	WORD $0x3dc087f2 // ldr	q18, [sp,
	WORD $0x3dc083f3 // ldr	q19, [sp,
	WORD $0x4f7454c6 // shl	v6.2d, v6.2d,
	WORD $0x4f745427 // shl	v7.2d, v1.2d,
	WORD $0x4e62cf49 // fmla	v9.2d, v26.2d, v2.2d
	WORD $0x3dc067e2 // ldr	q2, [sp,
	WORD $0x6e6bdc71 // fmul	v17.2d, v3.2d, v11.2d
	WORD $0x3dc063f4 // ldr	q20, [sp,
	WORD $0x3dc06be1 // ldr	q1, [sp,
	WORD $0x3dc06fe3 // ldr	q3, [sp,
	WORD $0x3dc073e4 // ldr	q4, [sp,
	WORD $0x3dc077f7 // ldr	q23, [sp,
	WORD $0x3dc077e5 // ldr	q5, [sp,
	WORD $0x3dc057f6 // ldr	q22, [sp,
	WORD $0x3dc053f9 // ldr	q25, [sp,
	WORD $0x3dc053fe // ldr	q30, [sp,
	WORD $0x3dc04fef // ldr	q15, [sp,
	WORD $0x3dc053ec // ldr	q12, [sp,
	WORD $0x3dc04bee // ldr	q14, [sp,
	WORD $0x3dc05fea // ldr	q10, [sp,
	WORD $0x3dc047e0 // ldr	q0, [sp,
	WORD $0x3dc027f5 // ldr	q21, [sp,
	WORD $0x6e67de07 // fmul	v7.2d, v16.2d, v7.2d
	WORD $0x4e618a31 // frintn	v17.2d, v17.2d
	WORD $0x4e69cf5f // fmla	v31.2d, v26.2d, v9.2d
	WORD $0x6e60deb0 // fmul	v16.2d, v21.2d, v0.2d
	WORD $0x3dc04fe0 // ldr	q0, [sp,
	WORD $0x3dc00be9 // ldr	q9, [sp,
	WORD $0x4e67d527 // fadd	v7.2d, v9.2d, v7.2d
	WORD $0x4ef1ce4b // fmls	v11.2d, v18.2d, v17.2d
	WORD $0x3dc04bf2 // ldr	q18, [sp,
	WORD $0x4e7fcf5d // fmla	v29.2d, v26.2d, v31.2d
	WORD $0x4ee0f609 // fmin	v9.2d, v16.2d, v0.2d
	WORD $0x3dc00fe0 // ldr	q0, [sp,
	WORD $0x6e67fc00 // fdiv	v0.2d, v0.2d, v7.2d
	WORD $0x4ef1ce6b // fmls	v11.2d, v19.2d, v17.2d
	WORD $0x4e7dcf5b // fmla	v27.2d, v26.2d, v29.2d
	WORD $0x4e72f527 // fmax	v7.2d, v9.2d, v18.2d
	WORD $0x3dc08bf2 // ldr	q18, [sp,
	WORD $0x4e74cd62 // fmla	v2.2d, v11.2d, v20.2d
	WORD $0x4e7bcf5c // fmla	v28.2d, v26.2d, v27.2d
	WORD $0x6ee0f8e7 // fneg	v7.2d, v7.2d
	WORD $0x4e62cd61 // fmla	v1.2d, v11.2d, v2.2d
	WORD $0x6e66df82 // fmul	v2.2d, v28.2d, v6.2d
	WORD $0x6e67de52 // fmul	v18.2d, v18.2d, v7.2d
	WORD $0x4e61cd63 // fmla	v3.2d, v11.2d, v1.2d
	WORD $0x3dc003e1 // ldr	q1, [sp]                        // 16-byte Folded Reload
	WORD $0x4e618a46 // frintn	v6.2d, v18.2d
	WORD $0x4e62d421 // fadd	v1.2d, v1.2d, v2.2d
	WORD $0x3dc087e2 // ldr	q2, [sp,
	WORD $0x4e63cd64 // fmla	v4.2d, v11.2d, v3.2d
	WORD $0x4ee1ba23 // fcvtzs	v3.2d, v17.2d
	WORD $0x4ee6cc47 // fmls	v7.2d, v2.2d, v6.2d
	WORD $0x3dc007e2 // ldr	q2, [sp,
	WORD $0x6e61fc41 // fdiv	v1.2d, v2.2d, v1.2d
	WORD $0x3dc083e2 // ldr	q2, [sp,
	WORD $0x4e64cd77 // fmla	v23.2d, v11.2d, v4.2d
	WORD $0x4ee386c3 // add	v3.2d, v22.2d, v3.2d
	WORD $0x4ee6cc47 // fmls	v7.2d, v2.2d, v6.2d
	WORD $0x3dc067e2 // ldr	q2, [sp,
	WORD $0x3dc063e4 // ldr	q4, [sp,
	WORD $0x4e77cd65 // fmla	v5.2d, v11.2d, v23.2d
	WORD $0x4f745463 // shl	v3.2d, v3.2d,
	WORD $0x4e64cce2 // fmla	v2.2d, v7.2d, v4.2d
	WORD $0x3dc06be4 // ldr	q4, [sp,
	WORD $0x4e62cce4 // fmla	v4.2d, v7.2d, v2.2d
	WORD $0x6e63dca2 // fmul	v2.2d, v5.2d, v3.2d
	WORD $0x3dc06fe3 // ldr	q3, [sp,
	WORD $0x4ee1b8c5 // fcvtzs	v5.2d, v6.2d
	WORD $0x4e64cce3 // fmla	v3.2d, v7.2d, v4.2d
	WORD $0x3dc073e4 // ldr	q4, [sp,
	WORD $0x4e62d722 // fadd	v2.2d, v25.2d, v2.2d
	WORD $0x4e63cce4 // fmla	v4.2d, v7.2d, v3.2d
	WORD $0x3dc077e3 // ldr	q3, [sp,
	WORD $0x3dc077e6 // ldr	q6, [sp,
	WORD $0x6e62ffc2 // fdiv	v2.2d, v30.2d, v2.2d
	WORD $0x4e64cce3 // fmla	v3.2d, v7.2d, v4.2d
	WORD $0x3dc057e4 // ldr	q4, [sp,
	WORD $0x4ee58484 // add	v4.2d, v4.2d, v5.2d
	WORD $0x4e63cce6 // fmla	v6.2d, v7.2d, v3.2d
	WORD $0x6eefe707 // fcmgt	v7.2d, v24.2d, v15.2d
	WORD $0x4f745483 // shl	v3.2d, v4.2d,
	WORD $0x3dc053e4 // ldr	q4, [sp,
	WORD $0x6e63dcc3 // fmul	v3.2d, v6.2d, v3.2d
	WORD $0x4e63d483 // fadd	v3.2d, v4.2d, v3.2d
	WORD $0x3dc053e4 // ldr	q4, [sp,
	WORD $0x3dc03ff1 // ldr	q17, [sp,
	WORD $0x3dc013e5 // ldr	q5, [sp,
	WORD $0x6ee5e505 // fcmgt	v5.2d, v8.2d, v5.2d
	WORD $0x6e63fc83 // fdiv	v3.2d, v4.2d, v3.2d
	WORD $0x3dc02be4 // ldr	q4, [sp,
	WORD $0x3dc04fe6 // ldr	q6, [sp,
	WORD $0x3dc033f2 // ldr	q18, [sp,
	WORD $0x6ee4e624 // fcmgt	v4.2d, v17.2d, v4.2d
	WORD $0x6ee6e606 // fcmgt	v6.2d, v16.2d, v6.2d
	WORD $0x6ea71d82 // bit	v2.16b, v12.16b, v7.16b
	WORD $0x6ef8e5c7 // fcmgt	v7.2d, v14.2d, v24.2d
	WORD $0x6ea41e40 // bit	v0.16b, v18.16b, v4.16b
	WORD $0x3dc017e4 // ldr	q4, [sp,
	WORD $0x6ea71d42 // bit	v2.16b, v10.16b, v7.16b
	WORD $0x6ea51c81 // bit	v1.16b, v4.16b, v5.16b
	WORD $0x3dc02fe4 // ldr	q4, [sp,
	WORD $0x3dc053e5 // ldr	q5, [sp,
	WORD $0x6ef1e484 // fcmgt	v4.2d, v4.2d, v17.2d
	WORD $0x3dc01bf1 // ldr	q17, [sp,
	WORD $0x3dc04bf2 // ldr	q18, [sp,
	WORD $0x6ee8e631 // fcmgt	v17.2d, v17.2d, v8.2d
	WORD $0x6ea61ca3 // bit	v3.16b, v5.16b, v6.16b
	WORD $0x3dc037e6 // ldr	q6, [sp,
	WORD $0x6ef0e645 // fcmgt	v5.2d, v18.2d, v16.2d
	WORD $0x6ea41cc0 // bit	v0.16b, v6.16b, v4.16b
	WORD $0x3dc023e4 // ldr	q4, [sp,
	WORD $0x6eb11c81 // bit	v1.16b, v4.16b, v17.16b
	WORD $0x3dc05fe4 // ldr	q4, [sp,
	WORD $0x6ea51c83 // bit	v3.16b, v4.16b, v5.16b
	WORD $0x3dc043e4 // ldr	q4, [sp,
	WORD $0x6e60dc80 // fmul	v0.2d, v4.2d, v0.2d
	WORD $0x3dc03be4 // ldr	q4, [sp,
	WORD $0x6e61dc81 // fmul	v1.2d, v4.2d, v1.2d
	WORD $0x3dc01fe4 // ldr	q4, [sp,
	WORD $0x6e63dea3 // fmul	v3.2d, v21.2d, v3.2d
	WORD $0x6e62dc82 // fmul	v2.2d, v4.2d, v2.2d
	WORD $0xad3f0520 // stp	q0, q1, [x9,
	WORD $0xac820d22 // stp	q2, q3, [x9],
	WORD $0x54ffe54b // b.lt	.LBB0_2
	WORD $0xd1001d49 // sub	x9, x10,
	WORD $0xb240012a // orr	x10, x9,
	WORD $0xeb08015f // cmp	x10, x8
	WORD $0x540000eb // b.lt	.LBB0_6

LBB0_4:
	WORD $0xaa0903ec // mov	x12, x9
	WORD $0x1400003c // b	.LBB0_8

LBB0_5:
	WORD $0xaa1f03e9 // mov	x9, xzr
	WORD $0xb24003ea // orr	x10, xzr,
	WORD $0xeb08015f // cmp	x10, x8
	WORD $0x54ffff6a // b.ge	.LBB0_4

LBB0_6:
	WORD $0xd37df12b // lsl	x11, x9,
	WORD $0x8b0b000a // add	x10, x0, x11
	WORD $0x8b0b002b // add	x11, x1, x11

LBB0_7:
	WORD $0x3cc10540 // ldr	q0, [x10],
	WORD $0x3dc047e1 // ldr	q1, [sp,
	WORD $0x3dc04fe2 // ldr	q2, [sp,
	WORD $0x3dc04be3 // ldr	q3, [sp,
	WORD $0x91000d2d // add	x13, x9,
	WORD $0x6e61dc01 // fmul	v1.2d, v0.2d, v1.2d
	WORD $0x3dc08be4 // ldr	q4, [sp,
	WORD $0x9100092c // add	x12, x9,
	WORD $0xeb0801bf // cmp	x13, x8
	WORD $0xaa0c03e9 // mov	x9, x12
	WORD $0x4ee2f422 // fmin	v2.2d, v1.2d, v2.2d
	WORD $0x4e63f442 // fmax	v2.2d, v2.2d, v3.2d
	WORD $0x6ee0f842 // fneg	v2.2d, v2.2d
	WORD $0x6e62dc83 // fmul	v3.2d, v4.2d, v2.2d
	WORD $0x3dc087e4 // ldr	q4, [sp,
	WORD $0x4e618863 // frintn	v3.2d, v3.2d
	WORD $0x4ee3cc82 // fmls	v2.2d, v4.2d, v3.2d
	WORD $0x3dc083e4 // ldr	q4, [sp,
	WORD $0x4ee3cc82 // fmls	v2.2d, v4.2d, v3.2d
	WORD $0x3dc067e4 // ldr	q4, [sp,
	WORD $0x3dc063e5 // ldr	q5, [sp,
	WORD $0x4ee1b863 // fcvtzs	v3.2d, v3.2d
	WORD $0x4e65cc44 // fmla	v4.2d, v2.2d, v5.2d
	WORD $0x3dc06be5 // ldr	q5, [sp,
	WORD $0x4e64cc45 // fmla	v5.2d, v2.2d, v4.2d
	WORD $0x3dc06fe4 // ldr	q4, [sp,
	WORD $0x4e65cc44 // fmla	v4.2d, v2.2d, v5.2d
	WORD $0x3dc073e5 // ldr	q5, [sp,
	WORD $0x4e64cc45 // fmla	v5.2d, v2.2d, v4.2d
	WORD $0x3dc077e4 // ldr	q4, [sp,
	WORD $0x4e65cc44 // fmla	v4.2d, v2.2d, v5.2d
	WORD $0x3dc077e5 // ldr	q5, [sp,
	WORD $0x3dc057e6 // ldr	q6, [sp,
	WORD $0x4ee384c3 // add	v3.2d, v6.2d, v3.2d
	WORD $0x4e64cc45 // fmla	v5.2d, v2.2d, v4.2d
	WORD $0x4f745462 // shl	v2.2d, v3.2d,
	WORD $0x3dc053e3 // ldr	q3, [sp,
	WORD $0x6e62dca2 // fmul	v2.2d, v5.2d, v2.2d
	WORD $0x4e62d462 // fadd	v2.2d, v3.2d, v2.2d
	WORD $0x3dc053e3 // ldr	q3, [sp,
	WORD $0x6e62fc62 // fdiv	v2.2d, v3.2d, v2.2d
	WORD $0x3dc04fe3 // ldr	q3, [sp,
	WORD $0x3dc053e4 // ldr	q4, [sp,
	WORD $0x3dc04be5 // ldr	q5, [sp,
	WORD $0x6ee3e423 // fcmgt	v3.2d, v1.2d, v3.2d
	WORD $0x6ee1e4a1 // fcmgt	v1.2d, v5.2d, v1.2d
	WORD $0x6ea31c82 // bit	v2.16b, v4.16b, v3.16b
	WORD $0x3dc05fe3 // ldr	q3, [sp,
	WORD $0x6e621c61 // bsl	v1.16b, v3.16b, v2.16b
	WORD $0x6e61dc00 // fmul	v0.2d, v0.2d, v1.2d
	WORD $0x3c810560 // str	q0, [x11],
	WORD $0x54fff9ab // b.lt	.LBB0_7

LBB0_8:
	WORD $0xeb0c0108 // subs	x8, x8, x12
	WORD $0x540006ad // b.le	.LBB0_11
	WORD $0xd37df18a // lsl	x10, x12,
	WORD $0x8b0a0029 // add	x9, x1, x10
	WORD $0x8b0a000a // add	x10, x0, x10

LBB0_10:
	WORD $0xfc408540 // ldr	d0, [x10],
	WORD $0x3dc047e1 // ldr	q1, [sp,
	WORD $0x3dc04fe2 // ldr	q2, [sp,
	WORD $0x3dc04be3 // ldr	q3, [sp,
	WORD $0xf1000508 // subs	x8, x8,
	WORD $0x4fc09021 // fmul	v1.2d, v1.2d, v0.d[0]
	WORD $0x3dc08be4 // ldr	q4, [sp,
	WORD $0x4ee2f422 // fmin	v2.2d, v1.2d, v2.2d
	WORD $0x4e63f442 // fmax	v2.2d, v2.2d, v3.2d
	WORD $0x6ee0f842 // fneg	v2.2d, v2.2d
	WORD $0x6e62dc83 // fmul	v3.2d, v4.2d, v2.2d
	WORD $0x3dc087e4 // ldr	q4, [sp,
	WORD $0x4e618863 // frintn	v3.2d, v3.2d
	WORD $0x4ee3cc82 // fmls	v2.2d, v4.2d, v3.2d
	WORD $0x3dc083e4 // ldr	q4, [sp,
	WORD $0x4ee3cc82 // fmls	v2.2d, v4.2d, v3.2d
	WORD $0x3dc067e4 // ldr	q4, [sp,
	WORD $0x3dc063e5 // ldr	q5, [sp,
	WORD $0x4ee1b863 // fcvtzs	v3.2d, v3.2d
	WORD $0x4e65cc44 // fmla	v4.2d, v2.2d, v5.2d
	WORD $0x3dc06be5 // ldr	q5, [sp,
	WORD $0x4e64cc45 // fmla	v5.2d, v2.2d, v4.2d
	WORD $0x3dc06fe4 // ldr	q4, [sp,
	WORD $0x4e65cc44 // fmla	v4.2d, v2.2d, v5.2d
	WORD $0x3dc073e5 // ldr	q5, [sp,
	WORD $0x4e64cc45 // fmla	v5.2d, v2.2d, v4.2d
	WORD $0x3dc077e4 // ldr	q4, [sp,
	WORD $0x4e65cc44 // fmla	v4.2d, v2.2d, v5.2d
	WORD $0x3dc077e5 // ldr	q5, [sp,
	WORD $0x3dc057e6 // ldr	q6, [sp,
	WORD $0x4ee384c3 // add	v3.2d, v6.2d, v3.2d
	WORD $0x4e64cc45 // fmla	v5.2d, v2.2d, v4.2d
	WORD $0x4f745462 // shl	v2.2d, v3.2d,
	WORD $0x3dc053e3 // ldr	q3, [sp,
	WORD $0x6e62dca2 // fmul	v2.2d, v5.2d, v2.2d
	WORD $0x4e62d462 // fadd	v2.2d, v3.2d, v2.2d
	WORD $0x3dc053e3 // ldr	q3, [sp,
	WORD $0x6e62fc62 // fdiv	v2.2d, v3.2d, v2.2d
	WORD $0x3dc04fe3 // ldr	q3, [sp,
	WORD $0x3dc053e4 // ldr	q4, [sp,
	WORD $0x3dc04be5 // ldr	q5, [sp,
	WORD $0x6ee3e423 // fcmgt	v3.2d, v1.2d, v3.2d
	WORD $0x6ee1e4a1 // fcmgt	v1.2d, v5.2d, v1.2d
	WORD $0x6ea31c82 // bit	v2.16b, v4.16b, v3.16b
	WORD $0x3dc05fe3 // ldr	q3, [sp,
	WORD $0x6e621c61 // bsl	v1.16b, v3.16b, v2.16b
	WORD $0x6e61dc00 // fmul	v0.2d, v0.2d, v1.2d
	WORD $0x0d9f8520 // st1	{ v0.d }[0], [x9],
	WORD $0x54fffa01 // b.ne	.LBB0_10

LBB0_11:
	WORD $0x9108c3ff // add	sp, sp,
	WORD $0xa9447bfd // ldp	x29, x30, [sp,
	WORD $0x6d4323e9 // ldp	d9, d8, [sp,
	WORD $0x6d422beb // ldp	d11, d10, [sp,
	WORD $0x6d4133ed // ldp	d13, d12, [sp,
	WORD $0x6cc53bef // ldp	d15, d14, [sp],
	RET
