// Copyright 2025 go-highway Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//go:build amd64 && goexperiment.simd

package asm

// Float16 conversion operations for x86-64 with F16C extension.
// Uses VCVTPH2PS and VCVTPS2PH instructions for efficient float16 <-> float32 conversion.
//
// NOTE: x86 F16C provides conversion-only instructions. There is NO native float16
// arithmetic on F16C - arithmetic must use the promote -> compute (float32) -> demote pattern.
// This is different from ARM NEON FP16 (ARMv8.2-A+) which has native FP16 arithmetic.

//go:generate go tool goat ../c/ops_f16_avx2_amd64.c -O3 --target amd64 -e="-mf16c" -e="-mavx2"

import "unsafe"

// PromoteF16ToF32F16C converts float16 values to float32 using F16C instructions.
// Input: a - slice of uint16 (float16 bit patterns)
// Output: result - slice of float32
// Processes up to min(len(a), len(result)) elements.
// Uses VCVTPH2PS instruction which converts 4 or 8 float16 to float32 in parallel.
func PromoteF16ToF32F16C(a []uint16, result []float32) {
	if len(a) == 0 || len(result) == 0 {
		return
	}
	n := int64(len(a))
	if int64(len(result)) < n {
		n = int64(len(result))
	}
	promote_f16_to_f32_f16c(
		unsafe.Pointer(&a[0]),
		unsafe.Pointer(&result[0]),
		unsafe.Pointer(&n),
	)
}

// DemoteF32ToF16F16C converts float32 values to float16 using F16C instructions.
// Input: a - slice of float32
// Output: result - slice of uint16 (float16 bit patterns)
// Processes up to min(len(a), len(result)) elements.
// Uses VCVTPS2PH instruction with round-to-nearest-even mode.
func DemoteF32ToF16F16C(a []float32, result []uint16) {
	if len(a) == 0 || len(result) == 0 {
		return
	}
	n := int64(len(a))
	if int64(len(result)) < n {
		n = int64(len(result))
	}
	demote_f32_to_f16_f16c(
		unsafe.Pointer(&a[0]),
		unsafe.Pointer(&result[0]),
		unsafe.Pointer(&n),
	)
}

// Assembly function declarations are in ops_f16_avx2_amd64.go (generated by GoAT)
