//go:build !noasm && arm64
// Code generated by GoAT. DO NOT EDIT.
// versions:
// 	clang   21.1.8
// 	objdump 2.45.1
// flags: -march=armv8-a+simd+fp -fno-builtin-memset -O3
// source: ../c/math_f64_neon_arm64.c

TEXT ·exp2_f64_neon(SB), $0-24
	MOVD input+0(FP), R0
	MOVD result+8(FP), R1
	MOVD len+16(FP), R2
	WORD $0xf9400048      // ldr	x8, [x2]
	WORD $0xf100091f      // cmp	x8, #2
	BLT  BB0_3
	WORD $0xd2de0009      // mov	x9, #263882790666240            ; =0xf00000000000
	WORD $0xf2f811e9      // movk	x9, #49295, lsl #48
	WORD $0x4e080d20      // dup.2d	v0, x9
	WORD $0xd2df0009      // mov	x9, #272678883688448            ; =0xf80000000000
	WORD $0xf2e811e9      // movk	x9, #16527, lsl #48
	WORD $0x4e080d21      // dup.2d	v1, x9
	WORD $0xd2873de9      // mov	x9, #14831                      ; =0x39ef
	WORD $0xf2bfdf49      // movk	x9, #65274, lsl #16
	WORD $0xf2c5c849      // movk	x9, #11842, lsl #32
	WORD $0xf2e7fcc9      // movk	x9, #16358, lsl #48
	WORD $0x4e080d22      // dup.2d	v2, x9
	WORD $0xd298e689      // mov	x9, #50996                      ; =0xc734
	WORD $0xf2b4aac9      // movk	x9, #42326, lsl #16
	WORD $0xf2c3bc69      // movk	x9, #7651, lsl #32
	WORD $0xf2e7d8e9      // movk	x9, #16071, lsl #48
	WORD $0x4e080d23      // dup.2d	v3, x9
	WORD $0xd2940349      // mov	x9, #40986                      ; =0xa01a
	WORD $0xf2a34029      // movk	x9, #6657, lsl #16
	WORD $0xf2c03409      // movk	x9, #416, lsl #32
	WORD $0xf2e7df49      // movk	x9, #16122, lsl #48
	WORD $0x4e080d24      // dup.2d	v4, x9
	WORD $0xd2940349      // mov	x9, #40986                      ; =0xa01a
	WORD $0xf2a34029      // movk	x9, #6657, lsl #16
	WORD $0xf2c03409      // movk	x9, #416, lsl #32
	WORD $0xf2e7e549      // movk	x9, #16170, lsl #48
	WORD $0x4e080d25      // dup.2d	v5, x9
	WORD $0xd28d82e9      // mov	x9, #27671                      ; =0x6c17
	WORD $0xf2a2d829      // movk	x9, #5825, lsl #16
	WORD $0xf2d82d89      // movk	x9, #49516, lsl #32
	WORD $0xf2e7eac9      // movk	x9, #16214, lsl #48
	WORD $0x4e080d26      // dup.2d	v6, x9
	WORD $0xb200e3e9      // mov	x9, #1229782938247303441        ; =0x1111111111111111
	WORD $0xf2e7f029      // movk	x9, #16257, lsl #48
	WORD $0x4e080d27      // dup.2d	v7, x9
	WORD $0xb200f3e9      // mov	x9, #6148914691236517205        ; =0x5555555555555555
	WORD $0xf28aaac9      // movk	x9, #21846
	WORD $0xf2e7f4a9      // movk	x9, #16293, lsl #48
	WORD $0x4e080d30      // dup.2d	v16, x9
	WORD $0x52800029      // mov	w9, #1                          ; =0x1
	WORD $0xb200f3ea      // mov	x10, #6148914691236517205       ; =0x5555555555555555
	WORD $0xf2e7f8aa      // movk	x10, #16325, lsl #48
	WORD $0x4e080d51      // dup.2d	v17, x10
	WORD $0x6f03f412      // fmov.2d	v18, #0.50000000
	WORD $0x6f03f613      // fmov.2d	v19, #1.00000000

BB0_2:
	WORD $0x3cc10414 // ldr	q20, [x0], #16
	WORD $0x4e60f694 // fmax.2d	v20, v20, v0
	WORD $0x4ee1f694 // fmin.2d	v20, v20, v1
	WORD $0x4e618a95 // frintn.2d	v21, v20
	WORD $0x4ef5d694 // fsub.2d	v20, v20, v21
	WORD $0x6e62de94 // fmul.2d	v20, v20, v2
	WORD $0x4ea41c96 // mov.16b	v22, v4
	WORD $0x4e74cc76 // fmla.2d	v22, v3, v20
	WORD $0x4ea51cb7 // mov.16b	v23, v5
	WORD $0x4e76ce97 // fmla.2d	v23, v20, v22
	WORD $0x4ea61cd6 // mov.16b	v22, v6
	WORD $0x4e77ce96 // fmla.2d	v22, v20, v23
	WORD $0x4ea71cf7 // mov.16b	v23, v7
	WORD $0x4e76ce97 // fmla.2d	v23, v20, v22
	WORD $0x4eb01e16 // mov.16b	v22, v16
	WORD $0x4e77ce96 // fmla.2d	v22, v20, v23
	WORD $0x4eb11e37 // mov.16b	v23, v17
	WORD $0x4e76ce97 // fmla.2d	v23, v20, v22
	WORD $0x4eb21e56 // mov.16b	v22, v18
	WORD $0x4e77ce96 // fmla.2d	v22, v20, v23
	WORD $0x4eb31e77 // mov.16b	v23, v19
	WORD $0x4e76ce97 // fmla.2d	v23, v20, v22
	WORD $0x4eb31e76 // mov.16b	v22, v19
	WORD $0x4e77ce96 // fmla.2d	v22, v20, v23
	WORD $0x4ee1bab4 // fcvtzs.2d	v20, v21
	WORD $0x4f745694 // shl.2d	v20, v20, #52
	WORD $0x4ef38694 // add.2d	v20, v20, v19
	WORD $0x6e74ded4 // fmul.2d	v20, v22, v20
	WORD $0x3c810434 // str	q20, [x1], #16
	WORD $0x91000929 // add	x9, x9, #2
	WORD $0xeb08013f // cmp	x9, x8
	BLT  BB0_2

BB0_3:
	RET

TEXT ·log2_f64_neon(SB), $0-24
	MOVD input+0(FP), R0
	MOVD result+8(FP), R1
	MOVD len+16(FP), R2
	WORD $0xf9400048      // ldr	x8, [x2]
	WORD $0xf100091f      // cmp	x8, #2
	BLT  BB1_3
	WORD $0x5280ffe9      // mov	w9, #2047                       ; =0x7ff
	WORD $0x4e080d20      // dup.2d	v0, x9
	WORD $0x92807fc9      // mov	x9, #-1023                      ; =0xfffffffffffffc01
	WORD $0x4e080d21      // dup.2d	v1, x9
	WORD $0x52800029      // mov	w9, #1                          ; =0x1
	WORD $0x92fffe0a      // mov	x10, #4503599627370495          ; =0xfffffffffffff
	WORD $0x4e080d42      // dup.2d	v2, x10
	WORD $0x6f03f603      // fmov.2d	v3, #1.00000000
	WORD $0x6f07f604      // fmov.2d	v4, #-1.00000000
	WORD $0x6f07f405      // fmov.2d	v5, #-0.50000000
	WORD $0xb200f3ea      // mov	x10, #6148914691236517205       ; =0x5555555555555555
	WORD $0xf2e7faaa      // movk	x10, #16341, lsl #48
	WORD $0x4e080d46      // dup.2d	v6, x10
	WORD $0x6f06f607      // fmov.2d	v7, #-0.25000000
	WORD $0xb201e7ea      // mov	x10, #-7378697629483820647      ; =0x9999999999999999
	WORD $0xf293334a      // movk	x10, #39322
	WORD $0xf2e7f92a      // movk	x10, #16329, lsl #48
	WORD $0x4e080d50      // dup.2d	v16, x10
	WORD $0xb200f3ea      // mov	x10, #6148914691236517205       ; =0x5555555555555555
	WORD $0xf2f7f8aa      // movk	x10, #49093, lsl #48
	WORD $0x4e080d51      // dup.2d	v17, x10
	WORD $0xd284924a      // mov	x10, #9362                      ; =0x2492
	WORD $0xf2b2492a      // movk	x10, #37449, lsl #16
	WORD $0xf2c9248a      // movk	x10, #18724, lsl #32
	WORD $0xf2e7f84a      // movk	x10, #16322, lsl #48
	WORD $0x4e080d52      // dup.2d	v18, x10
	WORD $0x6f06f413      // fmov.2d	v19, #-0.12500000
	WORD $0xd2905fca      // mov	x10, #33534                     ; =0x82fe
	WORD $0xf2aca56a      // movk	x10, #25899, lsl #16
	WORD $0xf2c2a8ea      // movk	x10, #5447, lsl #32
	WORD $0xf2e7feea      // movk	x10, #16375, lsl #48
	WORD $0x4e080d54      // dup.2d	v20, x10

BB1_2:
	WORD $0x3cc10415 // ldr	q21, [x0], #16
	WORD $0x6f4c06b6 // ushr.2d	v22, v21, #52
	WORD $0x4e201ed6 // and.16b	v22, v22, v0
	WORD $0x4e221eb5 // and.16b	v21, v21, v2
	WORD $0x4ea31eb5 // orr.16b	v21, v21, v3
	WORD $0x4e64d6b5 // fadd.2d	v21, v21, v4
	WORD $0x6e75deb7 // fmul.2d	v23, v21, v21
	WORD $0x6e77deb8 // fmul.2d	v24, v21, v23
	WORD $0x6e77def9 // fmul.2d	v25, v23, v23
	WORD $0x6e79deba // fmul.2d	v26, v21, v25
	WORD $0x6e78df1b // fmul.2d	v27, v24, v24
	WORD $0x6e7bdebc // fmul.2d	v28, v21, v27
	WORD $0x4e77ccb5 // fmla.2d	v21, v5, v23
	WORD $0x4e78ccd5 // fmla.2d	v21, v6, v24
	WORD $0x6e79df37 // fmul.2d	v23, v25, v25
	WORD $0x4e79ccf5 // fmla.2d	v21, v7, v25
	WORD $0x4e7ace15 // fmla.2d	v21, v16, v26
	WORD $0x4e7bce35 // fmla.2d	v21, v17, v27
	WORD $0x4e7cce55 // fmla.2d	v21, v18, v28
	WORD $0x4e77ce75 // fmla.2d	v21, v19, v23
	WORD $0x4ee186d6 // add.2d	v22, v22, v1
	WORD $0x4e61dad6 // scvtf.2d	v22, v22
	WORD $0x4e75ce96 // fmla.2d	v22, v20, v21
	WORD $0x3c810436 // str	q22, [x1], #16
	WORD $0x91000929 // add	x9, x9, #2
	WORD $0xeb08013f // cmp	x9, x8
	BLT  BB1_2

BB1_3:
	RET

TEXT ·exp_f64_neon(SB), $0-24
	MOVD input+0(FP), R0
	MOVD result+8(FP), R1
	MOVD len+16(FP), R2
	WORD $0xf9400048      // ldr	x8, [x2]
	WORD $0xf100091f      // cmp	x8, #2
	BLT  BB2_3
	WORD $0xd2c50009      // mov	x9, #43980465111040             ; =0x280000000000
	WORD $0xf2f810c9      // movk	x9, #49286, lsl #48
	WORD $0x4e080d20      // dup.2d	v0, x9
	WORD $0xd2c50009      // mov	x9, #43980465111040             ; =0x280000000000
	WORD $0xf2e810c9      // movk	x9, #16518, lsl #48
	WORD $0x4e080d21      // dup.2d	v1, x9
	WORD $0xd2905fc9      // mov	x9, #33534                      ; =0x82fe
	WORD $0xf2aca569      // movk	x9, #25899, lsl #16
	WORD $0xf2c2a8e9      // movk	x9, #5447, lsl #32
	WORD $0xf2e7fee9      // movk	x9, #16375, lsl #48
	WORD $0x4e080d22      // dup.2d	v2, x9
	WORD $0xd2873de9      // mov	x9, #14831                      ; =0x39ef
	WORD $0xf2bfdf49      // movk	x9, #65274, lsl #16
	WORD $0xf2c5c849      // movk	x9, #11842, lsl #32
	WORD $0xf2f7fcc9      // movk	x9, #49126, lsl #48
	WORD $0x4e080d23      // dup.2d	v3, x9
	WORD $0xd2940349      // mov	x9, #40986                      ; =0xa01a
	WORD $0xf2a34029      // movk	x9, #6657, lsl #16
	WORD $0xf2c03409      // movk	x9, #416, lsl #32
	WORD $0xf2e7df49      // movk	x9, #16122, lsl #48
	WORD $0x4e080d24      // dup.2d	v4, x9
	WORD $0xd2940349      // mov	x9, #40986                      ; =0xa01a
	WORD $0xf2a34029      // movk	x9, #6657, lsl #16
	WORD $0xf2c03409      // movk	x9, #416, lsl #32
	WORD $0xf2e7e549      // movk	x9, #16170, lsl #48
	WORD $0x4e080d25      // dup.2d	v5, x9
	WORD $0xd28d82e9      // mov	x9, #27671                      ; =0x6c17
	WORD $0xf2a2d829      // movk	x9, #5825, lsl #16
	WORD $0xf2d82d89      // movk	x9, #49516, lsl #32
	WORD $0xf2e7eac9      // movk	x9, #16214, lsl #48
	WORD $0x4e080d26      // dup.2d	v6, x9
	WORD $0xb200e3e9      // mov	x9, #1229782938247303441        ; =0x1111111111111111
	WORD $0xf2e7f029      // movk	x9, #16257, lsl #48
	WORD $0x4e080d27      // dup.2d	v7, x9
	WORD $0xb200f3e9      // mov	x9, #6148914691236517205        ; =0x5555555555555555
	WORD $0xf2e7f4a9      // movk	x9, #16293, lsl #48
	WORD $0x4e080d30      // dup.2d	v16, x9
	WORD $0x52800029      // mov	w9, #1                          ; =0x1
	WORD $0xb200f3ea      // mov	x10, #6148914691236517205       ; =0x5555555555555555
	WORD $0xf2e7f8aa      // movk	x10, #16325, lsl #48
	WORD $0x4e080d51      // dup.2d	v17, x10
	WORD $0x6f03f412      // fmov.2d	v18, #0.50000000
	WORD $0x6f03f613      // fmov.2d	v19, #1.00000000

BB2_2:
	WORD $0x3cc10414 // ldr	q20, [x0], #16
	WORD $0x4e60f694 // fmax.2d	v20, v20, v0
	WORD $0x4ee1f694 // fmin.2d	v20, v20, v1
	WORD $0x6e62de95 // fmul.2d	v21, v20, v2
	WORD $0x4e618ab5 // frintn.2d	v21, v21
	WORD $0x4e75cc74 // fmla.2d	v20, v3, v21
	WORD $0x4ea51cb6 // mov.16b	v22, v5
	WORD $0x4e74cc96 // fmla.2d	v22, v4, v20
	WORD $0x4ea61cd7 // mov.16b	v23, v6
	WORD $0x4e76ce97 // fmla.2d	v23, v20, v22
	WORD $0x4ea71cf6 // mov.16b	v22, v7
	WORD $0x4e77ce96 // fmla.2d	v22, v20, v23
	WORD $0x4eb01e17 // mov.16b	v23, v16
	WORD $0x4e76ce97 // fmla.2d	v23, v20, v22
	WORD $0x4eb11e36 // mov.16b	v22, v17
	WORD $0x4e77ce96 // fmla.2d	v22, v20, v23
	WORD $0x4eb21e57 // mov.16b	v23, v18
	WORD $0x4e76ce97 // fmla.2d	v23, v20, v22
	WORD $0x4eb31e76 // mov.16b	v22, v19
	WORD $0x4e77ce96 // fmla.2d	v22, v20, v23
	WORD $0x4eb31e77 // mov.16b	v23, v19
	WORD $0x4e76ce97 // fmla.2d	v23, v20, v22
	WORD $0x4ee1bab4 // fcvtzs.2d	v20, v21
	WORD $0x4f745694 // shl.2d	v20, v20, #52
	WORD $0x4ef38694 // add.2d	v20, v20, v19
	WORD $0x6e74def4 // fmul.2d	v20, v23, v20
	WORD $0x3c810434 // str	q20, [x1], #16
	WORD $0x91000929 // add	x9, x9, #2
	WORD $0xeb08013f // cmp	x9, x8
	BLT  BB2_2

BB2_3:
	RET

TEXT ·log_f64_neon(SB), $0-24
	MOVD input+0(FP), R0
	MOVD result+8(FP), R1
	MOVD len+16(FP), R2
	WORD $0xf9400048      // ldr	x8, [x2]
	WORD $0xf100091f      // cmp	x8, #2
	BLT  BB3_3
	WORD $0x5280ffe9      // mov	w9, #2047                       ; =0x7ff
	WORD $0x4e080d20      // dup.2d	v0, x9
	WORD $0x92807fc9      // mov	x9, #-1023                      ; =0xfffffffffffffc01
	WORD $0x4e080d21      // dup.2d	v1, x9
	WORD $0x52800029      // mov	w9, #1                          ; =0x1
	WORD $0x92fffe0a      // mov	x10, #4503599627370495          ; =0xfffffffffffff
	WORD $0x4e080d42      // dup.2d	v2, x10
	WORD $0x6f03f603      // fmov.2d	v3, #1.00000000
	WORD $0x6f07f604      // fmov.2d	v4, #-1.00000000
	WORD $0x6f07f405      // fmov.2d	v5, #-0.50000000
	WORD $0xb200f3ea      // mov	x10, #6148914691236517205       ; =0x5555555555555555
	WORD $0xf2e7faaa      // movk	x10, #16341, lsl #48
	WORD $0x4e080d46      // dup.2d	v6, x10
	WORD $0x6f06f607      // fmov.2d	v7, #-0.25000000
	WORD $0xb201e7ea      // mov	x10, #-7378697629483820647      ; =0x9999999999999999
	WORD $0xf293334a      // movk	x10, #39322
	WORD $0xf2e7f92a      // movk	x10, #16329, lsl #48
	WORD $0x4e080d50      // dup.2d	v16, x10
	WORD $0xb200f3ea      // mov	x10, #6148914691236517205       ; =0x5555555555555555
	WORD $0xf2f7f8aa      // movk	x10, #49093, lsl #48
	WORD $0x4e080d51      // dup.2d	v17, x10
	WORD $0xd284924a      // mov	x10, #9362                      ; =0x2492
	WORD $0xf2b2492a      // movk	x10, #37449, lsl #16
	WORD $0xf2c9248a      // movk	x10, #18724, lsl #32
	WORD $0xf2e7f84a      // movk	x10, #16322, lsl #48
	WORD $0x4e080d52      // dup.2d	v18, x10
	WORD $0x6f06f413      // fmov.2d	v19, #-0.12500000
	WORD $0xd2873dea      // mov	x10, #14831                     ; =0x39ef
	WORD $0xf2bfdf4a      // movk	x10, #65274, lsl #16
	WORD $0xf2c5c84a      // movk	x10, #11842, lsl #32
	WORD $0xf2e7fcca      // movk	x10, #16358, lsl #48
	WORD $0x4e080d54      // dup.2d	v20, x10

BB3_2:
	WORD $0x3cc10415 // ldr	q21, [x0], #16
	WORD $0x6f4c06b6 // ushr.2d	v22, v21, #52
	WORD $0x4e201ed6 // and.16b	v22, v22, v0
	WORD $0x4e221eb5 // and.16b	v21, v21, v2
	WORD $0x4ea31eb5 // orr.16b	v21, v21, v3
	WORD $0x4e64d6b5 // fadd.2d	v21, v21, v4
	WORD $0x6e75deb7 // fmul.2d	v23, v21, v21
	WORD $0x6e77deb8 // fmul.2d	v24, v21, v23
	WORD $0x6e77def9 // fmul.2d	v25, v23, v23
	WORD $0x6e79deba // fmul.2d	v26, v21, v25
	WORD $0x6e78df1b // fmul.2d	v27, v24, v24
	WORD $0x6e7bdebc // fmul.2d	v28, v21, v27
	WORD $0x4e77ccb5 // fmla.2d	v21, v5, v23
	WORD $0x4e78ccd5 // fmla.2d	v21, v6, v24
	WORD $0x6e79df37 // fmul.2d	v23, v25, v25
	WORD $0x4e79ccf5 // fmla.2d	v21, v7, v25
	WORD $0x4e7ace15 // fmla.2d	v21, v16, v26
	WORD $0x4e7bce35 // fmla.2d	v21, v17, v27
	WORD $0x4e7cce55 // fmla.2d	v21, v18, v28
	WORD $0x4e77ce75 // fmla.2d	v21, v19, v23
	WORD $0x4ee186d6 // add.2d	v22, v22, v1
	WORD $0x4e61dad6 // scvtf.2d	v22, v22
	WORD $0x4e76ce95 // fmla.2d	v21, v20, v22
	WORD $0x3c810435 // str	q21, [x1], #16
	WORD $0x91000929 // add	x9, x9, #2
	WORD $0xeb08013f // cmp	x9, x8
	BLT  BB3_2

BB3_3:
	RET

TEXT ·sin_f64_neon(SB), $0-24
	MOVD input+0(FP), R0
	MOVD result+8(FP), R1
	MOVD len+16(FP), R2
	WORD $0xf9400048      // ldr	x8, [x2]
	WORD $0xf100091f      // cmp	x8, #2
	BLT  BB4_3
	WORD $0x52800029      // mov	w9, #1                          ; =0x1
	WORD $0xd299106a      // mov	x10, #51331                     ; =0xc883
	WORD $0xf2adb92a      // movk	x10, #28105, lsl #16
	WORD $0xf2cbe60a      // movk	x10, #24368, lsl #32
	WORD $0xf2e7f88a      // movk	x10, #16324, lsl #48
	WORD $0x4e080d40      // dup.2d	v0, x10
	WORD $0xd285a30a      // mov	x10, #11544                     ; =0x2d18
	WORD $0xf2aa888a      // movk	x10, #21572, lsl #16
	WORD $0xf2c43f6a      // movk	x10, #8699, lsl #32
	WORD $0xf2f8032a      // movk	x10, #49177, lsl #48
	WORD $0x4e080d41      // dup.2d	v1, x10
	WORD $0xd285a30a      // mov	x10, #11544                     ; =0x2d18
	WORD $0xf2aa888a      // movk	x10, #21572, lsl #16
	WORD $0xf2c43f6a      // movk	x10, #8699, lsl #32
	WORD $0xf2e7ff2a      // movk	x10, #16377, lsl #48
	WORD $0x4e080d42      // dup.2d	v2, x10
	WORD $0xd285a30a      // mov	x10, #11544                     ; =0x2d18
	WORD $0xf2aa888a      // movk	x10, #21572, lsl #16
	WORD $0xf2c43f6a      // movk	x10, #8699, lsl #32
	WORD $0xf2f7ff2a      // movk	x10, #49145, lsl #48
	WORD $0x4e080d43      // dup.2d	v3, x10
	WORD $0xd285a30a      // mov	x10, #11544                     ; =0x2d18
	WORD $0xf2aa888a      // movk	x10, #21572, lsl #16
	WORD $0xf2c43f6a      // movk	x10, #8699, lsl #32
	WORD $0xf2e8012a      // movk	x10, #16393, lsl #48
	WORD $0x4e080d44      // dup.2d	v4, x10
	WORD $0xd285a30a      // mov	x10, #11544                     ; =0x2d18
	WORD $0xf2aa888a      // movk	x10, #21572, lsl #16
	WORD $0xf2c43f6a      // movk	x10, #8699, lsl #32
	WORD $0xf2f8012a      // movk	x10, #49161, lsl #48
	WORD $0x4e080d45      // dup.2d	v5, x10
	WORD $0xd2889c6a      // mov	x10, #17635                     ; =0x44e3
	WORD $0xf2acfeaa      // movk	x10, #26613, lsl #16
	WORD $0xf2dcc8aa      // movk	x10, #58949, lsl #32
	WORD $0xf2f7cb4a      // movk	x10, #48730, lsl #48
	WORD $0x4e080d46      // dup.2d	v6, x10
	WORD $0xd298e68a      // mov	x10, #50996                     ; =0xc734
	WORD $0xf2b4aaca      // movk	x10, #42326, lsl #16
	WORD $0xf2c3bc6a      // movk	x10, #7651, lsl #32
	WORD $0xf2e7d8ea      // movk	x10, #16071, lsl #48
	WORD $0x4e080d47      // dup.2d	v7, x10
	WORD $0xd294034a      // mov	x10, #40986                     ; =0xa01a
	WORD $0xf2a3402a      // movk	x10, #6657, lsl #16
	WORD $0xf2c0340a      // movk	x10, #416, lsl #32
	WORD $0xf2f7e54a      // movk	x10, #48938, lsl #48
	WORD $0x4e080d50      // dup.2d	v16, x10
	WORD $0xb200e3ea      // mov	x10, #1229782938247303441       ; =0x1111111111111111
	WORD $0xf2e7f02a      // movk	x10, #16257, lsl #48
	WORD $0x4e080d51      // dup.2d	v17, x10
	WORD $0xb200f3ea      // mov	x10, #6148914691236517205       ; =0x5555555555555555
	WORD $0xf2f7f8aa      // movk	x10, #49093, lsl #48
	WORD $0x4e080d52      // dup.2d	v18, x10
	WORD $0x6f03f613      // fmov.2d	v19, #1.00000000

BB4_2:
	WORD $0x3cc10414 // ldr	q20, [x0], #16
	WORD $0x6e60de95 // fmul.2d	v21, v20, v0
	WORD $0x4e618ab5 // frintn.2d	v21, v21
	WORD $0x4e75cc34 // fmla.2d	v20, v1, v21
	WORD $0x6ee2e695 // fcmgt.2d	v21, v20, v2
	WORD $0x4ef4d496 // fsub.2d	v22, v4, v20
	WORD $0x4ef4d4b7 // fsub.2d	v23, v5, v20
	WORD $0x6ef4e478 // fcmgt.2d	v24, v3, v20
	WORD $0x6eb51ed4 // bit.16b	v20, v22, v21
	WORD $0x6eb81ef4 // bit.16b	v20, v23, v24
	WORD $0x6e74de95 // fmul.2d	v21, v20, v20
	WORD $0x4ea71cf6 // mov.16b	v22, v7
	WORD $0x4e75ccd6 // fmla.2d	v22, v6, v21
	WORD $0x4eb01e17 // mov.16b	v23, v16
	WORD $0x4e76ceb7 // fmla.2d	v23, v21, v22
	WORD $0x4eb11e36 // mov.16b	v22, v17
	WORD $0x4e77ceb6 // fmla.2d	v22, v21, v23
	WORD $0x4eb21e57 // mov.16b	v23, v18
	WORD $0x4e76ceb7 // fmla.2d	v23, v21, v22
	WORD $0x4eb31e76 // mov.16b	v22, v19
	WORD $0x4e77ceb6 // fmla.2d	v22, v21, v23
	WORD $0x6e76de94 // fmul.2d	v20, v20, v22
	WORD $0x3c810434 // str	q20, [x1], #16
	WORD $0x91000929 // add	x9, x9, #2
	WORD $0xeb08013f // cmp	x9, x8
	BLT  BB4_2

BB4_3:
	RET

TEXT ·cos_f64_neon(SB), $0-24
	MOVD input+0(FP), R0
	MOVD result+8(FP), R1
	MOVD len+16(FP), R2
	WORD $0xf9400048      // ldr	x8, [x2]
	WORD $0xf100091f      // cmp	x8, #2
	BLT  BB5_3
	WORD $0xd2991069      // mov	x9, #51331                      ; =0xc883
	WORD $0xf2adb929      // movk	x9, #28105, lsl #16
	WORD $0xf2cbe609      // movk	x9, #24368, lsl #32
	WORD $0xf2e7f889      // movk	x9, #16324, lsl #48
	WORD $0x4e080d20      // dup.2d	v0, x9
	WORD $0xd285a309      // mov	x9, #11544                      ; =0x2d18
	WORD $0xf2aa8889      // movk	x9, #21572, lsl #16
	WORD $0xf2c43f69      // movk	x9, #8699, lsl #32
	WORD $0xf2f80329      // movk	x9, #49177, lsl #48
	WORD $0x4e080d21      // dup.2d	v1, x9
	WORD $0xd285a309      // mov	x9, #11544                      ; =0x2d18
	WORD $0xf2aa8889      // movk	x9, #21572, lsl #16
	WORD $0xf2c43f69      // movk	x9, #8699, lsl #32
	WORD $0xf2e7ff29      // movk	x9, #16377, lsl #48
	WORD $0x4e080d22      // dup.2d	v2, x9
	WORD $0xd285a309      // mov	x9, #11544                      ; =0x2d18
	WORD $0xf2aa8889      // movk	x9, #21572, lsl #16
	WORD $0xf2c43f69      // movk	x9, #8699, lsl #32
	WORD $0xf2e80129      // movk	x9, #16393, lsl #48
	WORD $0x4e080d23      // dup.2d	v3, x9
	WORD $0xd293eb89      // mov	x9, #40796                      ; =0x9f5c
	WORD $0xf2b6ef09      // movk	x9, #46968, lsl #16
	WORD $0xf2cfc9e9      // movk	x9, #32335, lsl #32
	WORD $0xf2f7d249      // movk	x9, #48786, lsl #48
	WORD $0x4e080d24      // dup.2d	v4, x9
	WORD $0xd2940349      // mov	x9, #40986                      ; =0xa01a
	WORD $0xf2a34029      // movk	x9, #6657, lsl #16
	WORD $0xf2c03409      // movk	x9, #416, lsl #32
	WORD $0xf2e7df49      // movk	x9, #16122, lsl #48
	WORD $0x4e080d25      // dup.2d	v5, x9
	WORD $0xd28d82e9      // mov	x9, #27671                      ; =0x6c17
	WORD $0xf2a2d829      // movk	x9, #5825, lsl #16
	WORD $0xf2d82d89      // movk	x9, #49516, lsl #32
	WORD $0xf2f7eac9      // movk	x9, #48982, lsl #48
	WORD $0x4e080d26      // dup.2d	v6, x9
	WORD $0x52800029      // mov	w9, #1                          ; =0x1
	WORD $0xb200f3ea      // mov	x10, #6148914691236517205       ; =0x5555555555555555
	WORD $0xf2e7f4aa      // movk	x10, #16293, lsl #48
	WORD $0x4e080d47      // dup.2d	v7, x10
	WORD $0x6f07f410      // fmov.2d	v16, #-0.50000000
	WORD $0x6f03f611      // fmov.2d	v17, #1.00000000

BB5_2:
	WORD $0x3cc10412 // ldr	q18, [x0], #16
	WORD $0x6e60de53 // fmul.2d	v19, v18, v0
	WORD $0x4e618a73 // frintn.2d	v19, v19
	WORD $0x4e73cc32 // fmla.2d	v18, v1, v19
	WORD $0x4ee0fa52 // fabs.2d	v18, v18
	WORD $0x4ef2d473 // fsub.2d	v19, v3, v18
	WORD $0x6ee2e654 // fcmgt.2d	v20, v18, v2
	WORD $0x6eb41e72 // bit.16b	v18, v19, v20
	WORD $0x6e72de52 // fmul.2d	v18, v18, v18
	WORD $0x4ea51cb3 // mov.16b	v19, v5
	WORD $0x4e72cc93 // fmla.2d	v19, v4, v18
	WORD $0x4ea61cd5 // mov.16b	v21, v6
	WORD $0x4e73ce55 // fmla.2d	v21, v18, v19
	WORD $0x4ea71cf3 // mov.16b	v19, v7
	WORD $0x4e75ce53 // fmla.2d	v19, v18, v21
	WORD $0x4eb01e15 // mov.16b	v21, v16
	WORD $0x4e73ce55 // fmla.2d	v21, v18, v19
	WORD $0x4eb11e33 // mov.16b	v19, v17
	WORD $0x4e75ce53 // fmla.2d	v19, v18, v21
	WORD $0x6ee0fa72 // fneg.2d	v18, v19
	WORD $0x6ef41e72 // bif.16b	v18, v19, v20
	WORD $0x3c810432 // str	q18, [x1], #16
	WORD $0x91000929 // add	x9, x9, #2
	WORD $0xeb08013f // cmp	x9, x8
	BLT  BB5_2

BB5_3:
	RET

TEXT ·tanh_f64_neon(SB), $0-24
	MOVD input+0(FP), R0
	MOVD result+8(FP), R1
	MOVD len+16(FP), R2
	WORD $0xf9400048      // ldr	x8, [x2]
	WORD $0xf100091f      // cmp	x8, #2
	BLT  BB6_3
	WORD $0x52800029      // mov	w9, #1                          ; =0x1
	WORD $0x6f01f660      // fmov.2d	v0, #19.00000000
	WORD $0x6f05f661      // fmov.2d	v1, #-19.00000000
	WORD $0xd2905fca      // mov	x10, #33534                     ; =0x82fe
	WORD $0xf2aca56a      // movk	x10, #25899, lsl #16
	WORD $0xf2c2a8ea      // movk	x10, #5447, lsl #32
	WORD $0xf2e7feea      // movk	x10, #16375, lsl #48
	WORD $0x4e080d42      // dup.2d	v2, x10
	WORD $0xd2873dea      // mov	x10, #14831                     ; =0x39ef
	WORD $0xf2bfdf4a      // movk	x10, #65274, lsl #16
	WORD $0xf2c5c84a      // movk	x10, #11842, lsl #32
	WORD $0xf2f7fcca      // movk	x10, #49126, lsl #48
	WORD $0x4e080d43      // dup.2d	v3, x10
	WORD $0xd294034a      // mov	x10, #40986                     ; =0xa01a
	WORD $0xf2a3402a      // movk	x10, #6657, lsl #16
	WORD $0xf2c0340a      // movk	x10, #416, lsl #32
	WORD $0xf2e7df4a      // movk	x10, #16122, lsl #48
	WORD $0x4e080d44      // dup.2d	v4, x10
	WORD $0xd294034a      // mov	x10, #40986                     ; =0xa01a
	WORD $0xf2a3402a      // movk	x10, #6657, lsl #16
	WORD $0xf2c0340a      // movk	x10, #416, lsl #32
	WORD $0xf2e7e54a      // movk	x10, #16170, lsl #48
	WORD $0x4e080d45      // dup.2d	v5, x10
	WORD $0xd28d82ea      // mov	x10, #27671                     ; =0x6c17
	WORD $0xf2a2d82a      // movk	x10, #5825, lsl #16
	WORD $0xf2d82d8a      // movk	x10, #49516, lsl #32
	WORD $0xf2e7eaca      // movk	x10, #16214, lsl #48
	WORD $0x4e080d46      // dup.2d	v6, x10
	WORD $0xb200e3ea      // mov	x10, #1229782938247303441       ; =0x1111111111111111
	WORD $0xf2e7f02a      // movk	x10, #16257, lsl #48
	WORD $0x4e080d47      // dup.2d	v7, x10
	WORD $0xb200f3ea      // mov	x10, #6148914691236517205       ; =0x5555555555555555
	WORD $0xf2e7f4aa      // movk	x10, #16293, lsl #48
	WORD $0x4e080d50      // dup.2d	v16, x10
	WORD $0xb200f3ea      // mov	x10, #6148914691236517205       ; =0x5555555555555555
	WORD $0xf2e7f8aa      // movk	x10, #16325, lsl #48
	WORD $0x4e080d51      // dup.2d	v17, x10
	WORD $0x6f03f412      // fmov.2d	v18, #0.50000000
	WORD $0x6f03f613      // fmov.2d	v19, #1.00000000
	WORD $0x6f07f614      // fmov.2d	v20, #-1.00000000

BB6_2:
	WORD $0x3cc10415 // ldr	q21, [x0], #16
	WORD $0x4ee0f6b5 // fmin.2d	v21, v21, v0
	WORD $0x4e61f6b5 // fmax.2d	v21, v21, v1
	WORD $0x4e75d6b5 // fadd.2d	v21, v21, v21
	WORD $0x6e62deb6 // fmul.2d	v22, v21, v2
	WORD $0x4e618ad6 // frintn.2d	v22, v22
	WORD $0x4e76cc75 // fmla.2d	v21, v3, v22
	WORD $0x4ea51cb7 // mov.16b	v23, v5
	WORD $0x4e75cc97 // fmla.2d	v23, v4, v21
	WORD $0x4ea61cd8 // mov.16b	v24, v6
	WORD $0x4e77ceb8 // fmla.2d	v24, v21, v23
	WORD $0x4ea71cf7 // mov.16b	v23, v7
	WORD $0x4e78ceb7 // fmla.2d	v23, v21, v24
	WORD $0x4eb01e18 // mov.16b	v24, v16
	WORD $0x4e77ceb8 // fmla.2d	v24, v21, v23
	WORD $0x4eb11e37 // mov.16b	v23, v17
	WORD $0x4e78ceb7 // fmla.2d	v23, v21, v24
	WORD $0x4eb21e58 // mov.16b	v24, v18
	WORD $0x4e77ceb8 // fmla.2d	v24, v21, v23
	WORD $0x4eb31e77 // mov.16b	v23, v19
	WORD $0x4e78ceb7 // fmla.2d	v23, v21, v24
	WORD $0x4eb31e78 // mov.16b	v24, v19
	WORD $0x4e77ceb8 // fmla.2d	v24, v21, v23
	WORD $0x4ee1bad5 // fcvtzs.2d	v21, v22
	WORD $0x4f7456b5 // shl.2d	v21, v21, #52
	WORD $0x4ef386b5 // add.2d	v21, v21, v19
	WORD $0x6e75df15 // fmul.2d	v21, v24, v21
	WORD $0x4e74d6b6 // fadd.2d	v22, v21, v20
	WORD $0x4e73d6b5 // fadd.2d	v21, v21, v19
	WORD $0x6e75fed5 // fdiv.2d	v21, v22, v21
	WORD $0x3c810435 // str	q21, [x1], #16
	WORD $0x91000929 // add	x9, x9, #2
	WORD $0xeb08013f // cmp	x9, x8
	BLT  BB6_2

BB6_3:
	RET

TEXT ·sigmoid_f64_neon(SB), $0-24
	MOVD input+0(FP), R0
	MOVD result+8(FP), R1
	MOVD len+16(FP), R2
	WORD $0xf9400048      // ldr	x8, [x2]
	WORD $0xf100091f      // cmp	x8, #2
	BLT  BB7_3
	WORD $0xd2c50009      // mov	x9, #43980465111040             ; =0x280000000000
	WORD $0xf2f810c9      // movk	x9, #49286, lsl #48
	WORD $0x4e080d20      // dup.2d	v0, x9
	WORD $0xd2c50009      // mov	x9, #43980465111040             ; =0x280000000000
	WORD $0xf2e810c9      // movk	x9, #16518, lsl #48
	WORD $0x4e080d21      // dup.2d	v1, x9
	WORD $0xd2905fc9      // mov	x9, #33534                      ; =0x82fe
	WORD $0xf2aca569      // movk	x9, #25899, lsl #16
	WORD $0xf2c2a8e9      // movk	x9, #5447, lsl #32
	WORD $0xf2f7fee9      // movk	x9, #49143, lsl #48
	WORD $0x4e080d22      // dup.2d	v2, x9
	WORD $0xd2873de9      // mov	x9, #14831                      ; =0x39ef
	WORD $0xf2bfdf49      // movk	x9, #65274, lsl #16
	WORD $0xf2c5c849      // movk	x9, #11842, lsl #32
	WORD $0xf2f7fcc9      // movk	x9, #49126, lsl #48
	WORD $0x4e080d23      // dup.2d	v3, x9
	WORD $0xd2940349      // mov	x9, #40986                      ; =0xa01a
	WORD $0xf2a34029      // movk	x9, #6657, lsl #16
	WORD $0xf2c03409      // movk	x9, #416, lsl #32
	WORD $0xf2e7df49      // movk	x9, #16122, lsl #48
	WORD $0x4e080d24      // dup.2d	v4, x9
	WORD $0xd2940349      // mov	x9, #40986                      ; =0xa01a
	WORD $0xf2a34029      // movk	x9, #6657, lsl #16
	WORD $0xf2c03409      // movk	x9, #416, lsl #32
	WORD $0xf2e7e549      // movk	x9, #16170, lsl #48
	WORD $0x4e080d25      // dup.2d	v5, x9
	WORD $0xd28d82e9      // mov	x9, #27671                      ; =0x6c17
	WORD $0xf2a2d829      // movk	x9, #5825, lsl #16
	WORD $0xf2d82d89      // movk	x9, #49516, lsl #32
	WORD $0xf2e7eac9      // movk	x9, #16214, lsl #48
	WORD $0x4e080d26      // dup.2d	v6, x9
	WORD $0xb200e3e9      // mov	x9, #1229782938247303441        ; =0x1111111111111111
	WORD $0xf2e7f029      // movk	x9, #16257, lsl #48
	WORD $0x4e080d27      // dup.2d	v7, x9
	WORD $0xb200f3e9      // mov	x9, #6148914691236517205        ; =0x5555555555555555
	WORD $0xf2e7f4a9      // movk	x9, #16293, lsl #48
	WORD $0x4e080d30      // dup.2d	v16, x9
	WORD $0x52800029      // mov	w9, #1                          ; =0x1
	WORD $0xb200f3ea      // mov	x10, #6148914691236517205       ; =0x5555555555555555
	WORD $0xf2e7f8aa      // movk	x10, #16325, lsl #48
	WORD $0x4e080d51      // dup.2d	v17, x10
	WORD $0x6f03f412      // fmov.2d	v18, #0.50000000
	WORD $0x6f03f613      // fmov.2d	v19, #1.00000000

BB7_2:
	WORD $0x3cc10414 // ldr	q20, [x0], #16
	WORD $0x4e60f694 // fmax.2d	v20, v20, v0
	WORD $0x4ee1f694 // fmin.2d	v20, v20, v1
	WORD $0x6ee0fa95 // fneg.2d	v21, v20
	WORD $0x6e62de94 // fmul.2d	v20, v20, v2
	WORD $0x4e618a94 // frintn.2d	v20, v20
	WORD $0x4e74cc75 // fmla.2d	v21, v3, v20
	WORD $0x4ea51cb6 // mov.16b	v22, v5
	WORD $0x4e75cc96 // fmla.2d	v22, v4, v21
	WORD $0x4ea61cd7 // mov.16b	v23, v6
	WORD $0x4e76ceb7 // fmla.2d	v23, v21, v22
	WORD $0x4ea71cf6 // mov.16b	v22, v7
	WORD $0x4e77ceb6 // fmla.2d	v22, v21, v23
	WORD $0x4eb01e17 // mov.16b	v23, v16
	WORD $0x4e76ceb7 // fmla.2d	v23, v21, v22
	WORD $0x4eb11e36 // mov.16b	v22, v17
	WORD $0x4e77ceb6 // fmla.2d	v22, v21, v23
	WORD $0x4eb21e57 // mov.16b	v23, v18
	WORD $0x4e76ceb7 // fmla.2d	v23, v21, v22
	WORD $0x4eb31e76 // mov.16b	v22, v19
	WORD $0x4e77ceb6 // fmla.2d	v22, v21, v23
	WORD $0x4eb31e77 // mov.16b	v23, v19
	WORD $0x4e76ceb7 // fmla.2d	v23, v21, v22
	WORD $0x4ee1ba94 // fcvtzs.2d	v20, v20
	WORD $0x4f745694 // shl.2d	v20, v20, #52
	WORD $0x4ef38694 // add.2d	v20, v20, v19
	WORD $0x6e74def4 // fmul.2d	v20, v23, v20
	WORD $0x4e73d694 // fadd.2d	v20, v20, v19
	WORD $0x6e74fe74 // fdiv.2d	v20, v19, v20
	WORD $0x3c810434 // str	q20, [x1], #16
	WORD $0x91000929 // add	x9, x9, #2
	WORD $0xeb08013f // cmp	x9, x8
	BLT  BB7_2

BB7_3:
	RET

TEXT ·tan_f64_neon(SB), $0-24
	MOVD input+0(FP), R0
	MOVD result+8(FP), R1
	MOVD len+16(FP), R2
	WORD $0xf9400048      // ldr	x8, [x2]
	WORD $0xf100091f      // cmp	x8, #2
	BLT  BB8_3
	WORD $0xd2991069      // mov	x9, #51331                      ; =0xc883
	WORD $0xf2adb929      // movk	x9, #28105, lsl #16
	WORD $0xf2cbe609      // movk	x9, #24368, lsl #32
	WORD $0xf2e7f889      // movk	x9, #16324, lsl #48
	WORD $0x4e080d20      // dup.2d	v0, x9
	WORD $0xd285a309      // mov	x9, #11544                      ; =0x2d18
	WORD $0xf2aa8889      // movk	x9, #21572, lsl #16
	WORD $0xf2c43f69      // movk	x9, #8699, lsl #32
	WORD $0xf2f80329      // movk	x9, #49177, lsl #48
	WORD $0x4e080d21      // dup.2d	v1, x9
	WORD $0xd285a309      // mov	x9, #11544                      ; =0x2d18
	WORD $0xf2aa8889      // movk	x9, #21572, lsl #16
	WORD $0xf2c43f69      // movk	x9, #8699, lsl #32
	WORD $0xf2e7ff29      // movk	x9, #16377, lsl #48
	WORD $0x4e080d22      // dup.2d	v2, x9
	WORD $0xd285a309      // mov	x9, #11544                      ; =0x2d18
	WORD $0xf2aa8889      // movk	x9, #21572, lsl #16
	WORD $0xf2c43f69      // movk	x9, #8699, lsl #32
	WORD $0xf2f7ff29      // movk	x9, #49145, lsl #48
	WORD $0x4e080d23      // dup.2d	v3, x9
	WORD $0xd285a309      // mov	x9, #11544                      ; =0x2d18
	WORD $0xf2aa8889      // movk	x9, #21572, lsl #16
	WORD $0xf2c43f69      // movk	x9, #8699, lsl #32
	WORD $0xf2e80129      // movk	x9, #16393, lsl #48
	WORD $0x4e080d24      // dup.2d	v4, x9
	WORD $0xd285a309      // mov	x9, #11544                      ; =0x2d18
	WORD $0xf2aa8889      // movk	x9, #21572, lsl #16
	WORD $0xf2c43f69      // movk	x9, #8699, lsl #32
	WORD $0xf2f80129      // movk	x9, #49161, lsl #48
	WORD $0x4e080d25      // dup.2d	v5, x9
	WORD $0xd2889c69      // mov	x9, #17635                      ; =0x44e3
	WORD $0xf2acfea9      // movk	x9, #26613, lsl #16
	WORD $0xf2dcc8a9      // movk	x9, #58949, lsl #32
	WORD $0xf2f7cb49      // movk	x9, #48730, lsl #48
	WORD $0x4e080d26      // dup.2d	v6, x9
	WORD $0xd298e689      // mov	x9, #50996                      ; =0xc734
	WORD $0xf2b4aac9      // movk	x9, #42326, lsl #16
	WORD $0xf2c3bc69      // movk	x9, #7651, lsl #32
	WORD $0xf2e7d8e9      // movk	x9, #16071, lsl #48
	WORD $0x4e080d27      // dup.2d	v7, x9
	WORD $0xd2940349      // mov	x9, #40986                      ; =0xa01a
	WORD $0xf2a34029      // movk	x9, #6657, lsl #16
	WORD $0xf2c03409      // movk	x9, #416, lsl #32
	WORD $0xf2f7e549      // movk	x9, #48938, lsl #48
	WORD $0x4e080d30      // dup.2d	v16, x9
	WORD $0xb200e3e9      // mov	x9, #1229782938247303441        ; =0x1111111111111111
	WORD $0xf2e7f029      // movk	x9, #16257, lsl #48
	WORD $0x4e080d31      // dup.2d	v17, x9
	WORD $0x52800029      // mov	w9, #1                          ; =0x1
	WORD $0xb200f3ea      // mov	x10, #6148914691236517205       ; =0x5555555555555555
	WORD $0xf2f7f8aa      // movk	x10, #49093, lsl #48
	WORD $0x4e080d52      // dup.2d	v18, x10
	WORD $0x6f03f613      // fmov.2d	v19, #1.00000000
	WORD $0xd293eb8a      // mov	x10, #40796                     ; =0x9f5c
	WORD $0xf2b6ef0a      // movk	x10, #46968, lsl #16
	WORD $0xf2cfc9ea      // movk	x10, #32335, lsl #32
	WORD $0xf2f7d24a      // movk	x10, #48786, lsl #48
	WORD $0x4e080d54      // dup.2d	v20, x10
	WORD $0xd294034a      // mov	x10, #40986                     ; =0xa01a
	WORD $0xf2a3402a      // movk	x10, #6657, lsl #16
	WORD $0xf2c0340a      // movk	x10, #416, lsl #32
	WORD $0xf2e7df4a      // movk	x10, #16122, lsl #48
	WORD $0x4e080d55      // dup.2d	v21, x10
	WORD $0xd28d82ea      // mov	x10, #27671                     ; =0x6c17
	WORD $0xf2a2d82a      // movk	x10, #5825, lsl #16
	WORD $0xf2d82d8a      // movk	x10, #49516, lsl #32
	WORD $0xf2f7eaca      // movk	x10, #48982, lsl #48
	WORD $0x4e080d56      // dup.2d	v22, x10
	WORD $0xb200f3ea      // mov	x10, #6148914691236517205       ; =0x5555555555555555
	WORD $0xf2e7f4aa      // movk	x10, #16293, lsl #48
	WORD $0x4e080d57      // dup.2d	v23, x10
	WORD $0x6f07f418      // fmov.2d	v24, #-0.50000000

BB8_2:
	WORD $0x3cc10419 // ldr	q25, [x0], #16
	WORD $0x6e60df3a // fmul.2d	v26, v25, v0
	WORD $0x4e618b5a // frintn.2d	v26, v26
	WORD $0x4e7acc39 // fmla.2d	v25, v1, v26
	WORD $0x6ee2e73a // fcmgt.2d	v26, v25, v2
	WORD $0x4ef9d49b // fsub.2d	v27, v4, v25
	WORD $0x6e791f7a // bsl.16b	v26, v27, v25
	WORD $0x6ef9e47b // fcmgt.2d	v27, v3, v25
	WORD $0x4efad4bc // fsub.2d	v28, v5, v26
	WORD $0x6ebb1f9a // bit.16b	v26, v28, v27
	WORD $0x6e7adf5b // fmul.2d	v27, v26, v26
	WORD $0x4ea71cfc // mov.16b	v28, v7
	WORD $0x4eb01e1d // mov.16b	v29, v16
	WORD $0x4e7bccdc // fmla.2d	v28, v6, v27
	WORD $0x4e7ccf7d // fmla.2d	v29, v27, v28
	WORD $0x4eb11e3c // mov.16b	v28, v17
	WORD $0x4e7dcf7c // fmla.2d	v28, v27, v29
	WORD $0x4eb21e5d // mov.16b	v29, v18
	WORD $0x4ee0fb39 // fabs.2d	v25, v25
	WORD $0x4e7ccf7d // fmla.2d	v29, v27, v28
	WORD $0x6ee2e73c // fcmgt.2d	v28, v25, v2
	WORD $0x4ef9d49e // fsub.2d	v30, v4, v25
	WORD $0x6ebc1fd9 // bit.16b	v25, v30, v28
	WORD $0x4eb31e7e // mov.16b	v30, v19
	WORD $0x6e79df39 // fmul.2d	v25, v25, v25
	WORD $0x4e7dcf7e // fmla.2d	v30, v27, v29
	WORD $0x4eb51ebb // mov.16b	v27, v21
	WORD $0x4e79ce9b // fmla.2d	v27, v20, v25
	WORD $0x4eb61edd // mov.16b	v29, v22
	WORD $0x4e7bcf3d // fmla.2d	v29, v25, v27
	WORD $0x4eb71efb // mov.16b	v27, v23
	WORD $0x6e7edf5a // fmul.2d	v26, v26, v30
	WORD $0x4e7dcf3b // fmla.2d	v27, v25, v29
	WORD $0x4eb81f1d // mov.16b	v29, v24
	WORD $0x4e7bcf3d // fmla.2d	v29, v25, v27
	WORD $0x4eb31e7b // mov.16b	v27, v19
	WORD $0x4e7dcf3b // fmla.2d	v27, v25, v29
	WORD $0x6ee0fb79 // fneg.2d	v25, v27
	WORD $0x6efc1f79 // bif.16b	v25, v27, v28
	WORD $0x6e79ff59 // fdiv.2d	v25, v26, v25
	WORD $0x3c810439 // str	q25, [x1], #16
	WORD $0x91000929 // add	x9, x9, #2
	WORD $0xeb08013f // cmp	x9, x8
	BLT  BB8_2

BB8_3:
	RET

TEXT ·atan_f64_neon(SB), $0-24
	MOVD input+0(FP), R0
	MOVD result+8(FP), R1
	MOVD len+16(FP), R2
	WORD $0xf9400048      // ldr	x8, [x2]
	WORD $0xf100091f      // cmp	x8, #2
	BLT  BB9_3
	WORD $0x52800029      // mov	w9, #1                          ; =0x1
	WORD $0x6f03f600      // fmov.2d	v0, #1.00000000
	WORD $0xd29de64a      // mov	x10, #61234                     ; =0xef32
	WORD $0xf2b33f8a      // movk	x10, #39420, lsl #16
	WORD $0xf2d04f2a      // movk	x10, #33401, lsl #32
	WORD $0xf2e7fb4a      // movk	x10, #16346, lsl #48
	WORD $0x4e080d41      // dup.2d	v1, x10
	WORD $0x6f07f602      // fmov.2d	v2, #-1.00000000
	WORD $0xd282e8aa      // mov	x10, #5957                      ; =0x1745
	WORD $0xf2ae8baa      // movk	x10, #29789, lsl #16
	WORD $0xf2c8ba2a      // movk	x10, #17873, lsl #32
	WORD $0xf2f7f6ea      // movk	x10, #49079, lsl #48
	WORD $0x4e080d43      // dup.2d	v3, x10
	WORD $0xd298e38a      // mov	x10, #50972                     ; =0xc71c
	WORD $0xf2a38e2a      // movk	x10, #7281, lsl #16
	WORD $0xf2ce38ea      // movk	x10, #29127, lsl #32
	WORD $0xf2e7f78a      // movk	x10, #16316, lsl #48
	WORD $0x4e080d44      // dup.2d	v4, x10
	WORD $0xd284920a      // mov	x10, #9360                      ; =0x2490
	WORD $0xf2b2492a      // movk	x10, #37449, lsl #16
	WORD $0xf2c9248a      // movk	x10, #18724, lsl #32
	WORD $0xf2f7f84a      // movk	x10, #49090, lsl #48
	WORD $0x4e080d45      // dup.2d	v5, x10
	WORD $0xb201e7ea      // mov	x10, #-7378697629483820647      ; =0x9999999999999999
	WORD $0xf293334a      // movk	x10, #39322
	WORD $0xf2e7f92a      // movk	x10, #16329, lsl #48
	WORD $0x4e080d46      // dup.2d	v6, x10
	WORD $0xb200f3ea      // mov	x10, #6148914691236517205       ; =0x5555555555555555
	WORD $0xf2f7faaa      // movk	x10, #49109, lsl #48
	WORD $0x4e080d47      // dup.2d	v7, x10
	WORD $0xd285a30a      // mov	x10, #11544                     ; =0x2d18
	WORD $0xf2aa888a      // movk	x10, #21572, lsl #16
	WORD $0xf2c43f6a      // movk	x10, #8699, lsl #32
	WORD $0xf2e7fd2a      // movk	x10, #16361, lsl #48
	WORD $0x4e080d50      // dup.2d	v16, x10
	WORD $0xd285a30a      // mov	x10, #11544                     ; =0x2d18
	WORD $0xf2aa888a      // movk	x10, #21572, lsl #16
	WORD $0xf2c43f6a      // movk	x10, #8699, lsl #32
	WORD $0xf2e7ff2a      // movk	x10, #16377, lsl #48
	WORD $0x4e080d51      // dup.2d	v17, x10

BB9_2:
	WORD $0x3cc10412 // ldr	q18, [x0], #16
	WORD $0x4ee0fa53 // fabs.2d	v19, v18
	WORD $0x6ee0e674 // fcmgt.2d	v20, v19, v0
	WORD $0x6e73fc15 // fdiv.2d	v21, v0, v19
	WORD $0x6eb41eb3 // bit.16b	v19, v21, v20
	WORD $0x6ee1e675 // fcmgt.2d	v21, v19, v1
	WORD $0x4e62d676 // fadd.2d	v22, v19, v2
	WORD $0x4e60d677 // fadd.2d	v23, v19, v0
	WORD $0x6e77fed6 // fdiv.2d	v22, v22, v23
	WORD $0x6eb51ed3 // bit.16b	v19, v22, v21
	WORD $0x6e73de76 // fmul.2d	v22, v19, v19
	WORD $0x4ea41c97 // mov.16b	v23, v4
	WORD $0x4e76cc77 // fmla.2d	v23, v3, v22
	WORD $0x4ea51cb8 // mov.16b	v24, v5
	WORD $0x4e77ced8 // fmla.2d	v24, v22, v23
	WORD $0x4ea61cd7 // mov.16b	v23, v6
	WORD $0x4e78ced7 // fmla.2d	v23, v22, v24
	WORD $0x4ea71cf8 // mov.16b	v24, v7
	WORD $0x4e77ced8 // fmla.2d	v24, v22, v23
	WORD $0x4ea01c17 // mov.16b	v23, v0
	WORD $0x4e78ced7 // fmla.2d	v23, v22, v24
	WORD $0x6e77de73 // fmul.2d	v19, v19, v23
	WORD $0x4e70d676 // fadd.2d	v22, v19, v16
	WORD $0x6eb51ed3 // bit.16b	v19, v22, v21
	WORD $0x4ef3d635 // fsub.2d	v21, v17, v19
	WORD $0x6eb41eb3 // bit.16b	v19, v21, v20
	WORD $0x4ee0ea52 // fcmlt.2d	v18, v18, #0.0
	WORD $0x6ee0fa74 // fneg.2d	v20, v19
	WORD $0x6e731e92 // bsl.16b	v18, v20, v19
	WORD $0x3c810432 // str	q18, [x1], #16
	WORD $0x91000929 // add	x9, x9, #2
	WORD $0xeb08013f // cmp	x9, x8
	BLT  BB9_2

BB9_3:
	RET

TEXT ·atan2_f64_neon(SB), $0-32
	MOVD y_arr+0(FP), R0
	MOVD x_arr+8(FP), R1
	MOVD result+16(FP), R2
	MOVD len+24(FP), R3
	WORD $0xf9400068       // ldr	x8, [x3]
	WORD $0xf100091f       // cmp	x8, #2
	BLT  BB10_3
	WORD $0x52800029       // mov	w9, #1                          ; =0x1
	WORD $0x6f03f600       // fmov.2d	v0, #1.00000000
	WORD $0xd29de64a       // mov	x10, #61234                     ; =0xef32
	WORD $0xf2b33f8a       // movk	x10, #39420, lsl #16
	WORD $0xf2d04f2a       // movk	x10, #33401, lsl #32
	WORD $0xf2e7fb4a       // movk	x10, #16346, lsl #48
	WORD $0x4e080d41       // dup.2d	v1, x10
	WORD $0x6f07f602       // fmov.2d	v2, #-1.00000000
	WORD $0xd282e8aa       // mov	x10, #5957                      ; =0x1745
	WORD $0xf2ae8baa       // movk	x10, #29789, lsl #16
	WORD $0xf2c8ba2a       // movk	x10, #17873, lsl #32
	WORD $0xf2f7f6ea       // movk	x10, #49079, lsl #48
	WORD $0x4e080d43       // dup.2d	v3, x10
	WORD $0xd298e38a       // mov	x10, #50972                     ; =0xc71c
	WORD $0xf2a38e2a       // movk	x10, #7281, lsl #16
	WORD $0xf2ce38ea       // movk	x10, #29127, lsl #32
	WORD $0xf2e7f78a       // movk	x10, #16316, lsl #48
	WORD $0x4e080d44       // dup.2d	v4, x10
	WORD $0xd284920a       // mov	x10, #9360                      ; =0x2490
	WORD $0xf2b2492a       // movk	x10, #37449, lsl #16
	WORD $0xf2c9248a       // movk	x10, #18724, lsl #32
	WORD $0xf2f7f84a       // movk	x10, #49090, lsl #48
	WORD $0x4e080d45       // dup.2d	v5, x10
	WORD $0xb201e7ea       // mov	x10, #-7378697629483820647      ; =0x9999999999999999
	WORD $0xf293334a       // movk	x10, #39322
	WORD $0xf2e7f92a       // movk	x10, #16329, lsl #48
	WORD $0x4e080d46       // dup.2d	v6, x10
	WORD $0xb200f3ea       // mov	x10, #6148914691236517205       ; =0x5555555555555555
	WORD $0xf2f7faaa       // movk	x10, #49109, lsl #48
	WORD $0x4e080d47       // dup.2d	v7, x10
	WORD $0xd285a30a       // mov	x10, #11544                     ; =0x2d18
	WORD $0xf2aa888a       // movk	x10, #21572, lsl #16
	WORD $0xf2c43f6a       // movk	x10, #8699, lsl #32
	WORD $0xf2e7fd2a       // movk	x10, #16361, lsl #48
	WORD $0x4e080d50       // dup.2d	v16, x10
	WORD $0xd285a30a       // mov	x10, #11544                     ; =0x2d18
	WORD $0xf2aa888a       // movk	x10, #21572, lsl #16
	WORD $0xf2c43f6a       // movk	x10, #8699, lsl #32
	WORD $0xf2e7ff2a       // movk	x10, #16377, lsl #48
	WORD $0x4e080d51       // dup.2d	v17, x10
	WORD $0xd285a30a       // mov	x10, #11544                     ; =0x2d18
	WORD $0xf2aa888a       // movk	x10, #21572, lsl #16
	WORD $0xf2c43f6a       // movk	x10, #8699, lsl #32
	WORD $0xf2e8012a       // movk	x10, #16393, lsl #48
	WORD $0x4e080d52       // dup.2d	v18, x10
	WORD $0xd285a30a       // mov	x10, #11544                     ; =0x2d18
	WORD $0xf2aa888a       // movk	x10, #21572, lsl #16
	WORD $0xf2c43f6a       // movk	x10, #8699, lsl #32
	WORD $0xf2f8012a       // movk	x10, #49161, lsl #48
	WORD $0x4e080d53       // dup.2d	v19, x10

BB10_2:
	WORD $0x3cc10414 // ldr	q20, [x0], #16
	WORD $0x3cc10435 // ldr	q21, [x1], #16
	WORD $0x6e75fe96 // fdiv.2d	v22, v20, v21
	WORD $0x4ee0fad7 // fabs.2d	v23, v22
	WORD $0x6ee0e6f8 // fcmgt.2d	v24, v23, v0
	WORD $0x6e77fc19 // fdiv.2d	v25, v0, v23
	WORD $0x6eb81f37 // bit.16b	v23, v25, v24
	WORD $0x6ee1e6f9 // fcmgt.2d	v25, v23, v1
	WORD $0x4e62d6fa // fadd.2d	v26, v23, v2
	WORD $0x4e60d6fb // fadd.2d	v27, v23, v0
	WORD $0x6e7bff5a // fdiv.2d	v26, v26, v27
	WORD $0x6eb91f57 // bit.16b	v23, v26, v25
	WORD $0x6e77defa // fmul.2d	v26, v23, v23
	WORD $0x4ea41c9b // mov.16b	v27, v4
	WORD $0x4e7acc7b // fmla.2d	v27, v3, v26
	WORD $0x4ea51cbc // mov.16b	v28, v5
	WORD $0x4e7bcf5c // fmla.2d	v28, v26, v27
	WORD $0x4ea61cdb // mov.16b	v27, v6
	WORD $0x4e7ccf5b // fmla.2d	v27, v26, v28
	WORD $0x4ea71cfc // mov.16b	v28, v7
	WORD $0x4e7bcf5c // fmla.2d	v28, v26, v27
	WORD $0x4ea01c1b // mov.16b	v27, v0
	WORD $0x4e7ccf5b // fmla.2d	v27, v26, v28
	WORD $0x6e7bdef7 // fmul.2d	v23, v23, v27
	WORD $0x4e70d6fa // fadd.2d	v26, v23, v16
	WORD $0x4ee0ead6 // fcmlt.2d	v22, v22, #0.0
	WORD $0x6eb91f57 // bit.16b	v23, v26, v25
	WORD $0x4ef7d639 // fsub.2d	v25, v17, v23
	WORD $0x6eb81f37 // bit.16b	v23, v25, v24
	WORD $0x6ee0faf8 // fneg.2d	v24, v23
	WORD $0x6e771f16 // bsl.16b	v22, v24, v23
	WORD $0x4ee0eab5 // fcmlt.2d	v21, v21, #0.0
	WORD $0x4ee0ea97 // fcmlt.2d	v23, v20, #0.0
	WORD $0x6ee0ca94 // fcmge.2d	v20, v20, #0.0
	WORD $0x4e72d6d8 // fadd.2d	v24, v22, v18
	WORD $0x4e73d6d9 // fadd.2d	v25, v22, v19
	WORD $0x4e351e94 // and.16b	v20, v20, v21
	WORD $0x4e351ef5 // and.16b	v21, v23, v21
	WORD $0x6e761f14 // bsl.16b	v20, v24, v22
	WORD $0x6eb51f34 // bit.16b	v20, v25, v21
	WORD $0x3c810454 // str	q20, [x2], #16
	WORD $0x91000929 // add	x9, x9, #2
	WORD $0xeb08013f // cmp	x9, x8
	BLT  BB10_2

BB10_3:
	RET

TEXT ·pow_f64_neon(SB), $80-32
	MOVD base+0(FP), R0
	MOVD exp_arr+8(FP), R1
	MOVD result+16(FP), R2
	MOVD len+24(FP), R3
	WORD $0xf9400068       // ldr	x8, [x3]
	WORD $0xf100091f       // cmp	x8, #2
	BLT  BB11_4
	WORD $0xd10143ff       // sub	sp, sp, #80
	WORD $0x6d013bef       // stp	d15, d14, [sp, #16]             ; 16-byte Folded Spill
	WORD $0x6d0233ed       // stp	d13, d12, [sp, #32]             ; 16-byte Folded Spill
	WORD $0x6d032beb       // stp	d11, d10, [sp, #48]             ; 16-byte Folded Spill
	WORD $0x6d0423e9       // stp	d9, d8, [sp, #64]               ; 16-byte Folded Spill
	WORD $0x5280ffe9       // mov	w9, #2047                       ; =0x7ff
	WORD $0x4e080d20       // dup.2d	v0, x9
	WORD $0x3d8003e0       // str	q0, [sp]                        ; 16-byte Folded Spill
	WORD $0x52800029       // mov	w9, #1                          ; =0x1
	WORD $0x92fffe0a       // mov	x10, #4503599627370495          ; =0xfffffffffffff
	WORD $0x4e080d41       // dup.2d	v1, x10
	WORD $0x6f03f602       // fmov.2d	v2, #1.00000000
	WORD $0xd28779aa       // mov	x10, #15309                     ; =0x3bcd
	WORD $0xf2accfea       // movk	x10, #26239, lsl #16
	WORD $0xf2d413ca       // movk	x10, #41118, lsl #32
	WORD $0xf2e7feca       // movk	x10, #16374, lsl #48
	WORD $0x4e080d43       // dup.2d	v3, x10
	WORD $0x6f03f404       // fmov.2d	v4, #0.50000000
	WORD $0x92807fca       // mov	x10, #-1023                     ; =0xfffffffffffffc01
	WORD $0x4e080d45       // dup.2d	v5, x10
	WORD $0x92807faa       // mov	x10, #-1022                     ; =0xfffffffffffffc02
	WORD $0x4e080d46       // dup.2d	v6, x10
	WORD $0x6f07f607       // fmov.2d	v7, #-1.00000000
	WORD $0x6f07f410       // fmov.2d	v16, #-0.50000000
	WORD $0xb200f3ea       // mov	x10, #6148914691236517205       ; =0x5555555555555555
	WORD $0xf2e7faaa       // movk	x10, #16341, lsl #48
	WORD $0x4e080d51       // dup.2d	v17, x10
	WORD $0x6f06f612       // fmov.2d	v18, #-0.25000000
	WORD $0xb201e7ea       // mov	x10, #-7378697629483820647      ; =0x9999999999999999
	WORD $0xf293334a       // movk	x10, #39322
	WORD $0xf2e7f92a       // movk	x10, #16329, lsl #48
	WORD $0x4e080d53       // dup.2d	v19, x10
	WORD $0xb200f3ea       // mov	x10, #6148914691236517205       ; =0x5555555555555555
	WORD $0xf2f7f8aa       // movk	x10, #49093, lsl #48
	WORD $0x4e080d54       // dup.2d	v20, x10
	WORD $0xd284924a       // mov	x10, #9362                      ; =0x2492
	WORD $0xf2b2492a       // movk	x10, #37449, lsl #16
	WORD $0xf2c9248a       // movk	x10, #18724, lsl #32
	WORD $0xf2e7f84a       // movk	x10, #16322, lsl #48
	WORD $0x4e080d55       // dup.2d	v21, x10
	WORD $0xd2873dea       // mov	x10, #14831                     ; =0x39ef
	WORD $0xf2bfdf4a       // movk	x10, #65274, lsl #16
	WORD $0xf2c5c84a       // movk	x10, #11842, lsl #32
	WORD $0xf2e7fcca       // movk	x10, #16358, lsl #48
	WORD $0x4e080d56       // dup.2d	v22, x10
	WORD $0xd2c5000a       // mov	x10, #43980465111040            ; =0x280000000000
	WORD $0xf2f810ca       // movk	x10, #49286, lsl #48
	WORD $0x4e080d57       // dup.2d	v23, x10
	WORD $0xd2c5000a       // mov	x10, #43980465111040            ; =0x280000000000
	WORD $0xf2e810ca       // movk	x10, #16518, lsl #48
	WORD $0x4e080d58       // dup.2d	v24, x10
	WORD $0xd2905fca       // mov	x10, #33534                     ; =0x82fe
	WORD $0xf2aca56a       // movk	x10, #25899, lsl #16
	WORD $0xf2c2a8ea       // movk	x10, #5447, lsl #32
	WORD $0xf2e7feea       // movk	x10, #16375, lsl #48
	WORD $0x4e080d59       // dup.2d	v25, x10
	WORD $0xd294034a       // mov	x10, #40986                     ; =0xa01a
	WORD $0xf2a3402a       // movk	x10, #6657, lsl #16
	WORD $0xf2c0340a       // movk	x10, #416, lsl #32
	WORD $0xf2e7df4a       // movk	x10, #16122, lsl #48
	WORD $0x4e080d5a       // dup.2d	v26, x10
	WORD $0xd294034a       // mov	x10, #40986                     ; =0xa01a
	WORD $0xf2a3402a       // movk	x10, #6657, lsl #16
	WORD $0xf2c0340a       // movk	x10, #416, lsl #32
	WORD $0xf2e7e54a       // movk	x10, #16170, lsl #48
	WORD $0x4e080d5b       // dup.2d	v27, x10
	WORD $0xd28d82ea       // mov	x10, #27671                     ; =0x6c17
	WORD $0xf2a2d82a       // movk	x10, #5825, lsl #16
	WORD $0xf2d82d8a       // movk	x10, #49516, lsl #32
	WORD $0xf2e7eaca       // movk	x10, #16214, lsl #48
	WORD $0x4e080d5c       // dup.2d	v28, x10
	WORD $0xb200e3ea       // mov	x10, #1229782938247303441       ; =0x1111111111111111
	WORD $0xf2e7f02a       // movk	x10, #16257, lsl #48
	WORD $0x4e080d5d       // dup.2d	v29, x10
	WORD $0xb200f3ea       // mov	x10, #6148914691236517205       ; =0x5555555555555555
	WORD $0xf2e7f4aa       // movk	x10, #16293, lsl #48
	WORD $0x4e080d5e       // dup.2d	v30, x10
	WORD $0xb200f3ea       // mov	x10, #6148914691236517205       ; =0x5555555555555555
	WORD $0xf2e7f8aa       // movk	x10, #16325, lsl #48
	WORD $0x4e080d5f       // dup.2d	v31, x10

BB11_2:
	WORD $0x3cc10408 // ldr	q8, [x0], #16
	WORD $0x4e211d09 // and.16b	v9, v8, v1
	WORD $0x4ea21d29 // orr.16b	v9, v9, v2
	WORD $0x6ee3e52a // fcmgt.2d	v10, v9, v3
	WORD $0x6e64dd2b // fmul.2d	v11, v9, v4
	WORD $0x6eaa1d69 // bit.16b	v9, v11, v10
	WORD $0x4e67d529 // fadd.2d	v9, v9, v7
	WORD $0x6e69dd2b // fmul.2d	v11, v9, v9
	WORD $0x6e6bdd2c // fmul.2d	v12, v9, v11
	WORD $0x6e6bdd6d // fmul.2d	v13, v11, v11
	WORD $0x6e6ddd2e // fmul.2d	v14, v9, v13
	WORD $0x6e6cdd8f // fmul.2d	v15, v12, v12
	WORD $0x6e6fdd20 // fmul.2d	v0, v9, v15
	WORD $0x4e6bce09 // fmla.2d	v9, v16, v11
	WORD $0x4e6cce29 // fmla.2d	v9, v17, v12
	WORD $0x4e6dce49 // fmla.2d	v9, v18, v13
	WORD $0x4e6ece69 // fmla.2d	v9, v19, v14
	WORD $0x6f4c0508 // ushr.2d	v8, v8, #52
	WORD $0x3dc003eb // ldr	q11, [sp]                       ; 16-byte Folded Reload
	WORD $0x4e2b1d08 // and.16b	v8, v8, v11
	WORD $0x6e651cca // bsl.16b	v10, v6, v5
	WORD $0x4ee88548 // add.2d	v8, v10, v8
	WORD $0x4e6fce89 // fmla.2d	v9, v20, v15
	WORD $0x4e60cea9 // fmla.2d	v9, v21, v0
	WORD $0x4e61d900 // scvtf.2d	v0, v8
	WORD $0x4e60cec9 // fmla.2d	v9, v22, v0
	WORD $0x3cc10420 // ldr	q0, [x1], #16
	WORD $0x6e69dc00 // fmul.2d	v0, v0, v9
	WORD $0x4e77f400 // fmax.2d	v0, v0, v23
	WORD $0x4ef8f400 // fmin.2d	v0, v0, v24
	WORD $0x6e79dc08 // fmul.2d	v8, v0, v25
	WORD $0x4e618908 // frintn.2d	v8, v8
	WORD $0x4ee8cec0 // fmls.2d	v0, v22, v8
	WORD $0x4ebb1f69 // mov.16b	v9, v27
	WORD $0x4e60cf49 // fmla.2d	v9, v26, v0
	WORD $0x4ebc1f8a // mov.16b	v10, v28
	WORD $0x4e69cc0a // fmla.2d	v10, v0, v9
	WORD $0x4ebd1fa9 // mov.16b	v9, v29
	WORD $0x4e6acc09 // fmla.2d	v9, v0, v10
	WORD $0x4ebe1fca // mov.16b	v10, v30
	WORD $0x4e69cc0a // fmla.2d	v10, v0, v9
	WORD $0x4ebf1fe9 // mov.16b	v9, v31
	WORD $0x4e6acc09 // fmla.2d	v9, v0, v10
	WORD $0x4ea41c8a // mov.16b	v10, v4
	WORD $0x4e69cc0a // fmla.2d	v10, v0, v9
	WORD $0x4ea21c49 // mov.16b	v9, v2
	WORD $0x4e6acc09 // fmla.2d	v9, v0, v10
	WORD $0x4ea21c4a // mov.16b	v10, v2
	WORD $0x4e69cc0a // fmla.2d	v10, v0, v9
	WORD $0x4ee1b900 // fcvtzs.2d	v0, v8
	WORD $0x4f745400 // shl.2d	v0, v0, #52
	WORD $0x4ee28400 // add.2d	v0, v0, v2
	WORD $0x6e60dd40 // fmul.2d	v0, v10, v0
	WORD $0x3c810440 // str	q0, [x2], #16
	WORD $0x91000929 // add	x9, x9, #2
	WORD $0xeb08013f // cmp	x9, x8
	BLT  BB11_2
	WORD $0x6d4423e9 // ldp	d9, d8, [sp, #64]               ; 16-byte Folded Reload
	WORD $0x6d432beb // ldp	d11, d10, [sp, #48]             ; 16-byte Folded Reload
	WORD $0x6d4233ed // ldp	d13, d12, [sp, #32]             ; 16-byte Folded Reload
	WORD $0x6d413bef // ldp	d15, d14, [sp, #16]             ; 16-byte Folded Reload
	WORD $0x910143ff // add	sp, sp, #80

BB11_4:
	RET

TEXT ·erf_f64_neon(SB), $0-24
	MOVD input+0(FP), R0
	MOVD result+8(FP), R1
	MOVD len+16(FP), R2
	WORD $0xf9400048      // ldr	x8, [x2]
	WORD $0xf100091f      // cmp	x8, #2
	BLT  BB12_3
	WORD $0x52800029      // mov	w9, #1                          ; =0x1
	WORD $0xd28f718a      // mov	x10, #31628                     ; =0x7b8c
	WORD $0xf2b527aa      // movk	x10, #43325, lsl #16
	WORD $0xf2dee80a      // movk	x10, #63296, lsl #32
	WORD $0xf2e7fa8a      // movk	x10, #16340, lsl #48
	WORD $0x4e080d40      // dup.2d	v0, x10
	WORD $0x6f03f601      // fmov.2d	v1, #1.00000000
	WORD $0xd29425aa      // mov	x10, #41261                     ; =0xa12d
	WORD $0xf2a84aaa      // movk	x10, #16981, lsl #16
	WORD $0xf2df708a      // movk	x10, #64388, lsl #32
	WORD $0xf2e7fe0a      // movk	x10, #16368, lsl #48
	WORD $0x4e080d42      // dup.2d	v2, x10
	WORD $0xd289872a      // mov	x10, #19513                     ; =0x4c39
	WORD $0xf2aae02a      // movk	x10, #22273, lsl #16
	WORD $0xf2c8038a      // movk	x10, #16412, lsl #32
	WORD $0xf2f7feea      // movk	x10, #49143, lsl #48
	WORD $0x4e080d43      // dup.2d	v3, x10
	WORD $0xd29c2aea      // mov	x10, #57687                     ; =0xe157
	WORD $0xf2aab74a      // movk	x10, #21946, lsl #16
	WORD $0xf2d7c38a      // movk	x10, #48668, lsl #32
	WORD $0xf2e7feca      // movk	x10, #16374, lsl #48
	WORD $0x4e080d44      // dup.2d	v4, x10
	WORD $0xd2828d2a      // mov	x10, #5225                      ; =0x1469
	WORD $0xf2b9878a      // movk	x10, #52284, lsl #16
	WORD $0xf2c6a62a      // movk	x10, #13617, lsl #32
	WORD $0xf2f7fa4a      // movk	x10, #49106, lsl #48
	WORD $0x4e080d45      // dup.2d	v5, x10
	WORD $0xd28b4fca      // mov	x10, #23166                     ; =0x5a7e
	WORD $0xf2b8dd8a      // movk	x10, #50924, lsl #16
	WORD $0xf2c9e40a      // movk	x10, #20256, lsl #32
	WORD $0xf2e7fa0a      // movk	x10, #16336, lsl #48
	WORD $0x4e080d46      // dup.2d	v6, x10
	WORD $0xd2c5000a      // mov	x10, #43980465111040            ; =0x280000000000
	WORD $0xf2f810ca      // movk	x10, #49286, lsl #48
	WORD $0x4e080d47      // dup.2d	v7, x10
	WORD $0xd2905fca      // mov	x10, #33534                     ; =0x82fe
	WORD $0xf2aca56a      // movk	x10, #25899, lsl #16
	WORD $0xf2c2a8ea      // movk	x10, #5447, lsl #32
	WORD $0xf2e7feea      // movk	x10, #16375, lsl #48
	WORD $0x4e080d50      // dup.2d	v16, x10
	WORD $0xd2873dea      // mov	x10, #14831                     ; =0x39ef
	WORD $0xf2bfdf4a      // movk	x10, #65274, lsl #16
	WORD $0xf2c5c84a      // movk	x10, #11842, lsl #32
	WORD $0xf2f7fcca      // movk	x10, #49126, lsl #48
	WORD $0x4e080d51      // dup.2d	v17, x10
	WORD $0xd294034a      // mov	x10, #40986                     ; =0xa01a
	WORD $0xf2a3402a      // movk	x10, #6657, lsl #16
	WORD $0xf2c0340a      // movk	x10, #416, lsl #32
	WORD $0xf2e7df4a      // movk	x10, #16122, lsl #48
	WORD $0x4e080d52      // dup.2d	v18, x10
	WORD $0xd294034a      // mov	x10, #40986                     ; =0xa01a
	WORD $0xf2a3402a      // movk	x10, #6657, lsl #16
	WORD $0xf2c0340a      // movk	x10, #416, lsl #32
	WORD $0xf2e7e54a      // movk	x10, #16170, lsl #48
	WORD $0x4e080d53      // dup.2d	v19, x10
	WORD $0xd28d82ea      // mov	x10, #27671                     ; =0x6c17
	WORD $0xf2a2d82a      // movk	x10, #5825, lsl #16
	WORD $0xf2d82d8a      // movk	x10, #49516, lsl #32
	WORD $0xf2e7eaca      // movk	x10, #16214, lsl #48
	WORD $0x4e080d54      // dup.2d	v20, x10
	WORD $0xb200e3ea      // mov	x10, #1229782938247303441       ; =0x1111111111111111
	WORD $0xf2e7f02a      // movk	x10, #16257, lsl #48
	WORD $0x4e080d55      // dup.2d	v21, x10
	WORD $0xb200f3ea      // mov	x10, #6148914691236517205       ; =0x5555555555555555
	WORD $0xf2e7f4aa      // movk	x10, #16293, lsl #48
	WORD $0x4e080d56      // dup.2d	v22, x10
	WORD $0xb200f3ea      // mov	x10, #6148914691236517205       ; =0x5555555555555555
	WORD $0xf2e7f8aa      // movk	x10, #16325, lsl #48
	WORD $0x4e080d57      // dup.2d	v23, x10
	WORD $0x6f03f418      // fmov.2d	v24, #0.50000000

BB12_2:
	WORD $0x3cc10419 // ldr	q25, [x0], #16
	WORD $0x4ee0fb3a // fabs.2d	v26, v25
	WORD $0x4ea11c3b // mov.16b	v27, v1
	WORD $0x4ea31c7c // mov.16b	v28, v3
	WORD $0x6ee0fb3d // fneg.2d	v29, v25
	WORD $0x6e7ddf3d // fmul.2d	v29, v25, v29
	WORD $0x4e7acc1b // fmla.2d	v27, v0, v26
	WORD $0x4e67f7ba // fmax.2d	v26, v29, v7
	WORD $0x6e70df5d // fmul.2d	v29, v26, v16
	WORD $0x4e618bbd // frintn.2d	v29, v29
	WORD $0x4e7dce3a // fmla.2d	v26, v17, v29
	WORD $0x4eb31e7e // mov.16b	v30, v19
	WORD $0x6e7bfc3b // fdiv.2d	v27, v1, v27
	WORD $0x4e7ace5e // fmla.2d	v30, v18, v26
	WORD $0x4eb41e9f // mov.16b	v31, v20
	WORD $0x4e7ecf5f // fmla.2d	v31, v26, v30
	WORD $0x4eb51ebe // mov.16b	v30, v21
	WORD $0x4e7fcf5e // fmla.2d	v30, v26, v31
	WORD $0x4e7bcc5c // fmla.2d	v28, v2, v27
	WORD $0x4eb61edf // mov.16b	v31, v22
	WORD $0x4e7ecf5f // fmla.2d	v31, v26, v30
	WORD $0x4eb71efe // mov.16b	v30, v23
	WORD $0x4e7fcf5e // fmla.2d	v30, v26, v31
	WORD $0x4ea41c9f // mov.16b	v31, v4
	WORD $0x4e7ccf7f // fmla.2d	v31, v27, v28
	WORD $0x4eb81f1c // mov.16b	v28, v24
	WORD $0x4e7ecf5c // fmla.2d	v28, v26, v30
	WORD $0x4ea11c3e // mov.16b	v30, v1
	WORD $0x4e7ccf5e // fmla.2d	v30, v26, v28
	WORD $0x4ea11c3c // mov.16b	v28, v1
	WORD $0x4e7ecf5c // fmla.2d	v28, v26, v30
	WORD $0x4ea51cba // mov.16b	v26, v5
	WORD $0x4e7fcf7a // fmla.2d	v26, v27, v31
	WORD $0x4ea61cde // mov.16b	v30, v6
	WORD $0x4e7acf7e // fmla.2d	v30, v27, v26
	WORD $0x4ee1bbba // fcvtzs.2d	v26, v29
	WORD $0x6e7edf7b // fmul.2d	v27, v27, v30
	WORD $0x4f74575a // shl.2d	v26, v26, #52
	WORD $0x4ee1875a // add.2d	v26, v26, v1
	WORD $0x6e7adf9a // fmul.2d	v26, v28, v26
	WORD $0x6e7adf7a // fmul.2d	v26, v27, v26
	WORD $0x4efad43a // fsub.2d	v26, v1, v26
	WORD $0x4ee0eb39 // fcmlt.2d	v25, v25, #0.0
	WORD $0x6ee0fb5b // fneg.2d	v27, v26
	WORD $0x6e7a1f79 // bsl.16b	v25, v27, v26
	WORD $0x3c810439 // str	q25, [x1], #16
	WORD $0x91000929 // add	x9, x9, #2
	WORD $0xeb08013f // cmp	x9, x8
	BLT  BB12_2

BB12_3:
	RET

TEXT ·log10_f64_neon(SB), $0-24
	MOVD input+0(FP), R0
	MOVD result+8(FP), R1
	MOVD len+16(FP), R2
	WORD $0xf9400048      // ldr	x8, [x2]
	WORD $0xf100091f      // cmp	x8, #2
	BLT  BB13_3
	WORD $0x5280ffe9      // mov	w9, #2047                       ; =0x7ff
	WORD $0x4e080d20      // dup.2d	v0, x9
	WORD $0x92fffe09      // mov	x9, #4503599627370495           ; =0xfffffffffffff
	WORD $0x4e080d21      // dup.2d	v1, x9
	WORD $0x52800029      // mov	w9, #1                          ; =0x1
	WORD $0x6f03f602      // fmov.2d	v2, #1.00000000
	WORD $0xd28779aa      // mov	x10, #15309                     ; =0x3bcd
	WORD $0xf2accfea      // movk	x10, #26239, lsl #16
	WORD $0xf2d413ca      // movk	x10, #41118, lsl #32
	WORD $0xf2e7feca      // movk	x10, #16374, lsl #48
	WORD $0x4e080d43      // dup.2d	v3, x10
	WORD $0x6f03f404      // fmov.2d	v4, #0.50000000
	WORD $0x92807fca      // mov	x10, #-1023                     ; =0xfffffffffffffc01
	WORD $0x4e080d45      // dup.2d	v5, x10
	WORD $0x92807faa      // mov	x10, #-1022                     ; =0xfffffffffffffc02
	WORD $0x4e080d46      // dup.2d	v6, x10
	WORD $0x6f07f607      // fmov.2d	v7, #-1.00000000
	WORD $0x6f07f410      // fmov.2d	v16, #-0.50000000
	WORD $0xb200f3ea      // mov	x10, #6148914691236517205       ; =0x5555555555555555
	WORD $0xf2e7faaa      // movk	x10, #16341, lsl #48
	WORD $0x4e080d51      // dup.2d	v17, x10
	WORD $0x6f06f612      // fmov.2d	v18, #-0.25000000
	WORD $0xb201e7ea      // mov	x10, #-7378697629483820647      ; =0x9999999999999999
	WORD $0xf293334a      // movk	x10, #39322
	WORD $0xf2e7f92a      // movk	x10, #16329, lsl #48
	WORD $0x4e080d53      // dup.2d	v19, x10
	WORD $0xb200f3ea      // mov	x10, #6148914691236517205       ; =0x5555555555555555
	WORD $0xf2f7f8aa      // movk	x10, #49093, lsl #48
	WORD $0x4e080d54      // dup.2d	v20, x10
	WORD $0xd2905fca      // mov	x10, #33534                     ; =0x82fe
	WORD $0xf2aca56a      // movk	x10, #25899, lsl #16
	WORD $0xf2c2a8ea      // movk	x10, #5447, lsl #32
	WORD $0xf2e7feea      // movk	x10, #16375, lsl #48
	WORD $0x4e080d55      // dup.2d	v21, x10
	WORD $0xd28f3fea      // mov	x10, #31231                     ; =0x79ff
	WORD $0xf2aa13ea      // movk	x10, #20639, lsl #16
	WORD $0xf2c8826a      // movk	x10, #17427, lsl #32
	WORD $0xf2e7fa6a      // movk	x10, #16339, lsl #48
	WORD $0x4e080d56      // dup.2d	v22, x10

BB13_2:
	WORD $0x3cc10417 // ldr	q23, [x0], #16
	WORD $0x6f4c06f8 // ushr.2d	v24, v23, #52
	WORD $0x4e211ef7 // and.16b	v23, v23, v1
	WORD $0x4e201f18 // and.16b	v24, v24, v0
	WORD $0x4ea21ef7 // orr.16b	v23, v23, v2
	WORD $0x6ee3e6f9 // fcmgt.2d	v25, v23, v3
	WORD $0x6e64defa // fmul.2d	v26, v23, v4
	WORD $0x6eb91f57 // bit.16b	v23, v26, v25
	WORD $0x6e651cd9 // bsl.16b	v25, v6, v5
	WORD $0x4ef88738 // add.2d	v24, v25, v24
	WORD $0x4e67d6f7 // fadd.2d	v23, v23, v7
	WORD $0x6e77def9 // fmul.2d	v25, v23, v23
	WORD $0x6e79defa // fmul.2d	v26, v23, v25
	WORD $0x6e79df3b // fmul.2d	v27, v25, v25
	WORD $0x6e7bdefc // fmul.2d	v28, v23, v27
	WORD $0x6e7adf5d // fmul.2d	v29, v26, v26
	WORD $0x4e79ce17 // fmla.2d	v23, v16, v25
	WORD $0x4e7ace37 // fmla.2d	v23, v17, v26
	WORD $0x4e7bce57 // fmla.2d	v23, v18, v27
	WORD $0x4e7cce77 // fmla.2d	v23, v19, v28
	WORD $0x4e7dce97 // fmla.2d	v23, v20, v29
	WORD $0x4e61db18 // scvtf.2d	v24, v24
	WORD $0x4e77ceb8 // fmla.2d	v24, v21, v23
	WORD $0x6e76df17 // fmul.2d	v23, v24, v22
	WORD $0x3c810437 // str	q23, [x1], #16
	WORD $0x91000929 // add	x9, x9, #2
	WORD $0xeb08013f // cmp	x9, x8
	BLT  BB13_2

BB13_3:
	RET

TEXT ·exp10_f64_neon(SB), $0-24
	MOVD input+0(FP), R0
	MOVD result+8(FP), R1
	MOVD len+16(FP), R2
	WORD $0xf9400048      // ldr	x8, [x2]
	WORD $0xf100091f      // cmp	x8, #2
	BLT  BB14_3
	WORD $0xd2946e29      // mov	x9, #41841                      ; =0xa371
	WORD $0xf2a12f29      // movk	x9, #2425, lsl #16
	WORD $0xf2d269e9      // movk	x9, #37711, lsl #32
	WORD $0xf2e80149      // movk	x9, #16394, lsl #48
	WORD $0x4e080d20      // dup.2d	v0, x9
	WORD $0xd2de0009      // mov	x9, #263882790666240            ; =0xf00000000000
	WORD $0xf2f811e9      // movk	x9, #49295, lsl #48
	WORD $0x4e080d21      // dup.2d	v1, x9
	WORD $0xd2df0009      // mov	x9, #272678883688448            ; =0xf80000000000
	WORD $0xf2e811e9      // movk	x9, #16527, lsl #48
	WORD $0x4e080d22      // dup.2d	v2, x9
	WORD $0xd2873de9      // mov	x9, #14831                      ; =0x39ef
	WORD $0xf2bfdf49      // movk	x9, #65274, lsl #16
	WORD $0xf2c5c849      // movk	x9, #11842, lsl #32
	WORD $0xf2e7fcc9      // movk	x9, #16358, lsl #48
	WORD $0x4e080d23      // dup.2d	v3, x9
	WORD $0xd2940349      // mov	x9, #40986                      ; =0xa01a
	WORD $0xf2a34029      // movk	x9, #6657, lsl #16
	WORD $0xf2c03409      // movk	x9, #416, lsl #32
	WORD $0xf2e7df49      // movk	x9, #16122, lsl #48
	WORD $0x4e080d24      // dup.2d	v4, x9
	WORD $0xd2940349      // mov	x9, #40986                      ; =0xa01a
	WORD $0xf2a34029      // movk	x9, #6657, lsl #16
	WORD $0xf2c03409      // movk	x9, #416, lsl #32
	WORD $0xf2e7e549      // movk	x9, #16170, lsl #48
	WORD $0x4e080d25      // dup.2d	v5, x9
	WORD $0xd28d82e9      // mov	x9, #27671                      ; =0x6c17
	WORD $0xf2a2d829      // movk	x9, #5825, lsl #16
	WORD $0xf2d82d89      // movk	x9, #49516, lsl #32
	WORD $0xf2e7eac9      // movk	x9, #16214, lsl #48
	WORD $0x4e080d26      // dup.2d	v6, x9
	WORD $0xb200e3e9      // mov	x9, #1229782938247303441        ; =0x1111111111111111
	WORD $0xf2e7f029      // movk	x9, #16257, lsl #48
	WORD $0x4e080d27      // dup.2d	v7, x9
	WORD $0xb200f3e9      // mov	x9, #6148914691236517205        ; =0x5555555555555555
	WORD $0xf2e7f4a9      // movk	x9, #16293, lsl #48
	WORD $0x4e080d30      // dup.2d	v16, x9
	WORD $0x52800029      // mov	w9, #1                          ; =0x1
	WORD $0xb200f3ea      // mov	x10, #6148914691236517205       ; =0x5555555555555555
	WORD $0xf2e7f8aa      // movk	x10, #16325, lsl #48
	WORD $0x4e080d51      // dup.2d	v17, x10
	WORD $0x6f03f412      // fmov.2d	v18, #0.50000000
	WORD $0x6f03f613      // fmov.2d	v19, #1.00000000

BB14_2:
	WORD $0x3cc10414 // ldr	q20, [x0], #16
	WORD $0x6e60de94 // fmul.2d	v20, v20, v0
	WORD $0x4e61f694 // fmax.2d	v20, v20, v1
	WORD $0x4ee2f694 // fmin.2d	v20, v20, v2
	WORD $0x4e618a95 // frintn.2d	v21, v20
	WORD $0x4ef5d694 // fsub.2d	v20, v20, v21
	WORD $0x6e63de94 // fmul.2d	v20, v20, v3
	WORD $0x4ea51cb6 // mov.16b	v22, v5
	WORD $0x4e74cc96 // fmla.2d	v22, v4, v20
	WORD $0x4ea61cd7 // mov.16b	v23, v6
	WORD $0x4e76ce97 // fmla.2d	v23, v20, v22
	WORD $0x4ea71cf6 // mov.16b	v22, v7
	WORD $0x4e77ce96 // fmla.2d	v22, v20, v23
	WORD $0x4eb01e17 // mov.16b	v23, v16
	WORD $0x4e76ce97 // fmla.2d	v23, v20, v22
	WORD $0x4eb11e36 // mov.16b	v22, v17
	WORD $0x4e77ce96 // fmla.2d	v22, v20, v23
	WORD $0x4eb21e57 // mov.16b	v23, v18
	WORD $0x4e76ce97 // fmla.2d	v23, v20, v22
	WORD $0x4eb31e76 // mov.16b	v22, v19
	WORD $0x4e77ce96 // fmla.2d	v22, v20, v23
	WORD $0x4eb31e77 // mov.16b	v23, v19
	WORD $0x4e76ce97 // fmla.2d	v23, v20, v22
	WORD $0x4ee1bab4 // fcvtzs.2d	v20, v21
	WORD $0x4f745694 // shl.2d	v20, v20, #52
	WORD $0x4ef38694 // add.2d	v20, v20, v19
	WORD $0x6e74def4 // fmul.2d	v20, v23, v20
	WORD $0x3c810434 // str	q20, [x1], #16
	WORD $0x91000929 // add	x9, x9, #2
	WORD $0xeb08013f // cmp	x9, x8
	BLT  BB14_2

BB14_3:
	RET

TEXT ·sincos_f64_neon(SB), $0-32
	MOVD input+0(FP), R0
	MOVD sin_result+8(FP), R1
	MOVD cos_result+16(FP), R2
	MOVD len+24(FP), R3
	WORD $0xf9400068           // ldr	x8, [x3]
	WORD $0xf100091f           // cmp	x8, #2
	BLT  BB15_3
	WORD $0xd2991069           // mov	x9, #51331                      ; =0xc883
	WORD $0xf2adb929           // movk	x9, #28105, lsl #16
	WORD $0xf2cbe609           // movk	x9, #24368, lsl #32
	WORD $0xf2e7f889           // movk	x9, #16324, lsl #48
	WORD $0x4e080d20           // dup.2d	v0, x9
	WORD $0xd285a309           // mov	x9, #11544                      ; =0x2d18
	WORD $0xf2aa8889           // movk	x9, #21572, lsl #16
	WORD $0xf2c43f69           // movk	x9, #8699, lsl #32
	WORD $0xf2f80329           // movk	x9, #49177, lsl #48
	WORD $0x4e080d21           // dup.2d	v1, x9
	WORD $0xd285a309           // mov	x9, #11544                      ; =0x2d18
	WORD $0xf2aa8889           // movk	x9, #21572, lsl #16
	WORD $0xf2c43f69           // movk	x9, #8699, lsl #32
	WORD $0xf2e7ff29           // movk	x9, #16377, lsl #48
	WORD $0x4e080d22           // dup.2d	v2, x9
	WORD $0xd285a309           // mov	x9, #11544                      ; =0x2d18
	WORD $0xf2aa8889           // movk	x9, #21572, lsl #16
	WORD $0xf2c43f69           // movk	x9, #8699, lsl #32
	WORD $0xf2f7ff29           // movk	x9, #49145, lsl #48
	WORD $0x4e080d23           // dup.2d	v3, x9
	WORD $0xd285a309           // mov	x9, #11544                      ; =0x2d18
	WORD $0xf2aa8889           // movk	x9, #21572, lsl #16
	WORD $0xf2c43f69           // movk	x9, #8699, lsl #32
	WORD $0xf2e80129           // movk	x9, #16393, lsl #48
	WORD $0x4e080d24           // dup.2d	v4, x9
	WORD $0xd285a309           // mov	x9, #11544                      ; =0x2d18
	WORD $0xf2aa8889           // movk	x9, #21572, lsl #16
	WORD $0xf2c43f69           // movk	x9, #8699, lsl #32
	WORD $0xf2f80129           // movk	x9, #49161, lsl #48
	WORD $0x4e080d25           // dup.2d	v5, x9
	WORD $0xd2889c69           // mov	x9, #17635                      ; =0x44e3
	WORD $0xf2acfea9           // movk	x9, #26613, lsl #16
	WORD $0xf2dcc8a9           // movk	x9, #58949, lsl #32
	WORD $0xf2f7cb49           // movk	x9, #48730, lsl #48
	WORD $0x4e080d26           // dup.2d	v6, x9
	WORD $0xd298e689           // mov	x9, #50996                      ; =0xc734
	WORD $0xf2b4aac9           // movk	x9, #42326, lsl #16
	WORD $0xf2c3bc69           // movk	x9, #7651, lsl #32
	WORD $0xf2e7d8e9           // movk	x9, #16071, lsl #48
	WORD $0x4e080d27           // dup.2d	v7, x9
	WORD $0xd2940349           // mov	x9, #40986                      ; =0xa01a
	WORD $0xf2a34029           // movk	x9, #6657, lsl #16
	WORD $0xf2c03409           // movk	x9, #416, lsl #32
	WORD $0xf2f7e549           // movk	x9, #48938, lsl #48
	WORD $0x4e080d30           // dup.2d	v16, x9
	WORD $0xb200e3e9           // mov	x9, #1229782938247303441        ; =0x1111111111111111
	WORD $0xf2e7f029           // movk	x9, #16257, lsl #48
	WORD $0x4e080d31           // dup.2d	v17, x9
	WORD $0x52800029           // mov	w9, #1                          ; =0x1
	WORD $0xb200f3ea           // mov	x10, #6148914691236517205       ; =0x5555555555555555
	WORD $0xf2f7f8aa           // movk	x10, #49093, lsl #48
	WORD $0x4e080d52           // dup.2d	v18, x10
	WORD $0x6f03f613           // fmov.2d	v19, #1.00000000
	WORD $0xd293eb8a           // mov	x10, #40796                     ; =0x9f5c
	WORD $0xf2b6ef0a           // movk	x10, #46968, lsl #16
	WORD $0xf2cfc9ea           // movk	x10, #32335, lsl #32
	WORD $0xf2f7d24a           // movk	x10, #48786, lsl #48
	WORD $0x4e080d54           // dup.2d	v20, x10
	WORD $0xd294034a           // mov	x10, #40986                     ; =0xa01a
	WORD $0xf2a3402a           // movk	x10, #6657, lsl #16
	WORD $0xf2c0340a           // movk	x10, #416, lsl #32
	WORD $0xf2e7df4a           // movk	x10, #16122, lsl #48
	WORD $0x4e080d55           // dup.2d	v21, x10
	WORD $0xd28d82ea           // mov	x10, #27671                     ; =0x6c17
	WORD $0xf2a2d82a           // movk	x10, #5825, lsl #16
	WORD $0xf2d82d8a           // movk	x10, #49516, lsl #32
	WORD $0xf2f7eaca           // movk	x10, #48982, lsl #48
	WORD $0x4e080d56           // dup.2d	v22, x10
	WORD $0xb200f3ea           // mov	x10, #6148914691236517205       ; =0x5555555555555555
	WORD $0xf2e7f4aa           // movk	x10, #16293, lsl #48
	WORD $0x4e080d57           // dup.2d	v23, x10
	WORD $0x6f07f418           // fmov.2d	v24, #-0.50000000

BB15_2:
	WORD $0x3cc10419 // ldr	q25, [x0], #16
	WORD $0x6e60df3a // fmul.2d	v26, v25, v0
	WORD $0x4e618b5a // frintn.2d	v26, v26
	WORD $0x4e7acc39 // fmla.2d	v25, v1, v26
	WORD $0x6ee2e73a // fcmgt.2d	v26, v25, v2
	WORD $0x6ef9e47b // fcmgt.2d	v27, v3, v25
	WORD $0x4ef9d49c // fsub.2d	v28, v4, v25
	WORD $0x6e791f9a // bsl.16b	v26, v28, v25
	WORD $0x4efad4bc // fsub.2d	v28, v5, v26
	WORD $0x6ebb1f9a // bit.16b	v26, v28, v27
	WORD $0x6e7adf5b // fmul.2d	v27, v26, v26
	WORD $0x4ea71cfc // mov.16b	v28, v7
	WORD $0x4e7bccdc // fmla.2d	v28, v6, v27
	WORD $0x4eb01e1d // mov.16b	v29, v16
	WORD $0x4e7ccf7d // fmla.2d	v29, v27, v28
	WORD $0x4eb11e3c // mov.16b	v28, v17
	WORD $0x4e7dcf7c // fmla.2d	v28, v27, v29
	WORD $0x4eb21e5d // mov.16b	v29, v18
	WORD $0x4eb31e7e // mov.16b	v30, v19
	WORD $0x4ee0fb39 // fabs.2d	v25, v25
	WORD $0x4e7ccf7d // fmla.2d	v29, v27, v28
	WORD $0x6ee2e73c // fcmgt.2d	v28, v25, v2
	WORD $0x4ef9d49f // fsub.2d	v31, v4, v25
	WORD $0x6ebc1ff9 // bit.16b	v25, v31, v28
	WORD $0x6e79df39 // fmul.2d	v25, v25, v25
	WORD $0x4eb51ebf // mov.16b	v31, v21
	WORD $0x4e7dcf7e // fmla.2d	v30, v27, v29
	WORD $0x4e79ce9f // fmla.2d	v31, v20, v25
	WORD $0x4eb61edb // mov.16b	v27, v22
	WORD $0x4e7fcf3b // fmla.2d	v27, v25, v31
	WORD $0x4eb71efd // mov.16b	v29, v23
	WORD $0x4e7bcf3d // fmla.2d	v29, v25, v27
	WORD $0x6e7edf5a // fmul.2d	v26, v26, v30
	WORD $0x4eb81f1b // mov.16b	v27, v24
	WORD $0x4e7dcf3b // fmla.2d	v27, v25, v29
	WORD $0x4eb31e7d // mov.16b	v29, v19
	WORD $0x4e7bcf3d // fmla.2d	v29, v25, v27
	WORD $0x6ee0fbb9 // fneg.2d	v25, v29
	WORD $0x6efc1fb9 // bif.16b	v25, v29, v28
	WORD $0x3c81043a // str	q26, [x1], #16
	WORD $0x3c810459 // str	q25, [x2], #16
	WORD $0x91000929 // add	x9, x9, #2
	WORD $0xeb08013f // cmp	x9, x8
	BLT  BB15_2

BB15_3:
	RET
