//go:build !noasm && amd64
// Code generated by GoAT. DO NOT EDIT.
// versions:
// 	clang   21.1.8
// 	objdump 2.45.1
// flags: -mavx512bf16 -mavx512f -mavx512vl -mavx512dq -O3
// source: ../c/ops_bf16_avx512_amd64.c

package asm

import "unsafe"

//go:noescape
func demote_f32_to_bf16_avx512(a, result, len unsafe.Pointer)

//go:noescape
func demote_two_f32_to_bf16_avx512(lo, hi, result, len unsafe.Pointer)

//go:noescape
func promote_bf16_to_f32_avx512(a, result, len unsafe.Pointer)

//go:noescape
func dot_bf16_avx512(a, b, acc, len unsafe.Pointer)

//go:noescape
func add_bf16_avx512(a, b, result, len unsafe.Pointer)

//go:noescape
func mul_bf16_avx512(a, b, result, len unsafe.Pointer)

//go:noescape
func fma_bf16_avx512(a, b, c, result, len unsafe.Pointer)
