//go:build !noasm && arm64
// Code generated by GoAT. DO NOT EDIT.
// versions:
// 	clang   21.1.8
// 	objdump 2.45.1
// flags: -march=armv8-a+simd+fp -fno-builtin-memset -O3
// source: /Users/ajroetker/go/src/github.com/ajroetker/go-highway/hwy/contrib/loss/asm/basecutcrossentropygrad_c_f32_neon_arm64.c

TEXT ·cutcrossentropygrad_c_f32_neon(SB), $80-56
	MOVD hiddenStates+0(FP), R0
	MOVD embeddings+8(FP), R1
	MOVD labels+16(FP), R2
	MOVD gradOutput+24(FP), R3
	MOVD pnumPositions+32(FP), R4
	MOVD phiddenDim+40(FP), R5
	MOVD pvocabSize+48(FP), R6
	WORD $0xf94000a8              // ldr	x8, [x5]
	WORD $0xf9400089              // ldr	x9, [x4]
	WORD $0xf94000ca              // ldr	x10, [x6]
	WORD $0xf100013f              // cmp	x9, #0
	WORD $0xfa401904              // ccmp	x8, #0, #4, ne
	WORD $0xfa401944              // ccmp	x10, #0, #4, ne
	WORD $0xfa411928              // ccmp	x9, #1, #8, ne
	BLT  BB0_64
	WORD $0xaa0303e7              // mov	x7, x3
	WORD $0xd280000c              // mov	x12, #0                         ; =0x0
	WORD $0xd280000b              // mov	x11, #0                         ; =0x0

BB0_2:
	WORD $0xb86b784d // ldr	w13, [x2, x11, lsl #2]
	WORD $0x310005bf // cmn	w13, #1
	WORD $0xfa4dc144 // ccmp	x10, x13, #4, gt
	WORD $0x9a8cd58c // cinc	x12, x12, gt
	WORD $0x9100056b // add	x11, x11, #1
	WORD $0xeb0b013f // cmp	x9, x11
	BNE  BB0_2
	WORD $0xb400404c // cbz	x12, LBB0_64
	WORD $0xf80003f9 // str	x25, [sp, #-80]!                ; 8-byte Folded Spill [transformed]
	WORD $0xa9015ff8 // stp	x24, x23, [sp, #16]             ; 16-byte Folded Spill
	WORD $0xa90257f6 // stp	x22, x21, [sp, #32]             ; 16-byte Folded Spill
	WORD $0xa9034ff4 // stp	x20, x19, [sp, #48]             ; 16-byte Folded Spill
	WORD $0xa9047bfd // stp	x29, x30, [sp, #64]             ; 16-byte Folded Spill
	WORD $0xd280000b // mov	x11, #0                         ; =0x0
	WORD $0x9e630181 // ucvtf	d1, x12
	WORD $0x1e6e1000 // fmov	d0, #1.00000000
	WORD $0x927ef506 // and	x6, x8, #0xfffffffffffffffc
	WORD $0xd37ef50d // lsl	x13, x8, #2
	WORD $0x8b0d002c // add	x12, x1, x13
	WORD $0xf90007ec // str	x12, [sp, #8]                   ; 8-byte Folded Spill
	WORD $0xd2c5000f // mov	x15, #43980465111040            ; =0x280000000000
	WORD $0xf2e810cf // movk	x15, #16518, lsl #48
	WORD $0xd2c50010 // mov	x16, #43980465111040            ; =0x280000000000
	WORD $0xf2f810d0 // movk	x16, #49286, lsl #48
	WORD $0xd2905fd4 // mov	x20, #33534                     ; =0x82fe
	WORD $0xf2aca574 // movk	x20, #25899, lsl #16
	WORD $0xf2c2a8f4 // movk	x20, #5447, lsl #32
	WORD $0xf2e7fef4 // movk	x20, #16375, lsl #48
	WORD $0xd2bfdc15 // mov	x21, #4276092928                ; =0xfee00000
	WORD $0xf2c5c855 // movk	x21, #11842, lsl #32
	WORD $0xf2f7fcd5 // movk	x21, #49126, lsl #48
	WORD $0x1e611801 // fdiv	d1, d0, d1
	WORD $0xd2940356 // mov	x22, #40986                     ; =0xa01a
	WORD $0xf2a34036 // movk	x22, #6657, lsl #16
	WORD $0xf2c03416 // movk	x22, #416, lsl #32
	WORD $0xf2e7e556 // movk	x22, #16170, lsl #48
	WORD $0xd28d82f7 // mov	x23, #27671                     ; =0x6c17
	WORD $0xf2a2d837 // movk	x23, #5825, lsl #16
	WORD $0xf2d82d97 // movk	x23, #49516, lsl #32
	WORD $0xf2e7ead7 // movk	x23, #16214, lsl #48
	WORD $0xb200e3f8 // mov	x24, #1229782938247303441       ; =0x1111111111111111
	WORD $0xf2e7f038 // movk	x24, #16257, lsl #48
	WORD $0xb200f3f9 // mov	x25, #6148914691236517205       ; =0x5555555555555555
	WORD $0xf2e7f4b9 // movk	x25, #16293, lsl #48
	WORD $0xb200f3fe // mov	x30, #6148914691236517205       ; =0x5555555555555555
	WORD $0xf2e7f8be // movk	x30, #16325, lsl #48
	WORD $0xd2e7fe0e // mov	x14, #4607182418800017408       ; =0x3ff0000000000000
	WORD $0x1e624021 // fcvt	s1, d1
	WORD $0x1e6c1002 // fmov	d2, #0.50000000
	WORD $0x1e7e1003 // fmov	d3, #-1.00000000
	B    BB0_6

BB0_5:
	WORD $0x9100056b // add	x11, x11, #1
	WORD $0x8b0d0000 // add	x0, x0, x13
	WORD $0x8b0d00e7 // add	x7, x7, x13
	WORD $0xeb09017f // cmp	x11, x9
	BEQ  BB0_63

BB0_6:
	WORD $0xb86b7851 // ldr	w17, [x2, x11, lsl #2]
	WORD $0x37f80191 // tbnz	w17, #31, LBB0_10
	WORD $0xeb11015f // cmp	x10, x17
	BLE  BB0_10
	WORD $0xf100111f // cmp	x8, #4
	BGE  BB0_13
	WORD $0xd2800004 // mov	x4, #0                          ; =0x0
	WORD $0x6f00e404 // movi.2d	v4, #0000000000000000
	WORD $0x6e24d484 // faddp.4s	v4, v4, v4
	WORD $0x7e30d884 // faddp.2s	s4, v4
	WORD $0xeb08009f // cmp	x4, x8
	BLT  BB0_16
	B    BB0_17

BB0_10:
	WORD $0xf100051f // cmp	x8, #1
	BLT  BB0_5
	WORD $0xd280000c // mov	x12, #0                         ; =0x0

BB0_12:
	WORD $0xb82c78ff // str	wzr, [x7, x12, lsl #2]
	WORD $0x9100058c // add	x12, x12, #1
	WORD $0xeb0c011f // cmp	x8, x12
	BNE  BB0_12
	B    BB0_5

BB0_13:
	WORD $0x6f00e404 // movi.2d	v4, #0000000000000000
	WORD $0xaa0103ec // mov	x12, x1
	WORD $0xaa0003e3 // mov	x3, x0
	WORD $0x52800084 // mov	w4, #4                          ; =0x4

BB0_14:
	WORD $0x3cc10465 // ldr	q5, [x3], #16
	WORD $0x3cc10586 // ldr	q6, [x12], #16
	WORD $0x4e25ccc4 // fmla.4s	v4, v6, v5
	WORD $0x91001084 // add	x4, x4, #4
	WORD $0xeb08009f // cmp	x4, x8
	BLE  BB0_14
	WORD $0xaa0603e4 // mov	x4, x6
	WORD $0x6e24d484 // faddp.4s	v4, v4, v4
	WORD $0x7e30d884 // faddp.2s	s4, v4
	WORD $0xeb0800df // cmp	x6, x8
	BGE  BB0_17

BB0_16:
	WORD $0xbc647805 // ldr	s5, [x0, x4, lsl #2]
	WORD $0xbc647826 // ldr	s6, [x1, x4, lsl #2]
	WORD $0x1f0610a4 // fmadd	s4, s5, s6, s4
	WORD $0x91000484 // add	x4, x4, #1
	WORD $0xeb04011f // cmp	x8, x4
	BNE  BB0_16

BB0_17:
	WORD $0x1e22c084 // fcvt	d4, s4
	WORD $0xf100095f // cmp	x10, #2
	BLT  BB0_40
	WORD $0x1e6e1005 // fmov	d5, #1.00000000
	WORD $0xf94007e4 // ldr	x4, [sp, #8]                    ; 8-byte Folded Reload
	WORD $0x52800025 // mov	w5, #1                          ; =0x1
	B    BB0_21

BB0_19:
	WORD $0xd2effe0c // mov	x12, #9218868437227405312       ; =0x7ff0000000000000
	WORD $0x9e670187 // fmov	d7, x12

BB0_20:
	WORD $0x1e6728a5 // fadd	d5, d5, d7
	WORD $0x1e604086 // fmov	d6, d4
	WORD $0x910004a5 // add	x5, x5, #1
	WORD $0x8b0d0084 // add	x4, x4, x13
	WORD $0xeb0a00bf // cmp	x5, x10
	BEQ  BB0_36

BB0_21:
	WORD $0xf100111f // cmp	x8, #4
	BGE  BB0_23
	WORD $0xd280000c // mov	x12, #0                         ; =0x0
	WORD $0x6f00e406 // movi.2d	v6, #0000000000000000
	WORD $0x6e26d4c6 // faddp.4s	v6, v6, v6
	WORD $0x7e30d8c6 // faddp.2s	s6, v6
	WORD $0xeb08019f // cmp	x12, x8
	BLT  BB0_26
	B    BB0_27

BB0_23:
	WORD $0xd280000c // mov	x12, #0                         ; =0x0
	WORD $0x6f00e406 // movi.2d	v6, #0000000000000000
	WORD $0x52800083 // mov	w3, #4                          ; =0x4

BB0_24:
	WORD $0x3cec6807 // ldr	q7, [x0, x12]
	WORD $0x3cec6890 // ldr	q16, [x4, x12]
	WORD $0x4e27ce06 // fmla.4s	v6, v16, v7
	WORD $0x91001063 // add	x3, x3, #4
	WORD $0x9100418c // add	x12, x12, #16
	WORD $0xeb08007f // cmp	x3, x8
	BLE  BB0_24
	WORD $0xaa0603ec // mov	x12, x6
	WORD $0x6e26d4c6 // faddp.4s	v6, v6, v6
	WORD $0x7e30d8c6 // faddp.2s	s6, v6
	WORD $0xeb0800df // cmp	x6, x8
	BGE  BB0_27

BB0_26:
	WORD $0xbc6c7807 // ldr	s7, [x0, x12, lsl #2]
	WORD $0xbc6c7890 // ldr	s16, [x4, x12, lsl #2]
	WORD $0x1f1018e6 // fmadd	s6, s7, s16, s6
	WORD $0x9100058c // add	x12, x12, #1
	WORD $0xeb0c011f // cmp	x8, x12
	BNE  BB0_26

BB0_27:
	WORD $0x1e22c0c6 // fcvt	d6, s6
	WORD $0x1e662080 // fcmp	d4, d6
	BPL  BB0_30
	WORD $0x1e663884 // fsub	d4, d4, d6
	WORD $0x9e6701e7 // fmov	d7, x15
	WORD $0x1e672080 // fcmp	d4, d7
	BLE  BB0_33
	WORD $0xd2effe0c // mov	x12, #9218868437227405312       ; =0x7ff0000000000000
	WORD $0x9e670187 // fmov	d7, x12
	B    BB0_35

BB0_30:
	WORD $0x1e6438c6 // fsub	d6, d6, d4
	WORD $0x9e6701e7 // fmov	d7, x15
	WORD $0x1e6720c0 // fcmp	d6, d7
	BGT  BB0_19
	WORD $0x2f00e407 // movi	d7, #0000000000000000
	WORD $0x9e670210 // fmov	d16, x16
	WORD $0x1e7020c0 // fcmp	d6, d16
	BMI  BB0_20
	WORD $0x9e670287 // fmov	d7, x20
	WORD $0x1e6708c7 // fmul	d7, d6, d7
	WORD $0x1e6640f0 // frinta	d16, d7
	WORD $0x9e6702b1 // fmov	d17, x21
	WORD $0x1f511a06 // fmadd	d6, d16, d17, d6
	WORD $0xd2878d8c // mov	x12, #15468                     ; =0x3c6c
	WORD $0xf2a6af2c // movk	x12, #13689, lsl #16
	WORD $0xf2c73dec // movk	x12, #14831, lsl #32
	WORD $0xf2f7bd4c // movk	x12, #48618, lsl #48
	WORD $0x9e670191 // fmov	d17, x12
	WORD $0x1f511a06 // fmadd	d6, d16, d17, d6
	WORD $0xd2889c8c // mov	x12, #17636                     ; =0x44e4
	WORD $0xf2acfeac // movk	x12, #26613, lsl #16
	WORD $0xf2dcc8ac // movk	x12, #58949, lsl #32
	WORD $0xf2e7cb4c // movk	x12, #15962, lsl #48
	WORD $0x9e670190 // fmov	d16, x12
	WORD $0xd29b130c // mov	x12, #55448                     ; =0xd898
	WORD $0xf2bdff0c // movk	x12, #61432, lsl #16
	WORD $0xf2dddb0c // movk	x12, #61144, lsl #32
	WORD $0xf2e7c42c // movk	x12, #15905, lsl #48
	WORD $0x9e670191 // fmov	d17, x12
	WORD $0x1f5140d0 // fmadd	d16, d6, d17, d16
	WORD $0xd293eb8c // mov	x12, #40796                     ; =0x9f5c
	WORD $0xf2b6ef0c // movk	x12, #46968, lsl #16
	WORD $0xf2cfc9ec // movk	x12, #32335, lsl #32
	WORD $0xf2e7d24c // movk	x12, #16018, lsl #48
	WORD $0x9e670191 // fmov	d17, x12
	WORD $0x1f464610 // fmadd	d16, d16, d6, d17
	WORD $0xd298e68c // mov	x12, #50996                     ; =0xc734
	WORD $0xf2b4aacc // movk	x12, #42326, lsl #16
	WORD $0xf2c3bc6c // movk	x12, #7651, lsl #32
	WORD $0xf2e7d8ec // movk	x12, #16071, lsl #48
	WORD $0x9e670191 // fmov	d17, x12
	WORD $0x1f464610 // fmadd	d16, d16, d6, d17
	WORD $0xd294034c // mov	x12, #40986                     ; =0xa01a
	WORD $0xf2a3402c // movk	x12, #6657, lsl #16
	WORD $0xf2c0340c // movk	x12, #416, lsl #32
	WORD $0xf2e7df4c // movk	x12, #16122, lsl #48
	WORD $0x9e670191 // fmov	d17, x12
	WORD $0x1f464610 // fmadd	d16, d16, d6, d17
	WORD $0x9e6702d1 // fmov	d17, x22
	WORD $0x1f464610 // fmadd	d16, d16, d6, d17
	WORD $0x9e6702f1 // fmov	d17, x23
	WORD $0x1f464610 // fmadd	d16, d16, d6, d17
	WORD $0x9e670311 // fmov	d17, x24
	WORD $0x1f464610 // fmadd	d16, d16, d6, d17
	WORD $0x9e670331 // fmov	d17, x25
	WORD $0x1f464610 // fmadd	d16, d16, d6, d17
	WORD $0x9e6703d1 // fmov	d17, x30
	WORD $0x1f464610 // fmadd	d16, d16, d6, d17
	WORD $0x1f460a10 // fmadd	d16, d16, d6, d2
	WORD $0x1f460210 // fmadd	d16, d16, d6, d0
	WORD $0x1f460206 // fmadd	d6, d16, d6, d0
	WORD $0x9e6400ec // fcvtas	x12, d7
	WORD $0x8b0cd1cc // add	x12, x14, x12, lsl #52
	WORD $0x9e670187 // fmov	d7, x12
	WORD $0x1e6708c7 // fmul	d7, d6, d7
	B    BB0_20

BB0_33:
	WORD $0x2f00e407 // movi	d7, #0000000000000000
	WORD $0x9e670210 // fmov	d16, x16
	WORD $0x1e702080 // fcmp	d4, d16
	BMI  BB0_35
	WORD $0x9e670287 // fmov	d7, x20
	WORD $0x1e670887 // fmul	d7, d4, d7
	WORD $0x1e6640f0 // frinta	d16, d7
	WORD $0x9e6702b1 // fmov	d17, x21
	WORD $0x1f511204 // fmadd	d4, d16, d17, d4
	WORD $0xd2878d8c // mov	x12, #15468                     ; =0x3c6c
	WORD $0xf2a6af2c // movk	x12, #13689, lsl #16
	WORD $0xf2c73dec // movk	x12, #14831, lsl #32
	WORD $0xf2f7bd4c // movk	x12, #48618, lsl #48
	WORD $0x9e670191 // fmov	d17, x12
	WORD $0x1f511204 // fmadd	d4, d16, d17, d4
	WORD $0xd2889c8c // mov	x12, #17636                     ; =0x44e4
	WORD $0xf2acfeac // movk	x12, #26613, lsl #16
	WORD $0xf2dcc8ac // movk	x12, #58949, lsl #32
	WORD $0xf2e7cb4c // movk	x12, #15962, lsl #48
	WORD $0x9e670190 // fmov	d16, x12
	WORD $0xd29b130c // mov	x12, #55448                     ; =0xd898
	WORD $0xf2bdff0c // movk	x12, #61432, lsl #16
	WORD $0xf2dddb0c // movk	x12, #61144, lsl #32
	WORD $0xf2e7c42c // movk	x12, #15905, lsl #48
	WORD $0x9e670191 // fmov	d17, x12
	WORD $0x1f514090 // fmadd	d16, d4, d17, d16
	WORD $0xd293eb8c // mov	x12, #40796                     ; =0x9f5c
	WORD $0xf2b6ef0c // movk	x12, #46968, lsl #16
	WORD $0xf2cfc9ec // movk	x12, #32335, lsl #32
	WORD $0xf2e7d24c // movk	x12, #16018, lsl #48
	WORD $0x9e670191 // fmov	d17, x12
	WORD $0x1f444610 // fmadd	d16, d16, d4, d17
	WORD $0xd298e68c // mov	x12, #50996                     ; =0xc734
	WORD $0xf2b4aacc // movk	x12, #42326, lsl #16
	WORD $0xf2c3bc6c // movk	x12, #7651, lsl #32
	WORD $0xf2e7d8ec // movk	x12, #16071, lsl #48
	WORD $0x9e670191 // fmov	d17, x12
	WORD $0x1f444610 // fmadd	d16, d16, d4, d17
	WORD $0xd294034c // mov	x12, #40986                     ; =0xa01a
	WORD $0xf2a3402c // movk	x12, #6657, lsl #16
	WORD $0xf2c0340c // movk	x12, #416, lsl #32
	WORD $0xf2e7df4c // movk	x12, #16122, lsl #48
	WORD $0x9e670191 // fmov	d17, x12
	WORD $0x1f444610 // fmadd	d16, d16, d4, d17
	WORD $0x9e6702d1 // fmov	d17, x22
	WORD $0x1f444610 // fmadd	d16, d16, d4, d17
	WORD $0x9e6702f1 // fmov	d17, x23
	WORD $0x1f444610 // fmadd	d16, d16, d4, d17
	WORD $0x9e670311 // fmov	d17, x24
	WORD $0x1f444610 // fmadd	d16, d16, d4, d17
	WORD $0x9e670331 // fmov	d17, x25
	WORD $0x1f444610 // fmadd	d16, d16, d4, d17
	WORD $0x9e6703d1 // fmov	d17, x30
	WORD $0x1f444610 // fmadd	d16, d16, d4, d17
	WORD $0x1f440a10 // fmadd	d16, d16, d4, d2
	WORD $0x1f440210 // fmadd	d16, d16, d4, d0
	WORD $0x1f440204 // fmadd	d4, d16, d4, d0
	WORD $0x9e6400ec // fcvtas	x12, d7
	WORD $0x8b0cd1cc // add	x12, x14, x12, lsl #52
	WORD $0x9e670187 // fmov	d7, x12
	WORD $0x1e670887 // fmul	d7, d4, d7

BB0_35:
	WORD $0x1f4700a5 // fmadd	d5, d5, d7, d0
	WORD $0x1e6040c4 // fmov	d4, d6
	WORD $0x910004a5 // add	x5, x5, #1
	WORD $0x8b0d0084 // add	x4, x4, x13
	WORD $0xeb0a00bf // cmp	x5, x10
	BNE  BB0_21

BB0_36:
	WORD $0x9e6600a4 // fmov	x4, d5
	WORD $0x1e6040c4 // fmov	d4, d6
	WORD $0xaa1403f5 // mov	x21, x20
	WORD $0x9b117d11 // mul	x17, x8, x17
	WORD $0xf100111f // cmp	x8, #4
	BLT  BB0_41

BB0_37:
	WORD $0xd2800013 // mov	x19, #0                         ; =0x0
	WORD $0x8b11082c // add	x12, x1, x17, lsl #2
	WORD $0xaa0703e3 // mov	x3, x7

BB0_38:
	WORD $0x3cc10585 // ldr	q5, [x12], #16
	WORD $0x6ea0f8a5 // fneg.4s	v5, v5
	WORD $0x4f8190a5 // fmul.4s	v5, v5, v1[0]
	WORD $0x3c810465 // str	q5, [x3], #16
	WORD $0x91001265 // add	x5, x19, #4
	WORD $0x91002274 // add	x20, x19, #8
	WORD $0xaa0503f3 // mov	x19, x5
	WORD $0xeb08029f // cmp	x20, x8
	BLE  BB0_38
	WORD $0xeb0800bf // cmp	x5, x8
	BLT  BB0_42
	B    BB0_44

BB0_40:
	WORD $0xd2e7fe04 // mov	x4, #4607182418800017408        ; =0x3ff0000000000000
	WORD $0xaa1403f5 // mov	x21, x20
	WORD $0x9b117d11 // mul	x17, x8, x17
	WORD $0xf100111f // cmp	x8, #4
	BGE  BB0_37

BB0_41:
	WORD $0xd2800005 // mov	x5, #0                          ; =0x0
	WORD $0xeb0800bf // cmp	x5, x8
	BGE  BB0_44

BB0_42:
	WORD $0x8b11082c // add	x12, x1, x17, lsl #2

BB0_43:
	WORD $0xbc657985 // ldr	s5, [x12, x5, lsl #2]
	WORD $0x1e2188a5 // fnmul	s5, s5, s1
	WORD $0xbc2578e5 // str	s5, [x7, x5, lsl #2]
	WORD $0x910004a5 // add	x5, x5, #1
	WORD $0xeb05011f // cmp	x8, x5
	BNE  BB0_43

BB0_44:
	WORD $0xf100055f // cmp	x10, #1
	WORD $0xaa1503f4 // mov	x20, x21
	WORD $0xd2bfdc15 // mov	x21, #4276092928                ; =0xfee00000
	WORD $0xf2c5c855 // movk	x21, #11842, lsl #32
	WORD $0xf2f7fcd5 // movk	x21, #49126, lsl #48
	BLT  BB0_5
	WORD $0xd2800011 // mov	x17, #0                         ; =0x0
	WORD $0xd374f88c // ubfx	x12, x4, #52, #11
	WORD $0xd10ffd8c // sub	x12, x12, #1023
	WORD $0x9e620185 // scvtf	d5, x12
	WORD $0xd2e7fe0c // mov	x12, #4607182418800017408       ; =0x3ff0000000000000
	WORD $0xb340cc8c // bfxil	x12, x4, #0, #52
	WORD $0x9e670186 // fmov	d6, x12
	WORD $0x1e6328c6 // fadd	d6, d6, d3
	WORD $0xd289634c // mov	x12, #19226                     ; =0x4b1a
	WORD $0xf2a4ce4c // movk	x12, #9842, lsl #16
	WORD $0xf2de290c // movk	x12, #61768, lsl #32
	WORD $0xf2f7f8cc // movk	x12, #49094, lsl #48
	WORD $0x9e670187 // fmov	d7, x12
	WORD $0xd2819fac // mov	x12, #3325                      ; =0xcfd
	WORD $0xf2bd3e4c // movk	x12, #59890, lsl #16
	WORD $0xf2c02bec // movk	x12, #351, lsl #32
	WORD $0xf2e7f86c // movk	x12, #16323, lsl #48
	WORD $0x9e670190 // fmov	d16, x12
	WORD $0x1f501cc7 // fmadd	d7, d6, d16, d7
	WORD $0xd29ea90c // mov	x12, #62792                     ; =0xf548
	WORD $0xf2b5748c // movk	x12, #43940, lsl #16
	WORD $0xf2c9f6ec // movk	x12, #20407, lsl #32
	WORD $0xf2e7f98c // movk	x12, #16332, lsl #48
	WORD $0x9e670190 // fmov	d16, x12
	WORD $0x1f4640e7 // fmadd	d7, d7, d6, d16
	WORD $0xd286e9cc // mov	x12, #14158                     ; =0x374e
	WORD $0xf2b248ac // movk	x12, #37445, lsl #16
	WORD $0xf2c9248c // movk	x12, #18724, lsl #32
	WORD $0xf2f7fa4c // movk	x12, #49106, lsl #48
	WORD $0x9e670190 // fmov	d16, x12
	WORD $0x1f4640e7 // fmadd	d7, d7, d6, d16
	WORD $0xd283974c // mov	x12, #7354                      ; =0x1cba
	WORD $0xf2b32fcc // movk	x12, #39294, lsl #16
	WORD $0xf2d3332c // movk	x12, #39321, lsl #32
	WORD $0xf2e7fb2c // movk	x12, #16345, lsl #48
	WORD $0x9e670190 // fmov	d16, x12
	WORD $0x1f4640e7 // fmadd	d7, d7, d6, d16
	WORD $0x928f9bec // mov	x12, #-31968                    ; =0xffffffffffff8320
	WORD $0xf2bffc8c // movk	x12, #65508, lsl #16
	WORD $0xf2f7fbec // movk	x12, #49119, lsl #48
	WORD $0x9e670190 // fmov	d16, x12
	WORD $0x1f4640e7 // fmadd	d7, d7, d6, d16
	WORD $0x9297cdec // mov	x12, #-48752                    ; =0xffffffffffff4190
	WORD $0xf2bffe4c // movk	x12, #65522, lsl #16
	WORD $0xf2e7fdec // movk	x12, #16367, lsl #48
	WORD $0x9e670190 // fmov	d16, x12
	WORD $0x1f4640e7 // fmadd	d7, d7, d6, d16
	WORD $0x1e6708c6 // fmul	d6, d6, d7
	WORD $0xd2873dec // mov	x12, #14831                     ; =0x39ef
	WORD $0xf2bfdf4c // movk	x12, #65274, lsl #16
	WORD $0xf2c5c84c // movk	x12, #11842, lsl #32
	WORD $0xf2e7fccc // movk	x12, #16358, lsl #48
	WORD $0x9e670187 // fmov	d7, x12
	WORD $0x1f4718a5 // fmadd	d5, d5, d7, d6
	WORD $0x1e652884 // fadd	d4, d4, d5
	WORD $0xaa0103e4 // mov	x4, x1
	B    BB0_47

BB0_46:
	WORD $0x91000631 // add	x17, x17, #1
	WORD $0x8b0d0084 // add	x4, x4, x13
	WORD $0xeb0a023f // cmp	x17, x10
	BEQ  BB0_5

BB0_47:
	WORD $0xf100111f // cmp	x8, #4
	BGE  BB0_49
	WORD $0xd280000c // mov	x12, #0                         ; =0x0
	WORD $0x6f00e405 // movi.2d	v5, #0000000000000000
	WORD $0x6e25d4a5 // faddp.4s	v5, v5, v5
	WORD $0x7e30d8a5 // faddp.2s	s5, v5
	WORD $0xeb08019f // cmp	x12, x8
	BLT  BB0_52
	B    BB0_53

BB0_49:
	WORD $0xd280000c // mov	x12, #0                         ; =0x0
	WORD $0x6f00e405 // movi.2d	v5, #0000000000000000
	WORD $0x52800083 // mov	w3, #4                          ; =0x4

BB0_50:
	WORD $0x3cec6806 // ldr	q6, [x0, x12]
	WORD $0x3cec6887 // ldr	q7, [x4, x12]
	WORD $0x4e26cce5 // fmla.4s	v5, v7, v6
	WORD $0x91001063 // add	x3, x3, #4
	WORD $0x9100418c // add	x12, x12, #16
	WORD $0xeb08007f // cmp	x3, x8
	BLE  BB0_50
	WORD $0xaa0603ec // mov	x12, x6
	WORD $0x6e25d4a5 // faddp.4s	v5, v5, v5
	WORD $0x7e30d8a5 // faddp.2s	s5, v5
	WORD $0xeb0800df // cmp	x6, x8
	BGE  BB0_53

BB0_52:
	WORD $0xbc6c7806 // ldr	s6, [x0, x12, lsl #2]
	WORD $0xbc6c7887 // ldr	s7, [x4, x12, lsl #2]
	WORD $0x1f0714c5 // fmadd	s5, s6, s7, s5
	WORD $0x9100058c // add	x12, x12, #1
	WORD $0xeb0c011f // cmp	x8, x12
	BNE  BB0_52

BB0_53:
	WORD $0x1e22c0a5 // fcvt	d5, s5
	WORD $0x1e6438a5 // fsub	d5, d5, d4
	WORD $0x9e6701e6 // fmov	d6, x15
	WORD $0x1e6620a0 // fcmp	d5, d6
	BLE  BB0_55
	WORD $0x52aff00c // mov	w12, #2139095040                ; =0x7f800000
	WORD $0x1e270186 // fmov	s6, w12
	B    BB0_57

BB0_55:
	WORD $0x2f00e406 // movi	d6, #0000000000000000
	WORD $0x9e670207 // fmov	d7, x16
	WORD $0x1e6720a0 // fcmp	d5, d7
	BMI  BB0_57
	WORD $0x9e670286 // fmov	d6, x20
	WORD $0x1e6608a6 // fmul	d6, d5, d6
	WORD $0x1e6640c7 // frinta	d7, d6
	WORD $0x9e6702b0 // fmov	d16, x21
	WORD $0x1f5014e5 // fmadd	d5, d7, d16, d5
	WORD $0xd2878d8c // mov	x12, #15468                     ; =0x3c6c
	WORD $0xf2a6af2c // movk	x12, #13689, lsl #16
	WORD $0xf2c73dec // movk	x12, #14831, lsl #32
	WORD $0xf2f7bd4c // movk	x12, #48618, lsl #48
	WORD $0x9e670190 // fmov	d16, x12
	WORD $0x1f5014e5 // fmadd	d5, d7, d16, d5
	WORD $0xd2889c8c // mov	x12, #17636                     ; =0x44e4
	WORD $0xf2acfeac // movk	x12, #26613, lsl #16
	WORD $0xf2dcc8ac // movk	x12, #58949, lsl #32
	WORD $0xf2e7cb4c // movk	x12, #15962, lsl #48
	WORD $0x9e670187 // fmov	d7, x12
	WORD $0xd29b130c // mov	x12, #55448                     ; =0xd898
	WORD $0xf2bdff0c // movk	x12, #61432, lsl #16
	WORD $0xf2dddb0c // movk	x12, #61144, lsl #32
	WORD $0xf2e7c42c // movk	x12, #15905, lsl #48
	WORD $0x9e670190 // fmov	d16, x12
	WORD $0x1f501ca7 // fmadd	d7, d5, d16, d7
	WORD $0xd293eb8c // mov	x12, #40796                     ; =0x9f5c
	WORD $0xf2b6ef0c // movk	x12, #46968, lsl #16
	WORD $0xf2cfc9ec // movk	x12, #32335, lsl #32
	WORD $0xf2e7d24c // movk	x12, #16018, lsl #48
	WORD $0x9e670190 // fmov	d16, x12
	WORD $0x1f4540e7 // fmadd	d7, d7, d5, d16
	WORD $0xd298e68c // mov	x12, #50996                     ; =0xc734
	WORD $0xf2b4aacc // movk	x12, #42326, lsl #16
	WORD $0xf2c3bc6c // movk	x12, #7651, lsl #32
	WORD $0xf2e7d8ec // movk	x12, #16071, lsl #48
	WORD $0x9e670190 // fmov	d16, x12
	WORD $0x1f4540e7 // fmadd	d7, d7, d5, d16
	WORD $0xd294034c // mov	x12, #40986                     ; =0xa01a
	WORD $0xf2a3402c // movk	x12, #6657, lsl #16
	WORD $0xf2c0340c // movk	x12, #416, lsl #32
	WORD $0xf2e7df4c // movk	x12, #16122, lsl #48
	WORD $0x9e670190 // fmov	d16, x12
	WORD $0x1f4540e7 // fmadd	d7, d7, d5, d16
	WORD $0x9e6702d0 // fmov	d16, x22
	WORD $0x1f4540e7 // fmadd	d7, d7, d5, d16
	WORD $0x9e6702f0 // fmov	d16, x23
	WORD $0x1f4540e7 // fmadd	d7, d7, d5, d16
	WORD $0x9e670310 // fmov	d16, x24
	WORD $0x1f4540e7 // fmadd	d7, d7, d5, d16
	WORD $0x9e670330 // fmov	d16, x25
	WORD $0x1f4540e7 // fmadd	d7, d7, d5, d16
	WORD $0x9e6703d0 // fmov	d16, x30
	WORD $0x1f4540e7 // fmadd	d7, d7, d5, d16
	WORD $0x1f4508e7 // fmadd	d7, d7, d5, d2
	WORD $0x1f4500e7 // fmadd	d7, d7, d5, d0
	WORD $0x1f4500e5 // fmadd	d5, d7, d5, d0
	WORD $0x9e6400cc // fcvtas	x12, d6
	WORD $0x8b0cd1cc // add	x12, x14, x12, lsl #52
	WORD $0x9e670186 // fmov	d6, x12
	WORD $0x1e6608a5 // fmul	d5, d5, d6
	WORD $0x1e6240a6 // fcvt	s6, d5

BB0_57:
	WORD $0x1e2108c5 // fmul	s5, s6, s1
	WORD $0xf100111f // cmp	x8, #4
	BGE  BB0_59
	WORD $0xd280000c // mov	x12, #0                         ; =0x0
	B    BB0_61

BB0_59:
	WORD $0xd2800003 // mov	x3, #0                          ; =0x0
	WORD $0xd2800005 // mov	x5, #0                          ; =0x0

BB0_60:
	WORD $0x3ce368e6 // ldr	q6, [x7, x3]
	WORD $0x3ce36887 // ldr	q7, [x4, x3]
	WORD $0x4f8510e6 // fmla.4s	v6, v7, v5[0]
	WORD $0x3ca368e6 // str	q6, [x7, x3]
	WORD $0x910010ac // add	x12, x5, #4
	WORD $0x910020b3 // add	x19, x5, #8
	WORD $0x91004063 // add	x3, x3, #16
	WORD $0xaa0c03e5 // mov	x5, x12
	WORD $0xeb08027f // cmp	x19, x8
	BLE  BB0_60

BB0_61:
	WORD $0xeb08019f // cmp	x12, x8
	BGE  BB0_46

BB0_62:
	WORD $0xbc6c7886 // ldr	s6, [x4, x12, lsl #2]
	WORD $0xbc6c78e7 // ldr	s7, [x7, x12, lsl #2]
	WORD $0x1f061ca6 // fmadd	s6, s5, s6, s7
	WORD $0xbc2c78e6 // str	s6, [x7, x12, lsl #2]
	WORD $0x9100058c // add	x12, x12, #1
	WORD $0xeb0c011f // cmp	x8, x12
	BNE  BB0_62
	B    BB0_46

BB0_63:
	WORD $0xa9447bfd // ldp	x29, x30, [sp, #64]             ; 16-byte Folded Reload
	WORD $0xa9434ff4 // ldp	x20, x19, [sp, #48]             ; 16-byte Folded Reload
	WORD $0xa94257f6 // ldp	x22, x21, [sp, #32]             ; 16-byte Folded Reload
	WORD $0xa9415ff8 // ldp	x24, x23, [sp, #16]             ; 16-byte Folded Reload
	WORD $0xf84003f9 // ldr	x25, [sp], #80                  ; 8-byte Folded Reload [transformed]

BB0_64:
	RET
