// Code generated by github.com/ajroetker/go-highway/cmd/hwygen. DO NOT EDIT.

//go:build amd64 && goexperiment.simd

package wavelet

import (
	"simd/archsimd"

	"github.com/ajroetker/go-highway/hwy"
)

var LiftUpdate53Int32 func(target []int32, tLen int, neighbor []int32, nLen int, phase int)
var LiftUpdate53Int64 func(target []int64, tLen int, neighbor []int64, nLen int, phase int)
var LiftPredict53Int32 func(target []int32, tLen int, neighbor []int32, nLen int, phase int)
var LiftPredict53Int64 func(target []int64, tLen int, neighbor []int64, nLen int, phase int)
var LiftStep97Float16 func(target []hwy.Float16, tLen int, neighbor []hwy.Float16, nLen int, coeff hwy.Float16, phase int)
var LiftStep97BFloat16 func(target []hwy.BFloat16, tLen int, neighbor []hwy.BFloat16, nLen int, coeff hwy.BFloat16, phase int)
var LiftStep97Float32 func(target []float32, tLen int, neighbor []float32, nLen int, coeff float32, phase int)
var LiftStep97Float64 func(target []float64, tLen int, neighbor []float64, nLen int, coeff float64, phase int)
var ScaleSliceFloat16 func(data []hwy.Float16, n int, scale hwy.Float16)
var ScaleSliceBFloat16 func(data []hwy.BFloat16, n int, scale hwy.BFloat16)
var ScaleSliceFloat32 func(data []float32, n int, scale float32)
var ScaleSliceFloat64 func(data []float64, n int, scale float64)
var InterleaveFloat32 func(dst []float32, low []float32, sn int, high []float32, dn int, phase int)
var InterleaveFloat64 func(dst []float64, low []float64, sn int, high []float64, dn int, phase int)
var InterleaveInt32 func(dst []int32, low []int32, sn int, high []int32, dn int, phase int)
var InterleaveInt64 func(dst []int64, low []int64, sn int, high []int64, dn int, phase int)
var InterleaveUint32 func(dst []uint32, low []uint32, sn int, high []uint32, dn int, phase int)
var InterleaveUint64 func(dst []uint64, low []uint64, sn int, high []uint64, dn int, phase int)
var Synthesize53CoreInt32 func(data []int32, n int, low []int32, sn int, high []int32, dn int, phase int)
var Synthesize53CoreInt64 func(data []int64, n int, low []int64, sn int, high []int64, dn int, phase int)
var Synthesize53CoreColsInt32 func(colBuf []int32, height int, lowBuf []int32, sn int, highBuf []int32, dn int, phase int)
var Synthesize53CoreColsInt64 func(colBuf []int64, height int, lowBuf []int64, sn int, highBuf []int64, dn int, phase int)
var DeinterleaveFloat32 func(src []float32, low []float32, sn int, high []float32, dn int, phase int)
var DeinterleaveFloat64 func(src []float64, low []float64, sn int, high []float64, dn int, phase int)
var DeinterleaveInt32 func(src []int32, low []int32, sn int, high []int32, dn int, phase int)
var DeinterleaveInt64 func(src []int64, low []int64, sn int, high []int64, dn int, phase int)
var DeinterleaveUint32 func(src []uint32, low []uint32, sn int, high []uint32, dn int, phase int)
var DeinterleaveUint64 func(src []uint64, low []uint64, sn int, high []uint64, dn int, phase int)

// LiftUpdate53 applies the 5/3 update step: target[i] -= (neighbor[i+off1] + neighbor[i+off2] + 2) >> 2
// This is used for the update step in 5/3 synthesis and the predict step in analysis.
// The phase parameter determines the offset pattern for neighbor access.
//
// This function dispatches to the appropriate SIMD implementation at runtime.
func LiftUpdate53[T hwy.SignedInts](target []T, tLen int, neighbor []T, nLen int, phase int) {
	switch any(target).(type) {
	case []int32:
		LiftUpdate53Int32(any(target).([]int32), tLen, any(neighbor).([]int32), nLen, phase)
	case []int64:
		LiftUpdate53Int64(any(target).([]int64), tLen, any(neighbor).([]int64), nLen, phase)
	}
}

// LiftPredict53 applies the 5/3 predict step: target[i] += (neighbor[i+off1] + neighbor[i+off2]) >> 1
// This is used for the predict step in 5/3 synthesis and the update step in analysis.
//
// This function dispatches to the appropriate SIMD implementation at runtime.
func LiftPredict53[T hwy.SignedInts](target []T, tLen int, neighbor []T, nLen int, phase int) {
	switch any(target).(type) {
	case []int32:
		LiftPredict53Int32(any(target).([]int32), tLen, any(neighbor).([]int32), nLen, phase)
	case []int64:
		LiftPredict53Int64(any(target).([]int64), tLen, any(neighbor).([]int64), nLen, phase)
	}
}

// LiftStep97 applies a generic 9/7 lifting step: target[i] -= coeff * (neighbor[i+off1] + neighbor[i+off2])
// This is used for all four lifting steps in 9/7 transforms.
//
// This function dispatches to the appropriate SIMD implementation at runtime.
func LiftStep97[T hwy.Floats](target []T, tLen int, neighbor []T, nLen int, coeff T, phase int) {
	switch any(target).(type) {
	case []hwy.Float16:
		LiftStep97Float16(any(target).([]hwy.Float16), tLen, any(neighbor).([]hwy.Float16), nLen, any(coeff).(hwy.Float16), phase)
	case []hwy.BFloat16:
		LiftStep97BFloat16(any(target).([]hwy.BFloat16), tLen, any(neighbor).([]hwy.BFloat16), nLen, any(coeff).(hwy.BFloat16), phase)
	case []float32:
		LiftStep97Float32(any(target).([]float32), tLen, any(neighbor).([]float32), nLen, any(coeff).(float32), phase)
	case []float64:
		LiftStep97Float64(any(target).([]float64), tLen, any(neighbor).([]float64), nLen, any(coeff).(float64), phase)
	}
}

// ScaleSlice multiplies all elements by a scale factor: data[i] *= scale
//
// This function dispatches to the appropriate SIMD implementation at runtime.
func ScaleSlice[T hwy.Floats](data []T, n int, scale T) {
	switch any(data).(type) {
	case []hwy.Float16:
		ScaleSliceFloat16(any(data).([]hwy.Float16), n, any(scale).(hwy.Float16))
	case []hwy.BFloat16:
		ScaleSliceBFloat16(any(data).([]hwy.BFloat16), n, any(scale).(hwy.BFloat16))
	case []float32:
		ScaleSliceFloat32(any(data).([]float32), n, any(scale).(float32))
	case []float64:
		ScaleSliceFloat64(any(data).([]float64), n, any(scale).(float64))
	}
}

// Interleave interleaves low and high-pass coefficients into dst.
// phase=0: dst[2i]=low[i], dst[2i+1]=high[i]
// phase=1: dst[2i]=high[i], dst[2i+1]=low[i]
//
// This function dispatches to the appropriate SIMD implementation at runtime.
func Interleave[T hwy.Lanes](dst []T, low []T, sn int, high []T, dn int, phase int) {
	switch any(dst).(type) {
	case []float32:
		InterleaveFloat32(any(dst).([]float32), any(low).([]float32), sn, any(high).([]float32), dn, phase)
	case []float64:
		InterleaveFloat64(any(dst).([]float64), any(low).([]float64), sn, any(high).([]float64), dn, phase)
	case []int32:
		InterleaveInt32(any(dst).([]int32), any(low).([]int32), sn, any(high).([]int32), dn, phase)
	case []int64:
		InterleaveInt64(any(dst).([]int64), any(low).([]int64), sn, any(high).([]int64), dn, phase)
	case []uint32:
		InterleaveUint32(any(dst).([]uint32), any(low).([]uint32), sn, any(high).([]uint32), dn, phase)
	case []uint64:
		InterleaveUint64(any(dst).([]uint64), any(low).([]uint64), sn, any(high).([]uint64), dn, phase)
	}
}

// Synthesize53Core fuses copy + LiftUpdate53 + LiftPredict53 + Interleave
// into a single dispatch target, eliminating 2 indirect calls per 1D transform.
// data contains [low|high] on entry and interleaved samples on exit.
// low and high are scratch buffers with capacity >= sn and >= dn respectively.
//
// This function dispatches to the appropriate SIMD implementation at runtime.
func Synthesize53Core[T hwy.SignedInts](data []T, n int, low []T, sn int, high []T, dn int, phase int) {
	switch any(data).(type) {
	case []int32:
		Synthesize53CoreInt32(any(data).([]int32), n, any(low).([]int32), sn, any(high).([]int32), dn, phase)
	case []int64:
		Synthesize53CoreInt64(any(data).([]int64), n, any(low).([]int64), sn, any(high).([]int64), dn, phase)
	}
}

// Synthesize53CoreCols fuses copy + LiftUpdate53 + LiftPredict53 + Interleave
// for multiple columns processed in parallel via SIMD. The data layout is
// column-interleaved: colBuf[y*lanes + c] holds the value for row y, column c
// (where lanes = hwy.MaxLanes). Each SIMD load/store at colBuf[y*lanes:]
// touches all `lanes` columns for row y simultaneously.
//
// colBuf has height*lanes elements on entry ([low rows | high rows] interleaved
// by column) and contains the synthesized output on exit (interleaved rows).
// lowBuf and highBuf are scratch buffers with capacity >= sn*lanes and dn*lanes.
//
// This function dispatches to the appropriate SIMD implementation at runtime.
func Synthesize53CoreCols[T hwy.SignedInts](colBuf []T, height int, lowBuf []T, sn int, highBuf []T, dn int, phase int) {
	switch any(colBuf).(type) {
	case []int32:
		Synthesize53CoreColsInt32(any(colBuf).([]int32), height, any(lowBuf).([]int32), sn, any(highBuf).([]int32), dn, phase)
	case []int64:
		Synthesize53CoreColsInt64(any(colBuf).([]int64), height, any(lowBuf).([]int64), sn, any(highBuf).([]int64), dn, phase)
	}
}

// Deinterleave extracts low and high-pass coefficients from src.
// phase=0: low[i]=src[2i], high[i]=src[2i+1]
// phase=1: high[i]=src[2i], low[i]=src[2i+1]
//
// This function dispatches to the appropriate SIMD implementation at runtime.
func Deinterleave[T hwy.Lanes](src []T, low []T, sn int, high []T, dn int, phase int) {
	switch any(src).(type) {
	case []float32:
		DeinterleaveFloat32(any(src).([]float32), any(low).([]float32), sn, any(high).([]float32), dn, phase)
	case []float64:
		DeinterleaveFloat64(any(src).([]float64), any(low).([]float64), sn, any(high).([]float64), dn, phase)
	case []int32:
		DeinterleaveInt32(any(src).([]int32), any(low).([]int32), sn, any(high).([]int32), dn, phase)
	case []int64:
		DeinterleaveInt64(any(src).([]int64), any(low).([]int64), sn, any(high).([]int64), dn, phase)
	case []uint32:
		DeinterleaveUint32(any(src).([]uint32), any(low).([]uint32), sn, any(high).([]uint32), dn, phase)
	case []uint64:
		DeinterleaveUint64(any(src).([]uint64), any(low).([]uint64), sn, any(high).([]uint64), dn, phase)
	}
}

func init() {
	if hwy.NoSimdEnv() {
		initLiftingFallback()
		return
	}
	if archsimd.X86.AVX512() {
		initLiftingAVX512()
		return
	}
	if archsimd.X86.AVX2() {
		initLiftingAVX2()
		return
	}
	initLiftingFallback()
}

func initLiftingAVX2() {
	LiftUpdate53Int32 = BaseLiftUpdate53_avx2_Int32
	LiftUpdate53Int64 = BaseLiftUpdate53_avx2_Int64
	LiftPredict53Int32 = BaseLiftPredict53_avx2_Int32
	LiftPredict53Int64 = BaseLiftPredict53_avx2_Int64
	LiftStep97Float16 = BaseLiftStep97_avx2_Float16
	LiftStep97BFloat16 = BaseLiftStep97_avx2_BFloat16
	LiftStep97Float32 = BaseLiftStep97_avx2
	LiftStep97Float64 = BaseLiftStep97_avx2_Float64
	ScaleSliceFloat16 = BaseScaleSlice_avx2_Float16
	ScaleSliceBFloat16 = BaseScaleSlice_avx2_BFloat16
	ScaleSliceFloat32 = BaseScaleSlice_avx2
	ScaleSliceFloat64 = BaseScaleSlice_avx2_Float64
	InterleaveFloat32 = BaseInterleave_avx2
	InterleaveFloat64 = BaseInterleave_avx2_Float64
	InterleaveInt32 = BaseInterleave_avx2_Int32
	InterleaveInt64 = BaseInterleave_avx2_Int64
	InterleaveUint32 = BaseInterleave_avx2_Uint32
	InterleaveUint64 = BaseInterleave_avx2_Uint64
	Synthesize53CoreInt32 = BaseSynthesize53Core_avx2_Int32
	Synthesize53CoreInt64 = BaseSynthesize53Core_avx2_Int64
	Synthesize53CoreColsInt32 = BaseSynthesize53CoreCols_avx2_Int32
	Synthesize53CoreColsInt64 = BaseSynthesize53CoreCols_avx2_Int64
	DeinterleaveFloat32 = BaseDeinterleave_avx2
	DeinterleaveFloat64 = BaseDeinterleave_avx2_Float64
	DeinterleaveInt32 = BaseDeinterleave_avx2_Int32
	DeinterleaveInt64 = BaseDeinterleave_avx2_Int64
	DeinterleaveUint32 = BaseDeinterleave_avx2_Uint32
	DeinterleaveUint64 = BaseDeinterleave_avx2_Uint64
}

func initLiftingAVX512() {
	LiftUpdate53Int32 = BaseLiftUpdate53_avx512_Int32
	LiftUpdate53Int64 = BaseLiftUpdate53_avx512_Int64
	LiftPredict53Int32 = BaseLiftPredict53_avx512_Int32
	LiftPredict53Int64 = BaseLiftPredict53_avx512_Int64
	LiftStep97Float16 = BaseLiftStep97_avx512_Float16
	LiftStep97BFloat16 = BaseLiftStep97_avx512_BFloat16
	LiftStep97Float32 = BaseLiftStep97_avx512
	LiftStep97Float64 = BaseLiftStep97_avx512_Float64
	ScaleSliceFloat16 = BaseScaleSlice_avx512_Float16
	ScaleSliceBFloat16 = BaseScaleSlice_avx512_BFloat16
	ScaleSliceFloat32 = BaseScaleSlice_avx512
	ScaleSliceFloat64 = BaseScaleSlice_avx512_Float64
	InterleaveFloat32 = BaseInterleave_avx512
	InterleaveFloat64 = BaseInterleave_avx512_Float64
	InterleaveInt32 = BaseInterleave_avx512_Int32
	InterleaveInt64 = BaseInterleave_avx512_Int64
	InterleaveUint32 = BaseInterleave_avx512_Uint32
	InterleaveUint64 = BaseInterleave_avx512_Uint64
	Synthesize53CoreInt32 = BaseSynthesize53Core_avx512_Int32
	Synthesize53CoreInt64 = BaseSynthesize53Core_avx512_Int64
	Synthesize53CoreColsInt32 = BaseSynthesize53CoreCols_avx512_Int32
	Synthesize53CoreColsInt64 = BaseSynthesize53CoreCols_avx512_Int64
	DeinterleaveFloat32 = BaseDeinterleave_avx512
	DeinterleaveFloat64 = BaseDeinterleave_avx512_Float64
	DeinterleaveInt32 = BaseDeinterleave_avx512_Int32
	DeinterleaveInt64 = BaseDeinterleave_avx512_Int64
	DeinterleaveUint32 = BaseDeinterleave_avx512_Uint32
	DeinterleaveUint64 = BaseDeinterleave_avx512_Uint64
}

func initLiftingFallback() {
	LiftUpdate53Int32 = BaseLiftUpdate53_fallback_Int32
	LiftUpdate53Int64 = BaseLiftUpdate53_fallback_Int64
	LiftPredict53Int32 = BaseLiftPredict53_fallback_Int32
	LiftPredict53Int64 = BaseLiftPredict53_fallback_Int64
	LiftStep97Float16 = BaseLiftStep97_fallback_Float16
	LiftStep97BFloat16 = BaseLiftStep97_fallback_BFloat16
	LiftStep97Float32 = BaseLiftStep97_fallback
	LiftStep97Float64 = BaseLiftStep97_fallback_Float64
	ScaleSliceFloat16 = BaseScaleSlice_fallback_Float16
	ScaleSliceBFloat16 = BaseScaleSlice_fallback_BFloat16
	ScaleSliceFloat32 = BaseScaleSlice_fallback
	ScaleSliceFloat64 = BaseScaleSlice_fallback_Float64
	InterleaveFloat32 = BaseInterleave_fallback
	InterleaveFloat64 = BaseInterleave_fallback_Float64
	InterleaveInt32 = BaseInterleave_fallback_Int32
	InterleaveInt64 = BaseInterleave_fallback_Int64
	InterleaveUint32 = BaseInterleave_fallback_Uint32
	InterleaveUint64 = BaseInterleave_fallback_Uint64
	Synthesize53CoreInt32 = BaseSynthesize53Core_fallback_Int32
	Synthesize53CoreInt64 = BaseSynthesize53Core_fallback_Int64
	Synthesize53CoreColsInt32 = BaseSynthesize53CoreCols_fallback_Int32
	Synthesize53CoreColsInt64 = BaseSynthesize53CoreCols_fallback_Int64
	DeinterleaveFloat32 = BaseDeinterleave_fallback
	DeinterleaveFloat64 = BaseDeinterleave_fallback_Float64
	DeinterleaveInt32 = BaseDeinterleave_fallback_Int32
	DeinterleaveInt64 = BaseDeinterleave_fallback_Int64
	DeinterleaveUint32 = BaseDeinterleave_fallback_Uint32
	DeinterleaveUint64 = BaseDeinterleave_fallback_Uint64
}
