//go:build !noasm && amd64

// AVX-512 Matrix-Vector Multiplication for AMD64
// Uses AVX-512 SIMD instructions for efficient matvec.
// Requires AVX-512 FP16 (Sapphire Rapids+) for native f16 and
// AVX-512 BF16 (Cooper Lake+) for native bf16.
package asm

import (
	"unsafe"

	"github.com/ajroetker/go-highway/hwy"
)

// AVX-512 with FP16 and BF16 extensions
//go:generate go tool goat ../c/matvec_avx512_amd64.c -O3 --target amd64 -m avx512f -m avx512fp16 -m avx512bf16 -m avx512vl

// ============================================================================
// AVX-512 Matrix-Vector Multiplication
// ============================================================================

// MatVecAVX512F16 performs matrix-vector multiplication using AVX-512 FP16: result = M * v
// Uses native AVX-512 FP16 arithmetic (Intel Sapphire Rapids, AMD Zen5+).
// M is rows x cols (row-major), v is the input vector (cols elements),
// result is the output vector (rows elements).
//
// Parameters:
//   - m: rows x cols matrix (row-major)
//   - v: input vector (cols elements)
//   - result: output vector (rows elements)
//   - rows, cols: matrix dimensions
func MatVecAVX512F16(m []hwy.Float16, v []hwy.Float16, result []hwy.Float16, rows, cols int) {
	if rows == 0 || cols == 0 {
		return
	}
	if len(m) < rows*cols || len(v) < cols || len(result) < rows {
		return
	}
	rowsVal := int64(rows)
	colsVal := int64(cols)
	matvec_avx512_f16(
		unsafe.Pointer(&m[0]),
		unsafe.Pointer(&v[0]),
		unsafe.Pointer(&result[0]),
		unsafe.Pointer(&rowsVal),
		unsafe.Pointer(&colsVal),
	)
}

// MatVecAVX512BF16 performs matrix-vector multiplication using AVX-512 BF16: result = M * v
// Uses VDPBF16PS for bf16 dot product accumulate (Intel Cooper Lake, AMD Zen4+).
// M is rows x cols (row-major), v is the input vector (cols elements),
// result is the output vector (rows elements).
//
// Parameters:
//   - m: rows x cols matrix (row-major)
//   - v: input vector (cols elements)
//   - result: output vector (rows elements)
//   - rows, cols: matrix dimensions
func MatVecAVX512BF16(m []hwy.BFloat16, v []hwy.BFloat16, result []hwy.BFloat16, rows, cols int) {
	if rows == 0 || cols == 0 {
		return
	}
	if len(m) < rows*cols || len(v) < cols || len(result) < rows {
		return
	}
	rowsVal := int64(rows)
	colsVal := int64(cols)
	matvec_avx512_bf16(
		unsafe.Pointer(&m[0]),
		unsafe.Pointer(&v[0]),
		unsafe.Pointer(&result[0]),
		unsafe.Pointer(&rowsVal),
		unsafe.Pointer(&colsVal),
	)
}

// MatVecAVX512F32 performs matrix-vector multiplication using AVX-512: result = M * v
// M is rows x cols (row-major), v is the input vector (cols elements),
// result is the output vector (rows elements).
//
// Parameters:
//   - m: rows x cols matrix (row-major)
//   - v: input vector (cols elements)
//   - result: output vector (rows elements)
//   - rows, cols: matrix dimensions
func MatVecAVX512F32(m []float32, v []float32, result []float32, rows, cols int) {
	if rows == 0 || cols == 0 {
		return
	}
	if len(m) < rows*cols || len(v) < cols || len(result) < rows {
		return
	}
	rowsVal := int64(rows)
	colsVal := int64(cols)
	matvec_avx512_f32(
		unsafe.Pointer(&m[0]),
		unsafe.Pointer(&v[0]),
		unsafe.Pointer(&result[0]),
		unsafe.Pointer(&rowsVal),
		unsafe.Pointer(&colsVal),
	)
}

// MatVecAVX512F64 performs matrix-vector multiplication using AVX-512: result = M * v
// M is rows x cols (row-major), v is the input vector (cols elements),
// result is the output vector (rows elements).
//
// Parameters:
//   - m: rows x cols matrix (row-major)
//   - v: input vector (cols elements)
//   - result: output vector (rows elements)
//   - rows, cols: matrix dimensions
func MatVecAVX512F64(m []float64, v []float64, result []float64, rows, cols int) {
	if rows == 0 || cols == 0 {
		return
	}
	if len(m) < rows*cols || len(v) < cols || len(result) < rows {
		return
	}
	rowsVal := int64(rows)
	colsVal := int64(cols)
	matvec_avx512_f64(
		unsafe.Pointer(&m[0]),
		unsafe.Pointer(&v[0]),
		unsafe.Pointer(&result[0]),
		unsafe.Pointer(&rowsVal),
		unsafe.Pointer(&colsVal),
	)
}

// Assembly function declarations are in matvec_avx512_amd64.go (generated by GoAT)
