//go:build !noasm && amd64
// Code generated by GoAT. DO NOT EDIT.
// versions:
// 	clang   21.1.8
// 	objdump 2.45.1
// flags: -mavx2 -mfma -mf16c -O3
// source: ../c/matvec_avx2_amd64.c

package asm

import "unsafe"

//go:noescape
func matvec_avx2_f16(m, v, result, prows, pcols unsafe.Pointer)

//go:noescape
func matvec_avx2_bf16(m, v, result, prows, pcols unsafe.Pointer)

//go:noescape
func matvec_avx2_f32(m, v, result, prows, pcols unsafe.Pointer)

//go:noescape
func matvec_avx2_f64(m, v, result, prows, pcols unsafe.Pointer)
