//go:build !noasm && darwin && arm64

// SME Matrix-Vector Multiplication for ARM64 with SME extension
// Uses FMOPA outer product accumulate with ZA tiles for efficient matvec.
package asm

import "unsafe"

// -march=armv9-a+sme+sme-f64f64 enables SME with float64 FMOPA support
//go:generate go tool goat ../c/matvec_sme_arm64.c -O3 --target arm64 --target-os darwin -e="-march=armv9-a+sme+sme-f64f64"

// ============================================================================
// SME FMOPA Matrix-Vector Multiplication
// ============================================================================

// MatVecSMEF32 performs matrix-vector multiplication using SME FMOPA: result = MT^T * v = M * v
// MT is the transposed M matrix (cols x rows, row-major) for contiguous column access.
// v is the input vector (cols elements), result is the output vector (rows elements).
//
// Requires rows to be a multiple of 16 (SVL = 512 bits = 16 x float32).
//
// Parameters:
//   - mt: cols x rows matrix (M transposed, row-major)
//   - v: input vector (cols elements)
//   - result: output vector (rows elements)
//   - rows, cols: matrix dimensions
func MatVecSMEF32(mt []float32, v []float32, result []float32, rows, cols int) {
	if rows == 0 || cols == 0 {
		return
	}
	if len(mt) < cols*rows || len(v) < cols || len(result) < rows {
		return
	}
	rowsVal := int64(rows)
	colsVal := int64(cols)
	matvec_sme_f32(
		unsafe.Pointer(&mt[0]),
		unsafe.Pointer(&v[0]),
		unsafe.Pointer(&result[0]),
		unsafe.Pointer(&rowsVal),
		unsafe.Pointer(&colsVal),
	)
}

// MatVecSMEF64 performs matrix-vector multiplication using SME FMOPA: result = MT^T * v = M * v
// MT is the transposed M matrix (cols x rows, row-major) for contiguous column access.
// v is the input vector (cols elements), result is the output vector (rows elements).
//
// Requires rows to be a multiple of 8 (SVL = 512 bits = 8 x float64).
//
// Parameters:
//   - mt: cols x rows matrix (M transposed, row-major)
//   - v: input vector (cols elements)
//   - result: output vector (rows elements)
//   - rows, cols: matrix dimensions
func MatVecSMEF64(mt []float64, v []float64, result []float64, rows, cols int) {
	if rows == 0 || cols == 0 {
		return
	}
	if len(mt) < cols*rows || len(v) < cols || len(result) < rows {
		return
	}
	rowsVal := int64(rows)
	colsVal := int64(cols)
	matvec_sme_f64(
		unsafe.Pointer(&mt[0]),
		unsafe.Pointer(&v[0]),
		unsafe.Pointer(&result[0]),
		unsafe.Pointer(&rowsVal),
		unsafe.Pointer(&colsVal),
	)
}

// Assembly function declarations are in matvec_sme_arm64.go (generated by GoAT)
