// Code generated by hwygen. DO NOT EDIT.
//go:build !arm64 && !(amd64 && goexperiment.simd)

package sort

import (
	"os"

	"github.com/ajroetker/go-highway/hwy"
)

var SortSmallFloat32 func(data []float32)
var SortSmallFloat64 func(data []float64)
var SortSmallInt32 func(data []int32)
var SortSmallInt64 func(data []int64)
var IsSortedFloat32 func(data []float32) bool
var IsSortedFloat64 func(data []float64) bool
var IsSortedInt32 func(data []int32) bool
var IsSortedInt64 func(data []int64) bool

// SortSmall is the generic API that dispatches to the appropriate SIMD implementation.
func SortSmall[T hwy.Lanes](data []T) {
	switch any(data).(type) {
	case []float32:
		SortSmallFloat32(any(data).([]float32))
	case []float64:
		SortSmallFloat64(any(data).([]float64))
	case []int32:
		SortSmallInt32(any(data).([]int32))
	case []int64:
		SortSmallInt64(any(data).([]int64))
	}
}

// IsSorted is the generic API that dispatches to the appropriate SIMD implementation.
func IsSorted[T hwy.Lanes](data []T) bool {
	switch any(data).(type) {
	case []float32:
		return IsSortedFloat32(any(data).([]float32))
	case []float64:
		return IsSortedFloat64(any(data).([]float64))
	case []int32:
		return IsSortedInt32(any(data).([]int32))
	case []int64:
		return IsSortedInt64(any(data).([]int64))
	}
	panic("unreachable")
}

func init() {
	_ = os.Getenv // silence unused import
	initNetworkFallback()
}

func initNetworkFallback() {
	SortSmallFloat32 = BaseSortSmall_fallback
	SortSmallFloat64 = BaseSortSmall_fallback_Float64
	SortSmallInt32 = BaseSortSmall_fallback_Int32
	SortSmallInt64 = BaseSortSmall_fallback_Int64
	IsSortedFloat32 = BaseIsSorted_fallback
	IsSortedFloat64 = BaseIsSorted_fallback_Float64
	IsSortedInt32 = BaseIsSorted_fallback_Int32
	IsSortedInt64 = BaseIsSorted_fallback_Int64
}
