// Code generated by github.com/ajroetker/go-highway/cmd/hwygen. DO NOT EDIT.

//go:build arm64

package varint

import (
	"github.com/ajroetker/go-highway/hwy"
)

var DecodeGroupVarint32 func(src []byte) (values [4]uint32, consumed int)

func init() {
	if hwy.NoSimdEnv() {
		initGroupvarintFallback()
		return
	}
	initGroupvarintNEON()
	return
}

func initGroupvarintNEON() {
	DecodeGroupVarint32 = BaseDecodeGroupVarint32_neon
}

func initGroupvarintFallback() {
	DecodeGroupVarint32 = BaseDecodeGroupVarint32_fallback
}
