// Code generated by github.com/ajroetker/go-highway/cmd/hwygen. DO NOT EDIT.

//go:build amd64 && goexperiment.simd

package varint

import (
	"simd/archsimd"

	"github.com/ajroetker/go-highway/hwy"
)

var MaskedVByteDecodeBatch32 func(src []byte, dst []uint32, n int) (decoded int, consumed int)
var MaskedVByteDecodeGroup func(src []byte, dst []uint32) (decoded int, consumed int)
var MaskedVByteDecodeBatch64 func(src []byte, dst []uint64, n int) (decoded int, consumed int)

func init() {
	if hwy.NoSimdEnv() {
		initMaskedvbyteFallback()
		return
	}
	if archsimd.X86.AVX512() {
		initMaskedvbyteAVX512()
		return
	}
	if archsimd.X86.AVX2() {
		initMaskedvbyteAVX2()
		return
	}
	initMaskedvbyteFallback()
}

func initMaskedvbyteAVX2() {
	MaskedVByteDecodeBatch32 = BaseMaskedVByteDecodeBatch32_avx2
	MaskedVByteDecodeGroup = BaseMaskedVByteDecodeGroup_avx2
	MaskedVByteDecodeBatch64 = BaseMaskedVByteDecodeBatch64_avx2
}

func initMaskedvbyteAVX512() {
	MaskedVByteDecodeBatch32 = BaseMaskedVByteDecodeBatch32_avx512
	MaskedVByteDecodeGroup = BaseMaskedVByteDecodeGroup_avx512
	MaskedVByteDecodeBatch64 = BaseMaskedVByteDecodeBatch64_avx512
}

func initMaskedvbyteFallback() {
	MaskedVByteDecodeBatch32 = BaseMaskedVByteDecodeBatch32_fallback
	MaskedVByteDecodeGroup = BaseMaskedVByteDecodeGroup_fallback
	MaskedVByteDecodeBatch64 = BaseMaskedVByteDecodeBatch64_fallback
}
