// Code generated by github.com/ajroetker/go-highway/cmd/hwygen. DO NOT EDIT.

package matmul

import (
	"github.com/ajroetker/go-highway/hwy"
)

func BaseTranspose2D_fallback_Float16(src []hwy.Float16, m int, k int, dst []hwy.Float16) {
	if len(src) < m*k || len(dst) < k*m {
		return
	}
	lanes := hwy.MaxLanes[hwy.Float16]()
	for i := 0; i <= m-lanes; i += lanes {
		for j := 0; j <= k-lanes; j += lanes {
			transposeBlockSIMD(src, dst, i, j, m, k, lanes)
		}
	}
	transposeEdgesScalar(src, m, k, dst, lanes)
}

func BaseTranspose2D_fallback_BFloat16(src []hwy.BFloat16, m int, k int, dst []hwy.BFloat16) {
	if len(src) < m*k || len(dst) < k*m {
		return
	}
	lanes := hwy.MaxLanes[hwy.BFloat16]()
	for i := 0; i <= m-lanes; i += lanes {
		for j := 0; j <= k-lanes; j += lanes {
			transposeBlockSIMD(src, dst, i, j, m, k, lanes)
		}
	}
	transposeEdgesScalar(src, m, k, dst, lanes)
}

func BaseTranspose2D_fallback(src []float32, m int, k int, dst []float32) {
	if len(src) < m*k || len(dst) < k*m {
		return
	}
	for i := 0; i <= m-1; i++ {
		for j := 0; j <= k-1; j++ {
			transposeBlockSIMD(src, dst, i, j, m, k, 1)
		}
	}
	transposeEdgesScalar(src, m, k, dst, 1)
}

func BaseTranspose2D_fallback_Float64(src []float64, m int, k int, dst []float64) {
	if len(src) < m*k || len(dst) < k*m {
		return
	}
	for i := 0; i <= m-1; i++ {
		for j := 0; j <= k-1; j++ {
			transposeBlockSIMD(src, dst, i, j, m, k, 1)
		}
	}
	transposeEdgesScalar(src, m, k, dst, 1)
}
